CREATE TABLE HEL_ACCIO
(
  ID                   NUMBER(19)               NOT NULL,
  CODI                 VARCHAR2(64 CHAR)        NOT NULL,
  DESCRIPCIO           VARCHAR2(255 CHAR),
  JBPM_ACTION          VARCHAR2(255 CHAR)       NOT NULL,
  NOM                  VARCHAR2(255 CHAR)       NOT NULL,
  DEFINICIO_PROCES_ID  NUMBER(19)               NOT NULL
);

ALTER TABLE HEL_CAMP
 ADD (JBPM_ACTION  VARCHAR2(255 CHAR));

CREATE TABLE HEL_REDIR
(
  ID               NUMBER(19)                   NOT NULL,
  DATA_CANCELACIO  TIMESTAMP(6),
  DATA_FI          TIMESTAMP(6)                 NOT NULL,
  DATA_INICI       TIMESTAMP(6)                 NOT NULL,
  USUARI_DESTI     VARCHAR2(255 CHAR)           NOT NULL,
  USUARI_ORIGEN    VARCHAR2(255 CHAR)           NOT NULL
);

ALTER TABLE HEL_ACCIO ADD (
  PRIMARY KEY
 (ID),
  UNIQUE (CODI, DEFINICIO_PROCES_ID));

ALTER TABLE HEL_REDIR ADD (
  PRIMARY KEY
 (ID));

ALTER TABLE HEL_ACCIO
DROP CONSTRAINT HEL_DEFPROC_DOCUMENT_FK;
ALTER TABLE HEL_ACCIO ADD (
  CONSTRAINT HEL_DEFPROC_ACCIO_FK 
 FOREIGN KEY (DEFINICIO_PROCES_ID) 
 REFERENCES HEL_DEFINICIO_PROCES (ID));

ALTER TABLE JBPM_VARIABLEINSTANCE
 MODIFY(STRINGVALUE_ VARCHAR2(2048 CHAR));

ALTER TABLE HEL_EXPEDIENT_TIPUS
 MODIFY(SISTRA_MAPCAMPS VARCHAR2(2048 CHAR));
ALTER TABLE HEL_EXPEDIENT_TIPUS
 MODIFY(SISTRA_MAPDOCS VARCHAR2(2048 CHAR));

ALTER TABLE HEL_EXPEDIENT_TIPUS
 ADD (FORMEXT_URL  VARCHAR2(255 CHAR));
ALTER TABLE HEL_EXPEDIENT_TIPUS
 ADD (FORMEXT_USUARI  VARCHAR2(255 CHAR));
ALTER TABLE HEL_EXPEDIENT_TIPUS
 ADD (FORMEXT_CONTRASENYA  VARCHAR2(255 CHAR));

CREATE TABLE HEL_ALERTA
(
  ID                NUMBER(19)                  NOT NULL,
  DATA_CREACIO      TIMESTAMP(6)                NOT NULL,
  DATA_ELIMINACIO   TIMESTAMP(6),
  DATA_LECTURA      TIMESTAMP(6),
  DESTINATARI       VARCHAR2(255 CHAR)          NOT NULL,
  TASK_INSTANCE_ID  VARCHAR2(255 CHAR),
  TEXT              VARCHAR2(1024 CHAR),
  ENTORN_ID         NUMBER(19)                  NOT NULL,
  EXPEDIENT_ID      NUMBER(19)                  NOT NULL
);
ALTER TABLE HEL_ALERTA ADD (
  PRIMARY KEY
 (ID));
ALTER TABLE HEL_ALERTA ADD (
  CONSTRAINT HEL_ENTORN_ALERTA_FK 
 FOREIGN KEY (ENTORN_ID) 
 REFERENCES HEL_ENTORN (ID),
  CONSTRAINT HEL_EXPEDIENT_ALERTA_FK 
 FOREIGN KEY (EXPEDIENT_ID) 
 REFERENCES HEL_EXPEDIENT (ID));

ALTER TABLE HEL_CAMP
 ADD (ORDRE                NUMBER(10));

ALTER TABLE HEL_TERMINI
 ADD (DIES_PREVIS_AVIS     NUMBER(10));
ALTER TABLE HEL_TERMINI
 ADD (ALERTA_PREVIA        NUMBER(1));
ALTER TABLE HEL_TERMINI
 ADD (ALERTA_FINAL         NUMBER(1));
UPDATE HEL_TERMINI SET ALERTA_PREVIA=0, ALERTA_FINAL=0;

ALTER TABLE HEL_TERMINI_INICIAT
 ADD (ALERTA_PREVIA        NUMBER(1));
ALTER TABLE HEL_TERMINI_INICIAT
 ADD (ALERTA_FINAL         NUMBER(1));
ALTER TABLE HEL_TERMINI_INICIAT
 ADD (DATA_FI_PRORROGA     DATE);
ALTER TABLE HEL_TERMINI_INICIAT
 ADD (TASK_INSTANCE_ID     VARCHAR2(255 CHAR));
ALTER TABLE HEL_TERMINI_INICIAT
 ADD (TIMER_IDS            VARCHAR2(1024 CHAR));
ALTER TABLE HEL_TERMINI_INICIAT
 DROP COLUMN TIMER_NAME;
UPDATE HEL_TERMINI_INICIAT SET ALERTA_PREVIA=0, ALERTA_FINAL=0;
