
package net.conselldemallorca.helium.integracio.tramitacio;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b14002
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "TramitacioService", targetNamespace = "http://tramitacio.integracio.helium.conselldemallorca.net/", wsdlLocation = "file:/home/likewise-open/LIMIT_CECOMASA/josepg/git/helium/doc/wsdl/TramitacioService.wsdl")
public class TramitacioService_Service
    extends Service
{

    private final static URL TRAMITACIOSERVICE_WSDL_LOCATION;
    private final static WebServiceException TRAMITACIOSERVICE_EXCEPTION;
    private final static QName TRAMITACIOSERVICE_QNAME = new QName("http://tramitacio.integracio.helium.conselldemallorca.net/", "TramitacioService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/home/likewise-open/LIMIT_CECOMASA/josepg/git/helium/doc/wsdl/TramitacioService.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        TRAMITACIOSERVICE_WSDL_LOCATION = url;
        TRAMITACIOSERVICE_EXCEPTION = e;
    }

    public TramitacioService_Service() {
        super(__getWsdlLocation(), TRAMITACIOSERVICE_QNAME);
    }

    public TramitacioService_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), TRAMITACIOSERVICE_QNAME, features);
    }

    public TramitacioService_Service(URL wsdlLocation) {
        super(wsdlLocation, TRAMITACIOSERVICE_QNAME);
    }

    public TramitacioService_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, TRAMITACIOSERVICE_QNAME, features);
    }

    public TramitacioService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public TramitacioService_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns TramitacioService
     */
    @WebEndpoint(name = "TramitacioPort")
    public TramitacioService getTramitacioPort() {
        return super.getPort(new QName("http://tramitacio.integracio.helium.conselldemallorca.net/", "TramitacioPort"), TramitacioService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns TramitacioService
     */
    @WebEndpoint(name = "TramitacioPort")
    public TramitacioService getTramitacioPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://tramitacio.integracio.helium.conselldemallorca.net/", "TramitacioPort"), TramitacioService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (TRAMITACIOSERVICE_EXCEPTION!= null) {
            throw TRAMITACIOSERVICE_EXCEPTION;
        }
        return TRAMITACIOSERVICE_WSDL_LOCATION;
    }

}
