
package net.conselldemallorca.helium.integracio.tramitacio;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b14002
 * Generated source version: 2.2
 * 
 */
@WebService(name = "TramitacioService", targetNamespace = "http://tramitacio.integracio.helium.conselldemallorca.net/")
@XmlSeeAlso({
    net.conselldemallorca.helium.integracio.tramitacio.ObjectFactory.class,
    net.java.dev.jaxb.array.ObjectFactory.class
})
public interface TramitacioService {


    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns java.util.List<net.conselldemallorca.helium.integracio.tramitacio.CampProces>
     * @throws TramitacioException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "consultarVariablesProces", targetNamespace = "http://tramitacio.integracio.helium.conselldemallorca.net/", className = "net.conselldemallorca.helium.integracio.tramitacio.ConsultarVariablesProces")
    @ResponseWrapper(localName = "consultarVariablesProcesResponse", targetNamespace = "http://tramitacio.integracio.helium.conselldemallorca.net/", className = "net.conselldemallorca.helium.integracio.tramitacio.ConsultarVariablesProcesResponse")
    public List<CampProces> consultarVariablesProces(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2)
        throws TramitacioException_Exception
    ;

    /**
     * 
     * @param arg4
     * @param arg3
     * @param arg2
     * @param arg1
     * @param arg0
     * @throws TramitacioException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "setVariableProces", targetNamespace = "http://tramitacio.integracio.helium.conselldemallorca.net/", className = "net.conselldemallorca.helium.integracio.tramitacio.SetVariableProces")
    @ResponseWrapper(localName = "setVariableProcesResponse", targetNamespace = "http://tramitacio.integracio.helium.conselldemallorca.net/", className = "net.conselldemallorca.helium.integracio.tramitacio.SetVariableProcesResponse")
    public void setVariableProces(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        String arg3,
        @WebParam(name = "arg4", targetNamespace = "")
        Object arg4)
        throws TramitacioException_Exception
    ;

    /**
     * 
     * @param arg5
     * @param arg4
     * @param arg3
     * @param arg2
     * @param arg1
     * @param arg0
     * @param arg6
     * @return
     *     returns java.lang.Long
     * @throws TramitacioException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "setDocumentProces", targetNamespace = "http://tramitacio.integracio.helium.conselldemallorca.net/", className = "net.conselldemallorca.helium.integracio.tramitacio.SetDocumentProces")
    @ResponseWrapper(localName = "setDocumentProcesResponse", targetNamespace = "http://tramitacio.integracio.helium.conselldemallorca.net/", className = "net.conselldemallorca.helium.integracio.tramitacio.SetDocumentProcesResponse")
    public Long setDocumentProces(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        String arg3,
        @WebParam(name = "arg4", targetNamespace = "")
        String arg4,
        @WebParam(name = "arg5", targetNamespace = "")
        XMLGregorianCalendar arg5,
        @WebParam(name = "arg6", targetNamespace = "")
        byte[] arg6)
        throws TramitacioException_Exception
    ;

    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     * @throws TramitacioException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "agafarTasca", targetNamespace = "http://tramitacio.integracio.helium.conselldemallorca.net/", className = "net.conselldemallorca.helium.integracio.tramitacio.AgafarTasca")
    @ResponseWrapper(localName = "agafarTascaResponse", targetNamespace = "http://tramitacio.integracio.helium.conselldemallorca.net/", className = "net.conselldemallorca.helium.integracio.tramitacio.AgafarTascaResponse")
    public void agafarTasca(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2)
        throws TramitacioException_Exception
    ;

    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns java.util.List<net.conselldemallorca.helium.integracio.tramitacio.DocumentProces>
     * @throws TramitacioException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "consultarDocumentsProces", targetNamespace = "http://tramitacio.integracio.helium.conselldemallorca.net/", className = "net.conselldemallorca.helium.integracio.tramitacio.ConsultarDocumentsProces")
    @ResponseWrapper(localName = "consultarDocumentsProcesResponse", targetNamespace = "http://tramitacio.integracio.helium.conselldemallorca.net/", className = "net.conselldemallorca.helium.integracio.tramitacio.ConsultarDocumentsProcesResponse")
    public List<DocumentProces> consultarDocumentsProces(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2)
        throws TramitacioException_Exception
    ;

    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns java.util.List<net.conselldemallorca.helium.integracio.tramitacio.CampTasca>
     * @throws TramitacioException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "consultaFormulariTasca", targetNamespace = "http://tramitacio.integracio.helium.conselldemallorca.net/", className = "net.conselldemallorca.helium.integracio.tramitacio.ConsultaFormulariTasca")
    @ResponseWrapper(localName = "consultaFormulariTascaResponse", targetNamespace = "http://tramitacio.integracio.helium.conselldemallorca.net/", className = "net.conselldemallorca.helium.integracio.tramitacio.ConsultaFormulariTascaResponse")
    public List<CampTasca> consultaFormulariTasca(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2)
        throws TramitacioException_Exception
    ;

    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     * @throws TramitacioException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "reprendreExpedient", targetNamespace = "http://tramitacio.integracio.helium.conselldemallorca.net/", className = "net.conselldemallorca.helium.integracio.tramitacio.ReprendreExpedient")
    @ResponseWrapper(localName = "reprendreExpedientResponse", targetNamespace = "http://tramitacio.integracio.helium.conselldemallorca.net/", className = "net.conselldemallorca.helium.integracio.tramitacio.ReprendreExpedientResponse")
    public void reprendreExpedient(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2)
        throws TramitacioException_Exception
    ;

    /**
     * 
     * @param arg5
     * @param arg4
     * @param arg3
     * @param arg2
     * @param arg1
     * @param arg0
     * @param arg11
     * @param arg12
     * @param arg10
     * @param arg6
     * @param arg7
     * @param arg8
     * @param arg9
     * @return
     *     returns java.util.List<net.conselldemallorca.helium.integracio.tramitacio.ExpedientInfo>
     * @throws TramitacioException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "consultaExpedients", targetNamespace = "http://tramitacio.integracio.helium.conselldemallorca.net/", className = "net.conselldemallorca.helium.integracio.tramitacio.ConsultaExpedients")
    @ResponseWrapper(localName = "consultaExpedientsResponse", targetNamespace = "http://tramitacio.integracio.helium.conselldemallorca.net/", className = "net.conselldemallorca.helium.integracio.tramitacio.ConsultaExpedientsResponse")
    public List<ExpedientInfo> consultaExpedients(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        String arg3,
        @WebParam(name = "arg4", targetNamespace = "")
        XMLGregorianCalendar arg4,
        @WebParam(name = "arg5", targetNamespace = "")
        XMLGregorianCalendar arg5,
        @WebParam(name = "arg6", targetNamespace = "")
        String arg6,
        @WebParam(name = "arg7", targetNamespace = "")
        String arg7,
        @WebParam(name = "arg8", targetNamespace = "")
        boolean arg8,
        @WebParam(name = "arg9", targetNamespace = "")
        boolean arg9,
        @WebParam(name = "arg10", targetNamespace = "")
        Double arg10,
        @WebParam(name = "arg11", targetNamespace = "")
        Double arg11,
        @WebParam(name = "arg12", targetNamespace = "")
        String arg12)
        throws TramitacioException_Exception
    ;

    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     * @throws TramitacioException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "deleteExpedient", targetNamespace = "http://tramitacio.integracio.helium.conselldemallorca.net/", className = "net.conselldemallorca.helium.integracio.tramitacio.DeleteExpedient")
    @ResponseWrapper(localName = "deleteExpedientResponse", targetNamespace = "http://tramitacio.integracio.helium.conselldemallorca.net/", className = "net.conselldemallorca.helium.integracio.tramitacio.DeleteExpedientResponse")
    public void deleteExpedient(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2)
        throws TramitacioException_Exception
    ;

    /**
     * 
     * @param arg3
     * @param arg2
     * @param arg1
     * @param arg0
     * @throws TramitacioException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "finalitzarTasca", targetNamespace = "http://tramitacio.integracio.helium.conselldemallorca.net/", className = "net.conselldemallorca.helium.integracio.tramitacio.FinalitzarTasca")
    @ResponseWrapper(localName = "finalitzarTascaResponse", targetNamespace = "http://tramitacio.integracio.helium.conselldemallorca.net/", className = "net.conselldemallorca.helium.integracio.tramitacio.FinalitzarTascaResponse")
    public void finalitzarTasca(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        String arg3)
        throws TramitacioException_Exception
    ;

    /**
     * 
     * @param arg5
     * @param arg4
     * @param arg3
     * @param arg2
     * @param arg1
     * @param arg0
     * @param arg6
     * @throws TramitacioException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "setDocumentTasca", targetNamespace = "http://tramitacio.integracio.helium.conselldemallorca.net/", className = "net.conselldemallorca.helium.integracio.tramitacio.SetDocumentTasca")
    @ResponseWrapper(localName = "setDocumentTascaResponse", targetNamespace = "http://tramitacio.integracio.helium.conselldemallorca.net/", className = "net.conselldemallorca.helium.integracio.tramitacio.SetDocumentTascaResponse")
    public void setDocumentTasca(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        String arg3,
        @WebParam(name = "arg4", targetNamespace = "")
        String arg4,
        @WebParam(name = "arg5", targetNamespace = "")
        XMLGregorianCalendar arg5,
        @WebParam(name = "arg6", targetNamespace = "")
        byte[] arg6)
        throws TramitacioException_Exception
    ;

    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     * @throws TramitacioException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "alliberarTasca", targetNamespace = "http://tramitacio.integracio.helium.conselldemallorca.net/", className = "net.conselldemallorca.helium.integracio.tramitacio.AlliberarTasca")
    @ResponseWrapper(localName = "alliberarTascaResponse", targetNamespace = "http://tramitacio.integracio.helium.conselldemallorca.net/", className = "net.conselldemallorca.helium.integracio.tramitacio.AlliberarTascaResponse")
    public void alliberarTasca(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2)
        throws TramitacioException_Exception
    ;

    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns java.util.List<net.conselldemallorca.helium.integracio.tramitacio.TascaTramitacio>
     * @throws TramitacioException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "consultaTasquesPersonalsByCodi", targetNamespace = "http://tramitacio.integracio.helium.conselldemallorca.net/", className = "net.conselldemallorca.helium.integracio.tramitacio.ConsultaTasquesPersonalsByCodi")
    @ResponseWrapper(localName = "consultaTasquesPersonalsByCodiResponse", targetNamespace = "http://tramitacio.integracio.helium.conselldemallorca.net/", className = "net.conselldemallorca.helium.integracio.tramitacio.ConsultaTasquesPersonalsByCodiResponse")
    public List<TascaTramitacio> consultaTasquesPersonalsByCodi(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2)
        throws TramitacioException_Exception
    ;

    /**
     * 
     * @param arg0
     * @return
     *     returns net.conselldemallorca.helium.integracio.tramitacio.ArxiuProces
     * @throws TramitacioException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getArxiuProces", targetNamespace = "http://tramitacio.integracio.helium.conselldemallorca.net/", className = "net.conselldemallorca.helium.integracio.tramitacio.GetArxiuProces")
    @ResponseWrapper(localName = "getArxiuProcesResponse", targetNamespace = "http://tramitacio.integracio.helium.conselldemallorca.net/", className = "net.conselldemallorca.helium.integracio.tramitacio.GetArxiuProcesResponse")
    public ArxiuProces getArxiuProces(
        @WebParam(name = "arg0", targetNamespace = "")
        Long arg0)
        throws TramitacioException_Exception
    ;

    /**
     * 
     * @param arg3
     * @param arg2
     * @param arg1
     * @param arg0
     * @throws TramitacioException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "setDadesFormulariTasca", targetNamespace = "http://tramitacio.integracio.helium.conselldemallorca.net/", className = "net.conselldemallorca.helium.integracio.tramitacio.SetDadesFormulariTasca")
    @ResponseWrapper(localName = "setDadesFormulariTascaResponse", targetNamespace = "http://tramitacio.integracio.helium.conselldemallorca.net/", className = "net.conselldemallorca.helium.integracio.tramitacio.SetDadesFormulariTascaResponse")
    public void setDadesFormulariTasca(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        List<ParellaCodiValor> arg3)
        throws TramitacioException_Exception
    ;

    /**
     * 
     * @param arg3
     * @param arg2
     * @param arg1
     * @param arg0
     * @throws TramitacioException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "executarAccioProces", targetNamespace = "http://tramitacio.integracio.helium.conselldemallorca.net/", className = "net.conselldemallorca.helium.integracio.tramitacio.ExecutarAccioProces")
    @ResponseWrapper(localName = "executarAccioProcesResponse", targetNamespace = "http://tramitacio.integracio.helium.conselldemallorca.net/", className = "net.conselldemallorca.helium.integracio.tramitacio.ExecutarAccioProcesResponse")
    public void executarAccioProces(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        String arg3)
        throws TramitacioException_Exception
    ;

    /**
     * 
     * @param arg3
     * @param arg2
     * @param arg1
     * @param arg0
     * @throws TramitacioException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "esborrarDocumentTasca", targetNamespace = "http://tramitacio.integracio.helium.conselldemallorca.net/", className = "net.conselldemallorca.helium.integracio.tramitacio.EsborrarDocumentTasca")
    @ResponseWrapper(localName = "esborrarDocumentTascaResponse", targetNamespace = "http://tramitacio.integracio.helium.conselldemallorca.net/", className = "net.conselldemallorca.helium.integracio.tramitacio.EsborrarDocumentTascaResponse")
    public void esborrarDocumentTasca(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        String arg3)
        throws TramitacioException_Exception
    ;

    /**
     * 
     * @param arg3
     * @param arg2
     * @param arg1
     * @param arg0
     * @throws TramitacioException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "esborrarDocumentProces", targetNamespace = "http://tramitacio.integracio.helium.conselldemallorca.net/", className = "net.conselldemallorca.helium.integracio.tramitacio.EsborrarDocumentProces")
    @ResponseWrapper(localName = "esborrarDocumentProcesResponse", targetNamespace = "http://tramitacio.integracio.helium.conselldemallorca.net/", className = "net.conselldemallorca.helium.integracio.tramitacio.EsborrarDocumentProcesResponse")
    public void esborrarDocumentProces(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        Long arg3)
        throws TramitacioException_Exception
    ;

    /**
     * 
     * @param arg3
     * @param arg2
     * @param arg1
     * @param arg0
     * @throws TramitacioException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "esborrarVariableProces", targetNamespace = "http://tramitacio.integracio.helium.conselldemallorca.net/", className = "net.conselldemallorca.helium.integracio.tramitacio.EsborrarVariableProces")
    @ResponseWrapper(localName = "esborrarVariableProcesResponse", targetNamespace = "http://tramitacio.integracio.helium.conselldemallorca.net/", className = "net.conselldemallorca.helium.integracio.tramitacio.EsborrarVariableProcesResponse")
    public void esborrarVariableProces(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        String arg3)
        throws TramitacioException_Exception
    ;

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns java.util.List<net.conselldemallorca.helium.integracio.tramitacio.TascaTramitacio>
     * @throws TramitacioException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "consultaTasquesPersonals", targetNamespace = "http://tramitacio.integracio.helium.conselldemallorca.net/", className = "net.conselldemallorca.helium.integracio.tramitacio.ConsultaTasquesPersonals")
    @ResponseWrapper(localName = "consultaTasquesPersonalsResponse", targetNamespace = "http://tramitacio.integracio.helium.conselldemallorca.net/", className = "net.conselldemallorca.helium.integracio.tramitacio.ConsultaTasquesPersonalsResponse")
    public List<TascaTramitacio> consultaTasquesPersonals(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1)
        throws TramitacioException_Exception
    ;

    /**
     * 
     * @param arg3
     * @param arg2
     * @param arg1
     * @param arg0
     * @throws TramitacioException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "executarScriptProces", targetNamespace = "http://tramitacio.integracio.helium.conselldemallorca.net/", className = "net.conselldemallorca.helium.integracio.tramitacio.ExecutarScriptProces")
    @ResponseWrapper(localName = "executarScriptProcesResponse", targetNamespace = "http://tramitacio.integracio.helium.conselldemallorca.net/", className = "net.conselldemallorca.helium.integracio.tramitacio.ExecutarScriptProcesResponse")
    public void executarScriptProces(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        String arg3)
        throws TramitacioException_Exception
    ;

    /**
     * 
     * @param arg3
     * @param arg2
     * @param arg1
     * @param arg0
     * @throws TramitacioException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "aturarExpedient", targetNamespace = "http://tramitacio.integracio.helium.conselldemallorca.net/", className = "net.conselldemallorca.helium.integracio.tramitacio.AturarExpedient")
    @ResponseWrapper(localName = "aturarExpedientResponse", targetNamespace = "http://tramitacio.integracio.helium.conselldemallorca.net/", className = "net.conselldemallorca.helium.integracio.tramitacio.AturarExpedientResponse")
    public void aturarExpedient(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        String arg3)
        throws TramitacioException_Exception
    ;

    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns java.util.List<net.conselldemallorca.helium.integracio.tramitacio.DocumentTasca>
     * @throws TramitacioException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "consultaDocumentsTasca", targetNamespace = "http://tramitacio.integracio.helium.conselldemallorca.net/", className = "net.conselldemallorca.helium.integracio.tramitacio.ConsultaDocumentsTasca")
    @ResponseWrapper(localName = "consultaDocumentsTascaResponse", targetNamespace = "http://tramitacio.integracio.helium.conselldemallorca.net/", className = "net.conselldemallorca.helium.integracio.tramitacio.ConsultaDocumentsTascaResponse")
    public List<DocumentTasca> consultaDocumentsTasca(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2)
        throws TramitacioException_Exception
    ;

    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns java.util.List<net.conselldemallorca.helium.integracio.tramitacio.TascaTramitacio>
     * @throws TramitacioException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "consultaTasquesGrupByCodi", targetNamespace = "http://tramitacio.integracio.helium.conselldemallorca.net/", className = "net.conselldemallorca.helium.integracio.tramitacio.ConsultaTasquesGrupByCodi")
    @ResponseWrapper(localName = "consultaTasquesGrupByCodiResponse", targetNamespace = "http://tramitacio.integracio.helium.conselldemallorca.net/", className = "net.conselldemallorca.helium.integracio.tramitacio.ConsultaTasquesGrupByCodiResponse")
    public List<TascaTramitacio> consultaTasquesGrupByCodi(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2)
        throws TramitacioException_Exception
    ;

    /**
     * 
     * @param arg5
     * @param arg4
     * @param arg3
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     * @throws TramitacioException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "iniciExpedient", targetNamespace = "http://tramitacio.integracio.helium.conselldemallorca.net/", className = "net.conselldemallorca.helium.integracio.tramitacio.IniciExpedient")
    @ResponseWrapper(localName = "iniciExpedientResponse", targetNamespace = "http://tramitacio.integracio.helium.conselldemallorca.net/", className = "net.conselldemallorca.helium.integracio.tramitacio.IniciExpedientResponse")
    public String iniciExpedient(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        String arg3,
        @WebParam(name = "arg4", targetNamespace = "")
        String arg4,
        @WebParam(name = "arg5", targetNamespace = "")
        List<ParellaCodiValor> arg5)
        throws TramitacioException_Exception
    ;

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns java.util.List<net.conselldemallorca.helium.integracio.tramitacio.TascaTramitacio>
     * @throws TramitacioException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "consultaTasquesGrup", targetNamespace = "http://tramitacio.integracio.helium.conselldemallorca.net/", className = "net.conselldemallorca.helium.integracio.tramitacio.ConsultaTasquesGrup")
    @ResponseWrapper(localName = "consultaTasquesGrupResponse", targetNamespace = "http://tramitacio.integracio.helium.conselldemallorca.net/", className = "net.conselldemallorca.helium.integracio.tramitacio.ConsultaTasquesGrupResponse")
    public List<TascaTramitacio> consultaTasquesGrup(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1)
        throws TramitacioException_Exception
    ;

}
