-- #1383 Creació d'índexs per millorar rendiment consultes 


-- ORACLE / POSTGRESQL

CREATE INDEX HEL_EXPEDIENT_TIPENT_I ON HEL_EXPEDIENT (TIPUS_ID, ENTORN_ID);

ALTER INDEX HEL_EXPEDIENT_TIPENT_I REBUILD;

CREATE INDEX HEL_EXPEDIENT_ENT_ID_I ON HEL_EXPEDIENT
(ENTORN_ID, ID) ;

ALTER INDEX HEL_EXPEDIENT_ENT_ID_I REBUILD;

CREATE INDEX IDX_TASKINSTANCE ON JBPM_TASKINSTANCE
(ISSUSPENDED_, ACTORID_, ISOPEN_, ID_, PROCINST_);

ALTER INDEX IDX_TASKINSTANCE REBUILD;

CREATE INDEX IDX_POOLEDACTOR_ACTID ON JBPM_POOLEDACTOR
(ACTORID_, ID_);

ALTER INDEX IDX_POOLEDACTOR_ACTID REBUILD;

CREATE INDEX IDX_TASKACTORPOOL_POOL_TASK ON JBPM_TASKACTORPOOL
(POOLEDACTOR_, TASKINSTANCE_);

ALTER INDEX IDX_TASKACTORPOOL_POOL_TASK REBUILD;

DROP INDEX IDX_PLDACTR_ACTID;
