--#1705 Error notificant document amb descripció llarga
-- Incrementar llargària camp DESCRIPCIO

-- Oracle
ALTER TABLE HEL_DOCUMENT_NOTIFICACIO MODIFY DESCRIPCIO VARCHAR2(1000 CHAR);

-- Postgresql
ALTER TABLE HEL_DOCUMENT_NOTIFICACIO MODIFY DESCRIPCIO CHARACTER VARYING(1000);