package net.conselldemallorca.helium.integracio.zonaper.wsdl;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.2.2
 * Fri Dec 18 08:24:59 CET 2009
 * Generated source version: 2.2.2
 * 
 */
 
@WebService(targetNamespace = "urn:es:caib:zonaper:ws:v1:services", name = "BackofficeFacade")
@XmlSeeAlso({ObjectFactory.class})
public interface BackofficeFacade {

    @ResponseWrapper(localName = "altaExpedienteResponse", targetNamespace = "urn:es:caib:zonaper:ws:v1:model:BackofficeFacade", className = "net.conselldemallorca.helium.integracio.zonaper.wsdl.AltaExpedienteResponse")
    @RequestWrapper(localName = "altaExpediente", targetNamespace = "urn:es:caib:zonaper:ws:v1:model:BackofficeFacade", className = "net.conselldemallorca.helium.integracio.zonaper.wsdl.AltaExpediente")
    @WebResult(name = "altaExpedienteReturn", targetNamespace = "urn:es:caib:zonaper:ws:v1:model:BackofficeFacade")
    @WebMethod
    public java.lang.String altaExpediente(
        @WebParam(name = "expediente", targetNamespace = "urn:es:caib:zonaper:ws:v1:model:BackofficeFacade")
        net.conselldemallorca.helium.integracio.zonaper.wsdl.Expediente expediente
    ) throws BackofficeFacadeException_Exception;

    @ResponseWrapper(localName = "altaEventoExpedienteResponse", targetNamespace = "urn:es:caib:zonaper:ws:v1:model:BackofficeFacade", className = "net.conselldemallorca.helium.integracio.zonaper.wsdl.AltaEventoExpedienteResponse")
    @RequestWrapper(localName = "altaEventoExpediente", targetNamespace = "urn:es:caib:zonaper:ws:v1:model:BackofficeFacade", className = "net.conselldemallorca.helium.integracio.zonaper.wsdl.AltaEventoExpediente")
    @WebMethod
    public void altaEventoExpediente(
        @WebParam(name = "unidadAdministrativa", targetNamespace = "urn:es:caib:zonaper:ws:v1:model:BackofficeFacade")
        long unidadAdministrativa,
        @WebParam(name = "identificadorExpediente", targetNamespace = "urn:es:caib:zonaper:ws:v1:model:BackofficeFacade")
        java.lang.String identificadorExpediente,
        @WebParam(name = "claveExpediente", targetNamespace = "urn:es:caib:zonaper:ws:v1:model:BackofficeFacade")
        java.lang.String claveExpediente,
        @WebParam(name = "evento", targetNamespace = "urn:es:caib:zonaper:ws:v1:model:BackofficeFacade")
        net.conselldemallorca.helium.integracio.zonaper.wsdl.EventoExpediente evento
    ) throws BackofficeFacadeException_Exception;
}
