# Tamany màxim permès pels arxius pujats mitjançant HTTP (en bytes)
spring.http.multipart.max-file-size=MULTIPART_FILE_SIZE

# URL base (applet signatura, estampa signatura defecte, emails tasca)
app.base.url=BASE_URL
# URL base per a la verificació de firmes a Custòdia Antiga
app.arxiu.verificacio.baseurl=VERIFICACIO_BASE_URL

## Conversió de documents amb OpenOffice
app.conversio.actiu=CONVERSIO_ACTIU
app.conversio.openoffice.host=CONVERSIO_OPENOFFICE_HOST
app.conversio.openoffice.port=CONVERSIO_OPENOFFICE_PORT
app.conversio.openoffice.timeout=CONVERSIO_OPENOFFICE_TIMEOUT

## Enviaments de correu
app.correu.remitent=CORREU_REMITENT

## Plugin de Persones
app.persones.plugin.class=PERSONES_PLUGIN_CLASS
app.plugin.persones.pluginsib.userinformation.keycloak.serverurl=PERSONES_PLUGIN_KEYCLOAK_URL
app.plugin.persones.pluginsib.userinformation.keycloak.realm=PERSONES_PLUGIN_KEYCLOAK_REALM
app.plugin.persones.pluginsib.userinformation.keycloak.client_id=PERSONES_PLUGIN_KEYCLOAK_CLIENT_ID
app.plugin.persones.pluginsib.userinformation.keycloak.client_id_for_user_autentication=PERSONES_PLUGIN_KEYCLOAK_CLIENT_ID_USER_AUTH
app.plugin.persones.pluginsib.userinformation.keycloak.password_secret=PERSONES_PLUGIN_KEYCLOAK_CLIENT_ID_USER_AUTH_SECRET
app.plugin.persones.pluginsib.userinformation.keycloak.mapping.administrationID=PERSONES_PLUGIN_KEYCLOAK_MAP_ADMINID
app.plugin.persones.pluginsib.userinformation.keycloak.debug=PERSONES_PLUGIN_KEYCLOAK_DEBUG

## Plugin de l'arxiu digital
app.arxiu.plugin.class=ARXIU_PLUGIN_CLASS
app.plugin.arxiu.caib.base.url=ARXIU_PLUGIN_CAIB_URL
app.plugin.arxiu.caib.aplicacio.codi=ARXIU_PLUGIN_CAIB_APP_CODI
app.plugin.arxiu.caib.usuari=ARXIU_PLUGIN_CAIB_USUARI
app.plugin.arxiu.caib.contrasenya=ARXIU_PLUGIN_CAIB_CONTRASENYA
app.plugin.arxiu.caib.csv.definicio=ARXIU_PLUGIN_CAIB_CSV_DEF
app.plugin.arxiu.caib.conversio.imprimible.url=ARXIU_PLUGIN_CAIB_IMPRIMIBLE_URL
app.plugin.arxiu.caib.conversio.imprimible.usuari=ARXIU_PLUGIN_CAIB_IMPRIMIBLE_USUARI
app.plugin.arxiu.caib.conversio.imprimible.contrasenya=ARXIU_PLUGIN_CAIB_IMPRIMIBLE_CONTRASENYA

## Plugin de procediments (ROLSAC)
app.procediments.plugin.class=PROCEDIMENTS_PLUGIN_CLASS
app.plugins.procediments.rolsac.service.url=PROCEDIMENTS_PLUGIN_ROLSAC_URL
app.plugins.procediments.rolsac.service.username=PROCEDIMENTS_PLUGIN_ROLSAC_USERNAME
app.plugins.procediments.rolsac.service.password=PROCEDIMENTS_PLUGIN_ROLSAC_PASSWORD

## Plugin d'unitats orgàniques (DIR3)
app.unitats.organiques.dir3.plugin.service.class=UOS_PLUGIN_CLASS
app.unitats.organiques.dir3.plugin.service.url=UOS_PLUGIN_DIR3CAIB_URL
app.unitats.organiques.dir3.plugin.service.username=UOS_PLUGIN_DIR3CAIB_USERNAME
app.unitats.organiques.dir3.plugin.service.password=UOS_PLUGIN_DIR3CAIB_PASSWORD
app.unitats.organiques.dir3.plugin.service.connect.timeout=UOS_PLUGIN_DIR3CAIB_CONNECT_TIMEOUT
app.unitats.organiques.dir3.plugin.service.request.timeout=UOS_PLUGIN_DIR3CAIB_REQUEST_TIMEOUT
app.unitats.organiques.dir3.plugin.service.log.actiu=UOS_PLUGIN_DIR3CAIB_LOG_ACTIU
app.unitats.organiques.dir3.plugin.service.cerca.url=UOS_PLUGIN_DIR3CAIB_CERCA_URL

## Plugin de portafirmes
app.portasignatures.plugin.class=PORTAFIRMES_PLUGIN_CLASS
app.portasignatures.plugin.portafib.base.url=PORTAFIRMES_PLUGIN_PORTAFIB_URL
app.portasignatures.plugin.portafib.username=PORTAFIRMES_PLUGIN_PORTAFIB_USERNAME
app.portasignatures.plugin.portafib.password=PORTAFIRMES_PLUGIN_PORTAFIB_PASSWORD
app.portasignatures.plugin.portafib.perfil=PORTAFIRMES_PLUGIN_PORTAFIB_PERFIL
app.portasignatures.plugin.usuari.id=PORTAFIRMES_PLUGIN_USUARI_ID
app.portasignatures.plugin.portafib.firmasimpleasync.url=PORTAFIRMES_PLUGIN_PORTAFIB_FIRMASIMPLEASYNC_URL

## Plugin de validacio de firmes
app.validatesignature.plugin.class=VALIDATESIGNATURE_PLUGIN_CLASS
app.plugins.validatesignature.afirmacxf.applicationID=VALIDATESIGNATURE_PLUGIN_AFIRMACXF_APPID
app.plugins.validatesignature.afirmacxf.endpoint=VALIDATESIGNATURE_PLUGIN_AFIRMACXF_ENDPOINT
app.plugins.validatesignature.afirmacxf.authorization.username=VALIDATESIGNATURE_PLUGIN_AFIRMACXF_AUTH_USENAME
app.plugins.validatesignature.afirmacxf.authorization.password=VALIDATESIGNATURE_PLUGIN_AFIRMACXF_AUTH_PASSWORD
app.plugins.validatesignature.afirmacxf.authorization.method=VALIDATESIGNATURE_PLUGIN_AFIRMACXF_AUTH_METHOD
app.plugins.validatesignature.afirmacxf.ignoreservercertificates=VALIDATESIGNATURE_PLUGIN_AFIRMACXF_IGNORESERVERCERTS
app.plugins.validatesignature.afirmacxf.TransformersTemplatesPath=VALIDATESIGNATURE_PLUGIN_AFIRMACXF_TRANSFORMERS_TEMPLATES_PATH

## Plugin de dades externes
app.dadesext.dir3.plugin.service.class=DADESEXT_PLUGIN_CLASS
app.dadesext.dir3.plugin.service.url=DADESEXT_PLUGIN_DIR3CAIB_URL

## Integració amb DISTRIBUCIO
app.helium.distribucio.regles.api.rest.url=DISTRIBUCIO_REGLES_PLUGIN_CLASS
app.helium.distribucio.regles.api.rest.usuari=DISTRIBUCIO_REGLES_PLUGIN_USUARI
app.helium.distribucio.regles.api.rest.password=DISTRIBUCIO_REGLES_PLUGIN_PASSWORD
app.helium.distribucio.regles.api.rest.codi.backoffice=DISTRIBUCIO_REGLES_PLUGIN_CODI_BACKOFFICE

## Integració amb COMANDA
app.comanda.api.url=COMANDA_API_URL
app.comanda.api.user=COMANDA_API_USER
app.comanda.api.password=COMANDA_API_PASSWORD
app.comanda.logs.location=COMANDA_API_LOGS_LOCATION
