# Tamany màxim permès pels arxius pujats mitjançant HTTP (en bytes)
spring.http.multipart.max-file-size=MULTIPART_FILE_SIZE

# URL base (applet signatura, estampa signatura defecte, emails tasca)
es.caib.helium.base.url=BASE_URL
# URL base per a la verificació de firmes a Custòdia Antiga
es.caib.helium.arxiu.verificacio.baseurl=VERIFICACIO_BASE_URL

## Conversió de documents amb OpenOffice
es.caib.helium.conversio.actiu=CONVERSIO_ACTIU
es.caib.helium.conversio.openoffice.host=CONVERSIO_OPENOFFICE_HOST
es.caib.helium.conversio.openoffice.port=CONVERSIO_OPENOFFICE_PORT
es.caib.helium.conversio.openoffice.timeout=CONVERSIO_OPENOFFICE_TIMEOUT

## Enviaments de correu
es.caib.helium.correu.remitent=CORREU_REMITENT

## Període en mil·lisegons per a comprovar si hi ha execucions massives pendents
es.caib.helium.massiu.periode.noves=10000

## Plugin de Persones
es.caib.helium.persones.plugin.class=PERSONES_PLUGIN_CLASS
es.caib.helium.plugin.persones.pluginsib.userinformation.keycloak.serverurl=PERSONES_PLUGIN_KEYCLOAK_URL
es.caib.helium.plugin.persones.pluginsib.userinformation.keycloak.realm=PERSONES_PLUGIN_KEYCLOAK_REALM
es.caib.helium.plugin.persones.pluginsib.userinformation.keycloak.client_id=PERSONES_PLUGIN_KEYCLOAK_CLIENT_ID
es.caib.helium.plugin.persones.pluginsib.userinformation.keycloak.client_id_for_user_autentication=PERSONES_PLUGIN_KEYCLOAK_CLIENT_ID_USER_AUTH
es.caib.helium.plugin.persones.pluginsib.userinformation.keycloak.password_secret=PERSONES_PLUGIN_KEYCLOAK_CLIENT_ID_USER_AUTH_SECRET
es.caib.helium.plugin.persones.pluginsib.userinformation.keycloak.mapping.administrationID=PERSONES_PLUGIN_KEYCLOAK_MAP_ADMINID
es.caib.helium.plugin.persones.pluginsib.userinformation.keycloak.debug=PERSONES_PLUGIN_KEYCLOAK_DEBUG

## Plugin de l'arxiu digital
es.caib.helium.arxiu.plugin.class=ARXIU_PLUGIN_CLASS
es.caib.helium.plugin.arxiu.caib.base.url=ARXIU_PLUGIN_CAIB_URL
es.caib.helium.plugin.arxiu.caib.aplicacio.codi=ARXIU_PLUGIN_CAIB_APP_CODI
es.caib.helium.plugin.arxiu.caib.usuari=ARXIU_PLUGIN_CAIB_USUARI
es.caib.helium.plugin.arxiu.caib.contrasenya=ARXIU_PLUGIN_CAIB_CONTRASENYA
es.caib.helium.plugin.arxiu.caib.csv.definicio=ARXIU_PLUGIN_CAIB_CSV_DEF
es.caib.helium.plugin.arxiu.caib.conversio.imprimible.url=ARXIU_PLUGIN_CAIB_IMPRIMIBLE_URL
es.caib.helium.plugin.arxiu.caib.conversio.imprimible.usuari=ARXIU_PLUGIN_CAIB_IMPRIMIBLE_USUARI
es.caib.helium.plugin.arxiu.caib.conversio.imprimible.contrasenya=ARXIU_PLUGIN_CAIB_IMPRIMIBLE_CONTRASENYA

## Plugin de procediments (ROLSAC)
es.caib.helium.procediments.plugin.class=PROCEDIMENTS_PLUGIN_CLASS
es.caib.helium.plugins.procediments.rolsac.service.url=PROCEDIMENTS_PLUGIN_ROLSAC_URL
es.caib.helium.plugins.procediments.rolsac.service.username=PROCEDIMENTS_PLUGIN_ROLSAC_USERNAME
es.caib.helium.plugins.procediments.rolsac.service.password=PROCEDIMENTS_PLUGIN_ROLSAC_PASSWORD

## Plugin d'unitats orgàniques (DIR3)
es.caib.helium.unitats.organiques.dir3.plugin.service.class=UOS_PLUGIN_CLASS
es.caib.helium.unitats.organiques.dir3.plugin.service.url=UOS_PLUGIN_DIR3CAIB_URL
es.caib.helium.unitats.organiques.dir3.plugin.service.username=UOS_PLUGIN_DIR3CAIB_USERNAME
es.caib.helium.unitats.organiques.dir3.plugin.service.password=UOS_PLUGIN_DIR3CAIB_PASSWORD
es.caib.helium.unitats.organiques.dir3.plugin.service.connect.timeout=UOS_PLUGIN_DIR3CAIB_CONNECT_TIMEOUT
es.caib.helium.unitats.organiques.dir3.plugin.service.request.timeout=UOS_PLUGIN_DIR3CAIB_REQUEST_TIMEOUT
es.caib.helium.unitats.organiques.dir3.plugin.service.log.actiu=UOS_PLUGIN_DIR3CAIB_LOG_ACTIU
es.caib.helium.unitats.organiques.dir3.plugin.service.cerca.url=UOS_PLUGIN_DIR3CAIB_CERCA_URL

## Plugin de portafirmes
es.caib.helium.portasignatures.plugin.class=PORTAFIRMES_PLUGIN_CLASS
es.caib.helium.portasignatures.plugin.portafib.base.url=PORTAFIRMES_PLUGIN_PORTAFIB_URL
es.caib.helium.portasignatures.plugin.portafib.username=PORTAFIRMES_PLUGIN_PORTAFIB_USERNAME
es.caib.helium.portasignatures.plugin.portafib.password=PORTAFIRMES_PLUGIN_PORTAFIB_PASSWORD
es.caib.helium.portasignatures.plugin.portafib.perfil=PORTAFIRMES_PLUGIN_PORTAFIB_PERFIL
es.caib.helium.portasignatures.plugin.usuari.id=PORTAFIRMES_PLUGIN_USUARI_ID
es.caib.helium.portasignatures.plugin.portafib.firmasimpleasync.url=PORTAFIRMES_PLUGIN_PORTAFIB_FIRMASIMPLEASYNC_URL

## Plugin de validacio de firmes
es.caib.helium.validatesignature.plugin.class=VALIDATESIGNATURE_PLUGIN_CLASS
es.caib.helium.plugins.validatesignature.afirmacxf.applicationID=VALIDATESIGNATURE_PLUGIN_AFIRMACXF_APPID
es.caib.helium.plugins.validatesignature.afirmacxf.endpoint=VALIDATESIGNATURE_PLUGIN_AFIRMACXF_ENDPOINT
es.caib.helium.plugins.validatesignature.afirmacxf.authorization.username=VALIDATESIGNATURE_PLUGIN_AFIRMACXF_AUTH_USENAME
es.caib.helium.plugins.validatesignature.afirmacxf.authorization.password=VALIDATESIGNATURE_PLUGIN_AFIRMACXF_AUTH_PASSWORD
es.caib.helium.plugins.validatesignature.afirmacxf.authorization.method=VALIDATESIGNATURE_PLUGIN_AFIRMACXF_AUTH_METHOD
es.caib.helium.plugins.validatesignature.afirmacxf.ignoreservercertificates=VALIDATESIGNATURE_PLUGIN_AFIRMACXF_IGNORESERVERCERTS
es.caib.helium.plugins.validatesignature.afirmacxf.TransformersTemplatesPath=VALIDATESIGNATURE_PLUGIN_AFIRMACXF_TRANSFORMERS_TEMPLATES_PATH

## Plugin de dades externes
es.caib.helium.dadesext.dir3.plugin.service.class=DADESEXT_PLUGIN_CLASS
es.caib.helium.dadesext.dir3.plugin.service.url=DADESEXT_PLUGIN_DIR3CAIB_URL

## Integració amb DISTRIBUCIO
es.caib.helium.helium.distribucio.regles.api.rest.url=DISTRIBUCIO_REGLES_PLUGIN_CLASS
es.caib.helium.helium.distribucio.regles.api.rest.usuari=DISTRIBUCIO_REGLES_PLUGIN_USUARI
es.caib.helium.helium.distribucio.regles.api.rest.password=DISTRIBUCIO_REGLES_PLUGIN_PASSWORD
es.caib.helium.helium.distribucio.regles.api.rest.codi.backoffice=DISTRIBUCIO_REGLES_PLUGIN_CODI_BACKOFFICE

## Integració amb COMANDA
es.caib.helium.comanda.api.url=COMANDA_API_URL
es.caib.helium.comanda.api.user=COMANDA_API_USER
es.caib.helium.comanda.api.password=COMANDA_API_PASSWORD
es.caib.helium.comanda.logs.location=COMANDA_API_LOGS_LOCATION
