# Color de fons de la capçalera. Per defecte #ff9523
es.caib.helium.capsalera.color.fons=CAPSALERA_COLOR_FONS
# Color de la lletra de la capçalera. Per defecte white
es.caib.helium.capsalera.color.lletra=CAPSALERA_COLOR_LLETRA
# Per a habilitar/deshabilitar l'accés a la gestió de persones (true,false)
es.caib.helium.persones.actiu=PERSONES_ACTIU
# Per a habilitar/deshabilitar l'accés a la gestió de l'organigrama (true,false)
es.caib.helium.organigrama.actiu=ORGANIGRAMA_ACTIU
# Generador del número d'expedient per defecte (alerta amb els caràcters no permesos per Alfresco)
es.caib.helium.numexp.expression=NUMEXP_EXPRESSION
# Per a fer que el mòdul identity del jBPM agafi les dades de Helium o de les taules del jBPM (helium,jbpm)
es.caib.helium.jbpm.identity.source=IDENTITY_SOURCE
# Per a fer les assignacions de les persones d'una àrea recursives
es.caib.helium.jbpm.identity.recursiu=IDENTITY_RECURSIU
# Hora en què s'enviaràn els emails agrupats d'anotacions a l'usuari
es.caib.helium.anotacions.emails.agrupats.cron=EMAILS_AGRUPATS_CRON
# Indica quin és l'entorn per diferenciar-lo en l'enviament de correus, només pels entorns previs DEV, PRE i SE
es.caib.helium.entorn.helium=ENTORN

# Número de threads en paral·lel per consultar anotacions
es.caib.helium.anotacions.consulta.num.threads=5

# Número de reintents per provar la consulta d'una anotació pendent
es.caib.helium.anotacions.consulta.num.intents=5

# Conversió de documents generant plantilles a les tasques
es.caib.helium.conversio.gentasca.actiu=CONVERSIO_GENTASCA_ACTIU
es.caib.helium.conversio.gentasca.extension=CONVERSIO_GENTASCA_EXTENSION
# Conversió de documents per la signatura
es.caib.helium.conversio.signatura.actiu=CONVERSIO_SIGNATURA_ACTIU
es.caib.helium.conversio.signatura.extension=CONVERSIO_SIGNATURA_EXTENSION
# Conversió de documents ja registrats
es.caib.helium.conversio.registre.actiu=CONVERSIO_REGISTRE_ACTIU
es.caib.helium.conversio.registre.extension=CONVERSIO_REGISTRE_EXTENSION

## Calendari laboral
# Dies no laborables de la setmana (1:dilluns, ..., 7:diumenge)
es.caib.helium.calendari.nolabs=CALENDARI_NOLABS
# Horari laboral
es.caib.helium.calendari.horari=CALENDARI_HORARI
es.caib.helium.calendari.horeslab.dia=CALENDARI_HORESLAB_DIA
es.caib.helium.calendari.horeslab.setmana=CALENDARI_HORESLAB_SETMANA
es.caib.helium.calendari.dieslab.mes=CALENDARI_DIESLAB_MES
es.caib.helium.calendari.dieslab.any=CALENDARI_DIESLAB_ANY

## Enviaments de correu
es.caib.helium.correu.reintents=CORREU_REINTENTS
