# Color de fons de la capçalera. Per defecte app.capsalera.color.fons=#ff9523
app.capsalera.color.fons=CAPSALERA_COLOR_FONS
# Color de la lletra de la capçalera. Per defecte app.capsalera.color.lletra=white
app.capsalera.color.lletra=CAPSALERA_COLOR_LLETRA
# Per a habilitar/deshabilitar l'accés a la gestió de persones (true,false)
app.persones.actiu=PERSONES_ACTIU
# Per a habilitar/deshabilitar l'accés a la gestió de l'organigrama (true,false)
app.organigrama.actiu=ORGANIGRAMA_ACTIU
# Generador del número d'expedient per defecte (alerta amb els caràcters no permesos per Alfresco)
app.numexp.expression=NuMEXP_EXPRESSION
# Per a fer que el mòdul identity del jBPM agafi les dades de Helium o de les taules del jBPM (helium,jbpm)
app.jbpm.identity.source=IDENTITY_SOURCE
# Per a fer les assignacions de les persones d'una àrea recursives
app.jbpm.identity.recursiu=IDENTITY_RECURSIU
# Hora en què s'enviaràn els emails agrupats d'anotacions a l'usuari
app.anotacions.emails.agrupats.cron=EMAILS_AGRUPATS_CRON
# Indica quin és l'entorn per diferenciar-lo en l'enviament de correus, només pels entorns previs DEV, PRE i SE
app.entorn.helium=ENTORN

# Conversió de documents generant plantilles a les tasques
app.conversio.gentasca.actiu=CONVERSIO_GENTASCA_ACTIU
app.conversio.gentasca.extension=CONVERSIO_GENTASCA_EXTENSION
# Conversió de documents per la signatura
app.conversio.signatura.actiu=CONVERSIO_SIGNATURA_ACTIU
app.conversio.signatura.extension=CONVERSIO_SIGNATURA_EXTENSION
# Conversió de documents ja registrats
app.conversio.registre.actiu=CONVERSIO_REGISTRE_ACTIU
app.conversio.registre.extension=CONVERSIO_REGISTRE_EXTENSION
app.conversio.openoffice.timeout=CONVERSIO_REGISTRE_TIMEOUT

## Calendari laboral
# Dies no laborables de la setmana (1:dilluns, ..., 7:diumenge)
app.calendari.nolabs=CALENDARI_NOLABS
# Horari laboral
app.calendari.horari=CALENDARI_HORARI
app.calendari.horeslab.dia=CALENDARI_HORESLAB_DIA
app.calendari.horeslab.setmana=CALENDARI_HORESLAB_SETMANA
app.calendari.dieslab.mes=CALENDARI_DIESLAB_MES
app.calendari.dieslab.any=CALENDARI_DIESLAB_ANY

## Enviaments de correu
app.correu.reintents=CORREU_REINTENTS
