es.caib.concsv.new.digital.archive.organization=DIGITAL_ARCHIVE_ORG
es.caib.concsv.new.digital.archive.version=DIGITAL_ARCHIVE_VERSION
es.caib.concsv.new.digital.archive.traces=DIGITAL_ARCHIVE_TRACES

es.caib.concsv.consult.oldSafeKeeping=OLD_SAFEKEEPING_ACTIVE
es.caib.concsv.consult.newDigitalArchive=DIGITAL_ARCHIVE_ACTIVE

es.caib.concsv.performance=PERFORMANCE_ACTIVE

es.caib.concsv.query.url=http://APP_HOST/concsvfront/view.xhtml?hash=
es.caib.concsv.validation.url=http://APP_HOST/concsvfront

es.caib.concsv.front.preview.enabled=FRONT_PREVIEW_ENABLED