es.caib.concsv.show.captcha=SHOW_CAPTCHA_ACTIVE
es.caib.concsv.logo.path=LOGO_PATH
es.caib.concsv.optionalLabelMetadata.path=LABEL_METADATA_PATH
es.caib.concsv.ws.broker.security.user=WS_SECURITY_USERNAME
es.caib.concsv.ws.broker.security.password=WS_SECURITY_PASSWORD
es.caib.concsv.old.savekeeping.endpoint=OLD_SAFEKEEPING_ENDPOINT
es.caib.concsv.new.digital.archive.endpoint=DIGITAL_ARCHIVE_ENDPOINT
es.caib.concsv.new.digital.archive.app.client=DIGITAL_ARCHIVE_APP
es.caib.concsv.new.digital.archive.username=DIGITAL_ARCHIVE_USERNAME
es.caib.concsv.new.digital.archive.password=DIGITAL_ARCHIVE_PASSWORD
es.caib.concsv.do.tiny=TINY_ACTIVE
es.caib.concsv.tiny.rest.url=TINY_ENDPOINT
es.caib.concsv.tiny.username=TINY_USERNAME
es.caib.concsv.tiny.password=TINY_PASSWORD
es.caib.concsv.plugin.validatesignature.class=VALIDATESIGNATURE_CLASS
es.caib.concsv.plugins.validatesignature.afirmacxf.endpoint=VALIDATESIGNATURE_AFIRMA_ENDPOINT
es.caib.concsv.plugins.validatesignature.afirmacxf.applicationID=VALIDATESIGNATURE_AFIRMA_APP_ID
es.caib.concsv.plugins.validatesignature.afirmacxf.authorization.method=VALIDATESIGNATURE_AFIRMA_AUTH_METHOD
es.caib.concsv.plugins.validatesignature.afirmacxf.authorization.username=VALIDATESIGNATURE_AFIRMA_AUTH_USERNAME
es.caib.concsv.plugins.validatesignature.afirmacxf.authorization.password=VALIDATESIGNATURE_AFIRMA_AUTH_PASSWORD
es.caib.concsv.plugins.validatesignature.afirmacxf.TransformersTemplatesPath=VALIDATESIGNATURE_AFIRMA_TEMPLATES_PATH
es.caib.concsv.plugins.validatesignature.afirmacxf.printxml=VALIDATESIGNATURE_AFIRMA_PRINTXML
es.caib.concsv.plugins.validatesignature.afirmacxf.debug=VALIDATESIGNATURE_AFIRMA_DEBUG
es.caib.concsv.plugins.documentconverter.openoffice.host=DOCUMENTCONVERTER_HOST
es.caib.concsv.plugins.documentconverter.openoffice.port=DOCUMENTCONVERTER_PORT

es.caib.concsv.front.api.url=FRONT_API_URL
es.caib.concsv.front.recaptcha.enabled=FRONT_RECAPTCHA_ENABLED
es.caib.concsv.front.recaptcha.sitekey=FRONT_RECAPTCHA_SITE_KEY

# Ruta al fitxer de text opcional amb la llista de codis CSV's exclosos per descarregar l'original
#es.caib.concsv.arxiu.documents.exclosos.path=/opt/webapps/concsv/documents-exclosos.txt
