<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<groupId>es.caib.helium</groupId>
	<artifactId>helium</artifactId>
	<version>4.0</version>
	<packaging>pom</packaging>
	<parent>
		<groupId>org.springframework.boot</groupId>
		<artifactId>spring-boot-starter-parent</artifactId>
		<version>2.7.18</version>
	</parent>
	<properties>
		<spring-boot.version>2.7.18</spring-boot.version>
		<keycloak.version>21.1.1</keycloak.version>
		<metrics.version>4.2.22</metrics.version>
		<keycloak.version>22.0.4</keycloak.version>
		<orika.starter.version>2.4.6</orika.starter.version>
		<sitemesh.version>2.5.0</sitemesh.version>
		<commons-lang.version>2.6</commons-lang.version>
		<cxf.version>2.2.10</cxf.version>
		<lucene.version>2.9.4</lucene.version>
		<spring-security.version>5.7.11</spring-security.version>
		<jackson.version>3.1.0</jackson.version>
		<regweb.version>3.2.5</regweb.version>
		<dir3caib.version>1.0.7</dir3caib.version>
		<portafib.version>1.1</portafib.version>
		<openapi.version>1.7.0</openapi.version>
		<comanda.version>1.0.0</comanda.version>
		<java.compiler.version>11</java.compiler.version>
		<maven.compiler.target>${java.compiler.version}</maven.compiler.target>
		<maven.compiler.source>${java.compiler.version}</maven.compiler.source>
		<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
		<implementation.vendor>Límit Tecnologies</implementation.vendor>
	</properties>
	<dependencyManagement>
		<dependencies>
			<dependency>
				<groupId>javax.ejb</groupId>
				<artifactId>javax.ejb-api</artifactId>
				<version>3.2.2</version>
			</dependency>
			<dependency>
				<groupId>org.keycloak.bom</groupId>
				<artifactId>keycloak-adapter-bom</artifactId>
				<version>${keycloak.version}</version>
				<type>pom</type>
				<scope>import</scope>
			</dependency>
			<dependency>
				<groupId>opensymphony</groupId>
				<artifactId>sitemesh</artifactId>
				<version>2.5.0</version>
			</dependency>
			<dependency>
				<groupId>dev.akkinoc.spring.boot</groupId>
				<artifactId>orika-spring-boot-starter</artifactId>
				<version>${orika.starter.version}</version>
			</dependency>
		</dependencies>
	</dependencyManagement>
	<modules>
		<module>helium-commons</module>
		<module>helium-disseny</module>
		<module>helium-api-interna</module>
		<module>helium-persistence</module>
		<module>helium-plugin</module>
		<module>helium-plugin-impl</module>
		<module>helium-service-intf</module>
		<module>helium-service</module>
		<module>helium-ejb</module>
		<module>helium-back</module>
		<module>helium-ear</module>
		<!-- mòduls a migrar
		<module>helium-core-api</module>
		<module>helium-disseny</module>
		<module>helium-plugin-api</module>
		<module>helium-plugin-impl</module>
		<module>helium-jbpm3</module>
		<module>helium-core-common</module>
		<module>helium-core</module>
		<module>helium-webapp</module>
		<module>helium-ws</module>
		<module>helium-ear</module>
		<module>helium-applet</module>
		<module>helium-hibernate-entitymanager</module>
		<module>helium-ws-client</module>
		-->
	</modules>
	<build>
		<plugins>
			<plugin>
				<groupId>org.codehaus.mojo</groupId>
				<artifactId>buildnumber-maven-plugin</artifactId>
				<version>3.2.1</version>
				<executions>
					<execution>
						<phase>validate</phase>
						<goals>
							<goal>create</goal>
						</goals>
					</execution>
				</executions>
				<configuration>
					<doCheck>false</doCheck>
					<doUpdate>false</doUpdate>
					<ignoreEmptyScmUrl>true</ignoreEmptyScmUrl>
				</configuration>
			</plugin>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-deploy-plugin</artifactId>
				<configuration>
					<altDeploymentRepository>internal.repo::default::file://${project.build.directory}/mvn-repo</altDeploymentRepository>
				</configuration>
			</plugin>
			<plugin>
				<groupId>com.github.github</groupId>
				<artifactId>site-maven-plugin</artifactId>
				<version>0.12</version>
				<configuration>
					<message>Maven artifacts for ${project.version}</message>
					<outputDirectory>${project.build.directory}/mvn-repo</outputDirectory>
					<noJekyll>true</noJekyll>
					<branch>refs/heads/gh-pages</branch>
					<includes><include>**/*</include></includes>
					<path>maven</path>
					<!-- github repo name -->
					<repositoryName>maven</repositoryName>
					<!-- github username or organization  -->
					<repositoryOwner>GovernIB</repositoryOwner>
					<server>github_governib_maven</server>
					<merge>true</merge>
					<dryRun>false</dryRun>
				</configuration>
				<executions>
					<execution>
						<goals>
							<goal>site</goal>
						</goals>
						<phase>deploy</phase>
					</execution>
				</executions>
			</plugin>
		</plugins>
	</build>

	<distributionManagement>
		<repository>
			<id>github_governib_maven</id>
			<name>GitHub GovernIB Maven Repository</name>
			<url>file://${project.build.directory}/mvn-repo</url>
		</repository>
	</distributionManagement>

	<repositories>
		<repository>
			<id>github-governib-maven-repos</id>
			<name>GitHub GovernIB Maven Repository</name>
			<url>https://governib.github.io/maven/maven/</url>
		</repository>
	</repositories>
</project>
