
package net.conselldemallorca.helium.ws.backoffice.distribucio;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

import es.caib.helium.logic.intf.service.ws.backoffice.distribucio.AnotacioRegistreId;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b14002
 * Generated source version: 2.2
 * 
 */
@WebService(name = "Backoffice", targetNamespace = "http://www.caib.es/distribucio/ws/backoffice")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Backoffice {


    /**
     * 
     * @param ids
     */
    @WebMethod
    @RequestWrapper(localName = "comunicarAnotacionsPendents", targetNamespace = "http://www.caib.es/distribucio/ws/backoffice", className = "net.conselldemallorca.helium.ws.backoffice.distribucio.ComunicarAnotacionsPendents")
    @ResponseWrapper(localName = "comunicarAnotacionsPendentsResponse", targetNamespace = "http://www.caib.es/distribucio/ws/backoffice", className = "net.conselldemallorca.helium.ws.backoffice.distribucio.ComunicarAnotacionsPendentsResponse")
    public void comunicarAnotacionsPendents(
        @WebParam(name = "ids", targetNamespace = "")
        List<AnotacioRegistreId> ids);

}
