-- Retrocedir expedients
CREATE TABLE HEL_EXPEDIENT_LOG(
  ID                   NUMBER(19)               NOT NULL,
  ACCIO_TIPUS          NUMBER(10)               NOT NULL,
  ACCIO_PARAMS         VARCHAR2(255 CHAR),
  DATA                 TIMESTAMP(6)             NOT NULL,
  ESTAT                NUMBER(10)               NOT NULL,
  JBPM_LOGID           NUMBER(19),
  PROCESS_INSTANCE_ID  NUMBER(19),
  TARGET_ID            VARCHAR2(255 CHAR)       NOT NULL,
  USUARI               VARCHAR2(255 CHAR)       NOT NULL,
  EXPEDIENT_ID         NUMBER(19)               NOT NULL,
  PRIMARY KEY (ID),
  CONSTRAINT HEL_EXPEDIENT_LOGS_FK FOREIGN KEY (EXPEDIENT_ID) REFERENCES HEL_EXPEDIENT (ID));

-- Permisos per grup
ALTER TABLE HEL_EXPEDIENT_TIPUS ADD RESTRINGIR_GRUP NUMBER(1) DEFAULT 0;
ALTER TABLE HEL_EXPEDIENT ADD GRUP_CODI VARCHAR2(64 CHAR);

-- Actualització a la nova versió --
INSERT INTO HEL_VERSIO (
    ID,
    CODI,
    ORDRE,
    DATA_CREACIO,
    PROCES_EXECUTAT,
    SCRIPT_EXECUTAT,
    DATA_EXECUCIO_SCRIPT)
SELECT
    HIBERNATE_SEQUENCE.NEXTVAL ID,
    '2.4.0' CODI,
    240 ORDRE,
    SYSDATE DATA_CREACIO,
    0 PROCES_EXECUTAT,
    1 SCRIPT_EXECUTAT,
    SYSDATE DATA_EXECUCIO_SCRIPT
FROM DUAL
WHERE (SELECT COUNT(*) FROM HEL_VERSIO WHERE ORDRE = 240) = 0;
