
package net.conselldemallorca.helium.ws.tramitacio.v1;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

import net.conselldemallorca.helium.integracio.tramitacio.ParellaCodiValor;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b14002
 * Generated source version: 2.2
 * 
 */
@WebService(name = "TramitacioService", targetNamespace = "http://conselldemallorca.net/helium/ws/tramitacio/v1")
@XmlSeeAlso({
    net.conselldemallorca.helium.ws.tramitacio.v1.ObjectFactory.class,
    net.java.dev.jaxb.array.ObjectFactory.class
})
public interface TramitacioService {

	/**
     * 
     * @param entornCodi
     * @param expedientTipusCodi
     * @param numero
     * @param titol
     * @param valorsFormulari
     * @return processInstanceId de l'expedient creat
     * @throws TramitacioException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "iniciExpedient", targetNamespace = "http://conselldemallorca.net/helium/ws/tramitacio/v1", className = "net.conselldemallorca.helium.ws.tramitacio.v1.IniciExpedient")
    @ResponseWrapper(localName = "iniciExpedientResponse", targetNamespace = "http://conselldemallorca.net/helium/ws/tramitacio/v1", className = "net.conselldemallorca.helium.ws.tramitacio.v1.IniciExpedientResponse")
    public String iniciExpedient(
    	@WebParam(name = "entornCodi", targetNamespace = "")
    	String entornCodi,
    	@WebParam(name = "expedientTipusCodi", targetNamespace = "")
    	String expedientTipusCodi,
    	@WebParam(name = "numero", targetNamespace = "")
    	String numero,
    	@WebParam(name = "titol", targetNamespace = "")
    	String titol,
    	@WebParam(name = "valorsFormulari", targetNamespace = "")
    	List<ParellaCodiValor> valorsFormulari)
        throws TramitacioException_Exception
    ;

    /**
     * 
     * @param entornCodi
     * @return llista de tasques personals
     * @throws TramitacioException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "consultaTasquesPersonals", targetNamespace = "http://conselldemallorca.net/helium/ws/tramitacio/v1", className = "net.conselldemallorca.helium.ws.tramitacio.v1.ConsultaTasquesPersonals")
    @ResponseWrapper(localName = "consultaTasquesPersonalsResponse", targetNamespace = "http://conselldemallorca.net/helium/ws/tramitacio/v1", className = "net.conselldemallorca.helium.ws.tramitacio.v1.ConsultaTasquesPersonalsResponse")
    public List<TascaTramitacio> consultaTasquesPersonals(
        @WebParam(name = "entornCodi", targetNamespace = "")
        String entornCodi)
        throws TramitacioException_Exception
    ;

    /**
     * 
     * @param entornCodi
     * @return llista de tasques de grup
     * @throws TramitacioException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "consultaTasquesGrup", targetNamespace = "http://conselldemallorca.net/helium/ws/tramitacio/v1", className = "net.conselldemallorca.helium.ws.tramitacio.v1.ConsultaTasquesGrup")
    @ResponseWrapper(localName = "consultaTasquesGrupResponse", targetNamespace = "http://conselldemallorca.net/helium/ws/tramitacio/v1", className = "net.conselldemallorca.helium.ws.tramitacio.v1.ConsultaTasquesGrupResponse")
    public List<TascaTramitacio> consultaTasquesGrup(
        @WebParam(name = "entornCodi", targetNamespace = "")
        String entornCodi)
        throws TramitacioException_Exception
    ;

    /**
     * 
     * @param entornCodi
     * @param expedientNumero
     * @return llista de tasques personals
     * @throws TramitacioException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "consultaTasquesPersonalsByCodi", targetNamespace = "http://conselldemallorca.net/helium/ws/tramitacio/v1", className = "net.conselldemallorca.helium.ws.tramitacio.v1.ConsultaTasquesPersonalsByCodi")
    @ResponseWrapper(localName = "consultaTasquesPersonalsByCodiResponse", targetNamespace = "http://conselldemallorca.net/helium/ws/tramitacio/v1", className = "net.conselldemallorca.helium.ws.tramitacio.v1.ConsultaTasquesPersonalsByCodiResponse")
    public List<TascaTramitacio> consultaTasquesPersonalsByCodi(
        @WebParam(name = "entornCodi", targetNamespace = "")
        String entornCodi,
        @WebParam(name = "expedientNumero", targetNamespace = "")
        String expedientNumero)
        throws TramitacioException_Exception
    ;

    /**
     * 
     * @param entornCodi
     * @param expedientNumero
     * @return llista de tasques de grup
     * @throws TramitacioException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "consultaTasquesGrupByCodi", targetNamespace = "http://conselldemallorca.net/helium/ws/tramitacio/v1", className = "net.conselldemallorca.helium.ws.tramitacio.v1.ConsultaTasquesGrupByCodi")
    @ResponseWrapper(localName = "consultaTasquesGrupByCodiResponse", targetNamespace = "http://conselldemallorca.net/helium/ws/tramitacio/v1", className = "net.conselldemallorca.helium.ws.tramitacio.v1.ConsultaTasquesGrupByCodiResponse")
    public List<TascaTramitacio> consultaTasquesGrupByCodi(
        @WebParam(name = "entornCodi", targetNamespace = "")
        String entornCodi,
        @WebParam(name = "expedientNumero", targetNamespace = "")
        String expedientNumero)
        throws TramitacioException_Exception
    ;

    /**
     * 
     * @param entornCodi
     * @param tascaId
     * @throws TramitacioException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "agafarTasca", targetNamespace = "http://conselldemallorca.net/helium/ws/tramitacio/v1", className = "net.conselldemallorca.helium.ws.tramitacio.v1.AgafarTasca")
    @ResponseWrapper(localName = "agafarTascaResponse", targetNamespace = "http://conselldemallorca.net/helium/ws/tramitacio/v1", className = "net.conselldemallorca.helium.ws.tramitacio.v1.AgafarTascaResponse")
    public void agafarTasca(
        @WebParam(name = "entornCodi", targetNamespace = "")
        String entornCodi,
        @WebParam(name = "tascaId", targetNamespace = "")
        String tascaId)
        throws TramitacioException_Exception
    ;

    /**
     * 
     * @param entornCodi
     * @param tascaId
     * @throws TramitacioException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "alliberarTasca", targetNamespace = "http://conselldemallorca.net/helium/ws/tramitacio/v1", className = "net.conselldemallorca.helium.ws.tramitacio.v1.AlliberarTasca")
    @ResponseWrapper(localName = "alliberarTascaResponse", targetNamespace = "http://conselldemallorca.net/helium/ws/tramitacio/v1", className = "net.conselldemallorca.helium.ws.tramitacio.v1.AlliberarTascaResponse")
    public void alliberarTasca(
        @WebParam(name = "entornCodi", targetNamespace = "")
        String entornCodi,
        @WebParam(name = "tascaId", targetNamespace = "")
        String tascaId)
        throws TramitacioException_Exception
    ;

    /**
     * 
     * @param entornCodi
     * @param tascaId
     * @return llista de camps del formulari de la tasca
     * @throws TramitacioException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "consultaFormulariTasca", targetNamespace = "http://conselldemallorca.net/helium/ws/tramitacio/v1", className = "net.conselldemallorca.helium.ws.tramitacio.v1.ConsultaFormulariTasca")
    @ResponseWrapper(localName = "consultaFormulariTascaResponse", targetNamespace = "http://conselldemallorca.net/helium/ws/tramitacio/v1", className = "net.conselldemallorca.helium.ws.tramitacio.v1.ConsultaFormulariTascaResponse")
    public List<CampTasca> consultaFormulariTasca(
        @WebParam(name = "entornCodi", targetNamespace = "")
        String entornCodi,
        @WebParam(name = "tascaId", targetNamespace = "")
        String tascaId)
        throws TramitacioException_Exception
    ;

    /**
     * 
     * @param entornCodi
     * @param tascaId
     * @param valorsFormulari
     * @throws TramitacioException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "setDadesFormulariTasca", targetNamespace = "http://conselldemallorca.net/helium/ws/tramitacio/v1", className = "net.conselldemallorca.helium.ws.tramitacio.v1.SetDadesFormulariTasca")
    @ResponseWrapper(localName = "setDadesFormulariTascaResponse", targetNamespace = "http://conselldemallorca.net/helium/ws/tramitacio/v1", className = "net.conselldemallorca.helium.ws.tramitacio.v1.SetDadesFormulariTascaResponse")
    public void setDadesFormulariTasca(
        @WebParam(name = "entornCodi", targetNamespace = "")
        String entornCodi,
        @WebParam(name = "tascaId", targetNamespace = "")
        String tascaId,
        @WebParam(name = "valorsFormulari", targetNamespace = "")
        List<ParellaCodiValor> valorsFormulari)
        throws TramitacioException_Exception
    ;

    /**
     * 
     * @param entornCodi
     * @param tascaId
     * @return llista de documents de la tasca
     * @throws TramitacioException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "consultaDocumentsTasca", targetNamespace = "http://conselldemallorca.net/helium/ws/tramitacio/v1", className = "net.conselldemallorca.helium.ws.tramitacio.v1.ConsultaDocumentsTasca")
    @ResponseWrapper(localName = "consultaDocumentsTascaResponse", targetNamespace = "http://conselldemallorca.net/helium/ws/tramitacio/v1", className = "net.conselldemallorca.helium.ws.tramitacio.v1.ConsultaDocumentsTascaResponse")
    public List<DocumentTasca> consultaDocumentsTasca(
        @WebParam(name = "entornCodi", targetNamespace = "")
        String entornCodi,
        @WebParam(name = "tascaId", targetNamespace = "")
        String tascaId)
        throws TramitacioException_Exception
    ;

    /**
     * 
     * @param entornCodi
     * @param tascaId
     * @param documentCodi
     * @param arxiuNom
     * @param documentData
     * @param arxiuContingut
     * @throws TramitacioException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "setDocumentTasca", targetNamespace = "http://conselldemallorca.net/helium/ws/tramitacio/v1", className = "net.conselldemallorca.helium.ws.tramitacio.v1.SetDocumentTasca")
    @ResponseWrapper(localName = "setDocumentTascaResponse", targetNamespace = "http://conselldemallorca.net/helium/ws/tramitacio/v1", className = "net.conselldemallorca.helium.ws.tramitacio.v1.SetDocumentTascaResponse")
    public void setDocumentTasca(
        @WebParam(name = "entornCodi", targetNamespace = "")
        String entornCodi,
        @WebParam(name = "tascaId", targetNamespace = "")
        String tascaId,
        @WebParam(name = "documentCodi", targetNamespace = "")
        String documentCodi,
        @WebParam(name = "arxiuNom", targetNamespace = "")
        String arxiuNom,
        @WebParam(name = "documentData", targetNamespace = "")
        XMLGregorianCalendar documentData,
        @WebParam(name = "arxiuContingut", targetNamespace = "")
        byte[] arxiuContingut)
        throws TramitacioException_Exception
    ;

    /**
     * 
     * @param entornCodi
     * @param tascaId
     * @param documentCodi
     * @throws TramitacioException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "esborrarDocumentTasca", targetNamespace = "http://conselldemallorca.net/helium/ws/tramitacio/v1", className = "net.conselldemallorca.helium.ws.tramitacio.v1.EsborrarDocumentTasca")
    @ResponseWrapper(localName = "esborrarDocumentTascaResponse", targetNamespace = "http://conselldemallorca.net/helium/ws/tramitacio/v1", className = "net.conselldemallorca.helium.ws.tramitacio.v1.EsborrarDocumentTascaResponse")
    public void esborrarDocumentTasca(
        @WebParam(name = "entornCodi", targetNamespace = "")
        String entornCodi,
        @WebParam(name = "tascaId", targetNamespace = "")
        String tascaId,
        @WebParam(name = "documentCodi", targetNamespace = "")
        String documentCodi)
        throws TramitacioException_Exception
    ;

    /**
     * 
     * @param entornCodi
     * @param tascaId
     * @param transicio
     * @throws TramitacioException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "finalitzarTasca", targetNamespace = "http://conselldemallorca.net/helium/ws/tramitacio/v1", className = "net.conselldemallorca.helium.ws.tramitacio.v1.FinalitzarTasca")
    @ResponseWrapper(localName = "finalitzarTascaResponse", targetNamespace = "http://conselldemallorca.net/helium/ws/tramitacio/v1", className = "net.conselldemallorca.helium.ws.tramitacio.v1.FinalitzarTascaResponse")
    public void finalitzarTasca(
        @WebParam(name = "entornCodi", targetNamespace = "")
        String entornCodi,
        @WebParam(name = "tascaId", targetNamespace = "")
        String tascaId,
        @WebParam(name = "transicio", targetNamespace = "")
        String transicio)
        throws TramitacioException_Exception
    ;

    /**
     * 
     * @param entornCodi
     * @param processInstanceId
     * @return llista de variables de la instància de procés
     * @throws TramitacioException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "consultarVariablesProces", targetNamespace = "http://conselldemallorca.net/helium/ws/tramitacio/v1", className = "net.conselldemallorca.helium.ws.tramitacio.v1.ConsultarVariablesProces")
    @ResponseWrapper(localName = "consultarVariablesProcesResponse", targetNamespace = "http://conselldemallorca.net/helium/ws/tramitacio/v1", className = "net.conselldemallorca.helium.ws.tramitacio.v1.ConsultarVariablesProcesResponse")
    public List<CampProces> consultarVariablesProces(
        @WebParam(name = "entornCodi", targetNamespace = "")
        String entornCodi,
        @WebParam(name = "processInstanceId", targetNamespace = "")
        String processInstanceId)
        throws TramitacioException_Exception
    ;

    /**
     * 
     * @param entornCodi
     * @param processInstanceId
     * @param varCodi
     * @param varValor
     * @throws TramitacioException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "setVariableProces", targetNamespace = "http://conselldemallorca.net/helium/ws/tramitacio/v1", className = "net.conselldemallorca.helium.ws.tramitacio.v1.SetVariableProces")
    @ResponseWrapper(localName = "setVariableProcesResponse", targetNamespace = "http://conselldemallorca.net/helium/ws/tramitacio/v1", className = "net.conselldemallorca.helium.ws.tramitacio.v1.SetVariableProcesResponse")
    public void setVariableProces(
        @WebParam(name = "entornCodi", targetNamespace = "")
        String entornCodi,
        @WebParam(name = "processInstanceId", targetNamespace = "")
        String processInstanceId,
        @WebParam(name = "varCodi", targetNamespace = "")
        String varCodi,
        @WebParam(name = "varValor", targetNamespace = "")
        Object varValor)
        throws TramitacioException_Exception
    ;

    /**
     * 
     * @param entornCodi
     * @param processInstanceId
     * @param varCodi
     * @throws TramitacioException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "esborrarVariableProces", targetNamespace = "http://conselldemallorca.net/helium/ws/tramitacio/v1", className = "net.conselldemallorca.helium.ws.tramitacio.v1.EsborrarVariableProces")
    @ResponseWrapper(localName = "esborrarVariableProcesResponse", targetNamespace = "http://conselldemallorca.net/helium/ws/tramitacio/v1", className = "net.conselldemallorca.helium.ws.tramitacio.v1.EsborrarVariableProcesResponse")
    public void esborrarVariableProces(
        @WebParam(name = "entornCodi", targetNamespace = "")
        String entornCodi,
        @WebParam(name = "processInstanceId", targetNamespace = "")
        String processInstanceId,
        @WebParam(name = "varCodi", targetNamespace = "")
        String varCodi)
        throws TramitacioException_Exception
    ;

    /**
     * 
     * @param entornCodi
     * @param processInstanceId
     * @return la llista de documents de la instància de procés
     * @throws TramitacioException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "consultarDocumentsProces", targetNamespace = "http://conselldemallorca.net/helium/ws/tramitacio/v1", className = "net.conselldemallorca.helium.ws.tramitacio.v1.ConsultarDocumentsProces")
    @ResponseWrapper(localName = "consultarDocumentsProcesResponse", targetNamespace = "http://conselldemallorca.net/helium/ws/tramitacio/v1", className = "net.conselldemallorca.helium.ws.tramitacio.v1.ConsultarDocumentsProcesResponse")
    public List<DocumentProces> consultarDocumentsProces(
        @WebParam(name = "entornCodi", targetNamespace = "")
        String entornCodi,
        @WebParam(name = "processInstanceId", targetNamespace = "")
        String processInstanceId)
        throws TramitacioException_Exception
    ;

    /**
     * 
     * @param documentId
     * @return l'arxiu associat al document
     * @throws TramitacioException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getArxiuProces", targetNamespace = "http://conselldemallorca.net/helium/ws/tramitacio/v1", className = "net.conselldemallorca.helium.ws.tramitacio.v1.GetArxiuProces")
    @ResponseWrapper(localName = "getArxiuProcesResponse", targetNamespace = "http://conselldemallorca.net/helium/ws/tramitacio/v1", className = "net.conselldemallorca.helium.ws.tramitacio.v1.GetArxiuProcesResponse")
    public ArxiuProces getArxiuProces(
        @WebParam(name = "documentId", targetNamespace = "")
        Long documentId)
        throws TramitacioException_Exception
    ;

    /**
     * 
     * @param entornCodi
     * @param processInstanceId
     * @param documentCodi
     * @param arxiuNom
     * @param documentData
     * @param arxiuContingut
     * @return documentId del document creat
     * @throws TramitacioException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "setDocumentProces", targetNamespace = "http://conselldemallorca.net/helium/ws/tramitacio/v1", className = "net.conselldemallorca.helium.ws.tramitacio.v1.SetDocumentProces")
    @ResponseWrapper(localName = "setDocumentProcesResponse", targetNamespace = "http://conselldemallorca.net/helium/ws/tramitacio/v1", className = "net.conselldemallorca.helium.ws.tramitacio.v1.SetDocumentProcesResponse")
    public Long setDocumentProces(
        @WebParam(name = "entornCodi", targetNamespace = "")
        String entornCodi,
        @WebParam(name = "processInstanceId", targetNamespace = "")
        String processInstanceId,
        @WebParam(name = "documentCodi", targetNamespace = "")
        String documentCodi,
        @WebParam(name = "arxiuNom", targetNamespace = "")
        String arxiuNom,
        @WebParam(name = "documentData", targetNamespace = "")
        XMLGregorianCalendar documentData,
        @WebParam(name = "arxiuContingut", targetNamespace = "")
        byte[] arxiuContingut)
        throws TramitacioException_Exception
    ;

    /**
     * 
     * @param entornCodi
     * @param processInstanceId
     * @param documentCodi
     * @throws TramitacioException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "esborrarDocumentProces", targetNamespace = "http://conselldemallorca.net/helium/ws/tramitacio/v1", className = "net.conselldemallorca.helium.ws.tramitacio.v1.EsborrarDocumentProces")
    @ResponseWrapper(localName = "esborrarDocumentProcesResponse", targetNamespace = "http://conselldemallorca.net/helium/ws/tramitacio/v1", className = "net.conselldemallorca.helium.ws.tramitacio.v1.EsborrarDocumentProcesResponse")
    public void esborrarDocumentProces(
        @WebParam(name = "entornCodi", targetNamespace = "")
        String entornCodi,
        @WebParam(name = "processInstanceId", targetNamespace = "")
        String processInstanceId,
        @WebParam(name = "documentCodi", targetNamespace = "")
        Long documentCodi)
        throws TramitacioException_Exception
    ;

    /**
     * 
     * @param entornCodi
     * @param processInstanceId
     * @param accio
     * @throws TramitacioException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "executarAccioProces", targetNamespace = "http://conselldemallorca.net/helium/ws/tramitacio/v1", className = "net.conselldemallorca.helium.ws.tramitacio.v1.ExecutarAccioProces")
    @ResponseWrapper(localName = "executarAccioProcesResponse", targetNamespace = "http://conselldemallorca.net/helium/ws/tramitacio/v1", className = "net.conselldemallorca.helium.ws.tramitacio.v1.ExecutarAccioProcesResponse")
    public void executarAccioProces(
        @WebParam(name = "entornCodi", targetNamespace = "")
        String entornCodi,
        @WebParam(name = "processInstanceId", targetNamespace = "")
        String processInstanceId,
        @WebParam(name = "accio", targetNamespace = "")
        String accio)
        throws TramitacioException_Exception
    ;

    /**
     * 
     * @param entornCodi
     * @param processInstanceId
     * @param script
     * @throws TramitacioException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "executarScriptProces", targetNamespace = "http://conselldemallorca.net/helium/ws/tramitacio/v1", className = "net.conselldemallorca.helium.ws.tramitacio.v1.ExecutarScriptProces")
    @ResponseWrapper(localName = "executarScriptProcesResponse", targetNamespace = "http://conselldemallorca.net/helium/ws/tramitacio/v1", className = "net.conselldemallorca.helium.ws.tramitacio.v1.ExecutarScriptProcesResponse")
    public void executarScriptProces(
        @WebParam(name = "entornCodi", targetNamespace = "")
        String entornCodi,
        @WebParam(name = "processInstanceId", targetNamespace = "")
        String processInstanceId,
        @WebParam(name = "script", targetNamespace = "")
        String script)
        throws TramitacioException_Exception
    ;

    /**
     * 
     * @param entornCodi
     * @param processInstanceId
     * @param motiu
     * @throws TramitacioException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "aturarExpedient", targetNamespace = "http://conselldemallorca.net/helium/ws/tramitacio/v1", className = "net.conselldemallorca.helium.ws.tramitacio.v1.AturarExpedient")
    @ResponseWrapper(localName = "aturarExpedientResponse", targetNamespace = "http://conselldemallorca.net/helium/ws/tramitacio/v1", className = "net.conselldemallorca.helium.ws.tramitacio.v1.AturarExpedientResponse")
    public void aturarExpedient(
        @WebParam(name = "entornCodi", targetNamespace = "")
        String entornCodi,
        @WebParam(name = "processInstanceId", targetNamespace = "")
        String processInstanceId,
        @WebParam(name = "motiu", targetNamespace = "")
        String motiu)
        throws TramitacioException_Exception
    ;

    /**
     * 
     * @param entornCodi
     * @param processInstanceId
     * @throws TramitacioException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "reprendreExpedient", targetNamespace = "http://conselldemallorca.net/helium/ws/tramitacio/v1", className = "net.conselldemallorca.helium.ws.tramitacio.v1.ReprendreExpedient")
    @ResponseWrapper(localName = "reprendreExpedientResponse", targetNamespace = "http://conselldemallorca.net/helium/ws/tramitacio/v1", className = "net.conselldemallorca.helium.ws.tramitacio.v1.ReprendreExpedientResponse")
    public void reprendreExpedient(
        @WebParam(name = "entornCodi", targetNamespace = "")
        String entornCodi,
        @WebParam(name = "processInstanceId", targetNamespace = "")
        String processInstanceId)
        throws TramitacioException_Exception
    ;

    /**
     * 
     * @param entornCodi
     * @param titol
     * @param numero
     * @param dataInici1
     * @param dataInici2
     * @param expedientTipusCodi
     * @param estatCodi
     * @param iniciat
     * @param finalitzat
     * @param geoPosX
     * @param geoPosY
     * @param geoReferencia
     * @return llista d'expedients trobats
     * @throws TramitacioException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "consultaExpedients", targetNamespace = "http://conselldemallorca.net/helium/ws/tramitacio/v1", className = "net.conselldemallorca.helium.ws.tramitacio.v1.ConsultaExpedients")
    @ResponseWrapper(localName = "consultaExpedientsResponse", targetNamespace = "http://conselldemallorca.net/helium/ws/tramitacio/v1", className = "net.conselldemallorca.helium.ws.tramitacio.v1.ConsultaExpedientsResponse")
    public List<ExpedientInfo> consultaExpedients(
        @WebParam(name = "entornCodi", targetNamespace = "")
        String entornCodi,
        @WebParam(name = "titol", targetNamespace = "")
        String titol,
        @WebParam(name = "numero", targetNamespace = "")
        String numero,
        @WebParam(name = "dataInici1", targetNamespace = "")
        XMLGregorianCalendar dataInici1,
        @WebParam(name = "dataInici2", targetNamespace = "")
        XMLGregorianCalendar dataInici2,
        @WebParam(name = "expedientTipusCodi", targetNamespace = "")
        String expedientTipusCodi,
        @WebParam(name = "estatCodi", targetNamespace = "")
        String estatCodi,
        @WebParam(name = "iniciat", targetNamespace = "")
        boolean iniciat,
        @WebParam(name = "finalitzat", targetNamespace = "")
        boolean finalitzat,
        @WebParam(name = "geoPosX", targetNamespace = "")
        Double geoPosX,
        @WebParam(name = "geoPosY", targetNamespace = "")
        Double geoPosY,
        @WebParam(name = "geoReferencia", targetNamespace = "")
        String geoReferencia)
        throws TramitacioException_Exception
    ;

    /**
     * 
     * @param entornCodi
     * @param processInstanceId
     * @throws TramitacioException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "deleteExpedient", targetNamespace = "http://conselldemallorca.net/helium/ws/tramitacio/v1", className = "net.conselldemallorca.helium.ws.tramitacio.v1.DeleteExpedient")
    @ResponseWrapper(localName = "deleteExpedientResponse", targetNamespace = "http://conselldemallorca.net/helium/ws/tramitacio/v1", className = "net.conselldemallorca.helium.ws.tramitacio.v1.DeleteExpedientResponse")
    public void deleteExpedient(
        @WebParam(name = "entornCodi", targetNamespace = "")
        String entornCodi,
        @WebParam(name = "processInstanceId", targetNamespace = "")
        String processInstanceId)
        throws TramitacioException_Exception
    ;

}
