
package net.conselldemallorca.helium.ws.tramitacio.v1;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b14002
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "TramitacioException", targetNamespace = "http://conselldemallorca.net/helium/ws/tramitacio/v1")
public class TramitacioException_Exception
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private TramitacioException faultInfo;

    /**
     * 
     * @param message
     * @param faultInfo
     */
    public TramitacioException_Exception(String message, TramitacioException faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param message
     * @param faultInfo
     * @param cause
     */
    public TramitacioException_Exception(String message, TramitacioException faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: net.conselldemallorca.helium.ws.tramitacio.v1.TramitacioException
     */
    public TramitacioException getFaultInfo() {
        return faultInfo;
    }

}
