spring:
  application:
    name: helium-camunda
  profiles:
    active: @activatedProperties@
  cache:
    jcache:
      config: classpath:ehcache.xml

es:
  caib:
    helium:
      url: http://localhost:8080/heliumback
      helium-data-service-host: http://localhost:8083
      dada-service-user: user
      dada-service-password: pass
      engine: 
        codi: CAMUNDA01

camunda:
  bpm:
    eventing:
      execution: true
      history: true
      task: true

feign:
  client:
    config:
      default:
        loggerLevel: full

logging:
  level:
    es:
      caib:
        helium: info