server:
  port: 8082
  servlet:
    context-path: /helium-camunda
  error:
    include-message: always

spring:
  zipkin:
    enabled: false
  cloud:
    config:
      enabled: false
    discovery:
      enabled: false

  # OracleDB connection settings
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@//localhost:49161/xe
    username: hel_camunda1
    password: hel_camunda1
  # HikariCP settings
    hikari:
      minimumIdle: 5
      maximumPoolSize: 20
      idleTimeout: 30000
      maxLifetime: 2000000
      connectionTimeout: 30000
      poolName: HikariPoolDominis

  # JPA settings
  jpa:
    database: oracle
    database-platform: org.hibernate.dialect.Oracle12cDialect
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: false

  servlet:
    multipart:
      max-file-size: -1
      max-request-size: -1

camunda.bpm:
  admin-user:
    id: demo
    password: demo
    firstName: Demo
  filter:
    create: All tasks
  database:
camunda:
  bpm:
    database:
      type: oracle
      jdbc-batch-processing: false
#      schema-update: true
#      schema-name: hel_camunda

    eventing:
      execution: true
      history: true
      task: true

keycloak:
  realm: GOIB
  auth-server-url: http://docker.limit.es:21234/auth
  resource: goib-default
  public-client: true
  principal-attribute: preferred_username
  use-resource-role-mappings: true
  bearer-only: true

es:
  caib:
    helium:
      camunda:
        deployment:
          path: /home/siona/Feina/Server/camunda-bpm-wildfly-7.15.0/server/wildfly-22.0.1.Final/standalone/deployments

feign:
  client:
    config:
      default:
        loggerLevel: full