-- #1645 Incloure l'edició dels fluxos de firma a Helium


-- Oracle
ALTER TABLE HEL_DOCUMENT ADD (	
		PORTAFIRMES_FLUX_ID VARCHAR2(64 CHAR),
		PORTAFIRMES_ACTIU NUMBER(1) default 0, 
		PORTAFIRMES_RESPONSABLES VARCHAR2(512 CHAR),  
		PORTAFIRMES_FLUXTIP VARCHAR2(256 CHAR),
		PORTAFIRMES_SEQTIP VARCHAR2(256 CHAR)
		);	
ALTER TABLE HEL_PORTASIGNATURES MODIFY TOKEN_ID NUMBER(19,0) NULL;


-- Postgresql
ALTER TABLE HEL_DOCUMENT ADD (
	PORTAFIRMES_FLUX_ID     	character varying(64),
	PORTAFIRMES_ACTIU       	boolean DEFAULT FALSE,
	PORTAFIRMES_RESPONSABLES    character varying(512),
 	PORTAFIRMES_FLUXTIP     	character varying(256),
 	PORTAFIRMES_SEQTIP 			character varying(256)
 	); 	
ALTER TABLE HEL_PORTASIGNATURES ALTER COLUMN TOKEN_ID DROP NOT NULL;