//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.03.02 at 07:16:11 PM CET 
//


package es.caib.helium.domini.ws;

import es.caib.helium.domini.model.FilaResultat;
import es.caib.helium.domini.model.ParellaCodiValor;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the es.caib.helium.domini.ws package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _ConsultaDomini_QNAME = new QName("http://domini.integracio.helium.conselldemallorca.net/", "consultaDomini");
    private final static QName _ConsultaDominiResponse_QNAME = new QName("http://domini.integracio.helium.conselldemallorca.net/", "consultaDominiResponse");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: es.caib.helium.domini.ws
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ConsultaDomini }
     * 
     */
    public ConsultaDomini createConsultaDomini() {
        return new ConsultaDomini();
    }

    /**
     * Create an instance of {@link ConsultaDominiResponse }
     * 
     */
    public ConsultaDominiResponse createConsultaDominiResponse() {
        return new ConsultaDominiResponse();
    }

    /**
     * Create an instance of {@link ParellaCodiValor }
     * 
     */
    public ParellaCodiValor createParellaCodiValor() {
        return new ParellaCodiValor();
    }

    /**
     * Create an instance of {@link FilaResultat }
     * 
     */
    public FilaResultat createFilaResultat() {
        return new FilaResultat();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ConsultaDomini }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link ConsultaDomini }{@code >}
     */
    @XmlElementDecl(namespace = "http://domini.integracio.helium.conselldemallorca.net/", name = "consultaDomini")
    public JAXBElement<ConsultaDomini> createConsultaDomini(ConsultaDomini value) {
        return new JAXBElement<ConsultaDomini>(_ConsultaDomini_QNAME, ConsultaDomini.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ConsultaDominiResponse }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link ConsultaDominiResponse }{@code >}
     */
    @XmlElementDecl(namespace = "http://domini.integracio.helium.conselldemallorca.net/", name = "consultaDominiResponse")
    public JAXBElement<ConsultaDominiResponse> createConsultaDominiResponse(ConsultaDominiResponse value) {
        return new JAXBElement<ConsultaDominiResponse>(_ConsultaDominiResponse_QNAME, ConsultaDominiResponse.class, null, value);
    }

}
