-- Millorar logs portasignatures
ALTER TABLE HEL_PORTASIGNATURES ADD DATA_CB_DAR TIMESTAMP(6);
ALTER TABLE HEL_PORTASIGNATURES ADD DATA_CB_PRI TIMESTAMP(6);
ALTER TABLE HEL_PORTASIGNATURES ADD ERROR_CB_PROCES CLOB;

