-- Canvi a MAVEN --
UPDATE HEL_ACL_CLASS SET CLASS = 'net.conselldemallorca.helium.core.model.hibernate.Entorn' WHERE CLASS = 'net.conselldemallorca.helium.model.hibernate.Entorn';
UPDATE HEL_ACL_CLASS SET CLASS = 'net.conselldemallorca.helium.core.model.hibernate.ExpedientTipus' WHERE CLASS = 'net.conselldemallorca.helium.model.hibernate.ExpedientTipus';

-- Mapejos de SISTRA --
CREATE TABLE HEL_MAP_SISTRA(
        ID NUMBER(19) NOT NULL,
        CODIHELIUM VARCHAR2(255 CHAR) NOT NULL,
        CODISISTRA VARCHAR2(255 CHAR) NOT NULL,
        TIPUS NUMBER(10) NOT NULL,
        EXPEDIENT_TIPUS_ID NUMBER(19) NOT NULL,
        PRIMARY KEY (ID),
        CONSTRAINT HEL_EXPTIPUS_MAP_SISTRA_FK FOREIGN KEY (EXPEDIENT_TIPUS_ID) REFERENCES
        HEL_EXPEDIENT_TIPUS (ID),
        CONSTRAINT SYS_C0035059 UNIQUE (CODIHELIUM, EXPEDIENT_TIPUS_ID)
    );

-- Gestió de versions --
ALTER TABLE HEL_VERSIO ADD DATA_EXECUCIO TIMESTAMP(6);
ALTER TABLE HEL_VERSIO ADD PROCES_EXECUTAT NUMBER(1);
UPDATE HEL_VERSIO SET PROCES_EXECUTAT = 1, DATA_EXECUCIO = SYSDATE WHERE CODI = 'inicial';

-- Annexió automática de documents generats amb plantilla --
ALTER TABLE HEL_DOCUMENT
 ADD (ADJUNTAR_AUTO        NUMBER(1));
UPDATE HEL_DOCUMENT SET ADJUNTAR_AUTO = 1;

-- Canvi a la nova versió --
UPDATE HEL_IDGEN SET VALOR = VALOR+1 WHERE TAULA = 'hel_versio';
INSERT INTO HEL_VERSIO (ID, CODI, ORDRE, PROCES_EXECUTAT, DATA_EXECUCIO) VALUES ((SELECT VALOR FROM HEL_IDGEN WHERE TAULA = 'hel_versio' ),'2.1.0', 210, 0, SYSDATE);
