-- Consultes avançades --
ALTER TABLE HEL_CONSULTA
 ADD (INFORME_CONTINGUT        BLOB);
ALTER TABLE HEL_CONSULTA
 ADD (EXPORTAR_ACTIU        NUMBER(1) DEFAULT 1);
UPDATE HEL_CONSULTA SET EXPORTAR_ACTIU = 1;

-- Actualització a la nova versió --
INSERT INTO HEL_VERSIO (
    ID,
    CODI,
    ORDRE,
    DATA_CREACIO,
    PROCES_EXECUTAT,
    SCRIPT_EXECUTAT,
    DATA_EXECUCIO_SCRIPT)
SELECT
    HIBERNATE_SEQUENCE.NEXTVAL ID,
    '2.2.0' CODI,
    220 ORDRE,
    SYSDATE DATA_CREACIO,
    0 PROCES_EXECUTAT,
    1 SCRIPT_EXECUTAT,
    SYSDATE DATA_EXECUCIO_SCRIPT
FROM DUAL
WHERE (SELECT COUNT(*) FROM HEL_VERSIO WHERE ORDRE = 220) = 0;