-- Tipus de dada dels camps tipus textarea
ALTER TABLE HELIUM.JBPM_VARIABLEINSTANCE ADD (aux_clob CLOB);
UPDATE HELIUM.JBPM_VARIABLEINSTANCE SET aux_clob = STRINGVALUE_;
ALTER TABLE HELIUM.JBPM_VARIABLEINSTANCE DROP COLUMN STRINGVALUE_;
ALTER TABLE HELIUM.JBPM_VARIABLEINSTANCE RENAME COLUMN aux_clob TO STRINGVALUE_;

-- Actualització a la nova versió --
INSERT INTO HEL_VERSIO (
    ID,
    CODI,
    ORDRE,
    DATA_CREACIO,
    PROCES_EXECUTAT,
    SCRIPT_EXECUTAT,
    DATA_EXECUCIO_SCRIPT)
SELECT
    HIBERNATE_SEQUENCE.NEXTVAL ID,
    '2.5.0' CODI,
    250 ORDRE,
    SYSDATE DATA_CREACIO,
    0 PROCES_EXECUTAT,
    1 SCRIPT_EXECUTAT,
    SYSDATE DATA_EXECUCIO_SCRIPT
FROM DUAL
WHERE (SELECT COUNT(*) FROM HEL_VERSIO WHERE ORDRE = 250) = 0;
