
package net.conselldemallorca.helium.integracio.redose.client.wsdl;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.1 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "BackofficeFacadeService", targetNamespace = "urn:es:caib:redose:ws:v1:services", wsdlLocation = "file:/C:/Documents%20and%20Settings/josepg/Escritorio/actual/redose_ws/BackofficeFacade.wsdl")
public class BackofficeFacadeService
    extends Service
{

    private final static URL BACKOFFICEFACADESERVICE_WSDL_LOCATION;

    static {
        URL url = null;
        try {
            url = new URL("file:/C:/Documents%20and%20Settings/josepg/Escritorio/actual/redose_ws/BackofficeFacade.wsdl");
        } catch (MalformedURLException e) {
            e.printStackTrace();
        }
        BACKOFFICEFACADESERVICE_WSDL_LOCATION = url;
    }

    public BackofficeFacadeService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public BackofficeFacadeService() {
        super(BACKOFFICEFACADESERVICE_WSDL_LOCATION, new QName("urn:es:caib:redose:ws:v1:services", "BackofficeFacadeService"));
    }

    /**
     * 
     * @return
     *     returns BackofficeFacade
     */
    @WebEndpoint(name = "BackofficeFacade")
    public BackofficeFacade getBackofficeFacade() {
        return (BackofficeFacade)super.getPort(new QName("urn:es:caib:redose:ws:v1:services", "BackofficeFacade"), BackofficeFacade.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns BackofficeFacade
     */
    @WebEndpoint(name = "BackofficeFacade")
    public BackofficeFacade getBackofficeFacade(WebServiceFeature... features) {
        return (BackofficeFacade)super.getPort(new QName("urn:es:caib:redose:ws:v1:services", "BackofficeFacade"), BackofficeFacade.class, features);
    }

}
