
package net.conselldemallorca.helium.integracio.redose.client.wsdl;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.1 in JDK 6
 * Generated source version: 2.1
 * 
 */
@SuppressWarnings("serial")
@WebFault(name = "fault", targetNamespace = "urn:es:caib:redose:ws:v1:model:BackofficeFacade")
public class BackofficeFacadeException_Exception
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private BackofficeFacadeException faultInfo;

    /**
     * 
     * @param message
     * @param faultInfo
     */
    public BackofficeFacadeException_Exception(String message, BackofficeFacadeException faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param message
     * @param faultInfo
     * @param cause
     */
    public BackofficeFacadeException_Exception(String message, BackofficeFacadeException faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: net.conselldemallorca.helium.integracio.redose.wsdl.BackofficeFacadeException
     */
    public BackofficeFacadeException getFaultInfo() {
        return faultInfo;
    }

}
