
package net.conselldemallorca.helium.integracio.redose.client.wsdl;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.1 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "BackofficeFacade", targetNamespace = "urn:es:caib:redose:ws:v1:services")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface BackofficeFacade {


    /**
     * 
     * @param documento
     * @return
     *     returns net.conselldemallorca.helium.integracio.redose.wsdl.ReferenciaRDS
     * @throws BackofficeFacadeException_Exception
     */
    @WebMethod
    @WebResult(name = "insertarDocumentoReturn", targetNamespace = "urn:es:caib:redose:ws:v1:model:BackofficeFacade")
    @RequestWrapper(localName = "insertarDocumento", targetNamespace = "urn:es:caib:redose:ws:v1:model:BackofficeFacade", className = "net.conselldemallorca.helium.integracio.redose.wsdl.InsertarDocumento")
    @ResponseWrapper(localName = "insertarDocumentoResponse", targetNamespace = "urn:es:caib:redose:ws:v1:model:BackofficeFacade", className = "net.conselldemallorca.helium.integracio.redose.wsdl.InsertarDocumentoResponse")
    public ReferenciaRDS insertarDocumento(
        @WebParam(name = "documento", targetNamespace = "urn:es:caib:redose:ws:v1:model:BackofficeFacade")
        DocumentoRDS documento)
        throws BackofficeFacadeException_Exception
    ;

    /**
     * 
     * @param referencia
     * @return
     *     returns net.conselldemallorca.helium.integracio.redose.wsdl.DocumentoRDS
     * @throws BackofficeFacadeException_Exception
     */
    @WebMethod
    @WebResult(name = "consultarDocumentoReturn", targetNamespace = "urn:es:caib:redose:ws:v1:model:BackofficeFacade")
    @RequestWrapper(localName = "consultarDocumento", targetNamespace = "urn:es:caib:redose:ws:v1:model:BackofficeFacade", className = "net.conselldemallorca.helium.integracio.redose.wsdl.ConsultarDocumento")
    @ResponseWrapper(localName = "consultarDocumentoResponse", targetNamespace = "urn:es:caib:redose:ws:v1:model:BackofficeFacade", className = "net.conselldemallorca.helium.integracio.redose.wsdl.ConsultarDocumentoResponse")
    public DocumentoRDS consultarDocumento(
        @WebParam(name = "referencia", targetNamespace = "urn:es:caib:redose:ws:v1:model:BackofficeFacade")
        ReferenciaRDS referencia)
        throws BackofficeFacadeException_Exception
    ;

}
