
-- Actualització a la nova versió --
INSERT INTO HEL_VERSIO (
    ID,
    CODI,
    ORDRE,
    DATA_CREACIO,
    PROCES_EXECUTAT,
    SCRIPT_EXECUTAT,
    DATA_EXECUCIO_SCRIPT)
SELECT
    HIBERNATE_SEQUENCE.NEXTVAL ID,
    '3.3.0' CODI,
    330 ORDRE,
    SYSDATE DATA_CREACIO,
    0 PROCES_EXECUTAT,
    1 SCRIPT_EXECUTAT,
    SYSDATE DATA_EXECUCIO_SCRIPT
FROM DUAL
WHERE (SELECT COUNT(*) FROM HEL_VERSIO WHERE ORDRE = 330) = 0;

-- #1627 HELIUM sense motor de WF 

-- Nou camp pel tipus d'expedient ESTATS/FLUX
ALTER TABLE HEL_EXPEDIENT_TIPUS ADD TIPUS NUMBER(10) DEFAULT 0 NOT NULL;

-- Nou camp pel tipus d'acció ACCIO/HANDLER_PROPI/HANDLER_PREDEFINIT/SCRIPT
ALTER TABLE HEL_ACCIO ADD TIPUS VARCHAR2(32 CHAR) DEFAULT 'ACCIO' NOT NULL;
ALTER TABLE HEL_ACCIO ADD SCRIPT VARCHAR2(1024 CHAR);
ALTER TABLE HEL_ACCIO MODIFY (JBPM_ACTION NULL);

-- Nous camps per accions d'execució de handlers predefinits i propis
ALTER TABLE HEL_ACCIO ADD HANDLER_CLASSE VARCHAR2(255 CHAR);
ALTER TABLE HEL_ACCIO ADD HANDLER_DADES CLOB;

-- -- Nova taula per les regles dels estats
CREATE TABLE HEL_ESTAT_REGLA (
    ID				    NUMBER(19) 	        NOT NULL,
    NOM 				VARCHAR2(255 CHAR) 	NOT NULL,
    EXPEDIENT_TIPUS_ID  NUMBER(19) 	        NOT NULL,
    ESTAT_ID			NUMBER(19) 	        NOT NULL,
    ENTORN_ID			NUMBER(19) 	        NOT NULL,
    QUI 				VARCHAR2(32 CHAR) 	NOT NULL,
    QUE 				VARCHAR2(32 CHAR) 	NOT NULL,
    ACCIO 				VARCHAR2(32 CHAR) 	NOT NULL,
    ORDRE               NUMBER(10)          NOT NULL
);

CREATE TABLE HEL_ESTAT_REGLA_VALOR_QUI (
    REGLA_ID            NUMBER(19) 	        NOT NULL,
    VALOR 				VARCHAR2(255 CHAR) 	NOT NULL
);

CREATE TABLE HEL_ESTAT_REGLA_VALOR_QUE (
    REGLA_ID            NUMBER(19) 	        NOT NULL,
    VALOR 				VARCHAR2(255 CHAR) 	NOT NULL
);

ALTER TABLE HEL_ESTAT_REGLA ADD (CONSTRAINT HEL_ESTAT_REGLA_PK PRIMARY KEY (ID));
ALTER TABLE HEL_ESTAT_REGLA_VALOR_QUI ADD (CONSTRAINT HEL_ESTAT_REGLA_VALOR_QUI_PK PRIMARY KEY (REGLA_ID, VALOR));
ALTER TABLE HEL_ESTAT_REGLA_VALOR_QUE ADD (CONSTRAINT HEL_ESTAT_REGLA_VALOR_QUE_PK PRIMARY KEY (REGLA_ID, VALOR));

ALTER TABLE HEL_ESTAT_REGLA ADD (CONSTRAINT HEL_REGLA_EXPTIPUS_FK FOREIGN KEY (EXPEDIENT_TIPUS_ID) REFERENCES HEL_EXPEDIENT_TIPUS (ID));
ALTER TABLE HEL_ESTAT_REGLA ADD (CONSTRAINT HEL_REGLA_ESTAT_FK FOREIGN KEY (ESTAT_ID) REFERENCES HEL_ESTAT (ID));
ALTER TABLE HEL_ESTAT_REGLA ADD (CONSTRAINT HEL_REGLA_ENTORN_FK FOREIGN KEY (ENTORN_ID) REFERENCES HEL_ENTORN (ID));
ALTER TABLE HEL_ESTAT_REGLA ADD (CONSTRAINT HEL_REGLA_NOM_UK UNIQUE (ESTAT_ID, NOM));
ALTER TABLE HEL_ESTAT_REGLA_VALOR_QUI ADD (CONSTRAINT HEL_REGLA_VALOR_QUI_FK FOREIGN KEY (REGLA_ID) REFERENCES HEL_ESTAT_REGLA (ID));
ALTER TABLE HEL_ESTAT_REGLA_VALOR_QUE ADD (CONSTRAINT HEL_REGLA_VALOR_QUE_FK FOREIGN KEY (REGLA_ID) REFERENCES HEL_ESTAT_REGLA (ID));

CREATE INDEX HEL_REGLA_ENTORN_FK_I ON HEL_ESTAT_REGLA(ENTORN_ID);
CREATE INDEX HEL_REGLA_EXPTIPUS_FK_I ON HEL_ESTAT_REGLA(EXPEDIENT_TIPUS_ID);
CREATE INDEX HEL_REGLA_ESTAT_FK_I ON HEL_ESTAT_REGLA(ESTAT_ID);
CREATE INDEX HEL_REGLA_VALOR_QUI_FK_I ON HEL_ESTAT_REGLA_VALOR_QUI(REGLA_ID);
CREATE INDEX HEL_REGLA_VALOR_QUE_FK_I ON HEL_ESTAT_REGLA_VALOR_QUE(REGLA_ID);

GRANT SELECT, UPDATE, INSERT, DELETE ON HEL_ESTAT_REGLA TO WWW_HELIUM;
GRANT SELECT, UPDATE, INSERT, DELETE ON HEL_ESTAT_REGLA_VALOR_QUI TO WWW_HELIUM;
GRANT SELECT, UPDATE, INSERT, DELETE ON HEL_ESTAT_REGLA_VALOR_QUE TO WWW_HELIUM;


-- Noves taules per la relació entre estats i accions d'entrada i sortida

CREATE TABLE HEL_ESTAT_ACCIO_ENTRADA (
    ID				    NUMBER(19) 	        NOT NULL,
    ESTAT_ID			NUMBER(19) 	        NOT NULL,
    ACCIO_ID			NUMBER(19) 	        NOT NULL,
    ORDRE               NUMBER(10)          NOT NULL
);

CREATE TABLE HEL_ESTAT_ACCIO_SORTIDA (
    ID				    NUMBER(19) 	        NOT NULL,
    ESTAT_ID			NUMBER(19) 	        NOT NULL,
    ACCIO_ID			NUMBER(19) 	        NOT NULL,
    ORDRE               NUMBER(10)          NOT NULL
);

ALTER TABLE HEL_ESTAT_ACCIO_ENTRADA ADD (CONSTRAINT HEL_ESTACC_ENT_PK PRIMARY KEY (ID));
ALTER TABLE HEL_ESTAT_ACCIO_SORTIDA ADD (CONSTRAINT HEL_ESTACC_SORT_PK PRIMARY KEY (ID));

ALTER TABLE HEL_ESTAT_ACCIO_ENTRADA ADD (CONSTRAINT HEL_ESTACC_ENT_ESTAT_FK FOREIGN KEY (ESTAT_ID) REFERENCES HEL_ESTAT (ID));
ALTER TABLE HEL_ESTAT_ACCIO_ENTRADA ADD (CONSTRAINT HEL_ESTACC_ENT_ACCIO_FK FOREIGN KEY (ACCIO_ID) REFERENCES HEL_ACCIO (ID));
ALTER TABLE HEL_ESTAT_ACCIO_SORTIDA ADD (CONSTRAINT HEL_ESTACC_SORT_ESTAT_FK FOREIGN KEY (ESTAT_ID) REFERENCES HEL_ESTAT (ID));
ALTER TABLE HEL_ESTAT_ACCIO_SORTIDA ADD (CONSTRAINT HEL_ESTACC_SORT_ACCIO_FK FOREIGN KEY (ACCIO_ID) REFERENCES HEL_ACCIO (ID));

CREATE INDEX HEL_ESTACC_ENT_ESTAT_FK_I ON HEL_ESTAT_ACCIO_ENTRADA(ESTAT_ID);
CREATE INDEX HEL_ESTACC_SORT_ESTAT_FK_I ON HEL_ESTAT_ACCIO_SORTIDA(ESTAT_ID);

GRANT SELECT, UPDATE, INSERT, DELETE ON HEL_ESTAT_ACCIO_ENTRADA TO WWW_HELIUM;
GRANT SELECT, UPDATE, INSERT, DELETE ON HEL_ESTAT_ACCIO_SORTIDA TO WWW_HELIUM;

-- #1645 Incloure l'edició dels fluxos de firma a Helium
ALTER TABLE HEL_DOCUMENT ADD (	
		PORTAFIRMES_FLUX_ID VARCHAR2(64 CHAR),
		PORTAFIRMES_ACTIU NUMBER(1) default 0, 
		PORTAFIRMES_RESPONSABLES VARCHAR2(512 CHAR),  
		PORTAFIRMES_FLUXTIP VARCHAR2(256 CHAR),
		PORTAFIRMES_SEQTIP VARCHAR2(256 CHAR)
		);

ALTER TABLE HEL_PORTASIGNATURES MODIFY TOKEN_ID NUMBER(19,0) NULL;

--#1656 Permetre notificar més d'un document i a la vegada en un .zip
CREATE TABLE HEL_DOCUMENT_CONTINGUT (
  ID NUMBER(19)	NOT NULL,
  DOCUMENT_CONTINGUT NUMBER(19)			NOT NULL
);

GRANT SELECT, UPDATE, INSERT, DELETE ON HEL_DOCUMENT_CONTINGUT TO WWW_HELIUM;

ALTER TABLE HEL_DOCUMENT_CONTINGUT 	ADD (CONSTRAINT HEL_DOCSTORE_DOCCONT_ID_FK FOREIGN KEY (ID) REFERENCES HEL_DOCUMENT_STORE (ID));
ALTER TABLE HEL_DOCUMENT_CONTINGUT 	ADD (CONSTRAINT HEL_DOCSTORE_DOCCONT_CONT_FK FOREIGN KEY (DOCUMENT_CONTINGUT) REFERENCES HEL_DOCUMENT_STORE (ID));

--#1705 Error notificant document amb descripció llarga
-- Incrementar llargària camp DESCRIPCIO
ALTER TABLE HEL_DOCUMENT_NOTIFICACIO MODIFY DESCRIPCIO VARCHAR2(1000 CHAR);
