-- #1917 Implementar un API d'estadístiques que pugui ser consultat per un sistema extern

CREATE TABLE HEL_EXPLOT_DIM (
	ID NUMBER(19,0) NOT NULL,
	UNITAT_ORGANITZATIVA_ID NUMBER(19,0),
	UNITAT_ORGANITZATIVA_CODI VARCHAR2(9),
	ENTORN_ID NUMBER(19,0) NOT NULL,
	ENTORN_CODI VARCHAR2(64) NOT NULL,
	TIPUS_ID NUMBER(19,0) NOT NULL,
	TIPUS_CODI VARCHAR2(64) NOT NULL,
	CONSTRAINT PK_HEL_EXPLOT_DIM PRIMARY KEY (ID)
);

ALTER TABLE HEL_EXPLOT_DIM ADD CONSTRAINT HEL_EXPLOT_DIM_UK UNIQUE (
	UNITAT_ORGANITZATIVA_ID,
	ENTORN_ID,
	TIPUS_ID
);

CREATE TABLE HEL_EXPLOT_TEMPS (
	ID NUMBER(19, 0) NOT NULL,
	DATA date NOT NULL,
	ANUALITAT INTEGER NOT NULL,
	MES INTEGER NOT NULL,
	TRIMESTRE INTEGER NOT NULL,
	SETMANA INTEGER NOT NULL,
	DIA INTEGER NOT NULL,
	DIA_SETMANA VARCHAR2(2 CHAR),
	CONSTRAINT PK_HEL_EXPLOT_TEMPS PRIMARY KEY (ID)
);

CREATE TABLE HEL_EXPLOT_FET (
	ID NUMBER(19,0) NOT NULL,
	EXP_OBE NUMBER(19,0) NOT NULL,
	EXP_TAN NUMBER(19,0) NOT NULL,
	EXP_ANUL NUMBER(19,0) NOT NULL,
	EXP_ARX NUMBER(19,0) NOT NULL,
	EXP_NO_ANUL NUMBER(19,0) NOT NULL,
	EXP_TOTAL NUMBER(19,0) NOT NULL,
	TAS_PEN NUMBER(19,0) NOT NULL,
	TAS_FIN NUMBER(19,0) NOT NULL,
	AN_PEN NUMBER(19,0) NOT NULL,
	AN_PROC NUMBER(19,0) NOT NULL,
	CO_PINBAL NUMBER(19,0) NOT NULL,
	CO_NOTIB NUMBER(19,0) NOT NULL,
	CO_PORTAFIB NUMBER(19,0) NOT NULL,
	DIMENSIO_ID NUMBER(19,0) NOT NULL,
	TEMPS_ID NUMBER(19,0) NOT NULL,
	CONSTRAINT PK_HEL_EXPLOT_FET PRIMARY KEY (id)
);

ALTER TABLE HEL_EXPLOT_FET ADD CONSTRAINT FK_HEL_EXPLOT_FET_DIM FOREIGN KEY (DIMENSIO_ID) REFERENCES HEL_EXPLOT_DIM (ID);
ALTER TABLE HEL_EXPLOT_FET ADD CONSTRAINT FK_HEL_EXPLOT_FET_TEMPS FOREIGN KEY (TEMPS_ID) REFERENCES HEL_EXPLOT_TEMPS (ID);

CREATE PUBLIC SYNONYM HEL_EXPLOT_DIM FOR HEL_EXPLOT_DIM;
CREATE PUBLIC SYNONYM HEL_EXPLOT_TEMPS FOR HEL_EXPLOT_TEMPS;
CREATE PUBLIC SYNONYM HEL_EXPLOT_FET FOR HEL_EXPLOT_FET;

GRANT SELECT, UPDATE, INSERT, DELETE ON HEL_EXPLOT_DIM TO WWW_HELIUM;
GRANT SELECT, UPDATE, INSERT, DELETE ON HEL_EXPLOT_TEMPS TO WWW_HELIUM;
GRANT SELECT, UPDATE, INSERT, DELETE ON HEL_EXPLOT_FET TO WWW_HELIUM;

-- Postgresql

