--#1696 Guardar la traça de l'error en el processament d'anotacions

-- Oracle
ALTER TABLE HEL_ANOTACIO MODIFY ERROR_PROCESSAMENT VARCHAR2(2048 CHAR);

-- Postgresql
ALTER TABLE HEL_ANOTACIO MODIFY ERROR_PROCESSAMENT CHARACTER VARYING(2048);

