
package net.conselldemallorca.helium.integracio.bantel.client.wsdl;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.2.2
 * Wed Nov 25 12:25:54 CET 2009
 * Generated source version: 2.2.2
 * 
 */

@WebFault(name = "fault", targetNamespace = "urn:es:caib:bantel:ws:v1:model:BackofficeFacade")
public class BackofficeFacadeException_Exception extends Exception {
    public static final long serialVersionUID = 20091125122554L;
    
    private net.conselldemallorca.helium.integracio.bantel.client.wsdl.BackofficeFacadeException fault;

    public BackofficeFacadeException_Exception() {
        super();
    }
    
    public BackofficeFacadeException_Exception(String message) {
        super(message);
    }
    
    public BackofficeFacadeException_Exception(String message, Throwable cause) {
        super(message, cause);
    }

    public BackofficeFacadeException_Exception(String message, net.conselldemallorca.helium.integracio.bantel.client.wsdl.BackofficeFacadeException fault) {
        super(message);
        this.fault = fault;
    }

    public BackofficeFacadeException_Exception(String message, net.conselldemallorca.helium.integracio.bantel.client.wsdl.BackofficeFacadeException fault, Throwable cause) {
        super(message, cause);
        this.fault = fault;
    }

    public net.conselldemallorca.helium.integracio.bantel.client.wsdl.BackofficeFacadeException getFaultInfo() {
        return this.fault;
    }
}
