package net.conselldemallorca.helium.integracio.bantel.client.wsdl;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.2.2
 * Wed Nov 25 12:25:54 CET 2009
 * Generated source version: 2.2.2
 * 
 */
 
@WebService(targetNamespace = "urn:es:caib:bantel:ws:v1:services", name = "BackofficeFacade")
@XmlSeeAlso({ObjectFactory.class})
public interface BackofficeFacade {

    @ResponseWrapper(localName = "establecerResultadoProcesoResponse", targetNamespace = "urn:es:caib:bantel:ws:v1:model:BackofficeFacade", className = "net.conselldemallorca.helium.integracio.sistra.wsdl.EstablecerResultadoProcesoResponse")
    @RequestWrapper(localName = "establecerResultadoProceso", targetNamespace = "urn:es:caib:bantel:ws:v1:model:BackofficeFacade", className = "net.conselldemallorca.helium.integracio.sistra.wsdl.EstablecerResultadoProceso")
    @WebMethod
    public void establecerResultadoProceso(
        @WebParam(name = "numeroEntrada", targetNamespace = "urn:es:caib:bantel:ws:v1:model:BackofficeFacade")
        net.conselldemallorca.helium.integracio.bantel.client.wsdl.ReferenciaEntrada numeroEntrada,
        @WebParam(name = "resultado", targetNamespace = "urn:es:caib:bantel:ws:v1:model:BackofficeFacade")
        java.lang.String resultado,
        @WebParam(name = "resultadoProcesamiento", targetNamespace = "urn:es:caib:bantel:ws:v1:model:BackofficeFacade")
        java.lang.String resultadoProcesamiento
    ) throws BackofficeFacadeException_Exception;

    @ResponseWrapper(localName = "obtenerEntradaResponse", targetNamespace = "urn:es:caib:bantel:ws:v1:model:BackofficeFacade", className = "net.conselldemallorca.helium.integracio.sistra.wsdl.ObtenerEntradaResponse")
    @RequestWrapper(localName = "obtenerEntrada", targetNamespace = "urn:es:caib:bantel:ws:v1:model:BackofficeFacade", className = "net.conselldemallorca.helium.integracio.sistra.wsdl.ObtenerEntrada")
    @WebResult(name = "obtenerEntradaReturn", targetNamespace = "urn:es:caib:bantel:ws:v1:model:BackofficeFacade")
    @WebMethod
    public net.conselldemallorca.helium.integracio.bantel.client.wsdl.TramiteBTE obtenerEntrada(
        @WebParam(name = "numeroEntrada", targetNamespace = "urn:es:caib:bantel:ws:v1:model:BackofficeFacade")
        net.conselldemallorca.helium.integracio.bantel.client.wsdl.ReferenciaEntrada numeroEntrada
    ) throws BackofficeFacadeException_Exception;

    @ResponseWrapper(localName = "obtenerNumerosEntradasResponse", targetNamespace = "urn:es:caib:bantel:ws:v1:model:BackofficeFacade", className = "net.conselldemallorca.helium.integracio.sistra.wsdl.ObtenerNumerosEntradasResponse")
    @RequestWrapper(localName = "obtenerNumerosEntradas", targetNamespace = "urn:es:caib:bantel:ws:v1:model:BackofficeFacade", className = "net.conselldemallorca.helium.integracio.sistra.wsdl.ObtenerNumerosEntradas")
    @WebResult(name = "obtenerNumerosEntradasReturn", targetNamespace = "urn:es:caib:bantel:ws:v1:model:BackofficeFacade")
    @WebMethod
    public net.conselldemallorca.helium.integracio.bantel.client.wsdl.ReferenciasEntrada obtenerNumerosEntradas(
        @WebParam(name = "identificadorTramite", targetNamespace = "urn:es:caib:bantel:ws:v1:model:BackofficeFacade")
        java.lang.String identificadorTramite,
        @WebParam(name = "procesada", targetNamespace = "urn:es:caib:bantel:ws:v1:model:BackofficeFacade")
        java.lang.String procesada,
        @WebParam(name = "desde", targetNamespace = "urn:es:caib:bantel:ws:v1:model:BackofficeFacade")
        javax.xml.datatype.XMLGregorianCalendar desde,
        @WebParam(name = "hasta", targetNamespace = "urn:es:caib:bantel:ws:v1:model:BackofficeFacade")
        javax.xml.datatype.XMLGregorianCalendar hasta
    ) throws BackofficeFacadeException_Exception;
}
