-- #1933 Poder definir estats de sortida en els expedients basats per estats

-- Nova taula per poder definir els estats de sortida 
CREATE TABLE HEL_ESTAT_SORTIDA (
	ESTAT_ID NUMBER(19,0) NOT NULL,
	ESTAT_SEGUENT_ID NUMBER(19,0) NOT NULL,
	PRIMARY KEY (ESTAT_ID, ESTAT_SEGUENT_ID),
	CONSTRAINT HEL_ESTAT_ID_FK FOREIGN KEY (ESTAT_ID) REFERENCES HEL_ESTAT(ID),
	CONSTRAINT HEL_ESTAT_SEGUENT_ID_FK FOREIGN KEY (ESTAT_SEGUENT_ID) REFERENCES HEL_ESTAT(ID)
);

-- Nova columna per guardar els estats anteriors
ALTER TABLE HEL_EXPEDIENT ADD ESTATS_PREVIS VARCHAR2(1024);