ALTER TABLE HEL_USUARI_PREFS ADD CABECERA_REDUCIDA BOOLEAN NULL;
ALTER TABLE HEL_USUARI_PREFS ADD LISTADO BOOLEAN NULL;
ALTER TABLE HEL_USUARI_PREFS ADD CONSULTA_ID BIGINT NULL;
ALTER TABLE HEL_USUARI_PREFS ADD FILTRO_TAREAS_ACTIVAS BOOLEAN NULL;
ALTER TABLE HEL_USUARI_PREFS ADD NUM_ELEMENTOS_PAGINA BIGINT NULL;

-- Actualització a la nova versió --
INSERT INTO HEL_VERSIO (
    ID,
    CODI,
    ORDRE,
    DATA_CREACIO,
    PROCES_EXECUTAT,
    SCRIPT_EXECUTAT,
    DATA_EXECUCIO_SCRIPT)
SELECT
    NEXTVAL('HIBERNATE_SEQUENCE') ID,
    '3.0.0' CODI,
    300 ORDRE,
    current_date DATA_CREACIO,
    false PROCES_EXECUTAT,
    true SCRIPT_EXECUTAT,
    current_date DATA_EXECUCIO_SCRIPT
WHERE (SELECT COUNT(*) FROM HEL_VERSIO WHERE ORDRE = 300) = 0;

