<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<parent>
		<groupId>es.caib.helium</groupId>
		<artifactId>helium</artifactId>
		<version>4.0</version>
	</parent>
	<artifactId>helium-ear</artifactId>
	<packaging>ear</packaging>
	<dependencies>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-web</artifactId>
			<exclusions>
				<exclusion>
					<groupId>org.springframework.boot</groupId>
					<artifactId>spring-boot-starter-tomcat</artifactId>
				</exclusion>
			</exclusions>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-security</artifactId>
		</dependency>
		<dependency>
			<groupId>${project.groupId}</groupId>
			<artifactId>helium-back</artifactId>
			<version>${project.version}</version>
			<type>war</type>
		</dependency>
		<dependency>
			<groupId>${project.groupId}</groupId>
			<artifactId>helium-api-interna</artifactId>
			<version>${project.version}</version>
			<type>war</type>
		</dependency>
		<dependency>
			<groupId>${project.groupId}</groupId>
			<artifactId>helium-service-intf</artifactId>
			<version>${project.version}</version>
		</dependency>
		<dependency>
			<groupId>${project.groupId}</groupId>
			<artifactId>helium-plugin-impl</artifactId>
			<version>${project.version}</version>
		</dependency>
		<dependency>
			<groupId>${project.groupId}</groupId>
			<artifactId>helium-ejb</artifactId>
			<version>${project.version}</version>
			<type>ejb</type>
		</dependency>
		<dependency>
			<groupId>org.reactivestreams</groupId>
			<artifactId>reactive-streams</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.hateoas</groupId>
			<artifactId>spring-hateoas</artifactId>
			<version>1.5.5</version>
		</dependency>
	</dependencies>
	<build>
		<plugins>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-ear-plugin</artifactId>
				<version>3.2.0</version>
				<configuration>
					<generateApplicationXml>true</generateApplicationXml>
					<defaultLibBundleDir>/lib</defaultLibBundleDir>
					<includeLibInApplicationXml>false</includeLibInApplicationXml>
					<version>6</version>
					<initializeInOrder>true</initializeInOrder>
					<skinnyWars>true</skinnyWars>
					<packagingExcludes>lib/org.apache.cxf-cxf*</packagingExcludes>
					<archive>
						<manifestEntries>
							<Build-Timestamp>${maven.build.timestamp}</Build-Timestamp>
							<Implementation-Vendor>Límit Tecnologies</Implementation-Vendor>
							<Implementation-Version>${project.version}</Implementation-Version>
							<Implementation-SCM-Branch>${git.branch}</Implementation-SCM-Branch>
							<Implementation-SCM-Revision>${git.commit.id}</Implementation-SCM-Revision>
						</manifestEntries>
					</archive>
					<modules>
						<ejbModule>
							<groupId>${project.groupId}</groupId>
							<artifactId>helium-ejb</artifactId>
							<bundleFileName>helium-ejb.jar</bundleFileName>
						</ejbModule>
						<webModule>
							<groupId>${project.groupId}</groupId>
							<artifactId>helium-api-interna</artifactId>
							<contextRoot>/helium2api/interna</contextRoot>
							<bundleFileName>helium-api-interna.war</bundleFileName>
						</webModule>
						<webModule>
							<groupId>${project.groupId}</groupId>
							<artifactId>helium-back</artifactId>
							<contextRoot>/helium2back</contextRoot>
							<bundleFileName>helium-back.war</bundleFileName>
						</webModule>
					</modules>
				</configuration>
			</plugin>
			<plugin>
				<groupId>io.fabric8</groupId>
				<artifactId>docker-maven-plugin</artifactId>
				<version>0.42.1</version>
				<configuration>
					<verbose>true</verbose>
					<images>
						<image>
							<name>${project.parent.artifactId}</name>
							<alias>${project.parent.artifactId}</alias>
							<build>
								<from>280421/jboss-eap-caib-7.2</from>
								<maintainer>limit@limit.es</maintainer>
								<ports>
									<port>8080</port>
								</ports>
								<assemblies>
									<assembly>
										<name>copy_jboss_config</name>
										<inline>
											<fileSets>
												<fileSet>
													<directory>
														${basedir}/src/main/docker/jboss</directory>
													<outputDirectory>config</outputDirectory>
												</fileSet>
											</fileSets>
										</inline>
										<targetDir>$JBOSS_USERHOME</targetDir>
										<user>jboss:nogroup</user>
									</assembly>
									<assembly>
										<name>copy_config_files</name>
										<inline>
											<fileSets>
												<fileSet>
													<directory>
														${basedir}/src/main/docker/properties</directory>
													<outputDirectory>
														${project.parent.artifactId}</outputDirectory>
												</fileSet>
												<fileSet>
													<directory>
														${basedir}/src/main/docker/other</directory>
													<outputDirectory>
														${project.parent.artifactId}</outputDirectory>
												</fileSet>
											</fileSets>
										</inline>
										<targetDir>$JBOSS_USERHOME/apps</targetDir>
										<user>jboss:nogroup</user>
									</assembly>
									<assembly>
										<descriptorRef>artifact</descriptorRef>
										<targetDir>
											$JBOSS_HOME/standalone/deployments</targetDir>
										<user>jboss:nogroup</user>
									</assembly>
								</assemblies>
								<runCmds>
									<run>mkdir $JBOSS_USERHOME/apps/${project.parent.artifactId}/files</run>
									<run>chmod a+x $JBOSS_USERHOME/config/jboss_config.sh</run>
									<run>dos2unix $JBOSS_USERHOME/config/jboss_config.sh</run>
									<run>sed -i 's~#!/bin/sh~#!/bin/sh\n$JBOSS_USERHOME/config/jboss_config.sh~' $JBOSS_HOME/bin/standalone.sh</run>
								</runCmds>
								<tags>
									<tag>latest</tag>
									<tag>${project.version}</tag>
								</tags>
							</build>
						</image>
					</images>
				</configuration>
			</plugin>
		</plugins>
		<finalName>helium</finalName>
	</build>
</project>
