-- #1992 
-- Afegeix la nova columna per diferenciar el tipus segons si és procediment o servei
ALTER TABLE HEL_PROCEDIMENT ADD TIPUS VARCHAR2(20 CHAR) DEFAULT 'PROCEDIMENT' NOT NULL;

ALTER TABLE HEL_ANOTACIO ADD SERVEI_CODI VARCHAR2(64 CHAR);
ALTER TABLE HEL_ANOTACIO ADD PRESENCIAL NUMBER(1,0);
ALTER TABLE HEL_ANOTACIO ADD TRAMIT_CODI VARCHAR2(64 CHAR);
ALTER TABLE HEL_ANOTACIO ADD TRAMIT_NOM VARCHAR2(255 CHAR);