package es.caib.sdesapplin2.signatura.services.custodiadocumentos;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;

/**
 * This class was generated by Apache CXF 3.0.0-milestone2
 * 2014-04-30T09:01:06.078+02:00
 * Generated source version: 3.0.0-milestone2
 * 
 */
@WebService(targetNamespace = "http://sdesapplin2.caib.es/signatura/services/CustodiaDocumentos", name = "Custodia")
@SOAPBinding(style = SOAPBinding.Style.RPC)
public interface Custodia {

    @WebResult(name = "consultarDocumento_v2Response", targetNamespace = "http://sdesapplin2.caib.es/signatura/services/CustodiaDocumentos", partName = "consultarDocumento_v2Response")
    @WebMethod(operationName = "consultarDocumento_v2", action = "CustodiaDocumentos")
    public byte[] consultarDocumentoV2(
        @WebParam(partName = "in0", name = "in0")
        java.lang.String in0,
        @WebParam(partName = "in1", name = "in1")
        java.lang.String in1,
        @WebParam(partName = "in2", name = "in2")
        java.lang.String in2
    );

    @WebResult(name = "purgarDocumento_v2Response", targetNamespace = "http://sdesapplin2.caib.es/signatura/services/CustodiaDocumentos", partName = "purgarDocumento_v2Response")
    @WebMethod(operationName = "purgarDocumento_v2", action = "CustodiaDocumentos")
    public byte[] purgarDocumentoV2(
        @WebParam(partName = "in0", name = "in0")
        java.lang.String in0,
        @WebParam(partName = "in1", name = "in1")
        java.lang.String in1,
        @WebParam(partName = "in2", name = "in2")
        java.lang.String in2
    );

    @WebResult(name = "purgarDocumentoResponse", targetNamespace = "http://sdesapplin2.caib.es/signatura/services/CustodiaDocumentos", partName = "purgarDocumentoResponse")
    @WebMethod(action = "CustodiaDocumentos")
    public byte[] purgarDocumento(
        @WebParam(partName = "in0", name = "in0")
        java.lang.String in0,
        @WebParam(partName = "in1", name = "in1")
        java.lang.String in1,
        @WebParam(partName = "in2", name = "in2")
        java.lang.String in2
    );

    @WebResult(name = "custodiarDocumentoResponse", targetNamespace = "http://sdesapplin2.caib.es/signatura/services/CustodiaDocumentos", partName = "custodiarDocumentoResponse")
    @WebMethod(action = "CustodiaDocumentos")
    public byte[] custodiarDocumento(
        @WebParam(partName = "in0", name = "in0")
        java.lang.String in0
    );

    @WebResult(name = "eliminarDocumento_v2Response", targetNamespace = "http://sdesapplin2.caib.es/signatura/services/CustodiaDocumentos", partName = "eliminarDocumento_v2Response")
    @WebMethod(operationName = "eliminarDocumento_v2", action = "CustodiaDocumentos")
    public byte[] eliminarDocumentoV2(
        @WebParam(partName = "in0", name = "in0")
        java.lang.String in0,
        @WebParam(partName = "in1", name = "in1")
        java.lang.String in1,
        @WebParam(partName = "in2", name = "in2")
        java.lang.String in2
    );

    @WebResult(name = "custodiarPDFFirmadoResponse", targetNamespace = "http://sdesapplin2.caib.es/signatura/services/CustodiaDocumentos", partName = "custodiarPDFFirmadoResponse")
    @WebMethod(action = "CustodiaDocumentos")
    public byte[] custodiarPDFFirmado(
        @WebParam(partName = "in0", name = "in0")
        java.lang.String in0
    );

    @WebResult(name = "reservarDocumentoResponse", targetNamespace = "http://sdesapplin2.caib.es/signatura/services/CustodiaDocumentos", partName = "reservarDocumentoResponse")
    @WebMethod(action = "CustodiaDocumentos")
    public byte[] reservarDocumento(
        @WebParam(partName = "in0", name = "in0")
        java.lang.String in0,
        @WebParam(partName = "in1", name = "in1")
        java.lang.String in1,
        @WebParam(partName = "in2", name = "in2")
        java.lang.String in2
    );

    @WebResult(name = "eliminarDocumentoResponse", targetNamespace = "http://sdesapplin2.caib.es/signatura/services/CustodiaDocumentos", partName = "eliminarDocumentoResponse")
    @WebMethod(action = "CustodiaDocumentos")
    public byte[] eliminarDocumento(
        @WebParam(partName = "in0", name = "in0")
        java.lang.String in0,
        @WebParam(partName = "in1", name = "in1")
        java.lang.String in1,
        @WebParam(partName = "in2", name = "in2")
        java.lang.String in2
    );

    @WebResult(name = "custodiarPDFFirmado_v2Response", targetNamespace = "http://sdesapplin2.caib.es/signatura/services/CustodiaDocumentos", partName = "custodiarPDFFirmado_v2Response")
    @WebMethod(operationName = "custodiarPDFFirmado_v2", action = "CustodiaDocumentos")
    public byte[] custodiarPDFFirmadoV2(
        @WebParam(partName = "in0", name = "in0")
        byte[] in0
    );

    @WebResult(name = "reservarDocumento_v2Response", targetNamespace = "http://sdesapplin2.caib.es/signatura/services/CustodiaDocumentos", partName = "reservarDocumento_v2Response")
    @WebMethod(operationName = "reservarDocumento_v2", action = "CustodiaDocumentos")
    public byte[] reservarDocumentoV2(
        @WebParam(partName = "in0", name = "in0")
        java.lang.String in0,
        @WebParam(partName = "in1", name = "in1")
        java.lang.String in1,
        @WebParam(partName = "in2", name = "in2")
        java.lang.String in2
    );

    @WebResult(name = "recuperarDocumentoResponse", targetNamespace = "http://sdesapplin2.caib.es/signatura/services/CustodiaDocumentos", partName = "recuperarDocumentoResponse")
    @WebMethod(action = "CustodiaDocumentos")
    public byte[] recuperarDocumento(
        @WebParam(partName = "in0", name = "in0")
        java.lang.String in0,
        @WebParam(partName = "in1", name = "in1")
        java.lang.String in1,
        @WebParam(partName = "in2", name = "in2")
        java.lang.String in2
    );

    @WebResult(name = "verificarDocumento_v2Response", targetNamespace = "http://sdesapplin2.caib.es/signatura/services/CustodiaDocumentos", partName = "verificarDocumento_v2Response")
    @WebMethod(operationName = "verificarDocumento_v2", action = "CustodiaDocumentos")
    public byte[] verificarDocumentoV2(
        @WebParam(partName = "in0", name = "in0")
        java.lang.String in0,
        @WebParam(partName = "in1", name = "in1")
        java.lang.String in1,
        @WebParam(partName = "in2", name = "in2")
        java.lang.String in2
    );

    @WebResult(name = "recuperarDocumento_v2Response", targetNamespace = "http://sdesapplin2.caib.es/signatura/services/CustodiaDocumentos", partName = "recuperarDocumento_v2Response")
    @WebMethod(operationName = "recuperarDocumento_v2", action = "CustodiaDocumentos")
    public byte[] recuperarDocumentoV2(
        @WebParam(partName = "in0", name = "in0")
        java.lang.String in0,
        @WebParam(partName = "in1", name = "in1")
        java.lang.String in1,
        @WebParam(partName = "in2", name = "in2")
        java.lang.String in2
    );

    @WebResult(name = "custodiarDocumento_v2Response", targetNamespace = "http://sdesapplin2.caib.es/signatura/services/CustodiaDocumentos", partName = "custodiarDocumento_v2Response")
    @WebMethod(operationName = "custodiarDocumento_v2", action = "CustodiaDocumentos")
    public byte[] custodiarDocumentoV2(
        @WebParam(partName = "in0", name = "in0")
        byte[] in0
    );

    @WebResult(name = "verificarDocumentoResponse", targetNamespace = "http://sdesapplin2.caib.es/signatura/services/CustodiaDocumentos", partName = "verificarDocumentoResponse")
    @WebMethod(action = "CustodiaDocumentos")
    public byte[] verificarDocumento(
        @WebParam(partName = "in0", name = "in0")
        java.lang.String in0,
        @WebParam(partName = "in1", name = "in1")
        java.lang.String in1,
        @WebParam(partName = "in2", name = "in2")
        java.lang.String in2
    );

    @WebResult(name = "custodiarDocumentoXAdESResponse", targetNamespace = "http://sdesapplin2.caib.es/signatura/services/CustodiaDocumentos", partName = "custodiarDocumentoXAdESResponse")
    @WebMethod(action = "CustodiaDocumentos")
    public byte[] custodiarDocumentoXAdES(
        @WebParam(partName = "in0", name = "in0")
        byte[] in0
    );

    @WebResult(name = "custodiarDocumentoSMIME_v2Response", targetNamespace = "http://sdesapplin2.caib.es/signatura/services/CustodiaDocumentos", partName = "custodiarDocumentoSMIME_v2Response")
    @WebMethod(operationName = "custodiarDocumentoSMIME_v2", action = "CustodiaDocumentos")
    public byte[] custodiarDocumentoSMIMEV2(
        @WebParam(partName = "in0", name = "in0")
        byte[] in0
    );

    @WebResult(name = "custodiarDocumentoSMIMEResponse", targetNamespace = "http://sdesapplin2.caib.es/signatura/services/CustodiaDocumentos", partName = "custodiarDocumentoSMIMEResponse")
    @WebMethod(action = "CustodiaDocumentos")
    public byte[] custodiarDocumentoSMIME(
        @WebParam(partName = "in0", name = "in0")
        java.lang.String in0
    );

    @WebResult(name = "obtenerInformeDocumento_v2Response", targetNamespace = "http://sdesapplin2.caib.es/signatura/services/CustodiaDocumentos", partName = "obtenerInformeDocumento_v2Response")
    @WebMethod(operationName = "obtenerInformeDocumento_v2", action = "CustodiaDocumentos")
    public byte[] obtenerInformeDocumentoV2(
        @WebParam(partName = "in0", name = "in0")
        java.lang.String in0,
        @WebParam(partName = "in1", name = "in1")
        java.lang.String in1,
        @WebParam(partName = "in2", name = "in2")
        java.lang.String in2
    );

    @WebResult(name = "consultarDocumentoResponse", targetNamespace = "http://sdesapplin2.caib.es/signatura/services/CustodiaDocumentos", partName = "consultarDocumentoResponse")
    @WebMethod(action = "CustodiaDocumentos")
    public byte[] consultarDocumento(
        @WebParam(partName = "in0", name = "in0")
        java.lang.String in0,
        @WebParam(partName = "in1", name = "in1")
        java.lang.String in1,
        @WebParam(partName = "in2", name = "in2")
        java.lang.String in2
    );

    @WebResult(name = "consultarReservaDocumentoResponse", targetNamespace = "http://sdesapplin2.caib.es/signatura/services/CustodiaDocumentos", partName = "consultarReservaDocumentoResponse")
    @WebMethod(action = "CustodiaDocumentos")
    public byte[] consultarReservaDocumento(
        @WebParam(partName = "in0", name = "in0")
        java.lang.String in0,
        @WebParam(partName = "in1", name = "in1")
        java.lang.String in1,
        @WebParam(partName = "in2", name = "in2")
        java.lang.String in2
    );

    @WebResult(name = "obtenerInformeDocumentoResponse", targetNamespace = "http://sdesapplin2.caib.es/signatura/services/CustodiaDocumentos", partName = "obtenerInformeDocumentoResponse")
    @WebMethod(action = "CustodiaDocumentos")
    public byte[] obtenerInformeDocumento(
        @WebParam(partName = "in0", name = "in0")
        java.lang.String in0,
        @WebParam(partName = "in1", name = "in1")
        java.lang.String in1,
        @WebParam(partName = "in2", name = "in2")
        java.lang.String in2
    );
}
