--#1658 Poder afegir un manual d'ajuda per tipus d'expedient

-- Oracle
ALTER TABLE HEL_EXPEDIENT_TIPUS ADD MANUAL_AJUDA_CONTENT BLOB;
ALTER TABLE HEL_EXPEDIENT_TIPUS ADD MANUAL_AJUDA_NOM VARCHAR2(1024 CHAR);

-- Postgresql
ALTER TABLE HEL_EXPEDIENT_TIPUS ADD MANUAL_AJUDA_CONTENT BYTEA;
ALTER TABLE HEL_EXPEDIENT_TIPUS ADD MANUAL_AJUDA_NOM character varying(1024);
