-- Llistat amb la informació pel llistat d'expedients
CREATE TABLE HEL_EXPEDIENT
(
    ID                  NUMBER(19)                NOT NULL,
    ENTORN_ID           NUMBER(19)                NOT NULL,
    EXPEDIENT_TIPUS_ID  NUMBER(19)                NOT NULL,
    PROCESS_INSTANCE_ID VARCHAR2(255 CHAR)        NOT NULL,
    NUMERO              VARCHAR2(64 CHAR)         NOT NULL,
    TITOL               VARCHAR2(255 CHAR),
    DATA_INICI          TIMESTAMP(6)              NOT NULL,
    DATA_FI             TIMESTAMP(6),
    ESTAT_TIPUS         VARCHAR2(16 CHAR)         NOT NULL,
    ESTAT_ID            NUMBER(19),
  	ATURAT              NUMBER(1)                 NOT NULL DEFAULT 0,
    INFO_ATURAT         VARCHAR2(1024 CHAR),
  	ANULAT              NUMBER(1)                 NOT NULL DEFAULT 0,
    COMENTARI_ANULAT    VARCHAR2(255 CHAR),
    ALERTES_TOTALS      NUMBER(19)                NOT NULL DEFAULT 0,
    ALERTES_PENDENTS    NUMBER(19)                NOT NULL DEFAULT 0,
  	AMB_ERRORS          NUMBER(1)                 NOT NULL DEFAULT 0
);

CREATE INDEX HEL_EXPEDIENT_EXPTIP_I ON HEL_EXPEDIENT (EXPEDIENT_TIPUS_ID);
CREATE INDEX HEL_EXPEDIENT_ENTORN_I ON HEL_EXPEDIENT (ENTORN_ID);


CREATE PUBLIC SYNONYM HEL_EXPEDIENT FOR HEL_EXPEDIENT;
GRANT SELECT, UPDATE, INSERT, DELETE ON HEL_EXPEDIENT TO WWW_HELIUM;


