-- Consultes avançades --
ALTER TABLE HEL_CONSULTA MOVE LOB (INFORME_CONTINGUT) STORE AS HEL_CONSULTA_CONT_LOB (TABLESPACE HELIUM_LOB);
CREATE PUBLIC SYNONYM HEL_CONSULTA_SUB FOR HEL_DOCUMENT_TASCA;
GRANT SELECT, UPDATE, INSERT, DELETE ON HEL_CONSULTA_SUB TO WWW_HELIUM;