# docker-compose.yml
version: '3'
services:
  database:
    image: "postgres:latest"
    ports:
      - 5432:5432
    env_file:
      - application.properties
    volumes:
    - ./db-data/:/var/lib/postgresql/data/