///*
// * HeliumMS Dominis API
// * Microservei de Dominis de HeliumMS
// *
// * OpenAPI spec version: 1.0.0
// * Contact: limit@limit.es
// *
// * NOTE: This class is auto generated by the swagger code generator program.
// * https://github.com/swagger-api/swagger-codegen.git
// * Do not edit the class manually.
// */
//
//package net.conselldemallorca.helium.ms.domini.client.api;
//
//import net.conselldemallorca.helium.ms.domini.client.model.Domini;
//import net.conselldemallorca.helium.ms.domini.client.model.DominiPagedList;
//import net.conselldemallorca.helium.ms.domini.client.model.PatchDocument;
//import org.junit.Test;
//import org.junit.Ignore;
//
//import java.util.ArrayList;
//import java.util.HashMap;
//import java.util.List;
//import java.util.Map;
//
///**
// * API tests for DissenyApi
// */
//@Ignore
//public class DissenyApiTest {
//
//    private final DissenyApi api = new DissenyApi();
//
//    /**
//     * Crea un nou domini
//     *
//     * Afegiex un nou domini al sistema
//     *
//     * @throws ApiException
//     *          if the Api call fails
//     */
//    @Test
//    public void createDominiV1Test() {
//        Domini body = null;
//        api.createDominiV1(body);
//
//        // TODO: test validations
//    }
//    /**
//     * Elimina un domini donat el seu identificador
//     *
//     * Elimina el domini amb l&#x27;identificador passat al paràmetre &#x60;dominiId&#x60;
//     *
//     * @throws ApiException
//     *          if the Api call fails
//     */
//    @Test
//    public void deleteDominiV1Test() {
//        Long dominiId = null;
//        api.deleteDominiV1(dominiId);
//
//        // TODO: test validations
//    }
//    /**
//     * Consulta un domini donat el seu identificador
//     *
//     * Retorna les dades del domini amb l&#x27;identificador informat al paràmetre &#x60;dominiId&#x60;
//     *
//     * @throws ApiException
//     *          if the Api call fails
//     */
//    @Test
//    public void getDominiV1Test() {
//        Long dominiId = null;
//        Domini response = api.getDominiV1(dominiId);
//
//        // TODO: test validations
//    }
//    /**
//     * Cerca de dominis
//     *
//     * Obté una página de la cerca dels **dominis** del sistema.  La cerca pot rebre paràmetres per - ordenar - paginar - filtrar (utilitzant sintaxi rsql) 
//     *
//     * @throws ApiException
//     *          if the Api call fails
//     */
//    @Test
//    public void listDominisV1Test() {
//        Long entornId = null;
//        String filtre = null;
//        Long expedientTipusId = null;
//        Long expedientTipusPareId = null;
//        Integer page = null;
//        Integer size = null;
//        String sort = null;
//        DominiPagedList response = api.listDominisV1(entornId, filtre, expedientTipusId, expedientTipusPareId, page, size, sort);
//
//        // TODO: test validations
//    }
//    /**
//     * Actualitza camps concrets d&#x27;un domini donat el seu identificador
//     *
//     * Modifica els camps del domini amb l&#x27;identificador passat al paràmetre &#x60;dominiId&#x60;, amb els camps de l&#x27;objecte Domini passat al body de la petició.   Només modifica els camps informats en l&#x27;objecte. Els camps no inclosos en l&#x27;objecte no seran modificats. 
//     *
//     * @throws ApiException
//     *          if the Api call fails
//     */
//    @Test
//    public void patchDominiV1Test() {
//        List<PatchDocument> body = null;
//        Long dominiId = null;
//        api.patchDominiV1(body, dominiId);
//
//        // TODO: test validations
//    }
//    /**
//     * Modifica un domini donat el seu identificador
//     *
//     * Modifica el domini amb l&#x27;identificador passat al paràmetre &#x60;dominiId&#x60;, amb les totes dades de l&#x27;objecte Domini passat al body de la petició
//     *
//     * @throws ApiException
//     *          if the Api call fails
//     */
//    @Test
//    public void updateDominiV1Test() {
//        Domini body = null;
//        Long dominiId = null;
//        api.updateDominiV1(body, dominiId);
//
//        // TODO: test validations
//    }
//}
