# HELIUM 3.3.11

# ###################### #
# PROPIETATS AFEGIDES    #
# ###################### #

#1985 Comunicar a l'API de Comanda les tasques i les modificacions

app.comanda.api.url=https://dev.caib.es/comandaapi/interna
app.comanda.api.user=helium
app.comanda.api.password=******

#1986 Crear API REST per a que Comanda pugui consultar els logs de l'aplicació

# Propietat per indicar la carpeta de logs de helium
app.comanda.logs.location=/opt/helium/logs