# HELIUM 3.3.12.1


# ###################### #
# PROPERTIES AFEGIDES    #
# ###################### #

# Propietat opcional per configurar si comunicar o no les tasques a Comanda. Per defefecte si no s'informa el valor és true
app.comanda.notifica.tasques=true