<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<parent>
		<groupId>es.caib.helium</groupId>
		<artifactId>helium</artifactId>
		<version>4.0</version>
	</parent>
	<artifactId>helium-service-intf</artifactId>
	<dependencies>
		<dependency>
			<groupId>org.projectlombok</groupId>
			<artifactId>lombok</artifactId>
			<scope>provided</scope>
		</dependency>
		<dependency>
			<groupId>${project.groupId}</groupId>
			<artifactId>helium-commons</artifactId>
			<version>${project.version}</version>
		</dependency>
		<dependency>
			<groupId>${project.groupId}</groupId>
			<artifactId>helium-disseny</artifactId>
			<version>${project.version}</version>
		</dependency>
		<dependency>
			<groupId>org.springframework.security</groupId>
			<artifactId>spring-security-core</artifactId>
			<scope>provided</scope>
		</dependency>
		<dependency>
			<groupId>org.hibernate.validator</groupId>
			<artifactId>hibernate-validator</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.security</groupId>
			<artifactId>spring-security-acl</artifactId>
			<scope>provided</scope>
		</dependency>
		<dependency>
			<groupId>io.dropwizard.metrics</groupId>
			<artifactId>metrics-core</artifactId>
			<version>${metrics.version}</version>
			<exclusions>
				<exclusion>
					<artifactId>slf4j-api</artifactId>
					<groupId>org.slf4j</groupId>
				</exclusion>
			</exclusions>
		</dependency>
		<dependency>
			<groupId>io.dropwizard.metrics</groupId>
			<artifactId>metrics-json</artifactId>
			<version>${metrics.version}</version>
    		<scope>compile</scope>
		</dependency>
		<dependency>
			<groupId>es.caib.comanda</groupId>
			<artifactId>comanda-api-client-management</artifactId>
			<version>${comanda.version}</version>
			<exclusions>
				<exclusion>
					<groupId>org.jboss.resteasy</groupId>
					<artifactId>resteasy-client</artifactId>
				</exclusion>
				<exclusion>
					<groupId>org.jboss.resteasy</groupId>
					<artifactId>resteasy-multipart-provider</artifactId>
				</exclusion>
				<exclusion>
					<groupId>org.jboss.resteasy</groupId>
					<artifactId>resteasy-jackson2-provider</artifactId>
				</exclusion>
			</exclusions>
		</dependency>
		<dependency>
			<groupId>es.caib.comanda</groupId>
			<artifactId>comanda-api-utils</artifactId>
			<version>${comanda.version}</version>
		</dependency>
		<dependency>
			<groupId>es.caib.helium</groupId>
			<artifactId>helium-disseny</artifactId>
			<version>4.0</version>
			<scope>compile</scope>
		</dependency>
		<dependency>
			<groupId>es.caib.helium</groupId>
			<artifactId>helium-disseny</artifactId>
			<version>4.0</version>
			<scope>compile</scope>
		</dependency>
	</dependencies>
</project>
