CREATE TABLE HEL_TASCA_EXPEDIENT (
	ID				NUMBER(19)		NOT NULL ENABLE,
	NAME			VARCHAR2(255),
	DESCRIPTION		VARCHAR2(2000),
	OWNER			VARCHAR2(255),
	GROUP_ID		VARCHAR2(255),
	ASSIGNEE		VARCHAR2(255),
	PRIORITY 		NUMBER(19)		NOT NULL ENABLE,
	CREATE_TIME		TIMESTAMP(6)	NOT NULL ENABLE,
	START_TIME		TIMESTAMP(6),
	CLAIM_TIME		TIMESTAMP(6),
	END_TIME		TIMESTAMP(6),
	DUE_DATE		TIMESTAMP(6),
	OPEN			NUMBER(1),
	COMPLETED		NUMBER(1),
	CANCELLED		NUMBER(1),
	SUSPENDED		NUMBER(1),
	DURATION		NUMBER(19,0),
	TASK_ID			VARCHAR2(64)	NOT NULL ENABLE,
	TASK_CODE		VARCHAR2(255),
	EXPEDIENT_ID	NUMBER(19)		NOT NULL ENABLE
);

CREATE TABLE HEL_TASCA_CANDIDATE (
	ID				NUMBER(19)		NOT NULL ENABLE,
	GRUP_ID			VARCHAR2(255),
	TIPUS			VARCHAR2(255),
	USER_ID			VARCHAR2(255),
	TASCA_ID		NUMBER(19)		NOT NULL ENABLE
);

ALTER TABLE HEL_TASCA_EXPEDIENT ADD (
  CONSTRAINT HEL_TASCA_EXPEDIENT_PK PRIMARY KEY (ID),
  CONSTRAINT HEL_TASCA_EXPEDIENT_UK UNIQUE (EXPEDIENT_ID, TASK_ID)
);

ALTER TABLE HEL_TASCA_EXPEDIENT ADD CONSTRAINT HEL_TASCA_EXPEDIENT_FK
	FOREIGN KEY (EXPEDIENT_ID) REFERENCES HEL_EXPEDIENT(ID);

ALTER TABLE HEL_TASCA_CANDIDATE ADD (
  CONSTRAINT HEL_TASCA_CANDIDATE_PK PRIMARY KEY (ID),
  CONSTRAINT HEL_TASCA_CANDIDATE_UK UNIQUE (TASCA_ID, GRUP_ID, USER_ID)
);

ALTER TABLE HEL_TASCA_CANDIDATE ADD CONSTRAINT HEL_TASCA_CANDIDATE_FK
	FOREIGN KEY (TASCA_ID) REFERENCES HEL_TASCA_EXPEDIENT(ID);

GRANT SELECT, UPDATE, INSERT, DELETE ON HEL_TASCA_EXPEDIENT TO WWW_HELIUM2;
GRANT SELECT, UPDATE, INSERT, DELETE ON HEL_TASCA_CANDIDATE TO WWW_HELIUM2;
