ALTER TABLE HEL_ESTAT_REGLA MODIFY ESTAT_ID NUMBER(19,0) NULL;
ALTER TABLE HEL_PETICIO_PINBAL ADD SERVEI_CODI VARCHAR2(32 CHAR);
ALTER TABLE HEL_CAMP ADD INDEXABLE NUMBER(1) DEFAULT 0 NOT NULL;

ALTER TABLE HEL_PROCEDIMENT ADD TIPUS VARCHAR2(20 CHAR) DEFAULT 'PROCEDIMENT' NOT NULL;
