
CREATE INDEX HEL_ACCIO_EXPTIP_I ON HEL_ACCIO
(EXPEDIENT_TIPUS_ID);

CREATE INDEX HEL_CAMPREG_REGISTRE_I ON HEL_CAMP_REGISTRE
(REGISTRE_ID);

CREATE INDEX HEL_CAMPREG_MEMBRE_I ON HEL_CAMP_REGISTRE
(MEMBRE_ID);

CREATE INDEX HEL_CAMPAGRUP_DEFPROC_I ON HEL_CAMP_AGRUP
(DEFINICIO_PROCES_ID);

CREATE INDEX HEL_CAMPAGRUP_EXPTIP_I ON HEL_CAMP_AGRUP
(EXPEDIENT_TIPUS_ID);

CREATE INDEX HEL_CAMP_AGRUP_I ON HEL_CAMP
(CAMP_AGRUPACIO_ID);

CREATE INDEX HEL_CAMP_ENUM_I ON HEL_CAMP
(ENUMERACIO_ID);

CREATE INDEX HEL_CAMP_DOMINI_I ON HEL_CAMP
(DOMINI_ID);

CREATE INDEX HEL_CAMP_CONSULTA_I ON HEL_CAMP
(CONSULTA_ID);

CREATE INDEX HEL_CAMP_DEFPROC_I ON HEL_CAMP
(DEFINICIO_PROCES_ID);

CREATE INDEX HEL_CAMP_EXPTIP_I ON HEL_CAMP
(EXPEDIENT_TIPUS_ID);

CREATE INDEX HEL_AREATIPUS_ENTORN_I ON HEL_AREA_TIPUS
(ENTORN_ID);

CREATE INDEX HEL_AREAMEMBRE_AREA_I ON HEL_AREA_MEMBRE
(AREA_ID);

CREATE INDEX HEL_AREA_TIPUS_I ON HEL_AREA
(TIPUS_ID);

CREATE INDEX HEL_AREA_ENTORN_I ON HEL_AREA
(ENTORN_ID);

CREATE INDEX HEL_AREA_PARE_I ON HEL_AREA
(PARE_ID);

CREATE INDEX HEL_ALERTA_EXPEDIENT_I ON HEL_ALERTA
(EXPEDIENT_ID);

CREATE INDEX HEL_ALERTA_ENTORN_I ON HEL_ALERTA
(ENTORN_ID);

CREATE INDEX HEL_ACCIO_DEFPROC_I ON HEL_ACCIO
(DEFINICIO_PROCES_ID);

CREATE INDEX HEL_VALIDACIO_TASCA_I ON HEL_VALIDACIO
(TASCA_ID);

CREATE INDEX HEL_VALIDACIO_CAMP_I ON HEL_VALIDACIO
(CAMP_ID);

CREATE INDEX HEL_TERMINIC_TERMINI_I ON HEL_TERMINI_INICIAT
(TERMINI_ID);

CREATE INDEX HEL_TERMINI_DEFPROC_I ON HEL_TERMINI
(DEFINICIO_PROCES_ID);

CREATE INDEX HEL_TASCA_DEFPROC_I ON HEL_TASCA
(DEFINICIO_PROCES_ID);

CREATE INDEX HEL_TASCA_JBPMNAME_I ON HEL_TASCA
(JBPM_NAME);

CREATE INDEX HEL_PERSONA_RELLEU_I ON HEL_PERSONA
(RELLEU_ID);

CREATE INDEX HEL_FIRTASCA_TASCA_I ON HEL_FIRMA_TASCA
(TASCA_ID);

CREATE INDEX HEL_FIRTASCA_DOCUMENT_I ON HEL_FIRMA_TASCA
(DOCUMENT_ID);

CREATE INDEX HEL_FIRTASCA_EXTIP_I ON HEL_CAMP_TASCA
(EXPEDIENT_TIPUS_ID);

CREATE INDEX HEL_EXPTIP_ENTORN_I ON HEL_EXPEDIENT_TIPUS
(ENTORN_ID);

CREATE INDEX HELIUM.HEL_EXTIP_PARE_I on HELIUM.HEL_EXPEDIENT_TIPUS
(EXPEDIENT_TIPUS_PARE_ID);

CREATE INDEX HEL_EXPEDIENT_TIPUS_I ON HEL_EXPEDIENT
(TIPUS_ID);

CREATE INDEX HEL_EXPEDIENT_ENTORN_I ON HEL_EXPEDIENT
(ENTORN_ID);

CREATE INDEX HEL_EXPEDIENT_ESTAT_I ON HEL_EXPEDIENT
(ESTAT_ID);

CREATE INDEX HEL_ESTAT_EXPTIP_I ON HEL_ESTAT
(EXPEDIENT_TIPUS_ID);

CREATE INDEX HEL_ENUM_ENTORN_I ON HEL_ENUMERACIO
(ENTORN_ID);

CREATE INDEX HEL_DOMINI_EXPTIP_I ON HEL_DOMINI
(EXPEDIENT_TIPUS_ID);

CREATE INDEX HEL_DOMINI_ENTORN_I ON HEL_DOMINI
(ENTORN_ID);

CREATE INDEX HEL_DOCTASCA_DOCUMENT_I ON HEL_DOCUMENT_TASCA
(DOCUMENT_ID);

CREATE INDEX HEL_DOCTASCA_TASCA_I ON HEL_DOCUMENT_TASCA
(TASCA_ID);

CREATE INDEX HEL_DOCTASCA_EXTIP_I ON HEL_CAMP_TASCA
(EXPEDIENT_TIPUS_ID);

CREATE INDEX HEL_DOCUMENT_DEFPROC_I ON HEL_DOCUMENT
(DEFINICIO_PROCES_ID);

CREATE INDEX HEL_DOCUMENT_EXPTIP_I ON HEL_DOCUMENT
(EXPEDIENT_TIPUS_ID);

CREATE INDEX HEL_DOCUMENT_CAMPDATA_I ON HEL_DOCUMENT
(CAMP_DATA_ID);

CREATE INDEX HEL_DEFPROC_ENTORN_I ON HEL_DEFINICIO_PROCES
(ENTORN_ID);

CREATE INDEX HEL_DEFPROC_EXPTIP_I ON HEL_DEFINICIO_PROCES
(EXPEDIENT_TIPUS_ID);

CREATE INDEX HEL_CONSULTACAMP_CONSULTA_I ON HEL_CONSULTA_CAMP
(CONSULTA_ID);

CREATE INDEX HEL_CONSULTA_ENTORN_I ON HEL_CONSULTA
(ENTORN_ID);

CREATE INDEX HEL_CONSULTA_EXPTIP_I ON HEL_CONSULTA
(EXPEDIENT_TIPUS_ID);

CREATE INDEX HEL_CARREC_ENTORN_I ON HEL_CARREC
(ENTORN_ID);

CREATE INDEX HEL_CARREC_AREA_I ON HEL_CARREC
(AREA_ID);

CREATE INDEX HEL_CAMPTASCA_CAMP_I ON HEL_CAMP_TASCA
(CAMP_ID);

CREATE INDEX HEL_CAMPTASCA_CAMP_I ON HEL_CAMP_TASCA
(CAMP_ID);

CREATE INDEX HEL_CAMP_TASCA_EXTIP_I ON HEL_CAMP_TASCA
(EXPEDIENT_TIPUS_ID);

CREATE INDEX HEL_EXPNOTELE_EXPEDIENT_ID_I ON HEL_EXPEDIENT_NOTIF_ELECTR 
(EXPEDIENT_ID);

CREATE INDEX HEL_REPRO_TASCA_CODI_I ON HEL_REPRO 
(TASCA_CODI);

CREATE INDEX HEL_INTERESSAT_EXPEDIENT_ID_I ON HEL_INTERESSAT 
(EXPEDIENT_ID);

CREATE INDEX IDX_VARINST_PRCINS ON JBPM_VARIABLEINSTANCE
(PROCESSINSTANCE_);

CREATE INDEX IDX_VARINST_TKVARMP ON JBPM_VARIABLEINSTANCE
(TOKENVARIABLEMAP_);

CREATE INDEX IDX_VARINST_TK ON JBPM_VARIABLEINSTANCE
(TOKEN_);

CREATE INDEX IDX_TRANSIT_TO ON JBPM_TRANSITION
(TO_);

CREATE INDEX IDX_TRANSIT_FROM ON JBPM_TRANSITION
(FROM_);

CREATE INDEX IDX_TRANS_PROCDEF ON JBPM_TRANSITION
(PROCESSDEFINITION_);

CREATE INDEX IDX_TKVARMAP_CTXT ON JBPM_TOKENVARIABLEMAP
(CONTEXTINSTANCE_);

CREATE INDEX IDX_TKVVARMP_TOKEN ON JBPM_TOKENVARIABLEMAP
(TOKEN_);

CREATE INDEX IDX_TOKEN_SUBPI ON JBPM_TOKEN
(SUBPROCESSINSTANCE_);

CREATE INDEX IDX_TOKEN_NODE ON JBPM_TOKEN
(NODE_);

CREATE INDEX IDX_TOKEN_PROCIN ON JBPM_TOKEN
(PROCESSINSTANCE_);

CREATE INDEX IDX_TOKEN_PARENT ON JBPM_TOKEN
(PARENT_);

CREATE INDEX IDX_TASKINST_PROC ON JBPM_TASKINSTANCE
(PROCINST_);

CREATE INDEX IDX_TASKINST_TSK ON JBPM_TASKINSTANCE
(TASK_, PROCINST_);

CREATE INDEX IDX_TASK_ACTORID ON JBPM_TASKINSTANCE
(ACTORID_);

CREATE INDEX IDX_TASKINST_TOKN ON JBPM_TASKINSTANCE
(TOKEN_);

CREATE INDEX IDX_TASKINST_SUSPOPEN ON JBPM_TASKINSTANCE
(ISSUSPENDED_, ISOPEN_);

CREATE INDEX IDX_TSKINST_SLINST ON JBPM_TASKINSTANCE
(SWIMLANINSTANCE_);

CREATE INDEX IDX_TSKINST_TMINST ON JBPM_TASKINSTANCE
(TASKMGMTINSTANCE_);

CREATE INDEX IDX_TASKINST_TSK2 ON JBPM_TASKINSTANCE
(TASK_);

CREATE INDEX IDX_TASK_TASKMGTDF ON JBPM_TASK
(TASKMGMTDEFINITION_);

CREATE INDEX IDX_TASK_TSKNODE ON JBPM_TASK
(TASKNODE_);

CREATE INDEX IDX_TASK_PROCDEF ON JBPM_TASK
(PROCESSDEFINITION_);

CREATE INDEX IDX_SWIMLINST_SL ON JBPM_SWIMLANEINSTANCE
(SWIMLANE_);

CREATE INDEX IDX_RTACTN_PRCINST ON JBPM_RUNTIMEACTION
(PROCESSINSTANCE_);

CREATE INDEX IDX_RTACTN_ACTION ON JBPM_RUNTIMEACTION
(ACTION_);

CREATE INDEX IDX_PROCIN_KEY ON JBPM_PROCESSINSTANCE
(KEY_);

CREATE INDEX IDX_PROCIN_PROCDEF ON JBPM_PROCESSINSTANCE
(PROCESSDEFINITION_);

CREATE INDEX IDX_PROCIN_ROOTTK ON JBPM_PROCESSINSTANCE
(ROOTTOKEN_);

CREATE INDEX IDX_PROCIN_SPROCTK ON JBPM_PROCESSINSTANCE
(SUPERPROCESSTOKEN_);

CREATE INDEX IDX_PROCDEF_STRTST ON JBPM_PROCESSDEFINITION
(STARTSTATE_);

CREATE INDEX HEL_EXPEDIENT_TIPENT_I ON HEL_EXPEDIENT
(TIPUS_ID, ENTORN_ID);

CREATE INDEX HEL_EXPEDIENT_ENT_ID_I ON HEL_EXPEDIENT
(ENTORN_ID, ID) ;

CREATE INDEX IDX_TASKINSTANCE ON JBPM_TASKINSTANCE
(ISSUSPENDED_, ACTORID_, ISOPEN_, ID_, PROCINST_);

CREATE INDEX IDX_POOLEDACTOR_ACTID ON JBPM_POOLEDACTOR
(ACTORID_, ID_);

CREATE INDEX IDX_TASKACTORPOOL_POOL_TASK ON JBPM_TASKACTORPOOL
(POOLEDACTOR_, TASKINSTANCE_);

CREATE INDEX IDX_TSKINST_SWLANE ON JBPM_POOLEDACTOR
(SWIMLANEINSTANCE_);

CREATE INDEX IDX_NODE_SUPRSTATE ON JBPM_NODE
(SUPERSTATE_);

CREATE INDEX IDX_NODE_ACTION ON JBPM_NODE
(ACTION_);

CREATE INDEX IDX_NODE_PROCDEF ON JBPM_NODE
(PROCESSDEFINITION_);

CREATE INDEX IDX_PSTATE_SBPRCDEF ON JBPM_NODE
(SUBPROCESSDEFINITION_);

CREATE INDEX IDX_MODINST_PRINST ON JBPM_MODULEINSTANCE
(PROCESSINSTANCE_);

CREATE INDEX IDX_MODDEF_PROCDF ON JBPM_MODULEDEFINITION
(PROCESSDEFINITION_);

CREATE INDEX IDX_JOB_PRINST ON JBPM_JOB
(PROCESSINSTANCE_);

CREATE INDEX IDX_JOB_TOKEN ON JBPM_JOB
(TOKEN_);

CREATE INDEX IDX_JOB_TSKINST ON JBPM_JOB
(TASKINSTANCE_);

CREATE INDEX IDX_DELEG_PRCD ON JBPM_DELEGATION
(PROCESSDEFINITION_);

CREATE INDEX IDX_COMMENT_TOKEN ON JBPM_COMMENT
(TOKEN_);

CREATE INDEX IDX_COMMENT_TSK ON JBPM_COMMENT
(TASKINSTANCE_);

CREATE INDEX IDX_ACTION_EVENT ON JBPM_ACTION
(EVENT_);

CREATE INDEX IDX_ACTION_PROCDF ON JBPM_ACTION
(PROCESSDEFINITION_);

CREATE INDEX IDX_ACTION_ACTNDL ON JBPM_ACTION
(ACTIONDELEGATION_);

CREATE INDEX IDX_LOG_ACTION ON JBPM_LOG
(ACTION_);

CREATE INDEX IDX_LOG_CHILD ON JBPM_LOG
(CHILD_);

CREATE INDEX IDX_LOG_DESTINATIONNODE ON JBPM_LOG
(DESTINATIONNODE_);

CREATE INDEX IDX_LOG_INDEX_NEWBYTEARRAY ON JBPM_LOG
(NEWBYTEARRAY_);

CREATE INDEX IDX_LOG_NODE ON JBPM_LOG
(NODE_);

CREATE INDEX IDX_LOG_OLDBYTEARRAY ON JBPM_LOG
(OLDBYTEARRAY_);

CREATE INDEX IDX_LOG_PARENT ON JBPM_LOG
(PARENT_);

CREATE INDEX IDX_LOG_SOURCENODE ON JBPM_LOG
(SOURCENODE_);

CREATE INDEX IDX_LOG_SWIMINST ON JBPM_LOG
(SWIMLANEINSTANCE_);

CREATE INDEX IDX_LOG_TASKINSTANCE ON JBPM_LOG
(TASKINSTANCE_);

CREATE INDEX IDX_LOG_TOKEN ON JBPM_LOG
(TOKEN_);

CREATE INDEX IDX_LOG_TRANSITION ON JBPM_LOG
(TRANSITION_);

CREATE INDEX IDX_LOG_VARINSTANCE ON JBPM_LOG
(VARIABLEINSTANCE_);

CREATE INDEX IDX_BYTEARR_FILE ON JBPM_BYTEARRAY
(FILEDEFINITION_);

CREATE INDEX IDX_VARINST_TINSTANCE ON JBPM_VARIABLEINSTANCE
(TASKINSTANCE_);

CREATE INDEX IDX_VARINST_BARR ON JBPM_VARIABLEINSTANCE
(BYTEARRAYVALUE_);

CREATE INDEX IDX_MODINST_DF ON JBPM_MODULEINSTANCE
(TASKMGMTDEFINITION_);

CREATE INDEX HEL_EXPLOG_EXPID_I ON HEL_EXPEDIENT_LOG 
(EXPEDIENT_ID);

CREATE INDEX HEL_EXPLOG_TARGETID_I ON HEL_EXPEDIENT_LOG 
(TARGET_ID);

CREATE INDEX HEL_NOTIFICACIO_EXPEDIENT_ID_I ON HEL_EXPEDIENT_NOTIFICACIO 
(EXPEDIENT_ID);

CREATE INDEX HEL_INTERESSAT_EXPEDIENT_ID_I ON HEL_INTERESSAT 
(EXPEDIENT_ID);

CREATE INDEX HEL_ENUM_ID_I ON HEL_ENUMERACIO_VALORS (ENUMERACIO_ID);

CREATE INDEX HEL_ANOTACIO_ANNEX_FK_I ON HEL_ANOTACIO_ANNEX(ANOTACIO_ID);
CREATE INDEX HEL_ANOTACIO_INTER_FK_I ON HEL_ANOTACIO_INTERESSAT(ANOTACIO_ID);
CREATE INDEX HEL_REPRESENTANT_ANOTACIO_FK_I ON HEL_ANOTACIO_INTERESSAT(REPRESENTANT_ID);
CREATE INDEX HEL_ANOTACIO_EXPEDIENT_FK_I ON HEL_ANOTACIO(EXPEDIENT_ID);
CREATE INDEX HEL_ANOTACIO_ET_FK_I ON HEL_ANOTACIO(EXPEDIENT_TIPUS_ID);

-- Index per a consulta d'operaicons massives pendents --
CREATE INDEX HEL_EXMASEXP_EXEMAS_I ON HEL_EXEC_MASEXP (EXECMAS_ID);

CREATE INDEX HEL_AVIS_DATA_INICI_I ON HEL_AVIS(DATA_INICI);
CREATE INDEX HEL_AVIS_DATA_FINAL_I ON HEL_AVIS(DATA_FINAL);

CREATE INDEX HEL_REGLA_ENTORN_FK_I ON HEL_ESTAT_REGLA(ENTORN_ID);
CREATE INDEX HEL_REGLA_EXPTIPUS_FK_I ON HEL_ESTAT_REGLA(EXPEDIENT_TIPUS_ID);
CREATE INDEX HEL_REGLA_ESTAT_FK_I ON HEL_ESTAT_REGLA(ESTAT_ID);
CREATE INDEX HEL_REGLA_VALOR_QUI_FK_I ON HEL_ESTAT_REGLA_VALOR_QUI(REGLA_ID);
CREATE INDEX HEL_REGLA_VALOR_QUE_FK_I ON HEL_ESTAT_REGLA_VALOR_QUE(REGLA_ID);

CREATE INDEX HEL_ESTACC_ENT_ESTAT_FK_I ON HEL_ESTAT_ACCIO_ENTRADA(ESTAT_ID);
CREATE INDEX HEL_ESTACC_SORT_ESTAT_FK_I ON HEL_ESTAT_ACCIO_SORTIDA(ESTAT_ID);
