CREATE TABLESPACE HELIUM2
 LOGGING
  DATAFILE 'HELIUM2.ORA'
SIZE 1024M REUSE  AUTOEXTEND  ON NEXT  1024K MAXSIZE  32767M
DEFAULT  STORAGE ( INITIAL 40K NEXT 40K MINEXTENTS 1 MAXEXTENTS  2147483645 PCTINCREASE 50 );

CREATE USER helium2 identified by helium2 default tablespace HELIUM2 TEMPORARY TABLESPACE temp;
GRANT CONNECT, RESOURCE, CREATE PUBLIC SYNONYM, drop public synonym, UNLIMITED TABLESPACE TO HELIUM2;