CREATE TABLE HEL_ACCIO
(
  ID                   NUMBER(19)               NOT NULL,
  CODI                 VARCHAR2(64 CHAR)        NOT NULL,
  TIPUS                VARCHAR2(32 CHAR) DEFAULT 'ACCIO' NOT NULL,
  CRON                 VARCHAR2(255 CHAR),
  DESCRIPCIO           VARCHAR2(255 CHAR),
  JBPM_ACTION          VARCHAR2(255 CHAR),
  NOM                  VARCHAR2(255 CHAR)       NOT NULL,
  OCULTA               NUMBER(1),
  PUBLICA              NUMBER(1),
  DEFINICIO_PROCES_ID  NUMBER(19),
  EXPEDIENT_TIPUS_ID   NUMBER(19),
  DEFPROC_JBPMKEY	   VARCHAR2(255 CHAR),
  ROLS                 VARCHAR2(512 CHAR),
  HANDLER_CLASSE       VARCHAR2(255 CHAR),
  HANDLER_DADES        CLOB,
  SCRIPT               VARCHAR2(1024 CHAR)
);

CREATE TABLE HEL_AVIS
(
  ID                   NUMBER(19)               NOT NULL,
  ASSUMPTE             VARCHAR2(256)            NOT NULL,
  MISSATGE             VARCHAR2(2048)           NOT NULL,
  DATA_INICI           TIMESTAMP(6)             NOT NULL,
  DATA_FINAL           TIMESTAMP(6)             NOT NULL,
  HORA_INICI	 	   VARCHAR2(5 CHAR),
  HORA_FI		 	   VARCHAR2(5 CHAR),
  ACTIU                NUMBER(1)                NOT NULL,
  AVIS_NIVELL          VARCHAR2(10)             NOT NULL,
  CREATEDBY_CODI       VARCHAR2(64),
  CREATEDDATE          TIMESTAMP(6),
  LASTMODIFIEDBY_CODI  VARCHAR2(64),
  LASTMODIFIEDDATE     TIMESTAMP(6)
);

CREATE TABLE HEL_ACL_CLASS
(
  ID     NUMBER(19)                             NOT NULL,
  CLASS  VARCHAR2(255 CHAR)                     NOT NULL
);

CREATE TABLE HEL_ACL_ENTRY
(
  ID                   NUMBER(19)               NOT NULL,
  ACE_ORDER            NUMBER(10)               NOT NULL,
  AUDIT_FAILURE        NUMBER(1)                NOT NULL,
  AUDIT_SUCCESS        NUMBER(1)                NOT NULL,
  GRANTING             NUMBER(1)                NOT NULL,
  MASK                 NUMBER(10)               NOT NULL,
  ACL_OBJECT_IDENTITY  NUMBER(19),
  SID                  NUMBER(19)
);


CREATE TABLE HEL_ACL_OBJECT_IDENTITY
(
  ID                  NUMBER(19)                NOT NULL,
  ENTRIES_INHERITING  NUMBER(1)                 NOT NULL,
  OBJECT_ID_IDENTITY  NUMBER(19)                NOT NULL,
  OBJECT_ID_CLASS     NUMBER(19),
  OWNER_SID           NUMBER(19),
  PARENT_OBJECT       NUMBER(19)
);


CREATE TABLE HEL_ACL_SID
(
  ID         NUMBER(19)                         NOT NULL,
  PRINCIPAL  NUMBER(1),
  SID        VARCHAR2(100 CHAR)                 NOT NULL
);


CREATE TABLE HEL_ACTION_LOG
(
  ID          NUMBER(19)                        NOT NULL,
  ACCIO       VARCHAR2(255 CHAR)                NOT NULL,
  COLUMNA_PK  VARCHAR2(255 CHAR)                NOT NULL,
  DATA        TIMESTAMP(6)                      NOT NULL,
  TAULA       VARCHAR2(255 CHAR)                NOT NULL,
  USUARI      VARCHAR2(255 CHAR)                NOT NULL,
  VALORS      VARCHAR2(255 CHAR)                NOT NULL
);


CREATE TABLE HEL_ALERTA
(
  ID                  NUMBER(19)                NOT NULL,
  CAUSA               VARCHAR2(255 CHAR),
  DATA_CREACIO        TIMESTAMP(6)              NOT NULL,
  DATA_ELIMINACIO     TIMESTAMP(6),
  DATA_LECTURA        TIMESTAMP(6),
  DESTINATARI         VARCHAR2(255 CHAR),
  PRIORITAT           NUMBER(10),
  TEXT                VARCHAR2(1024 CHAR),
  ENTORN_ID           NUMBER(19)                NOT NULL,
  EXPEDIENT_ID        NUMBER(19)                NOT NULL,
  TERMINI_INICIAT_ID  NUMBER(19)
);


CREATE TABLE HEL_AREA
(
  ID          NUMBER(19)                        NOT NULL,
  CODI        VARCHAR2(64 CHAR)                 NOT NULL,
  DESCRIPCIO  VARCHAR2(255 CHAR),
  NOM         VARCHAR2(255 CHAR)                NOT NULL,
  ENTORN_ID   NUMBER(19)                        NOT NULL,
  PARE_ID     NUMBER(19),
  TIPUS_ID    NUMBER(19)                        NOT NULL
);


CREATE TABLE HEL_AREA_JBPMID
(
  ID          NUMBER(19)                        NOT NULL,
  CODI        VARCHAR2(64 CHAR)                 NOT NULL,
  DESCRIPCIO  VARCHAR2(255 CHAR),
  NOM         VARCHAR2(255 CHAR)                NOT NULL
);


CREATE TABLE HEL_AREA_MEMBRE
(
  ID       NUMBER(19)                           NOT NULL,
  CODI     VARCHAR2(64 CHAR)                    NOT NULL,
  AREA_ID  NUMBER(19)                           NOT NULL
);


CREATE TABLE HEL_AREA_TIPUS
(
  ID          NUMBER(19)                        NOT NULL,
  CODI        VARCHAR2(64 CHAR)                 NOT NULL,
  DESCRIPCIO  VARCHAR2(255 CHAR),
  NOM         VARCHAR2(255 CHAR)                NOT NULL,
  ENTORN_ID   NUMBER(19)                        NOT NULL
);


CREATE TABLE HEL_CAMP
(
  ID                   NUMBER(19)               NOT NULL,
  CODI                 VARCHAR2(64 CHAR)        NOT NULL,
  DOMINI_CACHE_TEXT    NUMBER(1),
  DOMINI_CAMP_TEXT     VARCHAR2(64 CHAR),
  DOMINI_CAMP_VALOR    VARCHAR2(64 CHAR),
  DOMINI_PARAMID       VARCHAR2(255 CHAR),
  DOMINI_PARAMS        VARCHAR2(255 CHAR),
  DOMINI_INTERN        NUMBER(1),
  ETIQUETA             VARCHAR2(255 CHAR)       NOT NULL,
  JBPM_ACTION          VARCHAR2(255 CHAR),
  MULTIPLE             NUMBER(1),
  OBSERVACIONS         VARCHAR2(255 CHAR),
  OCULT                NUMBER(1),
  IGNORED              NUMBER(1),
  ORDRE                NUMBER(10),
  TIPUS                NUMBER(10)               NOT NULL,
  CAMP_AGRUPACIO_ID    NUMBER(19),
  DEFINICIO_PROCES_ID  NUMBER(19),
  EXPEDIENT_TIPUS_ID   NUMBER(19),
  DOMINI_ID            NUMBER(19),
  ENUMERACIO_ID        NUMBER(19),
  CONSULTA_ID          NUMBER(19),
  CONSULTA_CAMP_TEXT   VARCHAR2(64 CHAR),
  CONSULTA_CAMP_VALOR  VARCHAR2(64 CHAR),
  CONSULTA_PARAMS      VARCHAR2(255 CHAR),
  DEFPROC_JBPMKEY	   VARCHAR2(255 CHAR)
);

CREATE TABLE HEL_CAMP_AGRUP
(
  ID                   NUMBER(19)               NOT NULL,
  CODI                 VARCHAR2(64 CHAR)        NOT NULL,
  DESCRIPCIO           VARCHAR2(255 CHAR),
  NOM                  VARCHAR2(255 CHAR)       NOT NULL,
  ORDRE                NUMBER(10),
  DEFINICIO_PROCES_ID  NUMBER(19),
  EXPEDIENT_TIPUS_ID   NUMBER(19)
);


CREATE TABLE HEL_CAMP_REGISTRE
(
  ID           NUMBER(19)                       NOT NULL,
  LLISTAR      NUMBER(1),
  OBLIGATORI   NUMBER(1),
  ORDRE        NUMBER(10),
  MEMBRE_ID    NUMBER(19)                       NOT NULL,
  REGISTRE_ID  NUMBER(19)                       NOT NULL
);


CREATE TABLE HEL_CAMP_TASCA
(
  ID        	NUMBER(19)                          NOT NULL,
  ORDRE     	NUMBER(10),
  RF        	NUMBER(1),
  RO        	NUMBER(1),
  RQ        	NUMBER(1),
  WT        	NUMBER(1),
  CAMP_ID   	NUMBER(19)                          NOT NULL,
  TASCA_ID  	NUMBER(19)                          NOT NULL,
  AMPLE_COLS 	NUMBER(10) 		DEFAULT 12,
  BUIT_COLS 	NUMBER(10) 		DEFAULT 0,
  EXPEDIENT_TIPUS_ID NUMBER (19)
);


CREATE TABLE HEL_CARREC
(
  ID               NUMBER(19)                   NOT NULL,
  CODI             VARCHAR2(64 CHAR)            NOT NULL,
  DESCRIPCIO       VARCHAR2(255 CHAR),
  NOM_DONA         VARCHAR2(255 CHAR)           NOT NULL,
  NOM_HOME         VARCHAR2(255 CHAR)           NOT NULL,
  PERSONA_CODI     VARCHAR2(64 CHAR),
  PERSONA_SEXE     NUMBER(10),
  CARREC_DONA      VARCHAR2(255 CHAR)           NOT NULL,
  TRACTAMENT_HOME  VARCHAR2(255 CHAR)           NOT NULL,
  AREA_ID          NUMBER(19)                   NOT NULL,
  ENTORN_ID        NUMBER(19)                   NOT NULL
);


CREATE TABLE HEL_CARREC_JBPMID
(
  ID               NUMBER(19)                   NOT NULL,
  CODI             VARCHAR2(64 CHAR)            NOT NULL,
  DESCRIPCIO       VARCHAR2(255 CHAR),
  GRUP             VARCHAR2(64 CHAR)            NOT NULL,
  NOM_DONA         VARCHAR2(255 CHAR)           NOT NULL,
  NOM_HOME         VARCHAR2(255 CHAR)           NOT NULL,
  PERSONA_SEXE     NUMBER(10),
  CARREC_DONA      VARCHAR2(255 CHAR)           NOT NULL,
  TRACTAMENT_HOME  VARCHAR2(255 CHAR)           NOT NULL
);


CREATE TABLE HEL_CONSULTA
(
  ID                  NUMBER(19)                NOT NULL,
  CODI                VARCHAR2(64 CHAR)         NOT NULL,
  DESCRIPCIO          VARCHAR2(255 CHAR),
  EXPORTAR_ACTIU      NUMBER(1),
  OCULTAR_ACTIU       NUMBER(1),
  FORMAT_EXPORTACIO   VARCHAR2(16),
  GENERICA            NUMBER(1),
  INFORME_CONTINGUT   BLOB,
  INFORME_NOM         VARCHAR2(255 CHAR),
  NOM                 VARCHAR2(255 CHAR)        NOT NULL,
  ORDRE               NUMBER(10)                NOT NULL,
  VALORS_PREDEF       VARCHAR2(1024 CHAR),
  ENTORN_ID           NUMBER(19)                NOT NULL,
  EXPEDIENT_TIPUS_ID  NUMBER(19)                NOT NULL
);


CREATE TABLE HEL_CONSULTA_CAMP
(
  ID               NUMBER(19)                   NOT NULL,
  CAMP_CODI        VARCHAR2(64 CHAR)            NOT NULL,
  DEFPROC_JBPMKEY  VARCHAR2(255 CHAR),
  DEFPROC_VERSIO   NUMBER(10),
  ORDRE            NUMBER(10)                   NOT NULL,
  TIPUS            NUMBER(10)                   NOT NULL,
  CONSULTA_ID      NUMBER(19)                   NOT NULL,
  CAMP_DESCRIPCIO  VARCHAR2(255 CHAR),
  PARAM_TIPUS 	   NUMBER(10),
  AMPLE_COLS 	   NUMBER(10) 	DEFAULT 12,
  BUIT_COLS 	   NUMBER(10) 	DEFAULT 0
);


CREATE TABLE HEL_CONSULTA_SUB
(
  PARE_ID  NUMBER(19)                           NOT NULL,
  FILL_ID  NUMBER(19)                           NOT NULL
);


CREATE TABLE HEL_DEFINICIO_PROCES
(
  ID                  NUMBER(19)                NOT NULL,
  DATACREACIO         TIMESTAMP(6)              NOT NULL,
  ETIQUETA            VARCHAR2(64 CHAR),
  JBPM_ID             VARCHAR2(255 CHAR)        NOT NULL,
  JBPM_KEY            VARCHAR2(255 CHAR)        NOT NULL,
  VERSIO              NUMBER(10),
  ENTORN_ID           NUMBER(19)                NOT NULL,
  EXPEDIENT_TIPUS_ID  NUMBER(19)
);


CREATE TABLE HEL_DOCUMENT
(
  ID                     NUMBER(19)             NOT NULL,
  ADJUNTAR_AUTO          NUMBER(1),
  GENERAR_NOMES_TASCA    NUMBER(1) DEFAULT 0,
  ARXIU_CONTINGUT        BLOB,
  ARXIU_NOM              VARCHAR2(255 CHAR),
  CODI                   VARCHAR2(64 CHAR)      NOT NULL,
  CONTENT_TYPE           VARCHAR2(255 CHAR),
  CONVERTIR_EXT          VARCHAR2(10 CHAR),
  CUSTODIA_CODI          VARCHAR2(255 CHAR),
  DESCRIPCIO             VARCHAR2(255 CHAR),
  EXTENSIONS_PERMESES    VARCHAR2(255 CHAR),
  NOM                    VARCHAR2(255 CHAR)     NOT NULL,
  PLANTILLA              NUMBER(1),
  TIPUS_PORTASIGNATURES  NUMBER(10),
  CAMP_DATA_ID           NUMBER(19),
  DEFINICIO_PROCES_ID    NUMBER(19),
  EXPEDIENT_TIPUS_ID     NUMBER(19),
  IGNORED                NUMBER(1),
  NTI_ORIGEN             NUMBER(10),
  NTI_ESTADO_ELAB        NUMBER(10),
  NTI_TIPO_DOC           NUMBER(10),
  PORTAFIRMES_FLUX_ID    VARCHAR2(64 CHAR),
  PORTAFIRMES_ACTIU      NUMBER(1) DEFAULT 0, 
  PORTAFIRMES_RESPONSABLES VARCHAR2(512 CHAR),  
  PORTAFIRMES_FLUXTIP    VARCHAR2(256 CHAR),
  PORTAFIRMES_SEQTIP     VARCHAR2(256 CHAR),
  PORTAFIRMES_FLUX_NOM   VARCHAR2(512 CHAR),
  PINBAL_ACTIU           NUMBER(1) DEFAULT 0,
  PINBAL_FINALITAT       VARCHAR2(250 CHAR),
  PINBAL_SERVEI          NUMBER(19),
  PINBAL_CIFORGAN        NUMBER(1)
);

CREATE TABLE HEL_DOCUMENT_NOTIFICACIO (  
  ID                   	NUMBER(19)			NOT NULL,
  USUARI_CODI			VARCHAR2(255),
  EXPEDIENT_ID         	NUMBER(19)			NOT NULL,
  DOCUMENT_STORE_ID    	NUMBER(19)			NOT NULL,
  CERTIFICACIO_STORE_ID	NUMBER(19),
  EMISOR				VARCHAR2(10),
  TIPUS                	VARCHAR2(255),
  DATA_PROGRAMADA      	TIMESTAMP(6),
  RETARD				NUMBER(10),
  DATA_CADUCITAT      	TIMESTAMP(6),
  TIT_NOM           	VARCHAR2(100),
  TIT_LLINATGE1        	VARCHAR2(100),
  TIT_LLINATGE2        	VARCHAR2(100),
  TIT_NIF        		VARCHAR2(100),
  TIT_TELEFON        	VARCHAR2(16),
  TIT_EMAIL         	VARCHAR2(160),
  DEST_NOM           	VARCHAR2(100),
  DEST_LLINATGE1       	VARCHAR2(100),
  DEST_LLINATGE2       	VARCHAR2(100),
  DEST_NIF        		VARCHAR2(100),
  DEST_TELEFON        	VARCHAR2(16),
  DEST_EMAIL         	VARCHAR2(160),
  IDIOMA               	VARCHAR2(32),
  AVIS_TITOL           	VARCHAR2(256),
  AVIS_TEXT            	VARCHAR2(1024),
  AVIS_TEXT_MOBIL      	VARCHAR2(256),
  OFICI_TITOL          	VARCHAR2(256),
  OFICI_TEXT           	VARCHAR2(1024),
  ENV_ID           		VARCHAR2(100),
  ENV_REF           	VARCHAR2(100),
  ENV_DAT_ESTAT        	VARCHAR2(20),
  ENV_DAT_DATA        	TIMESTAMP(6),
  ENV_DAT_ORIGEN       	VARCHAR2(20),
  ENV_CERT_DATA        	TIMESTAMP(6),
  ENV_CERT_ORIGEN      	VARCHAR2(20),
  ENV_CERT_ARXIUUID		VARCHAR2(50),
  ESTAT                	VARCHAR2(20)		NOT NULL,
  ENVIAT_DATA       	TIMESTAMP(6),
  PROCESSAT_DATA       	TIMESTAMP(6),
  CANCELAT_DATA       	TIMESTAMP(6),
  ERROR         		NUMBER(1),
  ERROR_DESCRIPCIO		VARCHAR2(1000 CHAR),
  INTENT_NUM			NUMBER(10),
  INTENT_DATA          	TIMESTAMP(6),
  INTENT_PROXIM_DATA	TIMESTAMP(6),
  ENVIAMENT_TIPUS		VARCHAR2(255),
  CONCEPTE				VARCHAR2(256)		NOT NULL,
  DESCRIPCIO			VARCHAR2(256)
);

CREATE TABLE HEL_DOCUMENT_NOTIFICACIO_ANX (
  DOCUMENT_NOTIFICACIO_ID NUMBER(19)	NOT NULL,
  DOCUMENT_STORE_ID NUMBER(19)			NOT NULL
);


CREATE TABLE HEL_DOCUMENT_STORE
(
  ID                   NUMBER(19)               NOT NULL,
  ADJUNT               NUMBER(1),
  ADJUNT_TITOL         VARCHAR2(255 CHAR),
  ARXIU_CONTINGUT      BLOB,
  ARXIU_NOM            VARCHAR2(255 CHAR)       NOT NULL,
  DATA_CREACIO         TIMESTAMP(6)             NOT NULL,
  DATA_DOCUMENT        DATE                     NOT NULL,
  DATA_MODIFICACIO     TIMESTAMP(6)             NOT NULL,
  FONT                 NUMBER(10)               NOT NULL,
  JBPM_VARIABLE        VARCHAR2(255 CHAR)       NOT NULL,
  PROCESS_INSTANCE_ID  VARCHAR2(64 CHAR)        NOT NULL,
  REF_CUSTODIA         VARCHAR2(255 CHAR),
  REF_FONT             VARCHAR2(255 CHAR),
  REGISTRE_DATA        TIMESTAMP(6),
  REGISTRE_ENTRADA     NUMBER(1),
  REGISTRE_NUM         VARCHAR2(255 CHAR),
  REGISTRE_OFCODI      VARCHAR2(255 CHAR),
  REGISTRE_OFNOM       VARCHAR2(255 CHAR),
  REGISTRE_ORGCODI     VARCHAR2(255 CHAR),
  SIGNAT               NUMBER(1),
  NTI_VERSION          VARCHAR2(256),
  NTI_IDENTIFICADOR    VARCHAR2(52),
  NTI_ORGANO           VARCHAR2(256),
  NTI_ORIGEN           NUMBER(10),
  NTI_ESTADO_ELAB      NUMBER(10),
  NTI_NOMBRE_FMT       NUMBER(10),
  NTI_TIPO_DOC         NUMBER(10),
  NTI_IDDOC_ORIG       VARCHAR2(52),
  NTI_TIPO_FIRMA       NUMBER(10),
  NTI_CSV              VARCHAR2(256),
  NTI_DEF_GEN_CSV      VARCHAR2(256),
  ARXIU_UUID           VARCHAR2(36),
  DOCUMENT_VALID       NUMBER(1),
  DOCUMENT_ERROR       VARCHAR2(1000),
  ANNEX_ID             NUMBER(19),
  SYNC_REINTENTS       NUMBER(19, 0),
  SYNC_REINTENT_DATA   TIMESTAMP(6)
);


CREATE TABLE HEL_DOCUMENT_TASCA
(
  ID           NUMBER(19)                       NOT NULL,
  ORDRE        NUMBER(10),
  RO           NUMBER(1),
  RQ           NUMBER(1),
  DOCUMENT_ID  NUMBER(19)                       NOT NULL,
  TASCA_ID     NUMBER(19)                       NOT NULL,
  EXPEDIENT_TIPUS_ID NUMBER (19)
);


CREATE TABLE HEL_DOMINI
(
  ID                  NUMBER(19)                NOT NULL,
  CACHE_SEGONS        NUMBER(10),
  TIMEOUT        	  NUMBER(10),
  CODI                VARCHAR2(64 CHAR)         NOT NULL,
  CONTRASENYA         VARCHAR2(255 CHAR),
  DESCRIPCIO          VARCHAR2(255 CHAR),
  JNDI_DATASOURCE     VARCHAR2(255 CHAR),
  NOM                 VARCHAR2(255 CHAR)        NOT NULL,
  ORDRE_PARAMS        VARCHAR2(255 CHAR),
  ORIGEN_CREDS        NUMBER(10),
  SQLEXPR             VARCHAR2(1024 CHAR),
  TIPUS               NUMBER(10)                NOT NULL,
  TIPUS_AUTH          NUMBER(10),
  URL                 VARCHAR2(255 CHAR),
  USUARI              VARCHAR2(255 CHAR),
  ENTORN_ID           NUMBER(19)                NOT NULL,
  EXPEDIENT_TIPUS_ID  NUMBER(19)
);


CREATE TABLE HEL_ENTORN
(
  ID          NUMBER(19)                        NOT NULL,
  ACTIU       NUMBER(1),
  CODI        VARCHAR2(64 CHAR)                 NOT NULL,
  DESCRIPCIO  VARCHAR2(255 CHAR),
  NOM         VARCHAR2(255 CHAR)                NOT NULL,
  COLOR_FONS        VARCHAR2(255 CHAR) ,
  COLOR_LLETRA        VARCHAR2(255 CHAR)
);


CREATE TABLE HEL_ENUMERACIO
(
  ID                  NUMBER(19)                NOT NULL,
  CODI                VARCHAR2(64 CHAR)         NOT NULL,
  NOM                 VARCHAR2(255 CHAR)        NOT NULL,
  VALORS              VARCHAR2(4000 CHAR),
  ENTORN_ID           NUMBER(19)                NOT NULL,
  EXPEDIENT_TIPUS_ID  NUMBER(19)
);


CREATE TABLE HEL_ENUMERACIO_VALORS
(
  ID             NUMBER(19)                     NOT NULL,
  CODI           VARCHAR2(64 CHAR)              NOT NULL,
  NOM            VARCHAR2(255 CHAR)             NOT NULL,
  ORDRE          NUMBER(10)                     NOT NULL,
  ENUMERACIO_ID  NUMBER(19)                     NOT NULL
);


CREATE TABLE HEL_ESTAT
(
  ID                  NUMBER(19)                NOT NULL,
  CODI                VARCHAR2(64 CHAR)         NOT NULL,
  NOM                 VARCHAR2(255 CHAR)        NOT NULL,
  ORDRE               NUMBER(10)                NOT NULL,
  EXPEDIENT_TIPUS_ID  NUMBER(19)                NOT NULL
);


CREATE TABLE HEL_EXPEDIENT
(
  ID                   NUMBER(19)               NOT NULL,
  ANULAT               NUMBER(1),
  AUTENTICAT           NUMBER(1),
  AVISOS_EMAIL         VARCHAR2(255 CHAR),
  AVISOS_HABILITAT     NUMBER(1),
  AVISOS_MOBIL         VARCHAR2(255 CHAR),
  COMENTARI            VARCHAR2(255 CHAR),
  COMENTARIANULAT	   VARCHAR2(255 CHAR),
  DATA_FI              TIMESTAMP(6),
  DATA_INICI           TIMESTAMP(6)             NOT NULL,
  ERROR_FULL2		   CLOB,
  ERROR_FULL		   CLOB,
  ERROR_DESC		   VARCHAR2(255 CHAR),
  ERRORS_INTEGS 	   NUMBER(1),
  GEO_POSX             FLOAT(126),
  GEO_POSY             FLOAT(126),
  GEO_REFERENCIA       VARCHAR2(64 CHAR),
  IDIOMA               VARCHAR2(8 CHAR),
  INFO_ATURAT          VARCHAR2(1024 CHAR),
  INICIADOR_CODI       VARCHAR2(64 CHAR),
  INICIADOR_TIPUS      NUMBER(10),
  INTERESSAT_NIF       VARCHAR2(16 CHAR),
  INTERESSAT_NOM       VARCHAR2(255 CHAR),
  NOTTEL_HABILITAT     NUMBER(1),
  NUMERO               VARCHAR2(64 CHAR),
  NUMERO_DEFAULT       VARCHAR2(64 CHAR),
  PROCESS_INSTANCE_ID  VARCHAR2(255 CHAR)       NOT NULL,
  REGISTRE_DATA        TIMESTAMP(6),
  REGISTRE_NUM         VARCHAR2(64 CHAR),
  REPRESENTANT_NIF     VARCHAR2(16 CHAR),
  REPRESENTANT_NOM     VARCHAR2(255 CHAR),
  RESPONSABLE_CODI     VARCHAR2(64 CHAR),
  TITOL                VARCHAR2(255 CHAR),
  TRAMEXP_CLAU         VARCHAR2(255 CHAR),
  TRAMEXP_ID           VARCHAR2(255 CHAR),
  TRAMITADOR_NIF       VARCHAR2(16 CHAR),
  TRAMITADOR_NOM       VARCHAR2(255 CHAR),
  GRUP_CODI            VARCHAR2(64 CHAR),
  UNITAT_ADM           NUMBER(19),
  ENTORN_ID            NUMBER(19)               NOT NULL,
  ESTAT_ID             NUMBER(19),
  TIPUS_ID             NUMBER(19)               NOT NULL,
  AMB_RETROACCIO       NUMBER(1)	DEFAULT 1	NOT NULL,
  REINDEXAR_DATA	   TIMESTAMP(6),
  REINDEXAR_ERROR      NUMBER(1) DEFAULT 0      NOT NULL,
  NTI_ACTIU            NUMBER(1) DEFAULT 0,
  NTI_VERSION          VARCHAR2(256 CHAR),
  NTI_IDENTIFICADOR    VARCHAR2(52 CHAR),
  NTI_ORGANO           VARCHAR2(256 CHAR),
  NTI_SERIEDOCUMENTAL  VARCHAR2(16 CHAR),
  NTI_CLASIFICACION    VARCHAR2(44 CHAR),
  NTI_TIPO_FIRMA       NUMBER(10),
  NTI_CSV              VARCHAR2(256 CHAR),
  NTI_DEF_GEN_CSV      VARCHAR2(256 CHAR),
  ARXIU_ACTIU          NUMBER(1) DEFAULT 0,
  ARXIU_UUID           VARCHAR2(36 CHAR),
  ERROR_ARXIU          CLOB,
  SYNC_REINTENTS       NUMBER(19, 0),
  SYNC_REINTENT_DATA   TIMESTAMP(6),
  ESTATS_PREVIS        VARCHAR2(1024 CHAR),
  UNITAT_ORGANITZATIVA_ID NUMBER(19)
);


CREATE TABLE HEL_INTERESSAT
(
	ID					NUMBER(19)               NOT NULL,
	CODI                VARCHAR2(64 CHAR)        NOT NULL,
	DOCUMENTIDENT       VARCHAR2(256 CHAR)		 NOT NULL,
	NOM					VARCHAR2(255 CHAR),
	LLINATGE1			VARCHAR2(255 CHAR),
	LLINATGE2			VARCHAR2(255 CHAR),
	TIPUS				VARCHAR2(40 CHAR),
	EMAIL				VARCHAR2(255 CHAR),
	TELEFON				VARCHAR2(20 CHAR),
	EXPEDIENT_ID  		NUMBER(19),
	ENTREGAPOSTAL 		NUMBER(1,0) DEFAULT 0 	NOT NULL,
	ENTREGATIPUS 		NUMBER(10,0),
	LINIA1 				VARCHAR2(50 CHAR),
	LINIA2 				VARCHAR2(50 CHAR),
	ENTREGADEH 			NUMBER(1,0) DEFAULT 0 	NOT NULL,
	ENTREGADEHOBLIGAT 	NUMBER(1,0) DEFAULT 0 	NOT NULL,
	CODIPOSTAL 			VARCHAR2(5 CHAR),
	DIR3CODI 			VARCHAR2(21 CHAR),
    
    DIRECCIO            VARCHAR2(160 CHAR),
    CODIDIRE            VARCHAR2(21 CHAR),
    TIPUSDOCIDENT       VARCHAR2(64 CHAR),
    RAOSOCIAL           VARCHAR2(256 CHAR),
    ES_REPRESENTANT     NUMBER(1,0) DEFAULT 0 NOT NULL,
    OBSERVACIONS        VARCHAR2(256 CHAR),
    PAIS                VARCHAR2(4 CHAR),
    PROVINCIA           VARCHAR2(2 CHAR),
    MUNICIPI            VARCHAR2(5 CHAR),
    CANALNOTIF          VARCHAR2(8 CHAR),
    REPRESENTANT_ID     NUMBER(19)
);


CREATE TABLE HEL_EXEC_MASEXP (
	ID NUMBER(19) NOT NULL, 
	DATA_FI DATE, 
	DATA_INICI DATE, 
	ORDRE NUMBER(10) NOT NULL, 
	EXECMAS_ID NUMBER(19) NOT NULL, 
	EXPEDIENT_ID NUMBER(19), 
	ESTAT NUMBER(10), 
	ERROR CLOB, 
	TASCA_ID VARCHAR2(255 CHAR), 
	PROCINST_ID VARCHAR2(255 CHAR),
	AUX_TEXT VARCHAR2(255 CHAR),
    DEFPROC_ID NUMBER(19),
    AUX_ID NUMBER(19)
);

CREATE TABLE HEL_EXEC_MASSIVA (
	ID NUMBER(19) NOT NULL, 
	DATA_FI DATE, 
	DATA_INICI DATE NOT NULL, 
	PARAM1 VARCHAR2(255), 
	TIPUS NUMBER(10) NOT NULL, 
	USUARI VARCHAR2(64) NOT NULL, 
	EXPEDIENT_TIPUS_ID NUMBER(19), 
	ENV_CORREU NUMBER(1), 
	PARAM2 BLOB, 
	ENTORN NUMBER(19), 
	ROLS VARCHAR2(2000 CHAR), 
	CREDENCIALS RAW(2000)
);

CREATE TABLE HEL_EXPEDIENT_NOTIF_ELECTR (
  ID 					NUMBER 			NOT NULL ,
  DATA 					TIMESTAMP(0) 	NOT NULL ,
  EXPEDIENT_ID 			NUMBER 			NOT NULL ,
  NUMERO 				VARCHAR2(255) 	NOT NULL ,
  RDS_CODI 				VARCHAR2(255) 	NOT NULL ,
  RDS_CLAVE 			VARCHAR2(255) 	NOT NULL 
);

CREATE TABLE HEL_EXPEDIENT_LOG(
  ID                   NUMBER(19)               NOT NULL,
  ACCIO_TIPUS          NUMBER(10)               NOT NULL,
  ACCIO_PARAMS         VARCHAR2(2048 CHAR),
  DATA                 TIMESTAMP(6)             NOT NULL,
  ESTAT                NUMBER(10)               NOT NULL,
  INI_RETROCES         NUMBER(19),
  JBPM_LOGID           NUMBER(19),
  PROCESS_INSTANCE_ID  NUMBER(19),
  TARGET_ID            VARCHAR2(255 CHAR)       NOT NULL,
  USUARI               VARCHAR2(255 CHAR)       NOT NULL,
  EXPEDIENT_ID         NUMBER(19)               NOT NULL
);

CREATE TABLE HEL_EXPEDIENT_RELS
(
  ORIGEN_ID  NUMBER(19)                         NOT NULL,
  DESTI_ID   NUMBER(19)                         NOT NULL
);

CREATE TABLE HEL_EXPEDIENT_REINDEXACIO (
  ID 						NUMBER(19) 	NOT NULL,
  EXPEDIENT_ID				NUMBER(19) 	NOT NULL,
  DATA_REINDEXACIO			TIMESTAMP(6) NOT NULL
);

CREATE TABLE HEL_EXPEDIENT_TIPUS
(
  ID                   NUMBER(19)               NOT NULL,
  ANY_ACTUAL           NUMBER(10),
  CODI                 VARCHAR2(64 CHAR)        NOT NULL,
  TIPUS                NUMBER(10) DEFAULT 0     NOT NULL,
  DEMANA_NUMERO        NUMBER(1),
  DEMANA_TITOL         NUMBER(1),
  EXPRESSIO_NUMERO     VARCHAR2(255 CHAR),
  FORMEXT_CONTRASENYA  VARCHAR2(255 CHAR),
  FORMEXT_URL          VARCHAR2(255 CHAR),
  FORMEXT_USUARI       VARCHAR2(255 CHAR),
  JBPM_PD_KEY          VARCHAR2(255 CHAR),
  NOM                  VARCHAR2(255 CHAR)       NOT NULL,
  REINICIAR_ANUAL      NUMBER(1),
  RESPDEFAULT_CODI     VARCHAR2(64 CHAR),
  SEQUENCIA            NUMBER(19),
  SEQUENCIA_DEF        NUMBER(19),
  SISTRA_ACTIU         NUMBER(1) DEFAULT 0,
  SISTRA_CODTRA        VARCHAR2(64 CHAR),
  SISTRA_MAPADJ        VARCHAR2(2048 CHAR),
  SISTRA_MAPCAMPS      VARCHAR2(2048 CHAR),
  SISTRA_MAPDOCS       VARCHAR2(2048 CHAR),
  TE_NUMERO            NUMBER(1),
  TE_TITOL             NUMBER(1),
  RESTRINGIR_GRUP      NUMBER(1),
  TRAM_MASSIVA         NUMBER(1),
  ENTORN_ID            NUMBER(19)               NOT NULL,
  AMB_INFO_PROPIA      NUMBER(1) DEFAULT 0		NOT NULL,
  HERETABLE            NUMBER (1) DEFAULT 0,
  EXPEDIENT_TIPUS_PARE_ID	NUMBER (19),
  AMB_RETROACCIO	    NUMBER(1) DEFAULT 0      NOT NULL,
  REINDEXACIO_ASINCRONA NUMBER(1) DEFAULT 0      NOT NULL,
  SELECCIONAR_ANY NUMBER(1) DEFAULT 0      NOT NULL,
  DIES_NO_LABS			VARCHAR2(16),
  NOTIFICACIONS_ACTIVADES	NUMBER(1) DEFAULT 0      NOT NULL,
  NOTIFICACIO_ORGANCODI 	VARCHAR2(100),
  NOTIFICACIO_OFICINACODI 	VARCHAR2(100),
  NOTIFICACIO_UNITATADMIN 	VARCHAR2(100),
  NOTIFICACIO_CODPROC 		VARCHAR2(100),
  NOTIFICACIO_AVISTITOL 	VARCHAR2(256),
  NOTIFICACIO_AVISTEXT 		VARCHAR2(1024),
  NOTIFICACIO_AVISTEXTSMS 	VARCHAR2(200),
  NOTIFICACIO_OFICITITOL 	VARCHAR2(256),
  NOTIFICACIO_OFICITEXT 	VARCHAR2(1024),
  NTI_ACTIU                 NUMBER(1) DEFAULT 0,
  NTI_ORGANO                VARCHAR2(256),
  NTI_CLASIFICACION         VARCHAR2(44),
  NTI_SERIEDOCUMENTAL       VARCHAR2(16),
  PINBAL_ACTIU              NUMBER(1) DEFAULT 0,
  PINBAL_NIF_CIF            VARCHAR2(44 CHAR),
  ARXIU_ACTIU               NUMBER(1) DEFAULT 0,
  PROCEDIMENT_COMU			NUMBER(1) DEFAULT 0,
  NOTIB_ACTIU 				NUMBER(1) DEFAULT 0,
  NOTIB_EMISOR 				VARCHAR2(256),
  NOTIB_CODI_PROCEDIMENT 	VARCHAR2(9),
  NOTIB_SEU_UNITATADMIN 	VARCHAR2(100),
  NOTIB_SEU_OFICINA 		VARCHAR2(100),
  NOTIB_SEU_LLIBRE 			VARCHAR2(100),
  NOTIB_SEU_ORGAN 			VARCHAR2(100),
  NOTIB_SEU_IDIOMA 			VARCHAR2(10),
  NOTIB_AVISTITOL 			VARCHAR2(100),
  NOTIB_AVISTEXT 			VARCHAR2(1024),
  NOTIB_AVISTEXTSMS 		VARCHAR2(200),
  NOTIB_OFICITITOL 			VARCHAR2(256),
  NOTIB_OFICITEXT 			VARCHAR2(1024),
  DISTR_ACTIU 				NUMBER(1) DEFAULT 0,
  DISTR_CODI_PROCEDIMENT	VARCHAR2(200),
  DISTR_CODI_ASSUMPTE		VARCHAR2(20),
  DISTR_PRESENCIAL          NUMBER(1),
  DISTR_PROCES_AUTO 		NUMBER(1) DEFAULT 0,
  DISTR_SISTRA 				NUMBER(1) DEFAULT 0,
  ENVIAR_CORREU_ANOTACIONS  NUMBER(1,0) DEFAULT 0,
  MANUAL_AJUDA_CONTENT      BLOB,
  MANUAL_AJUDA_NOM          VARCHAR2(1024 CHAR)
);


CREATE TABLE HEL_EXPEDIENT_TIPUS_SEQANY (
  ID                NUMBER(19) NOT NULL,
  ANY_              NUMBER(10),
  SEQUENCIA         NUMBER(19),
  EXPEDIENT_TIPUS   NUMBER(19)
);


CREATE TABLE HEL_EXPEDIENT_TIPUS_SEQDEFANY
(
  ID                NUMBER(19)                  NOT NULL,
  ANY_              NUMBER(10)                  NOT NULL,
  SEQUENCIADEFAULT  NUMBER(19)                  NOT NULL,
  EXPEDIENT_TIPUS   NUMBER(19)
);


CREATE TABLE HEL_FESTIU
(
  ID    NUMBER(19)                              NOT NULL,
  DATA  DATE                                    NOT NULL
);


CREATE TABLE HEL_FIRMA_TASCA
(
  ID           NUMBER(19)                       NOT NULL,
  ORDRE        NUMBER(10),
  RQ           NUMBER(1),
  DOCUMENT_ID  NUMBER(19)                       NOT NULL,
  TASCA_ID     NUMBER(19)                       NOT NULL,
  EXPEDIENT_TIPUS_ID NUMBER (19)
);


CREATE TABLE HEL_FORMEXT
(
  ID               NUMBER(19)                   NOT NULL,
  DATA_DARRPET     TIMESTAMP(6),
  DATA_INICI       TIMESTAMP(6)                 NOT NULL,
  DATA_RECDADES    TIMESTAMP(6),
  DATA_FORMHEIGHT  NUMBER(10),
  DATA_FORMWIDTH   NUMBER(10),
  FORMID           VARCHAR2(255 CHAR)           NOT NULL,
  TASKID           VARCHAR2(255 CHAR)           NOT NULL,
  URL              VARCHAR2(1024 CHAR)          NOT NULL
);


CREATE TABLE HEL_IDGEN
(
  TAULA  VARCHAR2(255 CHAR),
  VALOR  NUMBER(10)
);


CREATE TABLE HEL_MAP_SISTRA
(
  ID                  NUMBER(19)                NOT NULL,
  CODIHELIUM          VARCHAR2(255 CHAR)        NOT NULL,
  CODISISTRA          VARCHAR2(255 CHAR)        NOT NULL,
  TIPUS               NUMBER(10)                NOT NULL,
  EXPEDIENT_TIPUS_ID  NUMBER(19)                NOT NULL,
  NO_SOBREESCRIURE	  NUMBER(1)					DEFAULT 0 NOT NULL 
);


CREATE TABLE HEL_PERMIS
(
  CODI        VARCHAR2(64 CHAR)                 NOT NULL,
  DESCRIPCIO  VARCHAR2(255 CHAR)
);


CREATE TABLE HEL_PERSONA
(
  ID              NUMBER(19)                    NOT NULL,
  AVIS_CORREU     NUMBER(1)                     NOT NULL,
  CODI            VARCHAR2(64 CHAR)             NOT NULL,
  DATA_NAIXEMENT  DATE,
  DNI             VARCHAR2(64 CHAR),
  EMAIL           VARCHAR2(255 CHAR),
  FONT            NUMBER(10),
  LLINATGE1       VARCHAR2(255 CHAR)            NOT NULL,
  LLINATGE2       VARCHAR2(255 CHAR),
  LLINATGES       VARCHAR2(255 CHAR),
  NOM             VARCHAR2(255 CHAR)            NOT NULL,
  NOM_SENCER      VARCHAR2(255 CHAR),
  SEXE            NUMBER(10)                    NOT NULL,
  RELLEU_ID       NUMBER(19)
);


CREATE TABLE HEL_PORTASIGNATURES
(
  ID                   NUMBER(19)                 NOT NULL,
  DATA_ENVIAT          TIMESTAMP(6),
  DOCUMENT_ID          NUMBER(10)                 NOT NULL,
  DOCUMENT_STORE_ID    NUMBER(19),
  ESTAT                NUMBER(10),
  MOTIU_REBUIG         VARCHAR2(255 CHAR),
  TOKEN_ID             NUMBER(19),
  TRANSICIO_KO         VARCHAR2(255 CHAR),
  TRANSICIO_OK         VARCHAR2(255 CHAR),
  TRANSICIO            NUMBER(10),
  DATA_SIGNAT_REBUTJAT TIMESTAMP(6),
  DATA_CUSTODIA_INTENT TIMESTAMP(6),
  DATA_CUSTODIA_OK     TIMESTAMP(6),
  DATA_SIGNAL_INTENT   TIMESTAMP(6),
  DATA_SIGNAL_OK       TIMESTAMP(6),
  DATA_CB_PRI          TIMESTAMP(6),
  DATA_CB_DAR          TIMESTAMP(6),
  ERROR_CB_PROCES      CLOB,
  PROCESS_INSTANCE_ID  VARCHAR2(255 CHAR),
  EXPEDIENT_ID         NUMBER(19)
);


CREATE TABLE HEL_REDIR
(
  ID               NUMBER(19)                   NOT NULL,
  DATA_CANCELACIO  TIMESTAMP(6),
  DATA_FI          TIMESTAMP(6)                 NOT NULL,
  DATA_INICI       TIMESTAMP(6)                 NOT NULL,
  EXPEDIENT_TIPUS_ID  NUMBER(19),
  USUARI_DESTI     VARCHAR2(255 CHAR)           NOT NULL,
  USUARI_ORIGEN    VARCHAR2(255 CHAR)           NOT NULL
);


CREATE TABLE HEL_REGISTRE
(
  ID                   NUMBER(19)               NOT NULL,
  ACCIO                NUMBER(10)               NOT NULL,
  DATA                 TIMESTAMP(6)             NOT NULL,
  ENTITAT              NUMBER(10)               NOT NULL,
  ENTITAT_ID           VARCHAR2(255 CHAR)       NOT NULL,
  EXPEDIENT_ID         NUMBER(19)               NOT NULL,
  MISSATGE             VARCHAR2(1024 CHAR),
  PROCESS_INSTANCE_ID  VARCHAR2(255 CHAR),
  RESPONSABLE_CODI     VARCHAR2(64 CHAR)        NOT NULL,
  VALOR_NOU            VARCHAR2(4000 CHAR),
  VALOR_VELL           VARCHAR2(4000 CHAR)
);


CREATE TABLE HEL_TASCA
(
  ID                   NUMBER(19)               NOT NULL,
  EXPRESSIO_DELEGACIO  VARCHAR2(255 CHAR),
  FORM_EXTERN          VARCHAR2(255 CHAR),
  JBPM_NAME            VARCHAR2(255 CHAR)       NOT NULL,
  MISSATGE_INFO        VARCHAR2(255 CHAR),
  MISSATGE_WARN        VARCHAR2(255 CHAR),
  NOM                  VARCHAR2(255 CHAR),
  NOM_SCRIPT           VARCHAR2(1024 CHAR),
  RECURS_FORM          VARCHAR2(255 CHAR),
  TIPUS                NUMBER(10)               NOT NULL,
  TRAM_MASSIVA         NUMBER(1),
  DEFINICIO_PROCES_ID  NUMBER(19)               NOT NULL,
  FIN_SEGON_PLA 	   NUMBER(1) DEFAULT 1 		NOT NULL,
  AMB_REPRO	 	  	   NUMBER(1) DEFAULT 0,
  MOSTRAR_AGRUPACIONS  NUMBER(1) DEFAULT 0
);


CREATE TABLE HEL_TERMINI
(
  ID                   NUMBER(19)               NOT NULL,
  ALERTA_COMPLETAT     NUMBER(1),
  ALERTA_FINAL         NUMBER(1),
  ALERTA_PREVIA        NUMBER(1),
  ANYS                 NUMBER(10),
  CODI                 VARCHAR2(64 CHAR)        NOT NULL,
  DESCRIPCIO           VARCHAR2(255 CHAR),
  DIES                 NUMBER(10),
  DIES_PREVIS_AVIS     NUMBER(10),
  DURADA_PREDEF        NUMBER(1),
  LABORABLE            NUMBER(1),
  MANUAL               NUMBER(1),
  MESOS                NUMBER(10),
  NOM                  VARCHAR2(255 CHAR)       NOT NULL,
  DEFINICIO_PROCES_ID  NUMBER(19),
  EXPEDIENT_TIPUS_ID   NUMBER(19)
);


CREATE TABLE HEL_TERMINI_INICIAT
(
  ID                   NUMBER(19)               NOT NULL,
  ALERTA_COMPLETAT     NUMBER(1),
  ALERTA_FINAL         NUMBER(1),
  ALERTA_PREVIA        NUMBER(1),
  ANYS                 NUMBER(10),
  DATA_ATURADA         DATE,
  DATA_CANCEL          DATE,
  DATA_COMPLETAT       DATE,
  DATA_FI              DATE                     NOT NULL,
  DATA_FI_PRORROGA     DATE,
  DATA_INICI           DATE                     NOT NULL,
  DIES                 NUMBER(10),
  DIES_ATURAT          NUMBER(10),
  MESOS                NUMBER(10),
  PROCESS_INSTANCE_ID  VARCHAR2(255 CHAR)       NOT NULL,
  TASK_INSTANCE_ID     VARCHAR2(255 CHAR),
  TIMER_IDS            VARCHAR2(1024 CHAR),
  TERMINI_ID           NUMBER(19)               NOT NULL
);


CREATE TABLE HEL_USUARI
(
  CODI         VARCHAR2(64 CHAR)                NOT NULL,
  ACTIU        NUMBER(1)                        NOT NULL,
  CONTRASENYA  VARCHAR2(255 CHAR)
);


CREATE TABLE HEL_USUARI_PERMIS
(
  CODI    VARCHAR2(64 CHAR)                     NOT NULL,
  PERMIS  VARCHAR2(64 CHAR)                     NOT NULL
);


CREATE TABLE HEL_USUARI_PREFS
(
  CODI            VARCHAR2(64 CHAR)             NOT NULL,
  DEFAULT_ENTORN  VARCHAR2(64 CHAR),
  IDIOMA          VARCHAR2(255 CHAR),
  CABECERA_REDUCIDA NUMBER(1) NULL ,
  LISTADO NUMBER(1) NULL ,
  CONSULTA_ID NUMBER(19) NULL ,
  FILTRO_TAREAS_ACTIVAS NUMBER(1) NULL ,
  NUM_ELEMENTOS_PAGINA NUMBER(3) NULL ,
  DEFAULT_TIPUS_EXPEDIENT NUMBER(19) ,
  CORREUS_BUSTIA NUMBER(1,0) DEFAULT 0 ,
  CORREUS_BUSTIA_AGRUPATS_DIA NUMBER(1,0) DEFAULT 0 ,
  EMAIL_ALTERNATIU VARCHAR2(255 CHAR),
  ENTORN_ACTUAL                VARCHAR2(64 CHAR),
  ENTORN_ACTUAL_DATA           TIMESTAMP(6)
);

CREATE TABLE HEL_VALIDACIO
(
  ID         NUMBER(19)                         NOT NULL,
  EXPRESSIO  VARCHAR2(1024 CHAR)                NOT NULL,
  MISSATGE   VARCHAR2(255 CHAR)                 NOT NULL,
  NOM        VARCHAR2(255 CHAR),
  ORDRE      NUMBER(10)                         NOT NULL,
  CAMP_ID    NUMBER(19),
  TASCA_ID   NUMBER(19)
);


CREATE TABLE HEL_VERSIO
(
  ID                    NUMBER(19)              NOT NULL,
  CODI                  VARCHAR2(64 CHAR)       NOT NULL,
  DATA_CREACIO          TIMESTAMP(6)            NOT NULL,
  DATA_EXECUCIO_PROCES  TIMESTAMP(6),
  DATA_EXECUCIO_SCRIPT  TIMESTAMP(6),
  DESCRIPCIO            VARCHAR2(255 CHAR),
  ORDRE                 NUMBER(10)              NOT NULL,
  PROCES_EXECUTAT       NUMBER(1),
  SCRIPT_EXECUTAT       NUMBER(1)
);


CREATE TABLE HEL_REPRO
(
  ID                  NUMBER(19)                NOT NULL,
  USUARI          	  VARCHAR2(255 CHAR),
  EXPTIP_ID			  NUMBER(19),
  TASCA_CODI		  VARCHAR2(255),
  NOM				  VARCHAR2(255 CHAR),
  VALORS   			  CLOB
);

-- Noves taules per les anotacions
CREATE TABLE HEL_ANOTACIO (
  ID 						NUMBER(19) 		NOT NULL,
  EXPEDIENT_TIPUS_ID		NUMBER(19) ,
  EXPEDIENT_ID				NUMBER(19) ,
  DISTRIBUCIO_ID				VARCHAR2(80) NOT NULL,
  DISTRIBUCIO_CLAU_ACCES		VARCHAR2(200) NOT NULL,
  ESTAT						NUMBER(19)               NOT NULL,
  DATA_RECEPCIO				TIMESTAMP(6) NOT NULL, 
  DATA_PROCESSAMENT			TIMESTAMP(6), 
  REBUIG_MOTIU				VARCHAR2(500),
  APLICACIO_CODI 			VARCHAR2(20), 
  APLICACIO_VERSIO 			VARCHAR2(15), 
  ASSUMPTE_CODI_CODI 		VARCHAR2(16), 
  ASSUMPTE_CODI_DESC 		VARCHAR2(100), 
  ASSUMPTE_TIPUS_CODI		VARCHAR2(16), 
  ASSUMPTE_TIPUS_DESC 		VARCHAR2(100), 
  DATA 						TIMESTAMP(6), 
  DOC_FISICA_CODI 			VARCHAR2(1), 
  DOC_FISICA_DESC 			VARCHAR2(100), 
  ENTITAT_CODI 				VARCHAR2(21), 
  ENTITAT_DESC 				VARCHAR2(100), 
  EXPEDIENT_NUMERO 			VARCHAR2(80), 
  EXPOSA 					CLOB, 
  EXTRACTE					VARCHAR2(240 CHAR),
  PROCEDIMENT_CODI			VARCHAR2(20),
  IDENTIFICADOR 			VARCHAR2(100), 
  IDIOMA_CODI 				VARCHAR2(2), 
  IDIOMA_DESC 				VARCHAR2(100), 
  LLIBRE_CODI 				VARCHAR2(4), 
  LLIBRE_DESC 				VARCHAR2(100), 
  OBSERVACIONS 				VARCHAR2(50), 
  OFICINA_CODI 				VARCHAR2(21), 
  OFICINA_DESC 				VARCHAR2(100), 
  ORIGEN_DATA 				TIMESTAMP(6), 
  ORIGEN_REGISTRE_NUM 		VARCHAR2(80), 
  REF_EXTERNA 				VARCHAR2(16), 
  SOLICITA 					CLOB, 
  TRANSPORT_NUM 			VARCHAR2(20), 
  TRANSPORT_TIPUS_CODI 		VARCHAR2(2), 
  TRANSPORT_TIPUS_DESC 		VARCHAR2(100), 
  USUARI_CODI 				VARCHAR2(20), 
  USUARI_NOM 				VARCHAR2(80), 
  DESTI_CODI 				VARCHAR2(21), 
  DESTI_DESCRIPCIO 			VARCHAR2(100),
  CONSULTA_INTENTS          NUMBER(10)      DEFAULT 0,
  CONSULTA_ERROR            VARCHAR2(1024 CHAR),
  CONSULTA_DATA             TIMESTAMP(6),
  ERROR_PROCESSAMENT        CLOB
);


CREATE TABLE HEL_ANOTACIO_ANNEX (
	ID 						NUMBER(19) 		NOT NULL, 
	CONTINGUT BLOB,
	FIRMA_CONTINGUT BLOB,
	FIRMA_PERFIL VARCHAR2(30),
	FIRMA_TAMANY NUMBER(10),
	FIRMA_TIPUS VARCHAR2(30),
	NOM VARCHAR2(80) NOT NULL,
	FIRMA_NOM VARCHAR2(80),
	NTI_FECHA_CAPTURA TIMESTAMP(6) NOT NULL,
	NTI_ORIGEN VARCHAR2(20) NOT NULL,
	NTI_TIPO_DOC VARCHAR2(20) NOT NULL,
	OBSERVACIONS VARCHAR2(50),
	SICRES_TIPO_DOC VARCHAR2(20),
	SICRES_VALIDEZ_DOC VARCHAR2(30),
	TAMANY NUMBER(10) NOT NULL,
	TIPUS_MIME VARCHAR2(255),
	TITOL VARCHAR2(200) NOT NULL,
	UUID VARCHAR2(100),
	ANOTACIO_ID NUMBER(19) NOT NULL,
	ESTAT VARCHAR2(20),
	ERROR VARCHAR2(4000),
	NTI_ESTADO_ELABORACIO VARCHAR2(50) NOT NULL,
	DOCUMENT_STORE_ID NUMBER(19),
    DOCUMENT_VALID NUMBER(1),
    DOCUMENT_ERROR VARCHAR2(1000),
    ARXIU_ESTAT VARCHAR2(20)
);


CREATE TABLE HEL_ANOTACIO_INTERESSAT 
  ( 
     ID                  NUMBER(19) NOT NULL, 
     ADRESA              VARCHAR2(160), 
     CANAL               VARCHAR2(30), 
     CP                  VARCHAR2(5), 
     DOC_NUMERO          VARCHAR2(17), 
     DOC_TIPUS           VARCHAR2(15), 
     EMAIL               VARCHAR2(160), 
     LLINATGE1           VARCHAR2(30), 
     LLINATGE2           VARCHAR2(30), 
     MUNICIPI_CODI       VARCHAR2(100), 
     NOM                 VARCHAR2(30), 
     OBSERVACIONS        VARCHAR2(160), 
     PAIS_CODI           VARCHAR2(4), 
     PROVINCIA_CODI      VARCHAR2(100), 
     RAO_SOCIAL          VARCHAR2(80), 
     TELEFON             VARCHAR2(20), 
     TIPUS               VARCHAR2(40) NOT NULL, 
     REPRESENTANT_ID     NUMBER(19), 
     ANOTACIO_ID         NUMBER(19), 
     PAIS                VARCHAR2(200), 
     PROVINCIA           VARCHAR2(200), 
     MUNICIPI            VARCHAR2(200), 
     ORGAN_CODI          VARCHAR(9)
  );

CREATE TABLE HEL_ESTAT_REGLA (
    ID				    NUMBER(19) 	        NOT NULL,
    NOM 				VARCHAR2(255 CHAR) 	NOT NULL,
    EXPEDIENT_TIPUS_ID  NUMBER(19) 	        NOT NULL,
    ESTAT_ID			NUMBER(19) 	        NOT NULL,
    ENTORN_ID			NUMBER(19) 	        NOT NULL,
    QUI 				VARCHAR2(32 CHAR) 	NOT NULL,
    QUE 				VARCHAR2(32 CHAR) 	NOT NULL,
    ACCIO 				VARCHAR2(32 CHAR) 	NOT NULL,
    ORDRE               NUMBER(10)          NOT NULL
);

CREATE TABLE HEL_ESTAT_REGLA_VALOR_QUI (
    REGLA_ID            NUMBER(19) 	        NOT NULL,
    VALOR 				VARCHAR2(255 CHAR) 	NOT NULL
);

CREATE TABLE HEL_ESTAT_REGLA_VALOR_QUE (
    REGLA_ID            NUMBER(19) 	        NOT NULL,
    VALOR 				VARCHAR2(255 CHAR) 	NOT NULL
);

CREATE TABLE HEL_ESTAT_ACCIO_ENTRADA (
    ID				    NUMBER(19) 	        NOT NULL,
    ESTAT_ID			NUMBER(19) 	        NOT NULL,
    ACCIO_ID			NUMBER(19) 	        NOT NULL,
    ORDRE               NUMBER(10)          NOT NULL
);

CREATE TABLE HEL_ESTAT_ACCIO_SORTIDA (
    ID				    NUMBER(19) 	        NOT NULL,
    ESTAT_ID			NUMBER(19) 	        NOT NULL,
    ACCIO_ID			NUMBER(19) 	        NOT NULL,
    ORDRE               NUMBER(10)          NOT NULL
);


CREATE TABLE HEL_UNITAT_ORGANITZATIVA (
  ID           				NUMBER(19)          NOT NULL,
  CODI 						VARCHAR2(9 CHAR) 		NOT NULL,
  DENOMINACIO 				VARCHAR2(300 CHAR) 		NOT NULL,
  NIF_CIF 					VARCHAR2(9 CHAR),
  CODI_UNITAT_SUPERIOR 		VARCHAR2(9 CHAR),
  CODI_UNITAT_ARREL 		VARCHAR2(9 CHAR),
  DATA_CREACIO_OFICIAL 		TIMESTAMP(6),
  DATA_SUPRESSIO_OFICIAL 	TIMESTAMP(6),
  DATA_EXTINCIO_FUNCIONAL 	TIMESTAMP(6),
  DATA_ANULACIO 	 		TIMESTAMP(6),
  DATA_SINCRONITZACIO 		TIMESTAMP(6),
  DATA_ACTUALITZACIO 		TIMESTAMP(6),
  ESTAT 					VARCHAR2(1 CHAR),
  CODI_PAIS 				VARCHAR2(3 CHAR),
  CODI_COMUNITAT 			VARCHAR2(2 CHAR),
  CODI_PROVINCIA 			VARCHAR2(2 CHAR),
  CODI_POSTAL 				VARCHAR2(5 CHAR),
  NOM_LOCALITAT 			VARCHAR2(50 CHAR),
  LOCALITAT 				VARCHAR2(40 CHAR),
  ADRESSA 					VARCHAR2(70 CHAR),
  TIPUS_VIA 	 			NUMBER(19),
  NOM_VIA 					VARCHAR2(200 CHAR),
  NUM_VIA 					VARCHAR2(100 CHAR),
  TIPUS_TRANSICIO 		    VARCHAR2(12 CHAR),

  CREATEDDATE          		TIMESTAMP(6),
  CREATEDBY_CODI       		VARCHAR2(256 CHAR),
  LASTMODIFIEDDATE     		TIMESTAMP(6),
  LASTMODIFIEDBY_CODI  		VARCHAR2(256 CHAR),
  CODI_DIR3_ENTITAT		 	VARCHAR2(9 CHAR)
);

CREATE TABLE HEL_UO_SINC_REL (
  ANTIGA_UO         			NUMBER(19)          NOT NULL,
  NOVA_UO           			NUMBER(19)          NOT NULL
);

CREATE TABLE HEL_PROCEDIMENT 
(
  ID						NUMBER(19)	    	NOT NULL,
  CODI          			VARCHAR2(64 CHAR)		NOT NULL,
  NOM						VARCHAR2(256 CHAR),
  CODISIA					VARCHAR2(64 CHAR),
  UNITAT_ORGANITZATIVA_ID   NUMBER(19),
  ESTAT                     VARCHAR2(20 CHAR) DEFAULT 'VIGENT' NOT NULL,
  COMU                      NUMBER DEFAULT 0
);


CREATE TABLE HEL_EXPEDIENT_TIPUS_UNITAT_ORG (
  ID           				NUMBER(19)      NOT NULL,
  EXPEDIENT_TIPUS_ID		NUMBER(19) 		NOT NULL,
  UNITAT_ORGANITZATIVA_ID   NUMBER(19) 		NOT NULL
);

CREATE TABLE HEL_PARAMETRE
(
  ID                NUMBER(19)               NOT NULL,
  CODI            	VARCHAR2(512)            NOT NULL,
  NOM		        VARCHAR2(256)			 NOT NULL,
  DESCRIPCIO        VARCHAR2(1024),
  VALOR           	VARCHAR2(256)
);

CREATE TABLE HEL_PETICIO_PINBAL (
  ID           				NUMBER(19)          NOT NULL,
  ENTORN_ID    				NUMBER(19)          NOT NULL,
  TIPUS_ID     				NUMBER(19)          NOT NULL,
  EXPEDIENT_ID 				NUMBER(19)          NOT NULL,
  DOCUMENT_ID  				NUMBER(19),
  PROCEDIMENT  				VARCHAR2(32 CHAR)   NOT NULL,
  USUARI	  				VARCHAR2(64 CHAR)   NOT NULL,
  DATA_PETICIO				TIMESTAMP(6)		NOT NULL,
  ASINCRONA					NUMBER(1,0)			DEFAULT 0 NOT NULL,
  ESTAT		  				VARCHAR2(32 CHAR)   NOT NULL,
  ERROR_MSG					CLOB,
  PINBAL_ID					VARCHAR2(64 CHAR),
  TOKEN_ID					NUMBER(19),
  
  DATA_PREVISTA				TIMESTAMP(6),
  DATA_DARRERA_CONSULTA		TIMESTAMP(6),
  
  TRANSICIO_OK 				VARCHAR2(32 CHAR),
  TRANSICIO_KO 				VARCHAR2(32 CHAR),
  DATA_PROCESSAMENT_PRIMER	TIMESTAMP(6),
  DATA_PROCESSAMENT_DARRER	TIMESTAMP(6),  
  ERROR_PROCESSAMENT		CLOB
);

CREATE TABLE HEL_PINBAL_SERVEI (
    ID NUMBER(19) NOT NULL, 
	CODI VARCHAR2(64 CHAR) NOT NULL,
	NOM VARCHAR2(256 CHAR) NOT NULL, 
	DOC_PERMES_DNI NUMBER(1,0) NOT NULL, 
	DOC_PERMES_NIF NUMBER(1,0) NOT NULL, 
	DOC_PERMES_CIF NUMBER(1,0) NOT NULL, 
	DOC_PERMES_NIE NUMBER(1,0) NOT NULL, 
	DOC_PERMES_PAS NUMBER(1,0) NOT NULL,
	CREATEDDATE TIMESTAMP (6),
	UPDATEDDATE TIMESTAMP (6),
	UPDATEDUSUARI VARCHAR2(64 BYTE),
	ACTIU NUMBER(1) NOT NULL
);
	
CREATE TABLE HEL_ANOTACIO_EMAIL (
  ID           				NUMBER(19,0)         	NOT NULL,
  REMITENT_CODI				VARCHAR2(64 CHAR) 		NOT NULL,
  DESTINATARI_CODI 			VARCHAR2(64 CHAR) 		NOT NULL,
  DESTINATARI_EMAIL			VARCHAR(256 CHAR)   	NOT NULL,
  ENVIAMENT_AGRUPAT			NUMBER(1,0) DEFAULT 0 	NOT NULL,
  ANOTACIO_ID				NUMBER(19,0)         	NOT NULL,
  EXPEDIENT_ID				NUMBER(19,0),
  EMAIL_TIPUS				VARCHAR2(64 CHAR) 		NOT NULL, --ARRIBADA | PROCESSADA | INCORPORADA
  NUM_INTENTS				NUMBER(19,0),
  DATA_CREACIO				TIMESTAMP(6)
);

CREATE TABLE HEL_ESTAT_SORTIDA (
	ESTAT_ID NUMBER(19,0) NOT NULL,
	ESTAT_SEGUENT_ID NUMBER(19,0) NOT NULL
);

CREATE TABLE HEL_DOCUMENT_CONTINGUT (
  ID NUMBER(19)	NOT NULL,
  DOCUMENT_CONTINGUT NUMBER(19)			NOT NULL
);

-- Taula per les dades dels expedients
CREATE TABLE HEL_EXPEDIENT_DADES
(
  ID                   NUMBER(19)      NOT NULL,
  EXPEDIENT_TIPUS_ID   NUMBER(19),
  EXPEDIENT_ID         NUMBER(19),
  PRINCIPAL            NUMBER(1),
  PROCESS_ID           NUMBER(19),
  PROCESS_ID           VARCHAR2(255 CHAR) ,
  TASK_ID              NUMBER(19),
  TASK_ID              VARCHAR2(255 CHAR) ,
  DADES                CLOB
      CONSTRAINT HEL_EXP_DADES_JSON_CHK
      CHECK (DADES IS JSON)
);


--------------------------------------------------------
-- Triggers de la lista de control d'accès
--------------------------------------------------------
CREATE OR REPLACE TRIGGER "HEL_ACL_CLASS_ID"
BEFORE INSERT ON HEL_ACL_CLASS
FOR EACH ROW
  BEGIN
    SELECT HEL_ACL_CLASS_SEQ.NEXTVAL INTO :new.id FROM dual;
  END;
 
CREATE OR REPLACE TRIGGER "HEL_ACL_ENTRY_ID"
BEFORE INSERT ON HEL_ACL_ENTRY
FOR EACH ROW
  BEGIN
    SELECT HEL_ACL_ENTRY_SEQ.NEXTVAL INTO :new.id FROM dual;
  END;
 
CREATE OR REPLACE TRIGGER "HEL_ACL_OBJECT_IDENTITY_ID"
BEFORE INSERT ON HEL_ACL_OBJECT_IDENTITY
FOR EACH ROW
  BEGIN
    SELECT HEL_ACL_OBJECT_IDENTITY_SEQ.NEXTVAL INTO :new.id FROM dual;
  END;
 
CREATE OR REPLACE TRIGGER "HEL_ACL_SID_ID"
BEFORE INSERT ON HEL_ACL_SID
FOR EACH ROW
  BEGIN
    SELECT HEL_ACL_SID_SEQ.NEXTVAL INTO :new.id FROM dual;
  END;
