
CREATE INDEX HEL_ACCIO_EXPTIP_I ON HEL_ACCIO
(EXPEDIENT_TIPUS_ID);

CREATE INDEX HEL_CAMPREG_REGISTRE_I ON HEL_CAMP_REGISTRE
(REGISTRE_ID);

CREATE INDEX HEL_CAMPREG_MEMBRE_I ON HEL_CAMP_REGISTRE
(MEMBRE_ID);

CREATE INDEX HEL_CAMPAGRUP_DEFPROC_I ON HEL_CAMP_AGRUP
(DEFINICIO_PROCES_ID);

CREATE INDEX HEL_CAMPAGRUP_EXPTIP_I ON HEL_CAMP_AGRUP
(EXPEDIENT_TIPUS_ID);

CREATE INDEX HEL_CAMP_AGRUP_I ON HEL_CAMP
(CAMP_AGRUPACIO_ID);

CREATE INDEX HEL_CAMP_ENUM_I ON HEL_CAMP
(ENUMERACIO_ID);

CREATE INDEX HEL_CAMP_DOMINI_I ON HEL_CAMP
(DOMINI_ID);

CREATE INDEX HEL_CAMP_CONSULTA_I ON HEL_CAMP
(CONSULTA_ID);

CREATE INDEX HEL_CAMP_DEFPROC_I ON HEL_CAMP
(DEFINICIO_PROCES_ID);

CREATE INDEX HEL_CAMP_EXPTIP_I ON HEL_CAMP
(EXPEDIENT_TIPUS_ID);

CREATE INDEX HEL_AREATIPUS_ENTORN_I ON HEL_AREA_TIPUS
(ENTORN_ID);

CREATE INDEX HEL_AREAMEMBRE_AREA_I ON HEL_AREA_MEMBRE
(AREA_ID);

CREATE INDEX HEL_AREA_TIPUS_I ON HEL_AREA
(TIPUS_ID);

CREATE INDEX HEL_AREA_ENTORN_I ON HEL_AREA
(ENTORN_ID);

CREATE INDEX HEL_AREA_PARE_I ON HEL_AREA
(PARE_ID);

CREATE INDEX HEL_ALERTA_EXPEDIENT_I ON HEL_ALERTA
(EXPEDIENT_ID);

CREATE INDEX HEL_ALERTA_ENTORN_I ON HEL_ALERTA
(ENTORN_ID);

CREATE INDEX HEL_ACCIO_DEFPROC_I ON HEL_ACCIO
(DEFINICIO_PROCES_ID);

CREATE INDEX HEL_VALIDACIO_TASCA_I ON HEL_VALIDACIO
(TASCA_ID);

CREATE INDEX HEL_VALIDACIO_CAMP_I ON HEL_VALIDACIO
(CAMP_ID);

CREATE INDEX HEL_TERMINIC_TERMINI_I ON HEL_TERMINI_INICIAT
(TERMINI_ID);

CREATE INDEX HEL_TERMINI_DEFPROC_I ON HEL_TERMINI
(DEFINICIO_PROCES_ID);

CREATE INDEX HEL_TASCA_DEFPROC_I ON HEL_TASCA
(DEFINICIO_PROCES_ID);

CREATE INDEX HEL_TASCA_JBPMNAME_I ON HEL_TASCA
(JBPM_NAME);

CREATE INDEX HEL_PERSONA_RELLEU_I ON HEL_PERSONA
(RELLEU_ID);

CREATE INDEX HEL_FIRTASCA_TASCA_I ON HEL_FIRMA_TASCA
(TASCA_ID);

CREATE INDEX HEL_FIRTASCA_DOCUMENT_I ON HEL_FIRMA_TASCA
(DOCUMENT_ID);

CREATE INDEX HEL_FIRTASCA_EXTIP_I ON HEL_CAMP_TASCA
(EXPEDIENT_TIPUS_ID);

CREATE INDEX HEL_EXPTIP_ENTORN_I ON HEL_EXPEDIENT_TIPUS
(ENTORN_ID);

CREATE INDEX HEL_EXTIP_PARE_I on HEL_EXPEDIENT_TIPUS
(EXPEDIENT_TIPUS_PARE_ID);

CREATE INDEX HEL_EXPEDIENT_TIPUS_I ON HEL_EXPEDIENT
(TIPUS_ID);

CREATE INDEX HEL_EXPEDIENT_ENTORN_I ON HEL_EXPEDIENT
(ENTORN_ID);

CREATE INDEX HEL_EXPEDIENT_ESTAT_I ON HEL_EXPEDIENT
(ESTAT_ID);

CREATE INDEX HEL_ESTAT_EXPTIP_I ON HEL_ESTAT
(EXPEDIENT_TIPUS_ID);

CREATE INDEX HEL_ENUM_ENTORN_I ON HEL_ENUMERACIO
(ENTORN_ID);

CREATE INDEX HEL_DOMINI_EXPTIP_I ON HEL_DOMINI
(EXPEDIENT_TIPUS_ID);

CREATE INDEX HEL_DOMINI_ENTORN_I ON HEL_DOMINI
(ENTORN_ID);

CREATE INDEX HEL_DOCTASCA_DOCUMENT_I ON HEL_DOCUMENT_TASCA
(DOCUMENT_ID);

CREATE INDEX HEL_DOCTASCA_TASCA_I ON HEL_DOCUMENT_TASCA
(TASCA_ID);

CREATE INDEX HEL_DOCUMENT_DEFPROC_I ON HEL_DOCUMENT
(DEFINICIO_PROCES_ID);

CREATE INDEX HEL_DOCUMENT_EXPTIP_I ON HEL_DOCUMENT
(EXPEDIENT_TIPUS_ID);

CREATE INDEX HEL_DOCUMENT_CAMPDATA_I ON HEL_DOCUMENT
(CAMP_DATA_ID);

CREATE INDEX HEL_DEFPROC_ENTORN_I ON HEL_DEFINICIO_PROCES
(ENTORN_ID);

CREATE INDEX HEL_DEFPROC_EXPTIP_I ON HEL_DEFINICIO_PROCES
(EXPEDIENT_TIPUS_ID);

CREATE INDEX HEL_CONSULTACAMP_CONSULTA_I ON HEL_CONSULTA_CAMP
(CONSULTA_ID);

CREATE INDEX HEL_CONSULTA_ENTORN_I ON HEL_CONSULTA
(ENTORN_ID);

CREATE INDEX HEL_CONSULTA_EXPTIP_I ON HEL_CONSULTA
(EXPEDIENT_TIPUS_ID);

CREATE INDEX HEL_CARREC_ENTORN_I ON HEL_CARREC
(ENTORN_ID);

CREATE INDEX HEL_CARREC_AREA_I ON HEL_CARREC
(AREA_ID);

CREATE INDEX HEL_CAMPTASCA_CAMP_I ON HEL_CAMP_TASCA
(CAMP_ID);

CREATE INDEX HEL_REPRO_TASCA_CODI_I ON HEL_REPRO 
(TASCA_CODI);

CREATE INDEX HEL_INTERESSAT_EXPEDIENT_ID_I ON HEL_INTERESSAT 
(EXPEDIENT_ID);

CREATE INDEX HEL_EXPLOG_EXPID_I ON HEL_EXPEDIENT_LOG 
(EXPEDIENT_ID);

CREATE INDEX HEL_EXPLOG_TARGETID_I ON HEL_EXPEDIENT_LOG 
(TARGET_ID);


CREATE INDEX HEL_ENUM_ID_I ON HEL_ENUMERACIO_VALORS (ENUMERACIO_ID);

CREATE INDEX HEL_ANOTACIO_ANNEX_FK_I ON HEL_ANOTACIO_ANNEX(ANOTACIO_ID);
CREATE INDEX HEL_ANOTACIO_INTER_FK_I ON HEL_ANOTACIO_INTERESSAT(ANOTACIO_ID);
CREATE INDEX HEL_REPRESENTANT_ANOTACIO_FK_I ON HEL_ANOTACIO_INTERESSAT(REPRESENTANT_ID);
CREATE INDEX HEL_ANOTACIO_EXPEDIENT_FK_I ON HEL_ANOTACIO(EXPEDIENT_ID);
CREATE INDEX HEL_ANOTACIO_ET_FK_I ON HEL_ANOTACIO(EXPEDIENT_TIPUS_ID);

-- Index per a consulta d'operaicons massives pendents --
CREATE INDEX HEL_EXMASEXP_EXEMAS_I ON HEL_EXEC_MASEXP (EXECMAS_ID);

CREATE INDEX HEL_AVIS_DATA_INICI_I ON HEL_AVIS(DATA_INICI);
CREATE INDEX HEL_AVIS_DATA_FINAL_I ON HEL_AVIS(DATA_FINAL);

CREATE INDEX HEL_REGLA_ENTORN_FK_I ON HEL_ESTAT_REGLA(ENTORN_ID);
CREATE INDEX HEL_REGLA_EXPTIPUS_FK_I ON HEL_ESTAT_REGLA(EXPEDIENT_TIPUS_ID);
CREATE INDEX HEL_REGLA_ESTAT_FK_I ON HEL_ESTAT_REGLA(ESTAT_ID);
CREATE INDEX HEL_REGLA_VALOR_QUI_FK_I ON HEL_ESTAT_REGLA_VALOR_QUI(REGLA_ID);
CREATE INDEX HEL_REGLA_VALOR_QUE_FK_I ON HEL_ESTAT_REGLA_VALOR_QUE(REGLA_ID);

CREATE INDEX HEL_ESTACC_ENT_ESTAT_FK_I ON HEL_ESTAT_ACCIO_ENTRADA(ESTAT_ID);
CREATE INDEX HEL_ESTACC_SORT_ESTAT_FK_I ON HEL_ESTAT_ACCIO_SORTIDA(ESTAT_ID);


-- Índex sobre les claus foranes
CREATE INDEX HEL_ED_ET_I ON HEL_EXPEDIENT_DADES 
(EXPEDIENT_TIPUS_ID);

CREATE INDEX HEL_ED_EX_I ON HEL_EXPEDIENT_DADES 
(EXPEDIENT_ID);

-- Índex per les dades JSON dels expeidents
CREATE SEARCH INDEX HEL_EXP_DADES_JSON_IDX
ON HEL_EXPEDIENT_DADES(DADES)
FOR JSON;