-- Claus primàries i úniques

ALTER TABLE HEL_UO_SINC_REL ADD CONSTRAINT HEL_UO_SINC_REL_MULT_UK UNIQUE (ANTIGA_UO, NOVA_UO);

ALTER TABLE HEL_ACCIO ADD (
  PRIMARY KEY
 (ID),
  UNIQUE (CODI, DEFINICIO_PROCES_ID, EXPEDIENT_TIPUS_ID));

ALTER TABLE HEL_ACL_CLASS ADD (
  PRIMARY KEY
 (ID),
  UNIQUE (CLASS));

ALTER TABLE HEL_ACL_ENTRY ADD (
  PRIMARY KEY
 (ID));

ALTER TABLE HEL_ACL_OBJECT_IDENTITY ADD (
  PRIMARY KEY
 (ID));

ALTER TABLE HEL_ACL_SID ADD (
  PRIMARY KEY
 (ID));

ALTER TABLE HEL_ACTION_LOG ADD (
  PRIMARY KEY
 (ID));

ALTER TABLE HEL_ALERTA ADD (
  PRIMARY KEY
 (ID));

ALTER TABLE HEL_AREA ADD (
  PRIMARY KEY
 (ID),
  UNIQUE (CODI, ENTORN_ID));

ALTER TABLE HEL_AREA_JBPMID ADD (
  PRIMARY KEY
 (ID));

ALTER TABLE HEL_AREA_MEMBRE ADD (
  PRIMARY KEY
 (ID),
  UNIQUE (CODI, AREA_ID));

ALTER TABLE HEL_AREA_TIPUS ADD (
  PRIMARY KEY
 (ID),
  UNIQUE (CODI, ENTORN_ID));

ALTER TABLE HEL_CAMP ADD (
  PRIMARY KEY
 (ID),
  UNIQUE (CODI, DEFINICIO_PROCES_ID, EXPEDIENT_TIPUS_ID));

ALTER TABLE HEL_CAMP_AGRUP ADD (
  PRIMARY KEY
 (ID),
  UNIQUE (CODI, DEFINICIO_PROCES_ID, EXPEDIENT_TIPUS_ID));

ALTER TABLE HEL_CAMP_REGISTRE ADD (
  PRIMARY KEY
 (ID),
  UNIQUE (REGISTRE_ID, ORDRE),
  UNIQUE (REGISTRE_ID, MEMBRE_ID));

ALTER TABLE HEL_CAMP_TASCA ADD (
  PRIMARY KEY
 (ID),
  UNIQUE (TASCA_ID, ORDRE),
  UNIQUE (CAMP_ID, TASCA_ID));

ALTER TABLE HEL_CARREC ADD (
  PRIMARY KEY
 (ID),
  UNIQUE (CODI, ENTORN_ID));

ALTER TABLE HEL_CARREC_JBPMID ADD (
  PRIMARY KEY
 (ID));

ALTER TABLE HEL_CONSULTA ADD (
  PRIMARY KEY
 (ID),
  UNIQUE (CODI, ENTORN_ID, EXPEDIENT_TIPUS_ID));

ALTER TABLE HEL_CONSULTA_CAMP ADD (
  PRIMARY KEY
 (ID),
  UNIQUE (CONSULTA_ID, CAMP_CODI, DEFPROC_JBPMKEY, DEFPROC_VERSIO, TIPUS));

ALTER TABLE HEL_CONSULTA_SUB ADD (
  PRIMARY KEY
 (PARE_ID, FILL_ID));

ALTER TABLE HEL_DEFINICIO_PROCES ADD (
  PRIMARY KEY
 (ID),
  UNIQUE (JBPM_ID));

ALTER TABLE HEL_DOCUMENT ADD (
  PRIMARY KEY
 (ID),
  UNIQUE (CODI, DEFINICIO_PROCES_ID, EXPEDIENT_TIPUS_ID));

ALTER TABLE HEL_DOCUMENT_STORE ADD (
  PRIMARY KEY
 (ID));

ALTER TABLE HEL_DOCUMENT_TASCA ADD (
  PRIMARY KEY
 (ID),
  UNIQUE (TASCA_ID, ORDRE),
  UNIQUE (DOCUMENT_ID, TASCA_ID));

ALTER TABLE HEL_DOMINI ADD (
  PRIMARY KEY
 (ID),
  UNIQUE (CODI, ENTORN_ID, EXPEDIENT_TIPUS_ID));

ALTER TABLE HEL_ENTORN ADD (
  PRIMARY KEY
 (ID),
  UNIQUE (CODI));

ALTER TABLE HEL_ENUMERACIO ADD (
  PRIMARY KEY
 (ID),
  UNIQUE (CODI, ENTORN_ID));

ALTER TABLE HEL_ENUMERACIO_VALORS ADD (
  PRIMARY KEY
 (ID));

ALTER TABLE HEL_ESTAT ADD (
  PRIMARY KEY
 (ID),
  UNIQUE (CODI, EXPEDIENT_TIPUS_ID));

ALTER TABLE HEL_EXPEDIENT ADD (
  PRIMARY KEY
 (ID),
  UNIQUE (PROCESS_INSTANCE_ID));

ALTER TABLE HEL_EXEC_MASEXP ADD (
  PRIMARY KEY
 (ID));

ALTER TABLE HEL_EXEC_MASSIVA ADD (
  PRIMARY KEY
 (ID));

ALTER TABLE HEL_EXPEDIENT_LOG ADD (
  PRIMARY KEY
 (ID));

ALTER TABLE HEL_EXPEDIENT_RELS ADD (
  PRIMARY KEY
 (ORIGEN_ID, DESTI_ID));

ALTER TABLE HEL_EXPEDIENT_TIPUS ADD (
  PRIMARY KEY
 (ID),
  UNIQUE (SISTRA_CODTRA),
  UNIQUE (CODI, ENTORN_ID));

ALTER TABLE HEL_AVIS ADD (
  CONSTRAINT HEL_AVIS_PK PRIMARY KEY (ID));

ALTER TABLE HEL_EXPEDIENT_TIPUS_SEQANY ADD (
  PRIMARY KEY (ID));

ALTER TABLE HEL_EXPEDIENT_TIPUS_SEQDEFANY ADD (
  PRIMARY KEY (ID));

ALTER TABLE HEL_FESTIU ADD (
  PRIMARY KEY
 (ID),
  UNIQUE (DATA));

ALTER TABLE HEL_FIRMA_TASCA ADD (
  PRIMARY KEY
 (ID),
  UNIQUE (TASCA_ID, ORDRE),
  UNIQUE (DOCUMENT_ID, TASCA_ID));

ALTER TABLE HEL_FORMEXT ADD (
  PRIMARY KEY
 (ID),
  UNIQUE (FORMID));

ALTER TABLE HEL_MAP_SISTRA ADD (
  PRIMARY KEY
 (ID),
  UNIQUE (CODIHELIUM, EXPEDIENT_TIPUS_ID));

ALTER TABLE HEL_PERMIS ADD (
  PRIMARY KEY
 (CODI));

ALTER TABLE HEL_PERSONA ADD (
  PRIMARY KEY
 (ID),
  UNIQUE (CODI));

ALTER TABLE HEL_PORTASIGNATURES ADD (
  PRIMARY KEY
 (ID),
  UNIQUE (DOCUMENT_ID, TOKEN_ID));

ALTER TABLE HEL_REDIR ADD (
  PRIMARY KEY
 (ID));

ALTER TABLE HEL_REGISTRE ADD (
  PRIMARY KEY
 (ID));

ALTER TABLE HEL_TASCA ADD (
  PRIMARY KEY
 (ID),
  UNIQUE (JBPM_NAME, DEFINICIO_PROCES_ID));

ALTER TABLE HEL_TERMINI ADD (
  PRIMARY KEY
 (ID),
  UNIQUE (CODI, DEFINICIO_PROCES_ID, EXPEDIENT_TIPUS_ID));

ALTER TABLE HEL_TERMINI_INICIAT ADD (
  PRIMARY KEY
 (ID),
  UNIQUE (TERMINI_ID, PROCESS_INSTANCE_ID));

ALTER TABLE HEL_USUARI ADD (
  PRIMARY KEY
 (CODI));

ALTER TABLE HEL_USUARI_PERMIS ADD (
  PRIMARY KEY
 (CODI, PERMIS));

ALTER TABLE HEL_USUARI_PREFS ADD (
  PRIMARY KEY
 (CODI));

ALTER TABLE HEL_VALIDACIO ADD (
  PRIMARY KEY
 (ID));

ALTER TABLE HEL_VERSIO ADD (
  PRIMARY KEY
 (ID),
  UNIQUE (CODI),
  UNIQUE (ORDRE));

ALTER TABLE HEL_REPRO ADD (
  PRIMARY KEY
 (ID));


ALTER TABLE HEL_ESTAT_REGLA ADD (
	CONSTRAINT HEL_ESTAT_REGLA_PK PRIMARY KEY (ID));

ALTER TABLE HEL_ESTAT_REGLA_VALOR_QUI ADD (
	CONSTRAINT HEL_ESTAT_REGLA_VALOR_QUI_PK PRIMARY KEY (REGLA_ID, VALOR));

ALTER TABLE HEL_ESTAT_REGLA_VALOR_QUE ADD (
	CONSTRAINT HEL_ESTAT_REGLA_VALOR_QUE_PK PRIMARY KEY (REGLA_ID, VALOR));

ALTER TABLE HEL_UNITAT_ORGANITZATIVA ADD (
  PRIMARY KEY
 (ID));


ALTER TABLE HEL_EXPEDIENT_DADES ADD (
  PRIMARY KEY
 (ID));

ALTER TABLE HEL_EXPEDIENT_DADES ADD (
	CONSTRAINT HEL_EXPEDIENT_DADES_UK UNIQUE (EXPEDIENT_TIPUS_ID, EXPEDIENT_ID, PROCESS_ID, TASK_ID));

ALTER TABLE HEL_RECURS ADD (
  PRIMARY KEY
 (ID));

-- Claus foranes

ALTER TABLE HEL_EXPEDIENT ADD (
	CONSTRAINT HEL_UNIT_ORG_EXPEDIENT_FK
	FOREIGN KEY (UNITAT_ORGANITZATIVA_ID) REFERENCES HEL_UNITAT_ORGANITZATIVA(ID));

ALTER TABLE HEL_EXPEDIENT_TIPUS_UNITAT_ORG ADD (
  	CONSTRAINT HEL_EXP_TIPUS_UO_PK PRIMARY KEY (ID));

ALTER TABLE HEL_EXPEDIENT_TIPUS_UNITAT_ORG ADD (
	CONSTRAINT HEL_EXP_TIPUS_EXPTIPUS_UO_FK
	FOREIGN KEY (EXPEDIENT_TIPUS_ID) REFERENCES HEL_EXPEDIENT_TIPUS(ID));

ALTER TABLE HEL_EXPEDIENT_TIPUS_UNITAT_ORG ADD (
	CONSTRAINT HEL_UNIT_ORG_EXPTIPUS_UO_FK
	FOREIGN KEY (UNITAT_ORGANITZATIVA_ID) REFERENCES HEL_UNITAT_ORGANITZATIVA(ID));

ALTER TABLE HEL_PROCEDIMENT ADD (
  CONSTRAINT HEL_PROCEDIMENT_PK PRIMARY KEY (ID));

ALTER TABLE HEL_PROCEDIMENT ADD CONSTRAINT HEL_PROCEDIMENT_UNITAT_FK
	FOREIGN KEY (UNITAT_ORGANITZATIVA_ID) REFERENCES HEL_UNITAT_ORGANITZATIVA(ID);

ALTER TABLE HEL_UO_SINC_REL ADD (
  CONSTRAINT HEL_UNITAT_ANTIGA_FK FOREIGN KEY (ANTIGA_UO)
    REFERENCES HEL_UNITAT_ORGANITZATIVA (ID));

ALTER TABLE HEL_UO_SINC_REL ADD (
  CONSTRAINT HEL_UNITAT_NOVA_FK FOREIGN KEY (NOVA_UO)
    REFERENCES HEL_UNITAT_ORGANITZATIVA (ID));


 ALTER TABLE HEL_INTERESSAT ADD (
  CONSTRAINT HEL_INTERESSAT_PK PRIMARY KEY (ID),
  CONSTRAINT HEL_EXPEDIENT_INTERESSAT_FK FOREIGN KEY (EXPEDIENT_ID)
	 REFERENCES HEL_EXPEDIENT (ID),
  CONSTRAINT HEL_INTERESSAT_REPRESENTANT_FK FOREIGN KEY (REPRESENTANT_ID)
	 REFERENCES HEL_INTERESSAT (ID));

ALTER TABLE HEL_PORTASIGNATURES ADD (
  CONSTRAINT HEL_EXPEDIENT_PSIGNA_FK FOREIGN KEY (EXPEDIENT_ID)
 REFERENCES HEL_EXPEDIENT (ID));




ALTER TABLE HEL_ACCIO ADD (
  CONSTRAINT HEL_DEFPROC_ACCIO_FK
 FOREIGN KEY (DEFINICIO_PROCES_ID)
 REFERENCES HEL_DEFINICIO_PROCES (ID));

ALTER TABLE HEL_ACCIO ADD (
  CONSTRAINT HEL_EXPTIP_ACCIO_FK
 FOREIGN KEY (EXPEDIENT_TIPUS_ID)
 REFERENCES HEL_EXPEDIENT_TIPUS (ID));

ALTER TABLE HEL_ACL_ENTRY ADD (
  CONSTRAINT HEL_ACLOBJID_ACLENTRY_FK
 FOREIGN KEY (ACL_OBJECT_IDENTITY)
 REFERENCES HEL_ACL_OBJECT_IDENTITY (ID),
  CONSTRAINT HEL_ACLSID_ACLENTRY_FK
 FOREIGN KEY (SID)
 REFERENCES HEL_ACL_SID (ID));

ALTER TABLE HEL_ACL_OBJECT_IDENTITY ADD (
  CONSTRAINT HEL_ACLSID_ACLOBJID_FK
 FOREIGN KEY (OWNER_SID)
 REFERENCES HEL_ACL_SID (ID),
  CONSTRAINT HEL_ACLOBJID_ACLOBJID_FK
 FOREIGN KEY (PARENT_OBJECT)
 REFERENCES HEL_ACL_OBJECT_IDENTITY (ID),
  CONSTRAINT HEL_ACLCLASS_ACLOBJID_FK
 FOREIGN KEY (OBJECT_ID_CLASS)
 REFERENCES HEL_ACL_CLASS (ID));

ALTER TABLE HEL_ALERTA ADD (
  CONSTRAINT HEL_ENTORN_ALERTA_FK
 FOREIGN KEY (ENTORN_ID)
 REFERENCES HEL_ENTORN (ID),
  CONSTRAINT HEL_EXPEDIENT_ALERTA_FK
 FOREIGN KEY (EXPEDIENT_ID)
 REFERENCES HEL_EXPEDIENT (ID),
  CONSTRAINT HEL_TERMINI_ALERTA_FK
 FOREIGN KEY (TERMINI_INICIAT_ID)
 REFERENCES HEL_TERMINI_INICIAT (ID));

ALTER TABLE HEL_AREA ADD (
  CONSTRAINT HEL_ENTORN_AREA_FK
 FOREIGN KEY (ENTORN_ID)
 REFERENCES HEL_ENTORN (ID),
  CONSTRAINT HEL_AREA_AREA_FK
 FOREIGN KEY (PARE_ID)
 REFERENCES HEL_AREA (ID),
  CONSTRAINT HEL_AREATIPUS_AREA_FK
 FOREIGN KEY (TIPUS_ID)
 REFERENCES HEL_AREA_TIPUS (ID));

ALTER TABLE HEL_AREA_MEMBRE ADD (
  CONSTRAINT HEL_AREA_AREAMEMBRE_FK
 FOREIGN KEY (AREA_ID)
 REFERENCES HEL_AREA (ID));

ALTER TABLE HEL_AREA_TIPUS ADD (
  CONSTRAINT HEL_ENTORN_AREATIPUS_FK
 FOREIGN KEY (ENTORN_ID)
 REFERENCES HEL_ENTORN (ID));

ALTER TABLE HEL_CAMP ADD (
  CONSTRAINT HEL_DEFPROC_CAMP_FK
 FOREIGN KEY (DEFINICIO_PROCES_ID)
 REFERENCES HEL_DEFINICIO_PROCES (ID),
  CONSTRAINT HEL_EXPTIP_CAMP_FK
 FOREIGN KEY (EXPEDIENT_TIPUS_ID)
 REFERENCES HEL_EXPEDIENT_TIPUS (ID),
  CONSTRAINT HEL_CAMPAGRUP_CAMP_FK
 FOREIGN KEY (CAMP_AGRUPACIO_ID)
 REFERENCES HEL_CAMP_AGRUP (ID),
  CONSTRAINT HEL_ENUMERACIO_CAMP_FK
 FOREIGN KEY (ENUMERACIO_ID)
 REFERENCES HEL_ENUMERACIO (ID),
  CONSTRAINT HEL_DOMINI_CAMP_FK
 FOREIGN KEY (DOMINI_ID)
 REFERENCES HEL_CONSULTA (ID),
  CONSTRAINT HEL_CONSULTA_CAMP_FK
 FOREIGN KEY (CONSULTA_ID)
 REFERENCES HEL_CONSULTA (ID));

ALTER TABLE HEL_CAMP_AGRUP ADD (
  CONSTRAINT HEL_DEFPROC_CAMPAGRUP_FK
 FOREIGN KEY (DEFINICIO_PROCES_ID)
 REFERENCES HEL_DEFINICIO_PROCES (ID),
  CONSTRAINT HEL_EXPTIP_CAMPAGRUP_FK
 FOREIGN KEY (EXPEDIENT_TIPUS_ID)
 REFERENCES HEL_EXPEDIENT_TIPUS (ID));

ALTER TABLE HEL_CAMP_REGISTRE ADD (
  CONSTRAINT HEL_CAMP_REGMEMBRE_FK
 FOREIGN KEY (MEMBRE_ID)
 REFERENCES HEL_CAMP (ID),
  CONSTRAINT HEL_CAMP_REGREGISTRE_FK
 FOREIGN KEY (REGISTRE_ID)
 REFERENCES HEL_CAMP (ID));

ALTER TABLE HEL_CAMP_TASCA ADD (
  CONSTRAINT HEL_TASCA_CAMPTASCA_FK
 FOREIGN KEY (TASCA_ID)
 REFERENCES HEL_TASCA (ID),
  CONSTRAINT HEL_CAMP_CAMPTASCA_FK
 FOREIGN KEY (CAMP_ID)
 REFERENCES HEL_CAMP (ID),
  CONSTRAINT HEL_EXPTIPUS_CAMPTASCA_FK
 FOREIGN KEY (EXPEDIENT_TIPUS_ID)
 REFERENCES HEL_EXPEDIENT_TIPUS (ID)
 );

ALTER TABLE HEL_CARREC ADD (
  CONSTRAINT HEL_ENTORN_CARREC_FK
 FOREIGN KEY (ENTORN_ID)
 REFERENCES HEL_ENTORN (ID),
  CONSTRAINT HEL_AREA_CARREC_FK
 FOREIGN KEY (AREA_ID)
 REFERENCES HEL_AREA (ID));

ALTER TABLE HEL_CONSULTA ADD (
  CONSTRAINT HEL_ENTORN_CONSULTA_FK
 FOREIGN KEY (ENTORN_ID)
 REFERENCES HEL_ENTORN (ID),
  CONSTRAINT HEL_EXPTIP_CONSULTA_FK
 FOREIGN KEY (EXPEDIENT_TIPUS_ID)
 REFERENCES HEL_EXPEDIENT_TIPUS (ID));

ALTER TABLE HEL_CONSULTA_CAMP ADD (
  CONSTRAINT HEL_CONSULTA_CONCAMP_FK
 FOREIGN KEY (CONSULTA_ID)
 REFERENCES HEL_CONSULTA (ID));

ALTER TABLE HEL_CONSULTA_SUB ADD (
  CONSTRAINT HEL_PARE_CONSULTASUB_FK
 FOREIGN KEY (FILL_ID)
 REFERENCES HEL_CONSULTA (ID),
  CONSTRAINT HEL_FILL_CONSULTASUB_FK
 FOREIGN KEY (PARE_ID)
 REFERENCES HEL_CONSULTA (ID));

ALTER TABLE HEL_DEFINICIO_PROCES ADD (
  CONSTRAINT HEL_ENTORN_DEFPROC_FK
 FOREIGN KEY (ENTORN_ID)
 REFERENCES HEL_ENTORN (ID),
  CONSTRAINT HEL_EXPTIP_DEFPROC_FK
 FOREIGN KEY (EXPEDIENT_TIPUS_ID)
 REFERENCES HEL_EXPEDIENT_TIPUS (ID));

ALTER TABLE HEL_DOCUMENT ADD (
  CONSTRAINT HEL_DEFPROC_DOCUMENT_FK
 FOREIGN KEY (DEFINICIO_PROCES_ID)
 REFERENCES HEL_DEFINICIO_PROCES (ID),
 CONSTRAINT HEL_EXPTIP_DOC_FK
 FOREIGN KEY (EXPEDIENT_TIPUS_ID)
 REFERENCES HEL_EXPEDIENT_TIPUS (ID),
  CONSTRAINT HEL_CAMP_DOCUMENT_FK
 FOREIGN KEY (CAMP_DATA_ID)
 REFERENCES HEL_CAMP (ID));

ALTER TABLE HEL_DOCUMENT_TASCA ADD (
  CONSTRAINT HEL_TASCA_DOCTASCA_FK
 FOREIGN KEY (TASCA_ID)
 REFERENCES HEL_TASCA (ID),
  CONSTRAINT HEL_DOCUMENT_DOCTASCA_FK
 FOREIGN KEY (DOCUMENT_ID)
 REFERENCES HEL_DOCUMENT (ID),
  CONSTRAINT HEL_EXPTIPUS_DOCTASCA_FK
 FOREIGN KEY (EXPEDIENT_TIPUS_ID)
 REFERENCES HEL_EXPEDIENT_TIPUS (ID)
 );

ALTER TABLE HEL_DOMINI ADD (
  CONSTRAINT HEL_ENTORN_DOMINI_FK
 FOREIGN KEY (ENTORN_ID)
 REFERENCES HEL_ENTORN (ID),
  CONSTRAINT HEL_EXPTIP_DOMINI_FK
 FOREIGN KEY (EXPEDIENT_TIPUS_ID)
 REFERENCES HEL_EXPEDIENT_TIPUS (ID));

ALTER TABLE HEL_ENUMERACIO ADD (
  CONSTRAINT HEL_ENTORN_ENUMERACIO_FK
 FOREIGN KEY (ENTORN_ID)
 REFERENCES HEL_ENTORN (ID),
  CONSTRAINT HEL_EXPTIP_ENUMERACIO_FK
 FOREIGN KEY (EXPEDIENT_TIPUS_ID)
 REFERENCES HEL_EXPEDIENT_TIPUS (ID));

ALTER TABLE HEL_ENUMERACIO_VALORS ADD (
  CONSTRAINT HEL_ENUMERACIO_VALORS_FK
 FOREIGN KEY (ENUMERACIO_ID)
 REFERENCES HEL_ENUMERACIO (ID));

ALTER TABLE HEL_ESTAT ADD (
  CONSTRAINT HEL_EXPTIPUS_ESTAT_FK
 FOREIGN KEY (EXPEDIENT_TIPUS_ID)
 REFERENCES HEL_EXPEDIENT_TIPUS (ID));

ALTER TABLE HEL_EXEC_MASEXP ADD (
  CONSTRAINT HEL_EXPEDIENT_EXEMASEX_FK
 FOREIGN KEY (EXPEDIENT_ID)
 REFERENCES HEL_EXPEDIENT (ID),
CONSTRAINT HEL_EXECMAS_EXEMASEX_FK
 FOREIGN KEY (EXECMAS_ID)
 REFERENCES HEL_EXEC_MASSIVA (ID));

ALTER TABLE HEL_EXEC_MASSIVA ADD (
  CONSTRAINT HEL_EXPTIPUS_EXEMAS_FK
 FOREIGN KEY (EXPEDIENT_TIPUS_ID)
 REFERENCES HEL_EXPEDIENT_TIPUS (ID));

ALTER TABLE HEL_EXPEDIENT ADD (
  CONSTRAINT HEL_ENTORN_EXPEDIENT_FK
 FOREIGN KEY (ENTORN_ID)
 REFERENCES HEL_ENTORN (ID),
  CONSTRAINT HEL_ESTAT_EXPEDIENT_FK
 FOREIGN KEY (ESTAT_ID)
 REFERENCES HEL_ESTAT (ID),
  CONSTRAINT HEL_EXPTIPUS_EXPEDIENT_FK
 FOREIGN KEY (TIPUS_ID)
 REFERENCES HEL_EXPEDIENT_TIPUS (ID));

ALTER TABLE HEL_EXPEDIENT_LOG ADD (
  CONSTRAINT HEL_EXPEDIENT_LOGS_FK
 FOREIGN KEY (EXPEDIENT_ID)
 REFERENCES HEL_EXPEDIENT (ID));

ALTER TABLE HEL_EXPEDIENT_RELS ADD (
  CONSTRAINT HEL_DESTI_EXPREL_FK
 FOREIGN KEY (DESTI_ID)
 REFERENCES HEL_EXPEDIENT (ID),
  CONSTRAINT HEL_ORIGEN_EXPREL_FK
 FOREIGN KEY (ORIGEN_ID)
 REFERENCES HEL_EXPEDIENT (ID));

ALTER TABLE HEL_EXPEDIENT_TIPUS ADD (
  CONSTRAINT HEL_ENTORN_EXPTIPUS_FK
 FOREIGN KEY (ENTORN_ID)
 REFERENCES HEL_ENTORN (ID));

ALTER TABLE HEL_EXPEDIENT_TIPUS ADD (
  CONSTRAINT HEL_EXPTIPUS_PARE_EXPTIPUS_FK
 FOREIGN KEY (EXPEDIENT_TIPUS_PARE_ID)
 REFERENCES HEL_EXPEDIENT_TIPUS (ID));

ALTER TABLE HEL_EXPEDIENT_TIPUS_SEQANY ADD (
  CONSTRAINT HEL_EXPTIPUS_SEQANY_FK
 FOREIGN KEY (EXPEDIENT_TIPUS)
 REFERENCES HEL_EXPEDIENT_TIPUS (ID));

ALTER TABLE HEL_EXPEDIENT_TIPUS_SEQDEFANY ADD (
   CONSTRAINT HEL_EXPTIPUS_SEQDEFANY_FK
  FOREIGN KEY (EXPEDIENT_TIPUS)
  REFERENCES HEL_EXPEDIENT_TIPUS (ID));

ALTER TABLE HEL_FIRMA_TASCA ADD (
  CONSTRAINT HEL_TASCA_FIRTASCA_FK
 FOREIGN KEY (TASCA_ID)
 REFERENCES HEL_TASCA (ID),
  CONSTRAINT HEL_DOCUMENT_FIRTASCA_FK
 FOREIGN KEY (DOCUMENT_ID)
 REFERENCES HEL_DOCUMENT (ID),
  CONSTRAINT HEL_EXPTIPUS_FIRTASCA_FK
 FOREIGN KEY (EXPEDIENT_TIPUS_ID)
 REFERENCES HEL_EXPEDIENT_TIPUS (ID)
 );

ALTER TABLE HEL_MAP_SISTRA ADD (
  CONSTRAINT HEL_EXPTIPUS_MAP_SISTRA_FK
 FOREIGN KEY (EXPEDIENT_TIPUS_ID)
 REFERENCES HEL_EXPEDIENT_TIPUS (ID));

ALTER TABLE HEL_PERSONA ADD (
  CONSTRAINT HEL_RELLEU_PERSONA_FK
 FOREIGN KEY (RELLEU_ID)
 REFERENCES HEL_PERSONA (ID));

ALTER TABLE HEL_TASCA ADD (
  CONSTRAINT HEL_DEFPROC_TASCA_FK
 FOREIGN KEY (DEFINICIO_PROCES_ID)
 REFERENCES HEL_DEFINICIO_PROCES (ID));

ALTER TABLE HEL_TERMINI ADD (
  CONSTRAINT HEL_DEFPROC_TERMINI_FK
 FOREIGN KEY (DEFINICIO_PROCES_ID)
 REFERENCES HEL_DEFINICIO_PROCES (ID),
  CONSTRAINT HEL_EXPTIP_TERMINI_FK
 FOREIGN KEY (EXPEDIENT_TIPUS_ID)
 REFERENCES HEL_EXPEDIENT_TIPUS (ID));

ALTER TABLE HEL_TERMINI_INICIAT ADD (
  CONSTRAINT HEL_TERMINI_TERMINIC_FK
 FOREIGN KEY (TERMINI_ID)
 REFERENCES HEL_TERMINI (ID));

ALTER TABLE HEL_USUARI_PERMIS ADD (
  CONSTRAINT HEL_PERMIS_USUARI_FK
 FOREIGN KEY (CODI)
 REFERENCES HEL_USUARI (CODI),
  CONSTRAINT HEL_USUARI_PERMIS_FK
 FOREIGN KEY (PERMIS)
 REFERENCES HEL_PERMIS (CODI));

ALTER TABLE HEL_VALIDACIO ADD (
  CONSTRAINT HEL_TASCA_VALIDACIO_FK
 FOREIGN KEY (TASCA_ID)
 REFERENCES HEL_TASCA (ID),
  CONSTRAINT HEL_CAMP_VALIDACIO_FK
 FOREIGN KEY (CAMP_ID)
 REFERENCES HEL_CAMP (ID));
ALTER TABLE HEL_REPRO ADD (
  CONSTRAINT HEL_EXPTIP_REPRO_FK
 FOREIGN KEY (EXPTIP_ID)
 REFERENCES HEL_EXPEDIENT_TIPUS (ID));






 ALTER TABLE HEL_DOCUMENT_NOTIFICACIO ADD (
	CONSTRAINT HEL_EXPEDIENT_DOCNOT_FK FOREIGN KEY (EXPEDIENT_ID)
	REFERENCES HEL_EXPEDIENT (ID));

ALTER TABLE HEL_DOCUMENT_NOTIFICACIO ADD (PRIMARY KEY (ID));
ALTER TABLE HEL_DOCUMENT_NOTIFICACIO ADD (
	CONSTRAINT HEL_DOCUMENT_DOCNOTIF_FK FOREIGN KEY (DOCUMENT_STORE_ID)
 	REFERENCES HEL_DOCUMENT_STORE (ID));

 ALTER TABLE HEL_DOCUMENT_NOTIFICACIO ADD (
	CONSTRAINT HEL_CERTIFICACIO_NOTIF_FK FOREIGN KEY (CERTIFICACIO_STORE_ID)
 	REFERENCES HEL_DOCUMENT_STORE (ID));


ALTER TABLE HEL_ANOTACIO ADD (
  CONSTRAINT HEL_ANOTACIO_PK PRIMARY KEY (ID));

ALTER TABLE HEL_ANOTACIO_ANNEX ADD (
  CONSTRAINT HEL_ANOTACIO_ANNEX_PK PRIMARY KEY (ID));

ALTER TABLE HEL_ANOTACIO_INTERESSAT ADD (
  CONSTRAINT HEL_ANOTACIO_INTERESSAT_PK PRIMARY KEY (ID));

ALTER TABLE HEL_ESTAT_ACCIO_ENTRADA ADD (
	CONSTRAINT HEL_ESTACC_ENT_PK PRIMARY KEY (ID));

ALTER TABLE HEL_ESTAT_ACCIO_SORTIDA ADD (
	CONSTRAINT HEL_ESTACC_SORT_PK PRIMARY KEY (ID));

ALTER TABLE HEL_PINBAL_SERVEI ADD (
	CONSTRAINT HEL_PINBAL_SERVEI_PK PRIMARY KEY (ID));

ALTER TABLE HEL_PETICIO_PINBAL ADD (
	CONSTRAINT HEL_PETICIO_PINBAL_PK PRIMARY KEY (ID));

ALTER TABLE HEL_ANOTACIO_INTERESSAT ADD (
  CONSTRAINT HEL_ANOTACIO_INTERESSAT_FK FOREIGN KEY (ANOTACIO_ID)
    REFERENCES HEL_ANOTACIO (ID));

ALTER TABLE HEL_ANOTACIO_ANNEX ADD (
  CONSTRAINT HEL_ANOTACIO_ANNEX_FK FOREIGN KEY (ANOTACIO_ID)
    REFERENCES HEL_ANOTACIO (ID));

ALTER TABLE HEL_ANOTACIO ADD (
  CONSTRAINT HEL_ET_ANOTACIO_FK FOREIGN KEY (EXPEDIENT_TIPUS_ID)
    REFERENCES HEL_EXPEDIENT_TIPUS (ID));

ALTER TABLE HEL_ANOTACIO ADD (
  CONSTRAINT HEL_EXPEDIENT_ANOTACIO_FK FOREIGN KEY (EXPEDIENT_ID)
    REFERENCES HEL_EXPEDIENT (ID));

ALTER TABLE HEL_ESTAT_REGLA ADD (
	CONSTRAINT HEL_REGLA_EXPTIPUS_FK FOREIGN KEY (EXPEDIENT_TIPUS_ID)
		REFERENCES HEL_EXPEDIENT_TIPUS (ID));

ALTER TABLE HEL_ESTAT_REGLA ADD (
	CONSTRAINT HEL_REGLA_ESTAT_FK FOREIGN KEY (ESTAT_ID)
		REFERENCES HEL_ESTAT (ID));

ALTER TABLE HEL_ESTAT_REGLA ADD (
	CONSTRAINT HEL_REGLA_ENTORN_FK FOREIGN KEY (ENTORN_ID)
			REFERENCES HEL_ENTORN (ID));

ALTER TABLE HEL_ESTAT_REGLA ADD (
	CONSTRAINT HEL_REGLA_NOM_UK UNIQUE (ESTAT_ID, NOM));

ALTER TABLE HEL_ESTAT_REGLA_VALOR_QUI ADD (
	CONSTRAINT HEL_REGLA_VALOR_QUI_FK FOREIGN KEY (REGLA_ID)
		REFERENCES HEL_ESTAT_REGLA (ID));

ALTER TABLE HEL_ESTAT_REGLA_VALOR_QUE ADD (
	CONSTRAINT HEL_REGLA_VALOR_QUE_FK FOREIGN KEY (REGLA_ID)
		REFERENCES HEL_ESTAT_REGLA (ID));

ALTER TABLE HEL_ESTAT_ACCIO_ENTRADA ADD (
	CONSTRAINT HEL_ESTACC_ENT_ESTAT_FK FOREIGN KEY (ESTAT_ID)
		REFERENCES HEL_ESTAT (ID));

ALTER TABLE HEL_ESTAT_ACCIO_ENTRADA ADD (
	CONSTRAINT HEL_ESTACC_ENT_ACCIO_FK FOREIGN KEY (ACCIO_ID)
		REFERENCES HEL_ACCIO (ID));

ALTER TABLE HEL_ESTAT_ACCIO_SORTIDA ADD (
	CONSTRAINT HEL_ESTACC_SORT_ESTAT_FK
		FOREIGN KEY (ESTAT_ID) REFERENCES HEL_ESTAT (ID));

ALTER TABLE HEL_ESTAT_ACCIO_SORTIDA ADD (
	CONSTRAINT HEL_ESTACC_SORT_ACCIO_FK FOREIGN KEY (ACCIO_ID)
		REFERENCES HEL_ACCIO (ID));


ALTER TABLE HEL_DOCUMENT_CONTINGUT 	ADD (
	CONSTRAINT HEL_DOCSTORE_DOCCONT_ID_FK FOREIGN KEY (ID)
		REFERENCES HEL_DOCUMENT_STORE (ID));

ALTER TABLE HEL_DOCUMENT_CONTINGUT 	ADD (
	CONSTRAINT HEL_DOCSTORE_DOCCONT_CONT_FK FOREIGN KEY (DOCUMENT_CONTINGUT)
		REFERENCES HEL_DOCUMENT_STORE (ID));

ALTER TABLE HEL_PETICIO_PINBAL ADD (
  CONSTRAINT HEL_PETICIO_EXPEDIENT_FK FOREIGN KEY (EXPEDIENT_ID)
    REFERENCES HEL_EXPEDIENT (ID));


ALTER TABLE HEL_ANOTACIO_EMAIL ADD (
  PRIMARY KEY (ID));

ALTER TABLE HEL_ANOTACIO_EMAIL ADD (
	CONSTRAINT HEL_ANOTACIO_ID_FK FOREIGN KEY (ANOTACIO_ID)
		REFERENCES HEL_ANOTACIO (ID));

ALTER TABLE HEL_ANOTACIO_EMAIL ADD (
	CONSTRAINT HEL_EXPEDIENT_ID_FK FOREIGN KEY (EXPEDIENT_ID)
		REFERENCES HEL_EXPEDIENT (ID));

ALTER TABLE HEL_ESTAT_SORTIDA ADD (
  PRIMARY KEY (ESTAT_ID, ESTAT_SEGUENT_ID));

ALTER TABLE HEL_ESTAT_SORTIDA ADD (
	CONSTRAINT HEL_ESTAT_ID_FK FOREIGN KEY (ESTAT_ID)
		REFERENCES HEL_ESTAT (ID));

ALTER TABLE HEL_ESTAT_SORTIDA ADD (
	CONSTRAINT HEL_ESTAT_SEGUENT_ID_FK FOREIGN KEY (ESTAT_SEGUENT_ID)
		REFERENCES HEL_ESTAT (ID));

ALTER TABLE HEL_EXPEDIENT_DADES ADD (
	CONSTRAINT HEL_ED_ET_FK FOREIGN KEY (EXPEDIENT_TIPUS_ID)
		REFERENCES HEL_EXPEDIENT_TIPUS (ID));

ALTER TABLE HEL_EXPEDIENT_DADES ADD (
	CONSTRAINT HEL_ED_EX_FK FOREIGN KEY (EXPEDIENT_ID)
		REFERENCES HEL_EXPEDIENT (ID));

ALTER TABLE HEL_RECURS ADD (
  	CONSTRAINT HEL_RECURS_EXPTIP_FK FOREIGN KEY (EXPEDIENT_TIPUS_ID)
		REFERENCES HEL_EXPEDIENT_TIPUS (ID));

ALTER TABLE HEL_RECURS ADD (
  	CONSTRAINT HEL_RECURS_DEFPROC_FK FOREIGN KEY (DEFINICIO_PROCES_ID)
		REFERENCES HEL_DEFINICIO_PROCES (ID));

ALTER TABLE HEL_EXPEDIENT_DOCUMENT ADD (
  CONSTRAINT HEL_EXP_DOC_PK PRIMARY KEY (DOCUMENT_STORE_ID));

ALTER TABLE HEL_EXPEDIENT_DOCUMENT ADD (
  	CONSTRAINT HEL_EXP_DOC_DOCUMENT_STORE_FK FOREIGN KEY (DOCUMENT_STORE_ID)
		REFERENCES HEL_DOCUMENT_STORE (ID));

ALTER TABLE HEL_EXPEDIENT_DOCUMENT ADD (
  	CONSTRAINT HEL_EXP_DOC_EXPEDIENT_FK FOREIGN KEY (EXPEDIENT_ID)
		REFERENCES HEL_EXPEDIENT (ID));

ALTER TABLE HEL_EXPLOT_DIM ADD CONSTRAINT HEL_EXPLOT_DIM_UK UNIQUE (
	UNITAT_ORGANITZATIVA_ID,
	ENTORN_ID,
	TIPUS_ID
);

ALTER TABLE HEL_EXPLOT_FET ADD CONSTRAINT HEL_EXPLOT_FET_DIM_FK FOREIGN KEY (DIMENSIO_ID) REFERENCES HEL_EXPLOT_DIM (ID);
ALTER TABLE HEL_EXPLOT_FET ADD CONSTRAINT HEL_EXPLOT_FET_TEMPS_FK FOREIGN KEY (TEMPS_ID) REFERENCES HEL_EXPLOT_TEMPS (ID);
