-- Taules per a execució massiva
CREATE TABLE HEL_EXEC_MASSIVA (
        ID BIGINT NOT NULL,
        DATA_INICI DATE NOT NULL,
        DATA_FI DATE,
        PARAM1 VARCHAR(255),
        TIPUS BIGINT NOT NULL,
        USUARI VARCHAR(64) NOT NULL,
        EXPEDIENT_TIPUS_ID BIGINT,
        ENV_CORREU BOOLEAN,
        PARAM2 BYTEA,
        ENTORN BIGINT,
        PRIMARY KEY (ID),
        CONSTRAINT HEL_EXPTIPUS_EXEMAS_FK FOREIGN KEY (EXPEDIENT_TIPUS_ID) REFERENCES HEL_EXPEDIENT_TIPUS (ID)
);
    
CREATE TABLE HEL_EXEC_MASEXP (
        ID BIGINT NOT NULL,
        DATA_INICI DATE,
        DATA_FI DATE,
        ORDRE BIGINT NOT NULL,
        EXECMAS_ID BIGINT NOT NULL,
        EXPEDIENT_ID BIGINT,
        ESTAT BIGINT,
        ERROR TEXT,
        TASCA_ID VARCHAR(255),
        PROCINST_ID VARCHAR(255),
        PRIMARY KEY (ID),
        CONSTRAINT HEL_EXPEDIENT_EXEMASEX_FK FOREIGN KEY (EXPEDIENT_ID) REFERENCES HEL_EXPEDIENT (ID),
        CONSTRAINT HEL_EXECMAS_EXEMASEX_FK FOREIGN KEY (EXECMAS_ID) REFERENCES HEL_EXEC_MASSIVA (ID)
);

--Nous indexos pel millorar el rendiment a la consulta dels camps de la definició de procés
CREATE INDEX HEL_CAMP_CODI_TIP ON HEL_CAMP (CODI, TIPUS);
CREATE INDEX HEL_CAMP_COD_TIP_DP ON HEL_CAMP (CODI, TIPUS, DEFINICIO_PROCES_ID);

-- Per a permetre triar l'any en la generació del número d'expedient
ALTER TABLE HEL_EXPEDIENT_TIPUS ADD SELECCIONAR_ANY BOOLEAN DEFAULT false NOT NULL;

-- Nou índex per la taula d'instàncies de tasca
CREATE INDEX IDX_TASKINST_PROC ON JBPM_TASKINSTANCE (PROCINST_);
CREATE INDEX IDX_TASKINST_TSK ON JBPM_TASKINSTANCE(TASK_);

-- Seqüències del tipus d'expedient
CREATE TABLE HEL_EXPEDIENT_TIPUS_SEQANY (
  ID                BIGINT NOT NULL,
  ANY_              BIGINT,
  SEQUENCIA         BIGINT,
  EXPEDIENT_TIPUS   BIGINT,
  PRIMARY KEY (ID),
  CONSTRAINT HEL_EXPTIPUS_SEQANY_FK FOREIGN KEY (EXPEDIENT_TIPUS) REFERENCES HEL_EXPEDIENT_TIPUS(ID)
);

-- Incrementar llargària camp params dels logs de l'expedient
ALTER TABLE HEL_EXPEDIENT_LOG ALTER COLUMN ACCIO_PARAMS TYPE VARCHAR(2048);

-- Restringir accions per rol
ALTER TABLE HEL_ACCIO ADD ROLS VARCHAR(512);

-- Paràmetres per a les consultes per tipus
ALTER TABLE HEL_CONSULTA_CAMP ADD CAMP_DESCRIPCIO VARCHAR(255);
ALTER TABLE HEL_CONSULTA_CAMP ADD PARAM_TIPUS BIGINT;

ALTER TABLE HEL_CAMP ADD IGNORED BOOLEAN DEFAULT false;

-- Actualització a la nova versió --
INSERT INTO HEL_VERSIO (
    ID,
    CODI,
    ORDRE,
    DATA_CREACIO,
    PROCES_EXECUTAT,
    SCRIPT_EXECUTAT,
    DATA_EXECUCIO_SCRIPT)
SELECT
    NEXTVAL('HIBERNATE_SEQUENCE') ID,
    '2.6.0' CODI,
    260 ORDRE,
    'now' DATA_CREACIO,
    false PROCES_EXECUTAT,
    true SCRIPT_EXECUTAT,
    'now' DATA_EXECUCIO_SCRIPT
WHERE (SELECT COUNT(*) FROM HEL_VERSIO WHERE ORDRE = 260) = 0;
