
/*
 * 
 */

package net.conselldemallorca.helium.integracio.plugins.portasignatures.service.wsdl;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.2.6
 * Mon Apr 12 09:26:50 CEST 2010
 * Generated source version: 2.2.6
 * 
 */


@WebServiceClient(name = "MCGDwsService", 
                  wsdlLocation = "file:MCGDWS.wsdl",
                  targetNamespace = "http://www.indra.es/portafirmasmcgdws/mcgdws") 
public class MCGDwsService extends Service {

    public final static URL WSDL_LOCATION;
    public final static QName SERVICE = new QName("http://www.indra.es/portafirmasmcgdws/mcgdws", "MCGDwsService");
    public final static QName MCGDWS = new QName("http://www.indra.es/portafirmasmcgdws/mcgdws", "MCGDWS");
    static {
        URL url = null;
        try {
            url = new URL("file:MCGDWS.wsdl");
        } catch (MalformedURLException e) {
            System.err.println("Can not initialize the default wsdl from file:MCGDWS.wsdl");
            // e.printStackTrace();
        }
        WSDL_LOCATION = url;
    }

    public MCGDwsService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public MCGDwsService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public MCGDwsService() {
        super(WSDL_LOCATION, SERVICE);
    }

    /**
     * 
     * @return
     *     returns MCGDws
     */
    @WebEndpoint(name = "MCGDWS")
    public MCGDws getMCGDWS() {
        return super.getPort(MCGDWS, MCGDws.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns MCGDws
     */
    @WebEndpoint(name = "MCGDWS")
    public MCGDws getMCGDWS(WebServiceFeature... features) {
        return super.getPort(MCGDWS, MCGDws.class, features);
    }

}
