-- Helium 3.3.6

-- #1795 Avís per email de nova anotació rebuda a Helium

ALTER TABLE HEL_USUARI_PREFS ADD CORREUS_BUSTIA BOOLEAN DEFAULT FALSE;
ALTER TABLE HEL_USUARI_PREFS ADD CORREUS_BUSTIA_AGRUPATS_DIA BOOLEAN DEFAULT FALSE;
ALTER TABLE HEL_USUARI_PREFS ADD  EMAIL_ALTERNATIU VARCHAR(255);

ALTER TABLE HEL_EXPEDIENT_TIPUS ADD  ENVIAR_CORREU_ANOTACIONS BOOLEAN DEFAULT FALSE;

-- -- Nova taula per els correus d'anotacions per enviar
CREATE TABLE HEL_ANOTACIO_EMAIL (
  ID           				BIGINT         	NOT NULL,
  REMITENT_CODI				VARCHAR(64) 		NOT NULL,
  DESTINATARI_CODI 			VARCHAR(64) 		NOT NULL,
  DESTINATARI_EMAIL			VARCHAR(256)   	NOT NULL,
  ENVIAMENT_AGRUPAT			BOOLEAN,
  ANOTACIO_ID				BIGINT         	NOT NULL,
  EXPEDIENT_ID				BIGINT,
  EMAIL_TIPUS				VARCHAR(64) 		NOT NULL, --ARRIBADA | PROCESSADA | INCORPORADA
  NUM_INTENTS				BIGINT,
  DATA_CREACIO				TIMESTAMP(6)
);

ALTER TABLE HEL_ANOTACIO_EMAIL ADD (
  	CONSTRAINT HEL_ANOTACIO_EMAIL_PK PRIMARY KEY (ID)); 

ALTER TABLE HEL_ANOTACIO_EMAIL ADD 
  CONSTRAINT HEL_ANOTACIO_ID_FK FOREIGN KEY (ANOTACIO_ID) 
    REFERENCES HEL_ANOTACIO (ID);

ALTER TABLE HEL_ANOTACIO_EMAIL ADD 
  CONSTRAINT HEL_EXPEDIENT_ID_FK FOREIGN KEY (EXPEDIENT_ID) 
    REFERENCES HEL_EXPEDIENT (ID);

-- #1798 Resoldre el nom de la via pels interessats de tipus administració

ALTER TABLE HEL_UNITAT_ORGANITZATIVA MODIFY (ADRESSA VARCHAR(255));

-- Posar dates de sincronització a null per tornar a recuperar l'adreça de totes les unitats organitzatives
UPDATE HEL_PARAMETRE SET VALOR = NULL WHERE CODI LIKE 'app.net.caib.helium.unitats.organitzatives.data.sincronitzacio';
UPDATE HEL_PARAMETRE SET VALOR = NULL WHERE CODI LIKE 'app.net.caib.helium.unitats.organitzatives.data.actualitzacio';
