-- #1990 
-- Afegeix la nova columna per poder marcar una variable tipus termini que només mostri els dies
ALTER TABLE HEL_CAMP ADD TERMINI_NOMES_DIES NUMBER(1,0) DEFAULT 0 NOT NULL;

-- #1992 
-- Afegeix la nova columna per diferenciar el tipus segons si és procediment o servei
ALTER TABLE HEL_PROCEDIMENT ADD TIPUS VARCHAR(20 CHAR) DEFAULT 'PROCEDIMENT' NOT NULL;

ALTER TABLE HEL_ANOTACIO ADD SERVEI_CODI VARCHAR(64 CHAR);
ALTER TABLE HEL_ANOTACIO ADD PRESENCIAL NUMBER(1,0);
ALTER TABLE HEL_ANOTACIO ADD TRAMIT_CODI VARCHAR(64 CHAR);
ALTER TABLE HEL_ANOTACIO ADD TRAMIT_NOM VARCHAR(255 CHAR);