
-- Actualització a la nova versió --
INSERT INTO HEL_VERSIO (
    ID,
    CODI,
    ORDRE,
    DATA_CREACIO,
    PROCES_EXECUTAT,
    SCRIPT_EXECUTAT,
    DATA_EXECUCIO_SCRIPT)
SELECT
    NEXTVAL('HIBERNATE_SEQUENCE') ID,
    '3.3.0' CODI,
    330 ORDRE,
    current_date data_creacio,
    false PROCES_EXECUTAT,
    true SCRIPT_EXECUTAT,
    current_date DATA_EXECUCIO_SCRIPT
WHERE (SELECT COUNT(*) FROM HEL_VERSIO WHERE ORDRE = 330) = 0;


-- #1627 HELIUM sense motor de WF 

-- Nou camp pel tipus d'expedient ESTATS/FLUX
ALTER TABLE HEL_EXPEDIENT_TIPUS ADD TIPUS INTEGER DEFAULT 0 NOT NULL;

-- Nou camp pel tipus d'acció ACCIO/HANDLER_PROPI/HANDLER_PREDEFINIT/SCRIPT
ALTER TABLE HEL_ACCIO ADD TIPUS VARCHAR(32) DEFAULT 'ACCIO' NOT NULL;
ALTER TABLE HEL_ACCIO ADD SCRIPT VARCHAR(1024);
ALTER TABLE HEL_ACCIO ALTER COLUMN JBPM_ACTION DROP NOT NULL;


-- Nous camps per accions d'execució de handlers predefinits i propis
ALTER TABLE HEL_ACCIO ADD HANDLER_CLASSE VARCHAR(255);
ALTER TABLE HEL_ACCIO ADD HANDLER_DADES BYTEA;

-- -- Nova taula per les regles dels estats
CREATE TABLE HEL_ESTAT_REGLA (
    ID				    BIGINT 	        NOT NULL,
    NOM 				VARCHAR(255) 	NOT NULL,
    EXPEDIENT_TIPUS_ID  BIGINT 	        NOT NULL,
    ESTAT_ID			BIGINT 	        NOT NULL,
    ENTORN_ID			BIGINT 	        NOT NULL,
    QUI 				VARCHAR(32) 	NOT NULL,
    QUE 				VARCHAR(32) 	NOT NULL,
    ACCIO 				VARCHAR(32) 	NOT NULL,
    ORDRE               INTEGER          NOT NULL
);

CREATE TABLE HEL_ESTAT_REGLA_VALOR_QUI (
    REGLA_ID            BIGINT 	        NOT NULL,
    VALOR 				VARCHAR(255) 	NOT NULL
);

CREATE TABLE HEL_ESTAT_REGLA_VALOR_QUE (
    REGLA_ID            BIGINT 	        NOT NULL,
    VALOR 				VARCHAR(255) 	NOT NULL
);

ALTER TABLE HEL_ESTAT_REGLA ADD CONSTRAINT HEL_ESTAT_REGLA_PK PRIMARY KEY (ID);
ALTER TABLE HEL_ESTAT_REGLA_VALOR_QUI ADD CONSTRAINT HEL_ESTAT_REGLA_VALOR_QUI_PK PRIMARY KEY (REGLA_ID, VALOR);
ALTER TABLE HEL_ESTAT_REGLA_VALOR_QUE ADD CONSTRAINT HEL_ESTAT_REGLA_VALOR_QUE_PK PRIMARY KEY (REGLA_ID, VALOR);

ALTER TABLE HEL_ESTAT_REGLA ADD CONSTRAINT HEL_REGLA_EXPTIPUS_FK FOREIGN KEY (EXPEDIENT_TIPUS_ID) REFERENCES HEL_EXPEDIENT_TIPUS (ID);
ALTER TABLE HEL_ESTAT_REGLA ADD CONSTRAINT HEL_REGLA_ESTAT_FK FOREIGN KEY (ESTAT_ID) REFERENCES HEL_ESTAT (ID);
ALTER TABLE HEL_ESTAT_REGLA ADD CONSTRAINT HEL_REGLA_ENTORN_FK FOREIGN KEY (ENTORN_ID) REFERENCES HEL_ENTORN (ID);
ALTER TABLE HEL_ESTAT_REGLA ADD CONSTRAINT HEL_REGLA_NOM_UK UNIQUE (ESTAT_ID, NOM);
ALTER TABLE HEL_ESTAT_REGLA_VALOR_QUI ADD CONSTRAINT HEL_REGLA_VALOR_QUI_FK FOREIGN KEY (REGLA_ID) REFERENCES HEL_ESTAT_REGLA (ID);
ALTER TABLE HEL_ESTAT_REGLA_VALOR_QUE ADD CONSTRAINT HEL_REGLA_VALOR_QUE_FK FOREIGN KEY (REGLA_ID) REFERENCES HEL_ESTAT_REGLA (ID);

CREATE INDEX HEL_REGLA_ENTORN_FK_I ON HEL_ESTAT_REGLA(ENTORN_ID);
CREATE INDEX HEL_REGLA_EXPTIPUS_FK_I ON HEL_ESTAT_REGLA(EXPEDIENT_TIPUS_ID);
CREATE INDEX HEL_REGLA_ESTAT_FK_I ON HEL_ESTAT_REGLA(ESTAT_ID);
CREATE INDEX HEL_REGLA_VALOR_QUI_FK_I ON HEL_ESTAT_REGLA_VALOR_QUI(REGLA_ID);
CREATE INDEX HEL_REGLA_VALOR_QUE_FK_I ON HEL_ESTAT_REGLA_VALOR_QUE(REGLA_ID);

-- Noves taules per la relació entre estats i accions d'entrada i sortida

CREATE TABLE HEL_ESTAT_ACCIO_ENTRADA (
    ID				    BIGINT 	        NOT NULL,
    ESTAT_ID			BIGINT 	        NOT NULL,
    ACCIO_ID			BIGINT 	        NOT NULL,
    ORDRE               INTEGER          NOT NULL
);

CREATE TABLE HEL_ESTAT_ACCIO_SORTIDA (
    ID				    BIGINT 	        NOT NULL,
    ESTAT_ID			BIGINT 	        NOT NULL,
    ACCIO_ID			BIGINT 	        NOT NULL,
    ORDRE               INTEGER          NOT NULL
);

ALTER TABLE HEL_ESTAT_ACCIO_ENTRADA ADD CONSTRAINT HEL_ESTACC_ENT_PK PRIMARY KEY (ID);
ALTER TABLE HEL_ESTAT_ACCIO_SORTIDA ADD CONSTRAINT HEL_ESTACC_SORT_PK PRIMARY KEY (ID);

ALTER TABLE HEL_ESTAT_ACCIO_ENTRADA ADD CONSTRAINT HEL_ESTACC_ENT_ESTAT_FK FOREIGN KEY (ESTAT_ID) REFERENCES HEL_ESTAT (ID);
ALTER TABLE HEL_ESTAT_ACCIO_ENTRADA ADD CONSTRAINT HEL_ESTACC_ENT_ACCIO_FK FOREIGN KEY (ACCIO_ID) REFERENCES HEL_ACCIO (ID);
ALTER TABLE HEL_ESTAT_ACCIO_SORTIDA ADD CONSTRAINT HEL_ESTACC_SORT_ESTAT_FK FOREIGN KEY (ESTAT_ID) REFERENCES HEL_ESTAT (ID);
ALTER TABLE HEL_ESTAT_ACCIO_SORTIDA ADD CONSTRAINT HEL_ESTACC_SORT_ACCIO_FK FOREIGN KEY (ACCIO_ID) REFERENCES HEL_ACCIO (ID);

CREATE INDEX HEL_ESTACC_ENT_ESTAT_FK_I ON HEL_ESTAT_ACCIO_ENTRADA(ESTAT_ID);
CREATE INDEX HEL_ESTACC_SORT_ESTAT_FK_I ON HEL_ESTAT_ACCIO_SORTIDA(ESTAT_ID);

-- #1645 Incloure l'edició dels fluxos de firma a Helium
ALTER TABLE HEL_DOCUMENT ADD (
	PORTAFIRMES_FLUX_ID     	character varying(64),
	PORTAFIRMES_ACTIU       	boolean DEFAULT FALSE,
	PORTAFIRMES_RESPONSABLES    character varying(512),
 	PORTAFIRMES_FLUXTIP     	character varying(256),
 	PORTAFIRMES_SEQTIP 			character varying(256)
 	); 	
>ALTER TABLE HEL_PORTASIGNATURES ALTER COLUMN TOKEN_ID DROP NOT NULL;

--#1656 Permetre notificar més d'un document i a la vegada en un .zip
CREATE TABLE HEL_DOCUMENT_CONTINGUT (
  ID BIGINT	NOT NULL,
  DOCUMENT_CONTINGUT BIGINT			NOT NULL
);

ALTER TABLE HEL_DOCUMENT_CONTINGUT ADD  CONSTRAINT HEL_DOCSTORE_DOCCONT_ID_FK FOREIGN KEY (ID) REFERENCES HEL_DOCUMENT_STORE (ID);
ALTER TABLE HEL_DOCUMENT_CONTINGUT 	ADD CONSTRAINT HEL_DOCSTORE_DOCCONT_CONT_FK FOREIGN KEY (DOCUMENT_CONTINGUT) REFERENCES HEL_DOCUMENT_STORE (ID);

--#1705 Error notificant document amb descripció llarga
-- Incrementar llargària camp DESCRIPCIO
ALTER TABLE HEL_DOCUMENT_NOTIFICACIO MODIFY DESCRIPCIO CHARACTER VARYING(1000);
