-- #1710 Adaptar el manteniment d'interessats als camps SICRES

-- Oracle

ALTER TABLE HEL_INTERESSAT MODIFY NOM NULL;
ALTER TABLE HEL_INTERESSAT MODIFY TELEFON VARCHAR2(20 CHAR);
ALTER TABLE HEL_INTERESSAT MODIFY DIR3CODI VARCHAR2(21 CHAR);
ALTER TABLE HEL_INTERESSAT RENAME COLUMN NIF TO DOCUMENTIDENT;--MARTA recordar esborrar la columna NIF a la bbdd de la 231!!!
ALTER TABLE HEL_INTERESSAT MODIFY DOCUMENTIDENT VARCHAR2(256 CHAR);

ALTER TABLE HEL_INTERESSAT ADD DIRECCIO VARCHAR2(160 CHAR);
ALTER TABLE HEL_INTERESSAT ADD CODIDIRE VARCHAR2(21 CHAR);
ALTER TABLE HEL_INTERESSAT ADD TIPUSDOCIDENT VARCHAR2(8 CHAR);
ALTER TABLE HEL_INTERESSAT ADD RAOSOCIAL VARCHAR2(256 CHAR);
ALTER TABLE HEL_INTERESSAT ADD ES_REPRESENTANT NUMBER(1,0) DEFAULT 0 NOT NULL;
ALTER TABLE HEL_INTERESSAT ADD OBSERVACIONS VARCHAR2(256 CHAR);

ALTER TABLE HEL_INTERESSAT ADD REPRESENTAT NUMBER(19);
ALTER TABLE HEL_INTERESSAT ADD REPRESENTANT NUMBER(19);

ALTER TABLE HEL_INTERESSAT ADD CONSTRAINT HEL_INTERESSAT_REPRESENTAT_FK FOREIGN KEY (REPRESENTAT) REFERENCES HEL_INTERESSAT(ID);
ALTER TABLE HEL_INTERESSAT ADD CONSTRAINT HEL_INTERESSAT_REPRESENTANT_FK FOREIGN KEY (REPRESENTANT) REFERENCES HEL_INTERESSAT(ID);

--canvis posteriors adaptar lo anterior
ALTER TABLE HEL_INTERESSAT DROP CONSTRAINT "HEL_INTERESSAT_REPRESENTAT_FK";

ALTER TABLE HEL_INTERESSAT ADD CONSTRAINT "HEL_INTERESSAT_REPRESENTAT_FK" FOREIGN KEY ("REPRESENTAT")
	  REFERENCES "HELIUM"."HEL_INTERESSAT" ("ID") ENABLE;
      
ALTER TABLE HEL_INTERESSAT MODIFY TIPUSDOCIDENT VARCHAR2(64 CHAR);

ALTER TABLE HEL_INTERESSAT RENAME COLUMN REPRESENTANT TO REPRESENTANT_ID;
ALTER TABLE HEL_INTERESSAT RENAME COLUMN REPRESENTAT TO REPRESENTAT_ID;

 
    
-- Postgresql

ALTER TABLE HEL_INTERESSAT ALTER COLUMN NOM DROP NOT NULL;
ALTER TABLE HEL_INTERESSAT MODIFY TELEFON CHARACTER VARYING(20);
ALTER TABLE HEL_INTERESSAT MODIFY DIR3CODI CHARACTER VARYING(21);
ALTER TABLE HEL_INTERESSAT RENAME COLUMN NIF TO DOCUMENTIDENT;
ALTER TABLE HEL_INTERESSAT MODIFY DOCUMENTIDENT VARCHAR(256 CHAR);

ALTER TABLE HEL_INTERESSAT ADD DIRECCIO VARCHAR(160);
ALTER TABLE HEL_INTERESSAT ADD CODIDIRE VARCHAR(21);
ALTER TABLE HEL_INTERESSAT ADD TIPUSDOCIDENT VARCHAR(8);
ALTER TABLE HEL_INTERESSAT ADD RAOSOCIAL VARCHAR(256);
ALTER TABLE HEL_INTERESSAT ADD ES_REPRESENTANT BOOLEAN DEFAULT FALSE NOT NULL;
ALTER TABLE HEL_INTERESSAT ADD OBSERVACIONS VARCHAR(256);

ALTER TABLE HEL_INTERESSAT ADD REPRESENTAT BIGINT;
ALTER TABLE HEL_INTERESSAT ADD REPRESENTANT BIGINT;

ALTER TABLE HEL_INTERESSAT ADD CONSTRAINT HEL_INTERESSAT_REPRESENTAT_FK FOREIGN KEY (REPRESENTAT) REFERENCES HEL_INTERESSAT(ID);
ALTER TABLE HEL_INTERESSAT ADD CONSTRAINT HEL_INTERESSAT_REPRESENTANT_FK FOREIGN KEY (REPRESENTANT) REFERENCES HEL_INTERESSAT(ID);


