--#1432 Poder diferenciar l'enton de PRE i PRO segons el color de la capçalera

--Oracle
ALTER TABLE HEL_ENTORN ADD COLOR_FONS VARCHAR2(255 CHAR);
ALTER TABLE HEL_ENTORN ADD COLOR_LLETRA VARCHAR2(255 CHAR);

--Postgres
ALTER TABLE HEL_ENTORN ADD COLOR_FONS character varying(255);
ALTER TABLE HEL_ENTORN ADD COLOR_LLETRA character varying(255);

