-- #1846 Evitar el canvi d'entorn funcional involuntari

-- Oracle
ALTER TABLE HEL_USUARI_PREFS ADD ENTORN_ACTUAL VARCHAR2(64 CHAR);
ALTER TABLE HEL_USUARI_PREFS ADD ENTORN_ACTUAL_DATA TIMESTAMP(6);

-- Postgres
ALTER TABLE HEL_USUARI_PREFS ADD ENTORN_ACTUAL VARCHAR(64);
ALTER TABLE HEL_USUARI_PREFS ADD ENTORN_ACTUAL_DATA timestamp without time zone;