package net.conselldemallorca.helium.integracio.tramitacio;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.0.0-milestone2
 * 2014-04-22T09:15:26.369+02:00
 * Generated source version: 3.0.0-milestone2
 * 
 */
@WebService(targetNamespace = "http://tramitacio.integracio.helium.conselldemallorca.net/", name = "TramitacioService")
@XmlSeeAlso({ObjectFactory.class, net.java.dev.jaxb.array.ObjectFactory.class})
public interface TramitacioService {

    @RequestWrapper(localName = "executarAccioProces", targetNamespace = "http://tramitacio.integracio.helium.conselldemallorca.net/", className = "net.conselldemallorca.helium.integracio.tramitacio.ExecutarAccioProces")
    @WebMethod
    @ResponseWrapper(localName = "executarAccioProcesResponse", targetNamespace = "http://tramitacio.integracio.helium.conselldemallorca.net/", className = "net.conselldemallorca.helium.integracio.tramitacio.ExecutarAccioProcesResponse")
    public void executarAccioProces(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        java.lang.String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        java.lang.String arg3
    ) throws TramitacioException_Exception;

    @RequestWrapper(localName = "esborrarDocumentTasca", targetNamespace = "http://tramitacio.integracio.helium.conselldemallorca.net/", className = "net.conselldemallorca.helium.integracio.tramitacio.EsborrarDocumentTasca")
    @WebMethod
    @ResponseWrapper(localName = "esborrarDocumentTascaResponse", targetNamespace = "http://tramitacio.integracio.helium.conselldemallorca.net/", className = "net.conselldemallorca.helium.integracio.tramitacio.EsborrarDocumentTascaResponse")
    public void esborrarDocumentTasca(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        java.lang.String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        java.lang.String arg3
    ) throws TramitacioException_Exception;

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "consultaFormulariTasca", targetNamespace = "http://tramitacio.integracio.helium.conselldemallorca.net/", className = "net.conselldemallorca.helium.integracio.tramitacio.ConsultaFormulariTasca")
    @WebMethod
    @ResponseWrapper(localName = "consultaFormulariTascaResponse", targetNamespace = "http://tramitacio.integracio.helium.conselldemallorca.net/", className = "net.conselldemallorca.helium.integracio.tramitacio.ConsultaFormulariTascaResponse")
    public java.util.List<net.conselldemallorca.helium.integracio.tramitacio.CampTasca> consultaFormulariTasca(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        java.lang.String arg2
    ) throws TramitacioException_Exception;

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "consultarVariablesProces", targetNamespace = "http://tramitacio.integracio.helium.conselldemallorca.net/", className = "net.conselldemallorca.helium.integracio.tramitacio.ConsultarVariablesProces")
    @WebMethod
    @ResponseWrapper(localName = "consultarVariablesProcesResponse", targetNamespace = "http://tramitacio.integracio.helium.conselldemallorca.net/", className = "net.conselldemallorca.helium.integracio.tramitacio.ConsultarVariablesProcesResponse")
    public java.util.List<net.conselldemallorca.helium.integracio.tramitacio.CampProces> consultarVariablesProces(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        java.lang.String arg2
    ) throws TramitacioException_Exception;

    @RequestWrapper(localName = "setVariableProces", targetNamespace = "http://tramitacio.integracio.helium.conselldemallorca.net/", className = "net.conselldemallorca.helium.integracio.tramitacio.SetVariableProces")
    @WebMethod
    @ResponseWrapper(localName = "setVariableProcesResponse", targetNamespace = "http://tramitacio.integracio.helium.conselldemallorca.net/", className = "net.conselldemallorca.helium.integracio.tramitacio.SetVariableProcesResponse")
    public void setVariableProces(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        java.lang.String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        java.lang.String arg3,
        @WebParam(name = "arg4", targetNamespace = "")
        java.lang.Object arg4
    ) throws TramitacioException_Exception;

    @RequestWrapper(localName = "agafarTasca", targetNamespace = "http://tramitacio.integracio.helium.conselldemallorca.net/", className = "net.conselldemallorca.helium.integracio.tramitacio.AgafarTasca")
    @WebMethod
    @ResponseWrapper(localName = "agafarTascaResponse", targetNamespace = "http://tramitacio.integracio.helium.conselldemallorca.net/", className = "net.conselldemallorca.helium.integracio.tramitacio.AgafarTascaResponse")
    public void agafarTasca(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        java.lang.String arg2
    ) throws TramitacioException_Exception;

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "consultaExpedients", targetNamespace = "http://tramitacio.integracio.helium.conselldemallorca.net/", className = "net.conselldemallorca.helium.integracio.tramitacio.ConsultaExpedients")
    @WebMethod
    @ResponseWrapper(localName = "consultaExpedientsResponse", targetNamespace = "http://tramitacio.integracio.helium.conselldemallorca.net/", className = "net.conselldemallorca.helium.integracio.tramitacio.ConsultaExpedientsResponse")
    public java.util.List<net.conselldemallorca.helium.integracio.tramitacio.ExpedientInfo> consultaExpedients(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        java.lang.String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        java.lang.String arg3,
        @WebParam(name = "arg4", targetNamespace = "")
        javax.xml.datatype.XMLGregorianCalendar arg4,
        @WebParam(name = "arg5", targetNamespace = "")
        javax.xml.datatype.XMLGregorianCalendar arg5,
        @WebParam(name = "arg6", targetNamespace = "")
        java.lang.String arg6,
        @WebParam(name = "arg7", targetNamespace = "")
        java.lang.String arg7,
        @WebParam(name = "arg8", targetNamespace = "")
        boolean arg8,
        @WebParam(name = "arg9", targetNamespace = "")
        boolean arg9,
        @WebParam(name = "arg10", targetNamespace = "")
        java.lang.Double arg10,
        @WebParam(name = "arg11", targetNamespace = "")
        java.lang.Double arg11,
        @WebParam(name = "arg12", targetNamespace = "")
        java.lang.String arg12
    ) throws TramitacioException_Exception;

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "consultaTasquesPersonalsByCodi", targetNamespace = "http://tramitacio.integracio.helium.conselldemallorca.net/", className = "net.conselldemallorca.helium.integracio.tramitacio.ConsultaTasquesPersonalsByCodi")
    @WebMethod
    @ResponseWrapper(localName = "consultaTasquesPersonalsByCodiResponse", targetNamespace = "http://tramitacio.integracio.helium.conselldemallorca.net/", className = "net.conselldemallorca.helium.integracio.tramitacio.ConsultaTasquesPersonalsByCodiResponse")
    public java.util.List<net.conselldemallorca.helium.integracio.tramitacio.TascaTramitacio> consultaTasquesPersonalsByCodi(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        java.lang.String arg2
    ) throws TramitacioException_Exception;

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "consultarDocumentsProces", targetNamespace = "http://tramitacio.integracio.helium.conselldemallorca.net/", className = "net.conselldemallorca.helium.integracio.tramitacio.ConsultarDocumentsProces")
    @WebMethod
    @ResponseWrapper(localName = "consultarDocumentsProcesResponse", targetNamespace = "http://tramitacio.integracio.helium.conselldemallorca.net/", className = "net.conselldemallorca.helium.integracio.tramitacio.ConsultarDocumentsProcesResponse")
    public java.util.List<net.conselldemallorca.helium.integracio.tramitacio.DocumentProces> consultarDocumentsProces(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        java.lang.String arg2
    ) throws TramitacioException_Exception;

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "setDocumentProces", targetNamespace = "http://tramitacio.integracio.helium.conselldemallorca.net/", className = "net.conselldemallorca.helium.integracio.tramitacio.SetDocumentProces")
    @WebMethod
    @ResponseWrapper(localName = "setDocumentProcesResponse", targetNamespace = "http://tramitacio.integracio.helium.conselldemallorca.net/", className = "net.conselldemallorca.helium.integracio.tramitacio.SetDocumentProcesResponse")
    public java.lang.Long setDocumentProces(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        java.lang.String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        java.lang.String arg3,
        @WebParam(name = "arg4", targetNamespace = "")
        java.lang.String arg4,
        @WebParam(name = "arg5", targetNamespace = "")
        javax.xml.datatype.XMLGregorianCalendar arg5,
        @WebParam(name = "arg6", targetNamespace = "")
        byte[] arg6
    ) throws TramitacioException_Exception;

    @RequestWrapper(localName = "setDadesFormulariTasca", targetNamespace = "http://tramitacio.integracio.helium.conselldemallorca.net/", className = "net.conselldemallorca.helium.integracio.tramitacio.SetDadesFormulariTasca")
    @WebMethod
    @ResponseWrapper(localName = "setDadesFormulariTascaResponse", targetNamespace = "http://tramitacio.integracio.helium.conselldemallorca.net/", className = "net.conselldemallorca.helium.integracio.tramitacio.SetDadesFormulariTascaResponse")
    public void setDadesFormulariTasca(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        java.lang.String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        java.util.List<net.conselldemallorca.helium.integracio.tramitacio.ParellaCodiValor> arg3
    ) throws TramitacioException_Exception;

    @RequestWrapper(localName = "finalitzarTasca", targetNamespace = "http://tramitacio.integracio.helium.conselldemallorca.net/", className = "net.conselldemallorca.helium.integracio.tramitacio.FinalitzarTasca")
    @WebMethod
    @ResponseWrapper(localName = "finalitzarTascaResponse", targetNamespace = "http://tramitacio.integracio.helium.conselldemallorca.net/", className = "net.conselldemallorca.helium.integracio.tramitacio.FinalitzarTascaResponse")
    public void finalitzarTasca(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        java.lang.String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        java.lang.String arg3
    ) throws TramitacioException_Exception;

    @RequestWrapper(localName = "setDocumentTasca", targetNamespace = "http://tramitacio.integracio.helium.conselldemallorca.net/", className = "net.conselldemallorca.helium.integracio.tramitacio.SetDocumentTasca")
    @WebMethod
    @ResponseWrapper(localName = "setDocumentTascaResponse", targetNamespace = "http://tramitacio.integracio.helium.conselldemallorca.net/", className = "net.conselldemallorca.helium.integracio.tramitacio.SetDocumentTascaResponse")
    public void setDocumentTasca(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        java.lang.String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        java.lang.String arg3,
        @WebParam(name = "arg4", targetNamespace = "")
        java.lang.String arg4,
        @WebParam(name = "arg5", targetNamespace = "")
        javax.xml.datatype.XMLGregorianCalendar arg5,
        @WebParam(name = "arg6", targetNamespace = "")
        byte[] arg6
    ) throws TramitacioException_Exception;

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "consultaTasquesGrupByCodi", targetNamespace = "http://tramitacio.integracio.helium.conselldemallorca.net/", className = "net.conselldemallorca.helium.integracio.tramitacio.ConsultaTasquesGrupByCodi")
    @WebMethod
    @ResponseWrapper(localName = "consultaTasquesGrupByCodiResponse", targetNamespace = "http://tramitacio.integracio.helium.conselldemallorca.net/", className = "net.conselldemallorca.helium.integracio.tramitacio.ConsultaTasquesGrupByCodiResponse")
    public java.util.List<net.conselldemallorca.helium.integracio.tramitacio.TascaTramitacio> consultaTasquesGrupByCodi(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        java.lang.String arg2
    ) throws TramitacioException_Exception;

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "consultaTasquesGrup", targetNamespace = "http://tramitacio.integracio.helium.conselldemallorca.net/", className = "net.conselldemallorca.helium.integracio.tramitacio.ConsultaTasquesGrup")
    @WebMethod
    @ResponseWrapper(localName = "consultaTasquesGrupResponse", targetNamespace = "http://tramitacio.integracio.helium.conselldemallorca.net/", className = "net.conselldemallorca.helium.integracio.tramitacio.ConsultaTasquesGrupResponse")
    public java.util.List<net.conselldemallorca.helium.integracio.tramitacio.TascaTramitacio> consultaTasquesGrup(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1
    ) throws TramitacioException_Exception;

    @RequestWrapper(localName = "esborrarDocumentProces", targetNamespace = "http://tramitacio.integracio.helium.conselldemallorca.net/", className = "net.conselldemallorca.helium.integracio.tramitacio.EsborrarDocumentProces")
    @WebMethod
    @ResponseWrapper(localName = "esborrarDocumentProcesResponse", targetNamespace = "http://tramitacio.integracio.helium.conselldemallorca.net/", className = "net.conselldemallorca.helium.integracio.tramitacio.EsborrarDocumentProcesResponse")
    public void esborrarDocumentProces(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        java.lang.String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        java.lang.Long arg3
    ) throws TramitacioException_Exception;

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "consultaDocumentsTasca", targetNamespace = "http://tramitacio.integracio.helium.conselldemallorca.net/", className = "net.conselldemallorca.helium.integracio.tramitacio.ConsultaDocumentsTasca")
    @WebMethod
    @ResponseWrapper(localName = "consultaDocumentsTascaResponse", targetNamespace = "http://tramitacio.integracio.helium.conselldemallorca.net/", className = "net.conselldemallorca.helium.integracio.tramitacio.ConsultaDocumentsTascaResponse")
    public java.util.List<net.conselldemallorca.helium.integracio.tramitacio.DocumentTasca> consultaDocumentsTasca(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        java.lang.String arg2
    ) throws TramitacioException_Exception;

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "consultaTasquesPersonals", targetNamespace = "http://tramitacio.integracio.helium.conselldemallorca.net/", className = "net.conselldemallorca.helium.integracio.tramitacio.ConsultaTasquesPersonals")
    @WebMethod
    @ResponseWrapper(localName = "consultaTasquesPersonalsResponse", targetNamespace = "http://tramitacio.integracio.helium.conselldemallorca.net/", className = "net.conselldemallorca.helium.integracio.tramitacio.ConsultaTasquesPersonalsResponse")
    public java.util.List<net.conselldemallorca.helium.integracio.tramitacio.TascaTramitacio> consultaTasquesPersonals(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1
    ) throws TramitacioException_Exception;

    @RequestWrapper(localName = "executarScriptProces", targetNamespace = "http://tramitacio.integracio.helium.conselldemallorca.net/", className = "net.conselldemallorca.helium.integracio.tramitacio.ExecutarScriptProces")
    @WebMethod
    @ResponseWrapper(localName = "executarScriptProcesResponse", targetNamespace = "http://tramitacio.integracio.helium.conselldemallorca.net/", className = "net.conselldemallorca.helium.integracio.tramitacio.ExecutarScriptProcesResponse")
    public void executarScriptProces(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        java.lang.String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        java.lang.String arg3
    ) throws TramitacioException_Exception;

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "iniciExpedient", targetNamespace = "http://tramitacio.integracio.helium.conselldemallorca.net/", className = "net.conselldemallorca.helium.integracio.tramitacio.IniciExpedient")
    @WebMethod
    @ResponseWrapper(localName = "iniciExpedientResponse", targetNamespace = "http://tramitacio.integracio.helium.conselldemallorca.net/", className = "net.conselldemallorca.helium.integracio.tramitacio.IniciExpedientResponse")
    public java.lang.String iniciExpedient(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        java.lang.String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        java.lang.String arg3,
        @WebParam(name = "arg4", targetNamespace = "")
        java.lang.String arg4,
        @WebParam(name = "arg5", targetNamespace = "")
        java.util.List<net.conselldemallorca.helium.integracio.tramitacio.ParellaCodiValor> arg5
    ) throws TramitacioException_Exception;

    @RequestWrapper(localName = "esborrarVariableProces", targetNamespace = "http://tramitacio.integracio.helium.conselldemallorca.net/", className = "net.conselldemallorca.helium.integracio.tramitacio.EsborrarVariableProces")
    @WebMethod
    @ResponseWrapper(localName = "esborrarVariableProcesResponse", targetNamespace = "http://tramitacio.integracio.helium.conselldemallorca.net/", className = "net.conselldemallorca.helium.integracio.tramitacio.EsborrarVariableProcesResponse")
    public void esborrarVariableProces(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        java.lang.String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        java.lang.String arg3
    ) throws TramitacioException_Exception;
}
