package net.conselldemallorca.helium.integracio.tramitacio;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.0.0-milestone2
 * 2014-04-22T09:15:26.402+02:00
 * Generated source version: 3.0.0-milestone2
 * 
 */
@WebServiceClient(name = "TramitacioService", 
                  wsdlLocation = "file:/C:/Users/javierg/workspace_helium_30/pru/WebContent/TramitacioService.wsdl",
                  targetNamespace = "http://tramitacio.integracio.helium.conselldemallorca.net/") 
public class TramitacioService_Service extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://tramitacio.integracio.helium.conselldemallorca.net/", "TramitacioService");
    public final static QName TramitacioPort = new QName("http://tramitacio.integracio.helium.conselldemallorca.net/", "TramitacioPort");
    static {
        URL url = null;
        try {
            url = new URL("file:/C:/Users/javierg/workspace_helium_30/pru/WebContent/TramitacioService.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(TramitacioService_Service.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/C:/Users/javierg/workspace_helium_30/pru/WebContent/TramitacioService.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public TramitacioService_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public TramitacioService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public TramitacioService_Service() {
        super(WSDL_LOCATION, SERVICE);
    }
    

    /**
     *
     * @return
     *     returns TramitacioService
     */
    @WebEndpoint(name = "TramitacioPort")
    public TramitacioService getTramitacioPort() {
        return super.getPort(TramitacioPort, TramitacioService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns TramitacioService
     */
    @WebEndpoint(name = "TramitacioPort")
    public TramitacioService getTramitacioPort(WebServiceFeature... features) {
        return super.getPort(TramitacioPort, TramitacioService.class, features);
    }

}
