
package net.conselldemallorca.helium.integracio.tramitacio;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.0.0-milestone2
 * 2014-04-22T09:15:26.074+02:00
 * Generated source version: 3.0.0-milestone2
 * 
 */
public final class TramitacioService_TramitacioPort_Client {

    private static final QName SERVICE_NAME = new QName("http://tramitacio.integracio.helium.conselldemallorca.net/", "TramitacioService");

    private TramitacioService_TramitacioPort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = TramitacioService_Service.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        TramitacioService_Service ss = new TramitacioService_Service(wsdlURL, SERVICE_NAME);
        TramitacioService port = ss.getTramitacioPort();  
        
        {
        System.out.println("Invoking executarAccioProces...");
        java.lang.String _executarAccioProces_arg0 = "_executarAccioProces_arg0-522664242";
        java.lang.String _executarAccioProces_arg1 = "_executarAccioProces_arg1-1917377259";
        java.lang.String _executarAccioProces_arg2 = "_executarAccioProces_arg2-1744313857";
        java.lang.String _executarAccioProces_arg3 = "_executarAccioProces_arg3719098449";
        try {
            port.executarAccioProces(_executarAccioProces_arg0, _executarAccioProces_arg1, _executarAccioProces_arg2, _executarAccioProces_arg3);

        } catch (TramitacioException_Exception e) { 
            System.out.println("Expected exception: TramitacioException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking esborrarDocumentTasca...");
        java.lang.String _esborrarDocumentTasca_arg0 = "_esborrarDocumentTasca_arg0-1451429164";
        java.lang.String _esborrarDocumentTasca_arg1 = "_esborrarDocumentTasca_arg11609681665";
        java.lang.String _esborrarDocumentTasca_arg2 = "_esborrarDocumentTasca_arg21796946469";
        java.lang.String _esborrarDocumentTasca_arg3 = "_esborrarDocumentTasca_arg31940754568";
        try {
            port.esborrarDocumentTasca(_esborrarDocumentTasca_arg0, _esborrarDocumentTasca_arg1, _esborrarDocumentTasca_arg2, _esborrarDocumentTasca_arg3);

        } catch (TramitacioException_Exception e) { 
            System.out.println("Expected exception: TramitacioException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking consultaFormulariTasca...");
        java.lang.String _consultaFormulariTasca_arg0 = "_consultaFormulariTasca_arg0-1871240413";
        java.lang.String _consultaFormulariTasca_arg1 = "_consultaFormulariTasca_arg1-2038382737";
        java.lang.String _consultaFormulariTasca_arg2 = "_consultaFormulariTasca_arg2-1644918838";
        try {
            java.util.List<net.conselldemallorca.helium.integracio.tramitacio.CampTasca> _consultaFormulariTasca__return = port.consultaFormulariTasca(_consultaFormulariTasca_arg0, _consultaFormulariTasca_arg1, _consultaFormulariTasca_arg2);
            System.out.println("consultaFormulariTasca.result=" + _consultaFormulariTasca__return);

        } catch (TramitacioException_Exception e) { 
            System.out.println("Expected exception: TramitacioException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking consultarVariablesProces...");
        java.lang.String _consultarVariablesProces_arg0 = "_consultarVariablesProces_arg0-323987905";
        java.lang.String _consultarVariablesProces_arg1 = "_consultarVariablesProces_arg1-1059515264";
        java.lang.String _consultarVariablesProces_arg2 = "_consultarVariablesProces_arg2395495995";
        try {
            java.util.List<net.conselldemallorca.helium.integracio.tramitacio.CampProces> _consultarVariablesProces__return = port.consultarVariablesProces(_consultarVariablesProces_arg0, _consultarVariablesProces_arg1, _consultarVariablesProces_arg2);
            System.out.println("consultarVariablesProces.result=" + _consultarVariablesProces__return);

        } catch (TramitacioException_Exception e) { 
            System.out.println("Expected exception: TramitacioException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking setVariableProces...");
        java.lang.String _setVariableProces_arg0 = "_setVariableProces_arg0-1088986934";
        java.lang.String _setVariableProces_arg1 = "_setVariableProces_arg1741535158";
        java.lang.String _setVariableProces_arg2 = "_setVariableProces_arg21448036684";
        java.lang.String _setVariableProces_arg3 = "_setVariableProces_arg31378616610";
        java.lang.Object _setVariableProces_arg4 = null;
        try {
            port.setVariableProces(_setVariableProces_arg0, _setVariableProces_arg1, _setVariableProces_arg2, _setVariableProces_arg3, _setVariableProces_arg4);

        } catch (TramitacioException_Exception e) { 
            System.out.println("Expected exception: TramitacioException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking agafarTasca...");
        java.lang.String _agafarTasca_arg0 = "_agafarTasca_arg02022872934";
        java.lang.String _agafarTasca_arg1 = "_agafarTasca_arg1-223558901";
        java.lang.String _agafarTasca_arg2 = "_agafarTasca_arg2487988524";
        try {
            port.agafarTasca(_agafarTasca_arg0, _agafarTasca_arg1, _agafarTasca_arg2);

        } catch (TramitacioException_Exception e) { 
            System.out.println("Expected exception: TramitacioException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking consultaExpedients...");
        java.lang.String _consultaExpedients_arg0 = "_consultaExpedients_arg0-598437739";
        java.lang.String _consultaExpedients_arg1 = "_consultaExpedients_arg1-1949716337";
        java.lang.String _consultaExpedients_arg2 = "_consultaExpedients_arg21584863032";
        java.lang.String _consultaExpedients_arg3 = "_consultaExpedients_arg3-541462804";
        javax.xml.datatype.XMLGregorianCalendar _consultaExpedients_arg4 = javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2014-04-22T09:15:26.190+02:00");
        javax.xml.datatype.XMLGregorianCalendar _consultaExpedients_arg5 = javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2014-04-22T09:15:26.193+02:00");
        java.lang.String _consultaExpedients_arg6 = "_consultaExpedients_arg6-641908272";
        java.lang.String _consultaExpedients_arg7 = "_consultaExpedients_arg71013512803";
        boolean _consultaExpedients_arg8 = true;
        boolean _consultaExpedients_arg9 = false;
        java.lang.Double _consultaExpedients_arg10 = Double.valueOf(0.7528170380769613);
        java.lang.Double _consultaExpedients_arg11 = Double.valueOf(0.15412406335600615);
        java.lang.String _consultaExpedients_arg12 = "_consultaExpedients_arg12578271152";
        try {
            java.util.List<net.conselldemallorca.helium.integracio.tramitacio.ExpedientInfo> _consultaExpedients__return = port.consultaExpedients(_consultaExpedients_arg0, _consultaExpedients_arg1, _consultaExpedients_arg2, _consultaExpedients_arg3, _consultaExpedients_arg4, _consultaExpedients_arg5, _consultaExpedients_arg6, _consultaExpedients_arg7, _consultaExpedients_arg8, _consultaExpedients_arg9, _consultaExpedients_arg10, _consultaExpedients_arg11, _consultaExpedients_arg12);
            System.out.println("consultaExpedients.result=" + _consultaExpedients__return);

        } catch (TramitacioException_Exception e) { 
            System.out.println("Expected exception: TramitacioException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking consultaTasquesPersonalsByCodi...");
        java.lang.String _consultaTasquesPersonalsByCodi_arg0 = "_consultaTasquesPersonalsByCodi_arg01053200215";
        java.lang.String _consultaTasquesPersonalsByCodi_arg1 = "_consultaTasquesPersonalsByCodi_arg11499584538";
        java.lang.String _consultaTasquesPersonalsByCodi_arg2 = "_consultaTasquesPersonalsByCodi_arg2-53581499";
        try {
            java.util.List<net.conselldemallorca.helium.integracio.tramitacio.TascaTramitacio> _consultaTasquesPersonalsByCodi__return = port.consultaTasquesPersonalsByCodi(_consultaTasquesPersonalsByCodi_arg0, _consultaTasquesPersonalsByCodi_arg1, _consultaTasquesPersonalsByCodi_arg2);
            System.out.println("consultaTasquesPersonalsByCodi.result=" + _consultaTasquesPersonalsByCodi__return);

        } catch (TramitacioException_Exception e) { 
            System.out.println("Expected exception: TramitacioException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking consultarDocumentsProces...");
        java.lang.String _consultarDocumentsProces_arg0 = "_consultarDocumentsProces_arg01113571052";
        java.lang.String _consultarDocumentsProces_arg1 = "_consultarDocumentsProces_arg1-1425800502";
        java.lang.String _consultarDocumentsProces_arg2 = "_consultarDocumentsProces_arg21282584447";
        try {
            java.util.List<net.conselldemallorca.helium.integracio.tramitacio.DocumentProces> _consultarDocumentsProces__return = port.consultarDocumentsProces(_consultarDocumentsProces_arg0, _consultarDocumentsProces_arg1, _consultarDocumentsProces_arg2);
            System.out.println("consultarDocumentsProces.result=" + _consultarDocumentsProces__return);

        } catch (TramitacioException_Exception e) { 
            System.out.println("Expected exception: TramitacioException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking setDocumentProces...");
        java.lang.String _setDocumentProces_arg0 = "_setDocumentProces_arg0-232682089";
        java.lang.String _setDocumentProces_arg1 = "_setDocumentProces_arg1-2142872054";
        java.lang.String _setDocumentProces_arg2 = "_setDocumentProces_arg21166165594";
        java.lang.String _setDocumentProces_arg3 = "_setDocumentProces_arg3621219341";
        java.lang.String _setDocumentProces_arg4 = "_setDocumentProces_arg4590758057";
        javax.xml.datatype.XMLGregorianCalendar _setDocumentProces_arg5 = javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2014-04-22T09:15:26.201+02:00");
        byte[] _setDocumentProces_arg6 = new byte[] {};
        try {
            java.lang.Long _setDocumentProces__return = port.setDocumentProces(_setDocumentProces_arg0, _setDocumentProces_arg1, _setDocumentProces_arg2, _setDocumentProces_arg3, _setDocumentProces_arg4, _setDocumentProces_arg5, _setDocumentProces_arg6);
            System.out.println("setDocumentProces.result=" + _setDocumentProces__return);

        } catch (TramitacioException_Exception e) { 
            System.out.println("Expected exception: TramitacioException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking setDadesFormulariTasca...");
        java.lang.String _setDadesFormulariTasca_arg0 = "_setDadesFormulariTasca_arg0-1078972131";
        java.lang.String _setDadesFormulariTasca_arg1 = "_setDadesFormulariTasca_arg1410282130";
        java.lang.String _setDadesFormulariTasca_arg2 = "_setDadesFormulariTasca_arg21772834250";
        java.util.List<net.conselldemallorca.helium.integracio.tramitacio.ParellaCodiValor> _setDadesFormulariTasca_arg3 = new java.util.ArrayList<net.conselldemallorca.helium.integracio.tramitacio.ParellaCodiValor>();
        net.conselldemallorca.helium.integracio.tramitacio.ParellaCodiValor _setDadesFormulariTasca_arg3Val1 = new net.conselldemallorca.helium.integracio.tramitacio.ParellaCodiValor();
        _setDadesFormulariTasca_arg3Val1.setCodi("Codi-1406633505");
        java.lang.Object _setDadesFormulariTasca_arg3Val1Valor = null;
        _setDadesFormulariTasca_arg3Val1.setValor(_setDadesFormulariTasca_arg3Val1Valor);
        _setDadesFormulariTasca_arg3.add(_setDadesFormulariTasca_arg3Val1);
        try {
            port.setDadesFormulariTasca(_setDadesFormulariTasca_arg0, _setDadesFormulariTasca_arg1, _setDadesFormulariTasca_arg2, _setDadesFormulariTasca_arg3);

        } catch (TramitacioException_Exception e) { 
            System.out.println("Expected exception: TramitacioException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking finalitzarTasca...");
        java.lang.String _finalitzarTasca_arg0 = "_finalitzarTasca_arg0739110844";
        java.lang.String _finalitzarTasca_arg1 = "_finalitzarTasca_arg1-1628287607";
        java.lang.String _finalitzarTasca_arg2 = "_finalitzarTasca_arg2-1957814976";
        java.lang.String _finalitzarTasca_arg3 = "_finalitzarTasca_arg3-950069249";
        try {
            port.finalitzarTasca(_finalitzarTasca_arg0, _finalitzarTasca_arg1, _finalitzarTasca_arg2, _finalitzarTasca_arg3);

        } catch (TramitacioException_Exception e) { 
            System.out.println("Expected exception: TramitacioException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking setDocumentTasca...");
        java.lang.String _setDocumentTasca_arg0 = "_setDocumentTasca_arg0-458613805";
        java.lang.String _setDocumentTasca_arg1 = "_setDocumentTasca_arg1-2018601185";
        java.lang.String _setDocumentTasca_arg2 = "_setDocumentTasca_arg21376877682";
        java.lang.String _setDocumentTasca_arg3 = "_setDocumentTasca_arg3-1363489514";
        java.lang.String _setDocumentTasca_arg4 = "_setDocumentTasca_arg4868370872";
        javax.xml.datatype.XMLGregorianCalendar _setDocumentTasca_arg5 = javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2014-04-22T09:15:26.207+02:00");
        byte[] _setDocumentTasca_arg6 = new byte[] {};
        try {
            port.setDocumentTasca(_setDocumentTasca_arg0, _setDocumentTasca_arg1, _setDocumentTasca_arg2, _setDocumentTasca_arg3, _setDocumentTasca_arg4, _setDocumentTasca_arg5, _setDocumentTasca_arg6);

        } catch (TramitacioException_Exception e) { 
            System.out.println("Expected exception: TramitacioException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking consultaTasquesGrupByCodi...");
        java.lang.String _consultaTasquesGrupByCodi_arg0 = "_consultaTasquesGrupByCodi_arg0-1410577018";
        java.lang.String _consultaTasquesGrupByCodi_arg1 = "_consultaTasquesGrupByCodi_arg1-1963322098";
        java.lang.String _consultaTasquesGrupByCodi_arg2 = "_consultaTasquesGrupByCodi_arg2-2140314468";
        try {
            java.util.List<net.conselldemallorca.helium.integracio.tramitacio.TascaTramitacio> _consultaTasquesGrupByCodi__return = port.consultaTasquesGrupByCodi(_consultaTasquesGrupByCodi_arg0, _consultaTasquesGrupByCodi_arg1, _consultaTasquesGrupByCodi_arg2);
            System.out.println("consultaTasquesGrupByCodi.result=" + _consultaTasquesGrupByCodi__return);

        } catch (TramitacioException_Exception e) { 
            System.out.println("Expected exception: TramitacioException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking consultaTasquesGrup...");
        java.lang.String _consultaTasquesGrup_arg0 = "_consultaTasquesGrup_arg01214535036";
        java.lang.String _consultaTasquesGrup_arg1 = "_consultaTasquesGrup_arg1-234353660";
        try {
            java.util.List<net.conselldemallorca.helium.integracio.tramitacio.TascaTramitacio> _consultaTasquesGrup__return = port.consultaTasquesGrup(_consultaTasquesGrup_arg0, _consultaTasquesGrup_arg1);
            System.out.println("consultaTasquesGrup.result=" + _consultaTasquesGrup__return);

        } catch (TramitacioException_Exception e) { 
            System.out.println("Expected exception: TramitacioException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking esborrarDocumentProces...");
        java.lang.String _esborrarDocumentProces_arg0 = "_esborrarDocumentProces_arg0-146841122";
        java.lang.String _esborrarDocumentProces_arg1 = "_esborrarDocumentProces_arg1511494102";
        java.lang.String _esborrarDocumentProces_arg2 = "_esborrarDocumentProces_arg2-614917757";
        java.lang.Long _esborrarDocumentProces_arg3 = Long.valueOf(999999183885851012l);
        try {
            port.esborrarDocumentProces(_esborrarDocumentProces_arg0, _esborrarDocumentProces_arg1, _esborrarDocumentProces_arg2, _esborrarDocumentProces_arg3);

        } catch (TramitacioException_Exception e) { 
            System.out.println("Expected exception: TramitacioException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking consultaDocumentsTasca...");
        java.lang.String _consultaDocumentsTasca_arg0 = "_consultaDocumentsTasca_arg0-498637701";
        java.lang.String _consultaDocumentsTasca_arg1 = "_consultaDocumentsTasca_arg11777039959";
        java.lang.String _consultaDocumentsTasca_arg2 = "_consultaDocumentsTasca_arg2463992855";
        try {
            java.util.List<net.conselldemallorca.helium.integracio.tramitacio.DocumentTasca> _consultaDocumentsTasca__return = port.consultaDocumentsTasca(_consultaDocumentsTasca_arg0, _consultaDocumentsTasca_arg1, _consultaDocumentsTasca_arg2);
            System.out.println("consultaDocumentsTasca.result=" + _consultaDocumentsTasca__return);

        } catch (TramitacioException_Exception e) { 
            System.out.println("Expected exception: TramitacioException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking consultaTasquesPersonals...");
        java.lang.String _consultaTasquesPersonals_arg0 = "_consultaTasquesPersonals_arg01205309542";
        java.lang.String _consultaTasquesPersonals_arg1 = "_consultaTasquesPersonals_arg1-1969890918";
        try {
            java.util.List<net.conselldemallorca.helium.integracio.tramitacio.TascaTramitacio> _consultaTasquesPersonals__return = port.consultaTasquesPersonals(_consultaTasquesPersonals_arg0, _consultaTasquesPersonals_arg1);
            System.out.println("consultaTasquesPersonals.result=" + _consultaTasquesPersonals__return);

        } catch (TramitacioException_Exception e) { 
            System.out.println("Expected exception: TramitacioException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking executarScriptProces...");
        java.lang.String _executarScriptProces_arg0 = "_executarScriptProces_arg0-1896621128";
        java.lang.String _executarScriptProces_arg1 = "_executarScriptProces_arg1459479554";
        java.lang.String _executarScriptProces_arg2 = "_executarScriptProces_arg2984417766";
        java.lang.String _executarScriptProces_arg3 = "_executarScriptProces_arg31293946554";
        try {
            port.executarScriptProces(_executarScriptProces_arg0, _executarScriptProces_arg1, _executarScriptProces_arg2, _executarScriptProces_arg3);

        } catch (TramitacioException_Exception e) { 
            System.out.println("Expected exception: TramitacioException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking iniciExpedient...");
        java.lang.String _iniciExpedient_arg0 = "_iniciExpedient_arg0-1736617225";
        java.lang.String _iniciExpedient_arg1 = "_iniciExpedient_arg11357439989";
        java.lang.String _iniciExpedient_arg2 = "_iniciExpedient_arg2836964566";
        java.lang.String _iniciExpedient_arg3 = "_iniciExpedient_arg3438966594";
        java.lang.String _iniciExpedient_arg4 = "_iniciExpedient_arg42010851971";
        java.util.List<net.conselldemallorca.helium.integracio.tramitacio.ParellaCodiValor> _iniciExpedient_arg5 = new java.util.ArrayList<net.conselldemallorca.helium.integracio.tramitacio.ParellaCodiValor>();
        net.conselldemallorca.helium.integracio.tramitacio.ParellaCodiValor _iniciExpedient_arg5Val1 = new net.conselldemallorca.helium.integracio.tramitacio.ParellaCodiValor();
        _iniciExpedient_arg5Val1.setCodi("Codi1974574295");
        java.lang.Object _iniciExpedient_arg5Val1Valor = null;
        _iniciExpedient_arg5Val1.setValor(_iniciExpedient_arg5Val1Valor);
        _iniciExpedient_arg5.add(_iniciExpedient_arg5Val1);
        try {
            java.lang.String _iniciExpedient__return = port.iniciExpedient(_iniciExpedient_arg0, _iniciExpedient_arg1, _iniciExpedient_arg2, _iniciExpedient_arg3, _iniciExpedient_arg4, _iniciExpedient_arg5);
            System.out.println("iniciExpedient.result=" + _iniciExpedient__return);

        } catch (TramitacioException_Exception e) { 
            System.out.println("Expected exception: TramitacioException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking esborrarVariableProces...");
        java.lang.String _esborrarVariableProces_arg0 = "_esborrarVariableProces_arg0-70050005";
        java.lang.String _esborrarVariableProces_arg1 = "_esborrarVariableProces_arg11010799643";
        java.lang.String _esborrarVariableProces_arg2 = "_esborrarVariableProces_arg2408586948";
        java.lang.String _esborrarVariableProces_arg3 = "_esborrarVariableProces_arg3-1147509637";
        try {
            port.esborrarVariableProces(_esborrarVariableProces_arg0, _esborrarVariableProces_arg1, _esborrarVariableProces_arg2, _esborrarVariableProces_arg3);

        } catch (TramitacioException_Exception e) { 
            System.out.println("Expected exception: TramitacioException has occurred.");
            System.out.println(e.toString());
        }
            }

        System.exit(0);
    }

}
