CREATE TABLE HEL_ALERTA
(
  ID                NUMBER(19)                  NOT NULL,
  DATA_CREACIO      TIMESTAMP(6)                NOT NULL,
  DATA_ELIMINACIO   TIMESTAMP(6),
  DATA_LECTURA      TIMESTAMP(6),
  DESTINATARI       VARCHAR2(255 CHAR)          NOT NULL,
  TASK_INSTANCE_ID  VARCHAR2(255 CHAR),
  TEXT              VARCHAR2(1024 CHAR),
  ENTORN_ID         NUMBER(19)                  NOT NULL,
  EXPEDIENT_ID      NUMBER(19)                  NOT NULL
);
ALTER TABLE HEL_ALERTA ADD (
  PRIMARY KEY
 (ID));
ALTER TABLE HEL_ALERTA ADD (
  CONSTRAINT HEL_ENTORN_ALERTA_FK 
 FOREIGN KEY (ENTORN_ID) 
 REFERENCES HEL_ENTORN (ID),
  CONSTRAINT HEL_EXPEDIENT_ALERTA_FK 
 FOREIGN KEY (EXPEDIENT_ID) 
 REFERENCES HEL_EXPEDIENT (ID));

ALTER TABLE HEL_CAMP
 ADD (ORDRE                NUMBER(10));

ALTER TABLE HEL_TERMINI
 ADD (DIES_PREVIS_AVIS     NUMBER(10));
ALTER TABLE HEL_TERMINI
 ADD (ALERTA_PREVIA        NUMBER(1));
ALTER TABLE HEL_TERMINI
 ADD (ALERTA_FINAL         NUMBER(1));
UPDATE HEL_TERMINI SET ALERTA_PREVIA=0, ALERTA_FINAL=0;

ALTER TABLE HEL_TERMINI_INICIAT
 ADD (ALERTA_PREVIA        NUMBER(1));
ALTER TABLE HEL_TERMINI_INICIAT
 ADD (ALERTA_FINAL         NUMBER(1));
ALTER TABLE HEL_TERMINI_INICIAT
 ADD (DATA_FI_PRORROGA     DATE);
ALTER TABLE HEL_TERMINI_INICIAT
 ADD (TASK_INSTANCE_ID     VARCHAR2(255 CHAR));
ALTER TABLE HEL_TERMINI_INICIAT
 ADD (TIMER_IDS            VARCHAR2(1024 CHAR));
ALTER TABLE HEL_TERMINI_INICIAT
 DROP COLUMN TIMER_NAME;
UPDATE HEL_TERMINI_INICIAT SET ALERTA_PREVIA=0, ALERTA_FINAL=0;

ALTER TABLE HEL_DOCUMENT_STORE
 ADD (REGISTRE_ANY         VARCHAR2(255 CHAR));
ALTER TABLE HEL_DOCUMENT_STORE
 ADD (REGISTRE_DATA        TIMESTAMP(6));
ALTER TABLE HEL_DOCUMENT_STORE
 ADD (REGISTRE_ENTRADA     NUMBER(1));
ALTER TABLE HEL_DOCUMENT_STORE
 ADD (REGISTRE_NUM         VARCHAR2(255 CHAR));
ALTER TABLE HEL_DOCUMENT_STORE
 ADD (REGISTRE_OFCODI      VARCHAR2(255 CHAR));
ALTER TABLE HEL_DOCUMENT_STORE
 ADD (REGISTRE_OFNOM       VARCHAR2(255 CHAR));
UPDATE HEL_DOCUMENT_STORE SET REGISTRE_ENTRADA=1;

ALTER TABLE HEL_TERMINI
 ADD (DURADA_PREDEF       NUMBER(1));
UPDATE HEL_TERMINI SET DURADA_PREDEF=1;
ALTER TABLE HEL_TERMINI_INICIAT
 ADD (ANYS        NUMBER(10));
ALTER TABLE HEL_TERMINI_INICIAT
 ADD (MESOS        NUMBER(10));
ALTER TABLE HEL_TERMINI_INICIAT
 ADD (DIES        NUMBER(10));
UPDATE HEL_TERMINI_INICIAT SET ANYS=0,MESOS=0,DIES=0;

ALTER TABLE HEL_EXPEDIENT
 ADD (REGISTRE_NUM       VARCHAR2(64 CHAR));
ALTER TABLE HEL_EXPEDIENT
 ADD (REGISTRE_DATA       DATE);
ALTER TABLE HEL_EXPEDIENT
 ADD (GEO_POSX       FLOAT(126));
ALTER TABLE HEL_EXPEDIENT
 ADD (GEO_POSY       FLOAT(126));
ALTER TABLE HEL_EXPEDIENT
 ADD (GEO_REFERENCIA       VARCHAR2(64 CHAR));

ALTER TABLE HEL_EXPEDIENT
 ADD (AVISOS_HABILITAT       NUMBER(1));
ALTER TABLE HEL_EXPEDIENT
 ADD (AVISOS_EMAIL       VARCHAR2(255 CHAR));
ALTER TABLE HEL_EXPEDIENT
 ADD (AVISOS_MOBIL       VARCHAR2(255 CHAR));
ALTER TABLE HEL_EXPEDIENT
 ADD (NOTTEL_HABILITAT       NUMBER(1));
UPDATE HEL_EXPEDIENT SET AVISOS_HABILITAT=0,NOTTEL_HABILITAT=0;

ALTER TABLE HEL_EXPEDIENT_TIPUS
 ADD (SISTRA_MAPADJ       VARCHAR2(2048 CHAR));

ALTER TABLE HEL_ENUMERACIO
 MODIFY VALORS VARCHAR2(4000 CHAR);

ALTER TABLE HEL_EXPEDIENT
 MODIFY REGISTRE_DATA TIMESTAMP;
ALTER TABLE HEL_EXPEDIENT
 ADD (UNITAT_ADM NUMBER(19));
ALTER TABLE HEL_EXPEDIENT
 ADD (IDIOMA VARCHAR2(8));
ALTER TABLE HEL_EXPEDIENT
 ADD (AUTENTICAT NUMBER(1));
ALTER TABLE HEL_EXPEDIENT
 ADD (TRAMITADOR_NIF VARCHAR2(16));
ALTER TABLE HEL_EXPEDIENT
 ADD (TRAMITADOR_NOM VARCHAR2(255));
ALTER TABLE HEL_EXPEDIENT
 ADD (INTERESSAT_NIF VARCHAR2(16));
ALTER TABLE HEL_EXPEDIENT
 ADD (INTERESSAT_NOM VARCHAR2(255));
ALTER TABLE HEL_EXPEDIENT
 ADD (REPRESENTANT_NIF VARCHAR2(16));
ALTER TABLE HEL_EXPEDIENT
 ADD (REPRESENTANT_NOM VARCHAR2(255));
UPDATE HEL_EXPEDIENT SET AUTENTICAT=0;

ALTER TABLE HEL_DOCUMENT_STORE
 DROP COLUMN REGISTRE_ANY;
ALTER TABLE HEL_DOCUMENT_STORE
 ADD (REGISTRE_ORGCODI VARCHAR2(255));
ALTER TABLE HEL_EXPEDIENT
 ADD (TRAMEXP_ID VARCHAR2(255));
ALTER TABLE HEL_EXPEDIENT
 ADD (TRAMEXP_CLAU VARCHAR2(255));

ALTER TABLE HEL_ALERTA
 DROP COLUMN TASK_INSTANCE_ID;
ALTER TABLE HEL_ALERTA
 ADD (TERMINI_INICIAT_ID NUMBER(19));
