package net.conselldemallorca.helium.integracio.bantel.service.wsdl;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.2.2
 * Wed Nov 25 15:36:42 CET 2009
 * Generated source version: 2.2.2
 * 
 */
 
@WebService(targetNamespace = "urn:es:caib:bantel:ws:v1:services", name = "BantelFacade")
@XmlSeeAlso({ObjectFactory.class})
public interface BantelFacade {

    @ResponseWrapper(localName = "avisoEntradasResponse", targetNamespace = "urn:es:caib:bantel:ws:v1:model:BantelFacade", className = "net.conselldemallorca.helium.integracio.bantel.service.wsdl.AvisoEntradasResponse")
    @RequestWrapper(localName = "avisoEntradas", targetNamespace = "urn:es:caib:bantel:ws:v1:model:BantelFacade", className = "net.conselldemallorca.helium.integracio.bantel.service.wsdl.AvisoEntradas")
    @WebMethod
    public void avisoEntradas(
        @WebParam(name = "numeroEntradas", targetNamespace = "urn:es:caib:bantel:ws:v1:model:BantelFacade")
        net.conselldemallorca.helium.integracio.bantel.service.wsdl.ReferenciasEntrada numeroEntradas
    ) throws BantelFacadeException_Exception;
}
