
package net.conselldemallorca.helium.integracio.bantel.service.wsdl;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.2.2
 * Wed Nov 25 15:36:42 CET 2009
 * Generated source version: 2.2.2
 * 
 */

@WebFault(name = "fault", targetNamespace = "urn:es:caib:bantel:ws:v1:model:BantelFacade")
public class BantelFacadeException_Exception extends Exception {
    public static final long serialVersionUID = 20091125153642L;
    
    private net.conselldemallorca.helium.integracio.bantel.service.wsdl.BantelFacadeException fault;

    public BantelFacadeException_Exception() {
        super();
    }
    
    public BantelFacadeException_Exception(String message) {
        super(message);
    }
    
    public BantelFacadeException_Exception(String message, Throwable cause) {
        super(message, cause);
    }

    public BantelFacadeException_Exception(String message, net.conselldemallorca.helium.integracio.bantel.service.wsdl.BantelFacadeException fault) {
        super(message);
        this.fault = fault;
    }

    public BantelFacadeException_Exception(String message, net.conselldemallorca.helium.integracio.bantel.service.wsdl.BantelFacadeException fault, Throwable cause) {
        super(message, cause);
        this.fault = fault;
    }

    public net.conselldemallorca.helium.integracio.bantel.service.wsdl.BantelFacadeException getFaultInfo() {
        return this.fault;
    }
}
