
/*
 * 
 */

package net.conselldemallorca.helium.integracio.bantel.service.wsdl;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.2.2
 * Wed Nov 25 15:36:42 CET 2009
 * Generated source version: 2.2.2
 * 
 */


@WebServiceClient(name = "BantelFacadeService", 
                  wsdlLocation = "file:BantelFacade.wsdl",
                  targetNamespace = "urn:es:caib:bantel:ws:v1:services") 
public class BantelFacadeService extends Service {

    public final static URL WSDL_LOCATION;
    public final static QName SERVICE = new QName("urn:es:caib:bantel:ws:v1:services", "BantelFacadeService");
    public final static QName BantelFacade = new QName("urn:es:caib:bantel:ws:v1:services", "BantelFacade");
    static {
        URL url = null;
        try {
            url = new URL("file:BantelFacade.wsdl");
        } catch (MalformedURLException e) {
            System.err.println("Can not initialize the default wsdl from file:BantelFacade.wsdl");
            // e.printStackTrace();
        }
        WSDL_LOCATION = url;
    }

    public BantelFacadeService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public BantelFacadeService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public BantelFacadeService() {
        super(WSDL_LOCATION, SERVICE);
    }

    /**
     * 
     * @return
     *     returns BantelFacade
     */
    @WebEndpoint(name = "BantelFacade")
    public BantelFacade getBantelFacade() {
        return super.getPort(BantelFacade, BantelFacade.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns BantelFacade
     */
    @WebEndpoint(name = "BantelFacade")
    public BantelFacade getBantelFacade(WebServiceFeature... features) {
        return super.getPort(BantelFacade, BantelFacade.class, features);
    }

}
