-- #1795 Avís per email de nova anotació rebuda a Helium

-- Oracle
ALTER TABLE HEL_USUARI_PREFS ADD CORREUS_BUSTIA NUMBER(1,0) DEFAULT 0;
ALTER TABLE HEL_USUARI_PREFS ADD CORREUS_BUSTIA_AGRUPATS_DIA NUMBER(1,0) DEFAULT 0;
ALTER TABLE HEL_USUARI_PREFS ADD  EMAIL_ALTERNATIU VARCHAR2(255 CHAR);

ALTER TABLE HEL_EXPEDIENT_TIPUS ADD  ENVIAR_CORREU_ANOTACIONS NUMBER(1,0) DEFAULT 0;

-- -- Nova taula per els correus d'anotacions per enviar
CREATE TABLE HEL_ANOTACIO_EMAIL (
  ID           				NUMBER(19,0)         	NOT NULL,
  REMITENT_CODI				VARCHAR2(64 CHAR) 		NOT NULL,
  DESTINATARI_CODI 			VARCHAR2(64 CHAR) 		NOT NULL,
  DESTINATARI_EMAIL			VARCHAR(256 CHAR)   	NOT NULL,
  ENVIAMENT_AGRUPAT			NUMBER(1,0) DEFAULT 0 	NOT NULL,
  ANOTACIO_ID				NUMBER(19,0)         	NOT NULL,
  EXPEDIENT_ID				NUMBER(19,0),
  EMAIL_TIPUS				VARCHAR2(64 CHAR) 		NOT NULL, --ARRIBADA | PROCESSADA | INCORPORADA
  NUM_INTENTS				NUMBER(19,0),
  DATA_CREACIO				TIMESTAMP(6),
  PRIMARY KEY (ID),
  CONSTRAINT HEL_ANOTACIO_ID_FK FOREIGN KEY (ANOTACIO_ID) REFERENCES HEL_ANOTACIO(ID),
  CONSTRAINT HEL_EXPEDIENT_ID_FK FOREIGN KEY (EXPEDIENT_ID) REFERENCES HEL_EXPEDIENT(ID)
);


GRANT SELECT, UPDATE, INSERT, DELETE ON HEL_ANOTACIO_EMAIL TO WWW_HELIUM;
    
-- Postgresql
ALTER TABLE HEL_USUARI_PREFS ADD CORREUS_BUSTIA BOOLEAN DEFAULT FALSE;
ALTER TABLE HEL_USUARI_PREFS ADD CORREUS_BUSTIA_AGRUPATS_DIA BOOLEAN DEFAULT FALSE;
ALTER TABLE HEL_USUARI_PREFS ADD  EMAIL_ALTERNATIU VARCHAR(255);

ALTER TABLE HEL_EXPEDIENT_TIPUS ADD  ENVIAR_CORREU_ANOTACIONS BOOLEAN DEFAULT FALSE;

-- -- Nova taula per els correus d'anotacions per enviar
CREATE TABLE HEL_ANOTACIO_EMAIL (
  ID           				BIGINT         	NOT NULL,
  REMITENT_CODI				VARCHAR(64) 		NOT NULL,
  DESTINATARI_CODI 			VARCHAR(64) 		NOT NULL,
  DESTINATARI_EMAIL			VARCHAR(256)   	NOT NULL,
  ENVIAMENT_AGRUPAT			BOOLEAN,
  ANOTACIO_ID				BIGINT         	NOT NULL,
  EXPEDIENT_ID				BIGINT,
  EMAIL_TIPUS				VARCHAR(64) 		NOT NULL, --ARRIBADA | PROCESSADA | INCORPORADA
  NUM_INTENTS				BIGINT,
  DATA_CREACIO				TIMESTAMP(6)
);

ALTER TABLE HEL_ANOTACIO_EMAIL ADD (
  	CONSTRAINT HEL_ANOTACIO_EMAIL_PK PRIMARY KEY (ID)); 

ALTER TABLE HEL_ANOTACIO_EMAIL ADD 
  CONSTRAINT HEL_ANOTACIO_ID_FK FOREIGN KEY (ANOTACIO_ID) 
    REFERENCES HEL_ANOTACIO (ID);

ALTER TABLE HEL_ANOTACIO_EMAIL ADD 
  CONSTRAINT HEL_EXPEDIENT_ID_FK FOREIGN KEY (EXPEDIENT_ID) 
    REFERENCES HEL_EXPEDIENT (ID);