
package es.caib.regtel.ws.v2.services;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import es.caib.regtel.ws.v2.model.acuserecibo.AcuseRecibo;
import es.caib.regtel.ws.v2.model.datosregistroentrada.DatosRegistroEntrada;
import es.caib.regtel.ws.v2.model.datosregistrosalida.DatosRegistroSalida;
import es.caib.regtel.ws.v2.model.detalleacuserecibo.DetalleAcuseRecibo;
import es.caib.regtel.ws.v2.model.firmaws.FirmaWS;
import es.caib.regtel.ws.v2.model.referenciards.ReferenciaRDSAsientoRegistral;
import es.caib.regtel.ws.v2.model.resultadoregistro.ResultadoRegistro;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "BackofficeFacade", targetNamespace = "urn:es:caib:regtel:ws:v2:services")
@XmlSeeAlso({
    es.caib.regtel.ws.v2.model.datosasunto.ObjectFactory.class,
    es.caib.regtel.ws.v2.model.datosinteresado.ObjectFactory.class,
    es.caib.regtel.ws.v2.model.datosregistroentrada.ObjectFactory.class,
    es.caib.regtel.ws.v2.model.acuserecibo.ObjectFactory.class,
    es.caib.regtel.ws.v2.model.datosrepresentado.ObjectFactory.class,
    es.caib.regtel.ws.v2.model.detalleacuserecibo.ObjectFactory.class,
    es.caib.regtel.ws.v2.model.backofficefacade.ObjectFactory.class,
    es.caib.regtel.ws.v2.model.oficinaregistral.ObjectFactory.class,
    es.caib.regtel.ws.v2.model.firmaws.ObjectFactory.class,
    es.caib.regtel.ws.v2.model.referenciards.ObjectFactory.class,
    es.caib.regtel.ws.v2.model.oficioremision.ObjectFactory.class,
    es.caib.regtel.ws.v2.model.resultadoregistro.ObjectFactory.class,
    es.caib.regtel.ws.v2.model.datosregistrosalida.ObjectFactory.class,
    es.caib.regtel.ws.v2.model.datosnotificacion.ObjectFactory.class,
    es.caib.regtel.ws.v2.model.documento.ObjectFactory.class,
    es.caib.regtel.ws.v2.model.aviso.ObjectFactory.class,
    es.caib.regtel.ws.v2.model.datosexpediente.ObjectFactory.class
})
public interface BackofficeFacade {


    /**
     * 
     * @param entrada
     * @return
     *     returns es.caib.regtel.ws.v2.model.resultadoregistro.ResultadoRegistro
     * @throws BackofficeFacadeException
     */
    @WebMethod
    @WebResult(name = "registroEntradaReturn", targetNamespace = "urn:es:caib:regtel:ws:v2:model:BackofficeFacade")
    @RequestWrapper(localName = "registroEntrada", targetNamespace = "urn:es:caib:regtel:ws:v2:model:BackofficeFacade", className = "es.caib.regtel.ws.v2.model.backofficefacade.RegistroEntrada")
    @ResponseWrapper(localName = "registroEntradaResponse", targetNamespace = "urn:es:caib:regtel:ws:v2:model:BackofficeFacade", className = "es.caib.regtel.ws.v2.model.backofficefacade.RegistroEntradaResponse")
    public ResultadoRegistro registroEntrada(
        @WebParam(name = "entrada", targetNamespace = "urn:es:caib:regtel:ws:v2:model:BackofficeFacade")
        DatosRegistroEntrada entrada)
        throws BackofficeFacadeException
    ;

    /**
     * 
     * @param entrada
     * @param diasPersistencia
     * @return
     *     returns es.caib.regtel.ws.v2.model.referenciards.ReferenciaRDSAsientoRegistral
     * @throws BackofficeFacadeException
     */
    @WebMethod
    @WebResult(name = "prepararRegistroEntradaReturn", targetNamespace = "urn:es:caib:regtel:ws:v2:model:BackofficeFacade")
    @RequestWrapper(localName = "prepararRegistroEntrada", targetNamespace = "urn:es:caib:regtel:ws:v2:model:BackofficeFacade", className = "es.caib.regtel.ws.v2.model.backofficefacade.PrepararRegistroEntrada")
    @ResponseWrapper(localName = "prepararRegistroEntradaResponse", targetNamespace = "urn:es:caib:regtel:ws:v2:model:BackofficeFacade", className = "es.caib.regtel.ws.v2.model.backofficefacade.PrepararRegistroEntradaResponse")
    public ReferenciaRDSAsientoRegistral prepararRegistroEntrada(
        @WebParam(name = "entrada", targetNamespace = "urn:es:caib:regtel:ws:v2:model:BackofficeFacade")
        DatosRegistroEntrada entrada,
        @WebParam(name = "diasPersistencia", targetNamespace = "urn:es:caib:regtel:ws:v2:model:BackofficeFacade")
        String diasPersistencia)
        throws BackofficeFacadeException
    ;

    /**
     * 
     * @param referenciaRDS
     * @param firma
     * @return
     *     returns es.caib.regtel.ws.v2.model.resultadoregistro.ResultadoRegistro
     * @throws BackofficeFacadeException
     */
    @WebMethod
    @WebResult(name = "registroEntradaConFirmaReturn", targetNamespace = "urn:es:caib:regtel:ws:v2:model:BackofficeFacade")
    @RequestWrapper(localName = "registroEntradaConFirma", targetNamespace = "urn:es:caib:regtel:ws:v2:model:BackofficeFacade", className = "es.caib.regtel.ws.v2.model.backofficefacade.RegistroEntradaConFirma")
    @ResponseWrapper(localName = "registroEntradaConFirmaResponse", targetNamespace = "urn:es:caib:regtel:ws:v2:model:BackofficeFacade", className = "es.caib.regtel.ws.v2.model.backofficefacade.RegistroEntradaConFirmaResponse")
    public ResultadoRegistro registroEntradaConFirma(
        @WebParam(name = "referenciaRDS", targetNamespace = "urn:es:caib:regtel:ws:v2:model:BackofficeFacade")
        ReferenciaRDSAsientoRegistral referenciaRDS,
        @WebParam(name = "firma", targetNamespace = "urn:es:caib:regtel:ws:v2:model:BackofficeFacade")
        FirmaWS firma)
        throws BackofficeFacadeException
    ;

    /**
     * 
     * @param notificacion
     * @return
     *     returns es.caib.regtel.ws.v2.model.resultadoregistro.ResultadoRegistro
     * @throws BackofficeFacadeException
     */
    @WebMethod
    @WebResult(name = "registroSalidaReturn", targetNamespace = "urn:es:caib:regtel:ws:v2:model:BackofficeFacade")
    @RequestWrapper(localName = "registroSalida", targetNamespace = "urn:es:caib:regtel:ws:v2:model:BackofficeFacade", className = "es.caib.regtel.ws.v2.model.backofficefacade.RegistroSalida")
    @ResponseWrapper(localName = "registroSalidaResponse", targetNamespace = "urn:es:caib:regtel:ws:v2:model:BackofficeFacade", className = "es.caib.regtel.ws.v2.model.backofficefacade.RegistroSalidaResponse")
    public ResultadoRegistro registroSalida(
        @WebParam(name = "notificacion", targetNamespace = "urn:es:caib:regtel:ws:v2:model:BackofficeFacade")
        DatosRegistroSalida notificacion)
        throws BackofficeFacadeException
    ;

    /**
     * 
     * @param numeroRegistro
     * @return
     *     returns es.caib.regtel.ws.v2.model.acuserecibo.AcuseRecibo
     * @throws BackofficeFacadeException
     */
    @WebMethod
    @WebResult(name = "obtenerAcuseReciboReturn", targetNamespace = "urn:es:caib:regtel:ws:v2:model:BackofficeFacade")
    @RequestWrapper(localName = "obtenerAcuseRecibo", targetNamespace = "urn:es:caib:regtel:ws:v2:model:BackofficeFacade", className = "es.caib.regtel.ws.v2.model.backofficefacade.ObtenerAcuseRecibo")
    @ResponseWrapper(localName = "obtenerAcuseReciboResponse", targetNamespace = "urn:es:caib:regtel:ws:v2:model:BackofficeFacade", className = "es.caib.regtel.ws.v2.model.backofficefacade.ObtenerAcuseReciboResponse")
    public AcuseRecibo obtenerAcuseRecibo(
        @WebParam(name = "numeroRegistro", targetNamespace = "urn:es:caib:regtel:ws:v2:model:BackofficeFacade")
        String numeroRegistro)
        throws BackofficeFacadeException
    ;

    /**
     * 
     * @param numeroRegistro
     * @return
     *     returns es.caib.regtel.ws.v2.model.detalleacuserecibo.DetalleAcuseRecibo
     * @throws BackofficeFacadeException
     */
    @WebMethod
    @WebResult(name = "obtenerDetalleAcuseReciboReturn", targetNamespace = "urn:es:caib:regtel:ws:v2:model:BackofficeFacade")
    @RequestWrapper(localName = "obtenerDetalleAcuseRecibo", targetNamespace = "urn:es:caib:regtel:ws:v2:model:BackofficeFacade", className = "es.caib.regtel.ws.v2.model.backofficefacade.ObtenerDetalleAcuseRecibo")
    @ResponseWrapper(localName = "obtenerDetalleAcuseReciboResponse", targetNamespace = "urn:es:caib:regtel:ws:v2:model:BackofficeFacade", className = "es.caib.regtel.ws.v2.model.backofficefacade.ObtenerDetalleAcuseReciboResponse")
    public DetalleAcuseRecibo obtenerDetalleAcuseRecibo(
        @WebParam(name = "numeroRegistro", targetNamespace = "urn:es:caib:regtel:ws:v2:model:BackofficeFacade")
        String numeroRegistro)
        throws BackofficeFacadeException
    ;

}
