
package es.caib.regtel.ws.v2.services;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "BackofficeFacadeService", targetNamespace = "urn:es:caib:regtel:ws:v2:services", wsdlLocation = "file:/C:/Users/PereP/git/sistra/moduls/modul-regtel/moduls/webservices/wsdl/regtel/v2/BackofficeFacade.wsdl")
public class BackofficeFacadeService
    extends Service
{

    private final static URL BACKOFFICEFACADESERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(es.caib.regtel.ws.v2.services.BackofficeFacadeService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = es.caib.regtel.ws.v2.services.BackofficeFacadeService.class.getResource(".");
            url = new URL(baseUrl, "file:/C:/Users/PereP/git/sistra/moduls/modul-regtel/moduls/webservices/wsdl/regtel/v2/BackofficeFacade.wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'file:/C:/Users/PereP/git/sistra/moduls/modul-regtel/moduls/webservices/wsdl/regtel/v2/BackofficeFacade.wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        BACKOFFICEFACADESERVICE_WSDL_LOCATION = url;
    }

    public BackofficeFacadeService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public BackofficeFacadeService() {
        super(BACKOFFICEFACADESERVICE_WSDL_LOCATION, new QName("urn:es:caib:regtel:ws:v2:services", "BackofficeFacadeService"));
    }

    /**
     * 
     * @return
     *     returns BackofficeFacade
     */
    @WebEndpoint(name = "BackofficeFacade")
    public BackofficeFacade getBackofficeFacade() {
        return super.getPort(new QName("urn:es:caib:regtel:ws:v2:services", "BackofficeFacade"), BackofficeFacade.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns BackofficeFacade
     */
    @WebEndpoint(name = "BackofficeFacade")
    public BackofficeFacade getBackofficeFacade(WebServiceFeature... features) {
        return super.getPort(new QName("urn:es:caib:regtel:ws:v2:services", "BackofficeFacade"), BackofficeFacade.class, features);
    }

}
