######################################################
# Helium Spring Boot 2
# Configuració específica.
######################################################

server:
    # Port on escolta l'aplicació quan s'inicia amb el servidor emeded
    port: 8080
    servlet:
        context-path: /heliumback
    tomcat:
        max-swallow-size: -1
spring:
    # Pàgines jsp a la carpeta src/main/webapp
    mvc:
        view:
            prefix: /WEB-INF/jsp/
            suffix: .jsp
    messages:
        basename: messages_helium
#    jpa:
#        properties:
#            hibernate:
#                format_sql: true
    servlet:
        multipart:
            max-file-size: 10MB
            max-request-size: 10MB

security:
    basic:
        enabled: false
management:
    security:
        enabled: false

keycloak:
    #keycloak.auth-server-url=http://localhost:8180/auth
    auth-server-url: http://docker.limit.es:21234/auth
    realm: GOIB
    resource: goib-default
    public-client: true
    principal-attribute: preferred_username
    use-resource-role-mappings: true

logging:
    level:
        es.caib.helium: DEBUG
        es.caib.helium.client: DEBUG
#        org.springframework: DEBUG
#        org.hibernate.SQL: DEBUG
#        org.hibernate.type.descriptor.sql.BasicBinder: TRACE

#feign:
#    client:
#        config:
#            default:
#                loggerLevel: full

# Propietats
es:
    caib:
        helium:
            properties: /home/siona/Feina/Conf/Helium/helium4/helium.properties
            system:
                properties: /home/siona/Feina/Conf/Helium/helium4/helium_system.properties
