######################################################
# Helium Spring Boot 2
# Configuració específica.
######################################################

server:
    # Port on escolta l'aplicació quan s'inicia amb el servidor emeded
    port: 8080
    servlet:
        context-path: /heliumback
spring:
    # Pàgines jsp a la carpeta src/main/webapp
    mvc:
        view:
            prefix: /WEB-INF/jsp/
            suffix: .jsp
    messages:
        basename: messages_helium

security:
    basic:
        enabled: false
management:
    security:
        enabled: false

keycloak:
    #keycloak.auth-server-url=http://localhost:8180/auth
    auth-server-url: http://docker.limit.es:21234/auth
    realm: GOIB
    resource: goib-default
    public-client: true
    principal-attribute: preferred_username
    use-resource-role-mappings: true

logging:
    level:
      es.caib.helium: DEBUG
#        org.springframework: TRACE
#        com: TRACE
          

# Propietats
es:
    caib:
        helium:
            properties: /helium/configMs/helium.properties
            system:
                properties: /helium/configMs/helium_system.properties