
package es.indra.portafirmasws.cws;

import javax.xml.ws.Endpoint;

/**
 * This class was generated by Apache CXF 3.0.0-milestone2
 * 2014-04-08T21:31:36.811+02:00
 * Generated source version: 3.0.0-milestone2
 * 
 */
 
public class Cws_CWS_Server{

    protected Cws_CWS_Server() throws java.lang.Exception {
        System.out.println("Starting Server");
        Object implementor = new CWSImpl();
        String address = "https://proves.caib.es/portafirmasws/web/services/CWS";
        Endpoint.publish(address, implementor);
    }
    
    public static void main(String args[]) throws java.lang.Exception { 
        new Cws_CWS_Server();
        System.out.println("Server ready..."); 
        
        Thread.sleep(5 * 60 * 1000); 
        System.out.println("Server exiting");
        System.exit(0);
    }
}
