
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package es.indra.portafirmasws.cws;

import java.util.logging.Logger;

/**
 * This class was generated by Apache CXF 3.0.0-milestone2
 * 2014-04-08T21:31:36.679+02:00
 * Generated source version: 3.0.0-milestone2
 * 
 */

@javax.jws.WebService(
                      serviceName = "CwsService",
                      portName = "CWS",
                      targetNamespace = "http://www.indra.es/portafirmasws/cws",
                      wsdlLocation = "file:/C:/Users/Javier/Workspace/helium-selenium-integraciones/WebContent/wsdl/cws.wsdl",
                      endpointInterface = "es.indra.portafirmasws.cws.Cws")
                      
public class CWSImpl implements Cws {

    private static final Logger LOG = Logger.getLogger(CWSImpl.class.getName());

    /* (non-Javadoc)
     * @see es.indra.portafirmasws.cws.Cws#searchDocuments(es.indra.portafirmasws.cws.SearchRequest  searchRequest )*
     */
    public es.indra.portafirmasws.cws.SearchResponse searchDocuments(SearchRequest searchRequest) { 
        LOG.info("Executing operation searchDocuments");
        System.out.println(searchRequest);
        try {
            es.indra.portafirmasws.cws.SearchResponse _return = new es.indra.portafirmasws.cws.SearchResponse();
            es.indra.portafirmasws.cws.Result _returnResult = new es.indra.portafirmasws.cws.Result();
            _returnResult.setCode(0);
            _returnResult.setMessage("Message1524844781");
            _return.setResult(_returnResult);
            es.indra.portafirmasws.cws.SearchResult _returnSearchResult = null;
            _return.setSearchResult(_returnSearchResult);
            _return.setVersion("Version2130811679");
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see es.indra.portafirmasws.cws.Cws#uploadDocument(es.indra.portafirmasws.cws.UploadRequest  uploadRequest )*
     */
    public es.indra.portafirmasws.cws.UploadResponse uploadDocument(UploadRequest uploadRequest) { 
        LOG.info("Executing operation uploadDocument");
        System.out.println(uploadRequest);
        try {
            es.indra.portafirmasws.cws.UploadResponse _return = new es.indra.portafirmasws.cws.UploadResponse();
            es.indra.portafirmasws.cws.Result _returnResult = new es.indra.portafirmasws.cws.Result();
            _returnResult.setCode(0);
            _returnResult.setMessage("Message1648720971");
            _return.setResult(_returnResult);
            es.indra.portafirmasws.cws.UploadResponseDocument _returnDocument = new es.indra.portafirmasws.cws.UploadResponseDocument();
            _returnDocument.setId(-1531662602);
            _return.setDocument(_returnDocument);
            _return.setVersion("Version982443651");
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see es.indra.portafirmasws.cws.Cws#downloadDocument(es.indra.portafirmasws.cws.DownloadRequest  downloadRequest )*
     */
    public es.indra.portafirmasws.cws.DownloadResponse downloadDocument(DownloadRequest downloadRequest) { 
        LOG.info("Executing operation downloadDocument");
        System.out.println(downloadRequest);
        try {
            es.indra.portafirmasws.cws.DownloadResponse _return = new es.indra.portafirmasws.cws.DownloadResponse();
            es.indra.portafirmasws.cws.Result _returnResult = new es.indra.portafirmasws.cws.Result();
            _returnResult.setCode(0);
            _returnResult.setMessage("Message-1541705619");
            _return.setResult(_returnResult);
            es.indra.portafirmasws.cws.DownloadResponseDocument _returnDocument = new es.indra.portafirmasws.cws.DownloadResponseDocument();
            _returnDocument.setId(-203229601);
            es.indra.portafirmasws.cws.DocumentAttributes _returnDocumentAttributes = new es.indra.portafirmasws.cws.DocumentAttributes();
            _returnDocumentAttributes.setState(Integer.valueOf(-1855481287));
            _returnDocumentAttributes.setTitle("Title-1124046660");
            _returnDocumentAttributes.setType(Integer.valueOf(-584543946));
            _returnDocumentAttributes.setSubject("Subject-1284391261");
            _returnDocumentAttributes.setDescription("Description-1257429402");
            _returnDocumentAttributes.setExtension("Extension-680903268");
            es.indra.portafirmasws.cws.Sender _returnDocumentAttributesSender = new es.indra.portafirmasws.cws.Sender();
            _returnDocumentAttributesSender.setName("Name1544610857");
            _returnDocumentAttributesSender.setEmail("Email23899676");
            _returnDocumentAttributes.setSender(_returnDocumentAttributesSender);
            _returnDocumentAttributes.setUrl("Url1439982126");
            es.indra.portafirmasws.cws.ImportanceEnum _returnDocumentAttributesImportance = es.indra.portafirmasws.cws.ImportanceEnum.LOW;
            _returnDocumentAttributes.setImportance(_returnDocumentAttributesImportance);
            javax.xml.bind.JAXBElement<javax.xml.datatype.XMLGregorianCalendar> _returnDocumentAttributesDateEntry = null;
            _returnDocumentAttributes.setDateEntry(_returnDocumentAttributesDateEntry);
            javax.xml.bind.JAXBElement<javax.xml.datatype.XMLGregorianCalendar> _returnDocumentAttributesDateLimit = null;
            _returnDocumentAttributes.setDateLimit(_returnDocumentAttributesDateLimit);
            javax.xml.bind.JAXBElement<javax.xml.datatype.XMLGregorianCalendar> _returnDocumentAttributesDateLastUpdate = null;
            _returnDocumentAttributes.setDateLastUpdate(_returnDocumentAttributesDateLastUpdate);
            javax.xml.bind.JAXBElement<javax.xml.datatype.XMLGregorianCalendar> _returnDocumentAttributesDateNotice = null;
            _returnDocumentAttributes.setDateNotice(_returnDocumentAttributesDateNotice);
            javax.xml.bind.JAXBElement<java.lang.Integer> _returnDocumentAttributesNumberAnnexes = null;
            _returnDocumentAttributes.setNumberAnnexes(_returnDocumentAttributesNumberAnnexes);
            javax.xml.bind.JAXBElement<java.lang.Boolean> _returnDocumentAttributesSignAnnexes = null;
            _returnDocumentAttributes.setSignAnnexes(_returnDocumentAttributesSignAnnexes);
            javax.xml.bind.JAXBElement<java.lang.String> _returnDocumentAttributesExternalData = null;
            _returnDocumentAttributes.setExternalData(_returnDocumentAttributesExternalData);
            javax.xml.bind.JAXBElement<java.lang.Integer> _returnDocumentAttributesTypeSign = null;
            _returnDocumentAttributes.setTypeSign(_returnDocumentAttributesTypeSign);
            javax.xml.bind.JAXBElement<java.lang.Boolean> _returnDocumentAttributesIsFileSign = null;
            _returnDocumentAttributes.setIsFileSign(_returnDocumentAttributesIsFileSign);
            javax.xml.bind.JAXBElement<java.lang.Boolean> _returnDocumentAttributesGenerateVisuals = null;
            _returnDocumentAttributes.setGenerateVisuals(_returnDocumentAttributesGenerateVisuals);
            javax.xml.bind.JAXBElement<es.indra.portafirmasws.cws.ExternalIDs> _returnDocumentAttributesExternalIds = null;
            _returnDocumentAttributes.setExternalIds(_returnDocumentAttributesExternalIds);
            _returnDocument.setAttributes(_returnDocumentAttributes);
            javax.xml.bind.JAXBElement<es.indra.portafirmasws.cws.ArchiveOptions> _returnDocumentArchiveOptions = null;
            _returnDocument.setArchiveOptions(_returnDocumentArchiveOptions);
            es.indra.portafirmasws.cws.Annexes _returnDocumentAnnexes = new es.indra.portafirmasws.cws.Annexes();
            java.util.List<es.indra.portafirmasws.cws.Annex> _returnDocumentAnnexesAnnex = new java.util.ArrayList<es.indra.portafirmasws.cws.Annex>();
            _returnDocumentAnnexes.getAnnex().addAll(_returnDocumentAnnexesAnnex);
            _returnDocument.setAnnexes(_returnDocumentAnnexes);
            javax.xml.bind.JAXBElement<es.indra.portafirmasws.cws.SignatureFiles> _returnDocumentSignatureFiles = null;
            _returnDocument.setSignatureFiles(_returnDocumentSignatureFiles);
            javax.xml.bind.JAXBElement<es.indra.portafirmasws.cws.VisualFiles> _returnDocumentVisualFiles = null;
            _returnDocument.setVisualFiles(_returnDocumentVisualFiles);
            es.indra.portafirmasws.cws.Steps _returnDocumentSteps = new es.indra.portafirmasws.cws.Steps();
            javax.xml.bind.JAXBElement<es.indra.portafirmasws.cws.SignModeEnum> _returnDocumentStepsSignMode = null;
            _returnDocumentSteps.setSignMode(_returnDocumentStepsSignMode);
            java.util.List<es.indra.portafirmasws.cws.Step> _returnDocumentStepsStep = new java.util.ArrayList<es.indra.portafirmasws.cws.Step>();
            _returnDocumentSteps.getStep().addAll(_returnDocumentStepsStep);
            _returnDocument.setSteps(_returnDocumentSteps);
            _return.setDocument(_returnDocument);
            _return.setVersion("Version-43287467");
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see es.indra.portafirmasws.cws.Cws#listDocuments(es.indra.portafirmasws.cws.ListRequest  listRequest )*
     */
    public es.indra.portafirmasws.cws.ListResponse listDocuments(ListRequest listRequest) { 
        LOG.info("Executing operation listDocuments");
        System.out.println(listRequest);
        try {
            es.indra.portafirmasws.cws.ListResponse _return = new es.indra.portafirmasws.cws.ListResponse();
            es.indra.portafirmasws.cws.Result _returnResult = new es.indra.portafirmasws.cws.Result();
            _returnResult.setCode(0);
            _returnResult.setMessage("Message1094858786");
            _return.setResult(_returnResult);
            es.indra.portafirmasws.cws.ListResponseDocuments _returnDocuments = new es.indra.portafirmasws.cws.ListResponseDocuments();
            java.util.List<es.indra.portafirmasws.cws.ListResponseDocument> _returnDocumentsDocument = new java.util.ArrayList<es.indra.portafirmasws.cws.ListResponseDocument>();
            es.indra.portafirmasws.cws.ListResponseDocument _returnDocumentsDocumentVal1 = new es.indra.portafirmasws.cws.ListResponseDocument();
            _returnDocumentsDocumentVal1.setId(-1244319895);
            es.indra.portafirmasws.cws.DocumentAttributes _returnDocumentsDocumentVal1Attributes = new es.indra.portafirmasws.cws.DocumentAttributes();
            _returnDocumentsDocumentVal1Attributes.setState(Integer.valueOf(-100549141));
            _returnDocumentsDocumentVal1Attributes.setTitle("Title1087355219");
            _returnDocumentsDocumentVal1Attributes.setType(Integer.valueOf(-635296266));
            _returnDocumentsDocumentVal1Attributes.setSubject("Subject153000487");
            _returnDocumentsDocumentVal1Attributes.setDescription("Description2089207570");
            _returnDocumentsDocumentVal1Attributes.setExtension("Extension-1993550518");
            es.indra.portafirmasws.cws.Sender _returnDocumentsDocumentVal1AttributesSender = new es.indra.portafirmasws.cws.Sender();
            _returnDocumentsDocumentVal1AttributesSender.setName("Name173572983");
            _returnDocumentsDocumentVal1AttributesSender.setEmail("Email-314366704");
            _returnDocumentsDocumentVal1Attributes.setSender(_returnDocumentsDocumentVal1AttributesSender);
            _returnDocumentsDocumentVal1Attributes.setUrl("Url857477623");
            es.indra.portafirmasws.cws.ImportanceEnum _returnDocumentsDocumentVal1AttributesImportance = es.indra.portafirmasws.cws.ImportanceEnum.NORMAL;
            _returnDocumentsDocumentVal1Attributes.setImportance(_returnDocumentsDocumentVal1AttributesImportance);
            javax.xml.bind.JAXBElement<javax.xml.datatype.XMLGregorianCalendar> _returnDocumentsDocumentVal1AttributesDateEntry = null;
            _returnDocumentsDocumentVal1Attributes.setDateEntry(_returnDocumentsDocumentVal1AttributesDateEntry);
            javax.xml.bind.JAXBElement<javax.xml.datatype.XMLGregorianCalendar> _returnDocumentsDocumentVal1AttributesDateLimit = null;
            _returnDocumentsDocumentVal1Attributes.setDateLimit(_returnDocumentsDocumentVal1AttributesDateLimit);
            javax.xml.bind.JAXBElement<javax.xml.datatype.XMLGregorianCalendar> _returnDocumentsDocumentVal1AttributesDateLastUpdate = null;
            _returnDocumentsDocumentVal1Attributes.setDateLastUpdate(_returnDocumentsDocumentVal1AttributesDateLastUpdate);
            javax.xml.bind.JAXBElement<javax.xml.datatype.XMLGregorianCalendar> _returnDocumentsDocumentVal1AttributesDateNotice = null;
            _returnDocumentsDocumentVal1Attributes.setDateNotice(_returnDocumentsDocumentVal1AttributesDateNotice);
            javax.xml.bind.JAXBElement<java.lang.Integer> _returnDocumentsDocumentVal1AttributesNumberAnnexes = null;
            _returnDocumentsDocumentVal1Attributes.setNumberAnnexes(_returnDocumentsDocumentVal1AttributesNumberAnnexes);
            javax.xml.bind.JAXBElement<java.lang.Boolean> _returnDocumentsDocumentVal1AttributesSignAnnexes = null;
            _returnDocumentsDocumentVal1Attributes.setSignAnnexes(_returnDocumentsDocumentVal1AttributesSignAnnexes);
            javax.xml.bind.JAXBElement<java.lang.String> _returnDocumentsDocumentVal1AttributesExternalData = null;
            _returnDocumentsDocumentVal1Attributes.setExternalData(_returnDocumentsDocumentVal1AttributesExternalData);
            javax.xml.bind.JAXBElement<java.lang.Integer> _returnDocumentsDocumentVal1AttributesTypeSign = null;
            _returnDocumentsDocumentVal1Attributes.setTypeSign(_returnDocumentsDocumentVal1AttributesTypeSign);
            javax.xml.bind.JAXBElement<java.lang.Boolean> _returnDocumentsDocumentVal1AttributesIsFileSign = null;
            _returnDocumentsDocumentVal1Attributes.setIsFileSign(_returnDocumentsDocumentVal1AttributesIsFileSign);
            javax.xml.bind.JAXBElement<java.lang.Boolean> _returnDocumentsDocumentVal1AttributesGenerateVisuals = null;
            _returnDocumentsDocumentVal1Attributes.setGenerateVisuals(_returnDocumentsDocumentVal1AttributesGenerateVisuals);
            javax.xml.bind.JAXBElement<es.indra.portafirmasws.cws.ExternalIDs> _returnDocumentsDocumentVal1AttributesExternalIds = null;
            _returnDocumentsDocumentVal1Attributes.setExternalIds(_returnDocumentsDocumentVal1AttributesExternalIds);
            _returnDocumentsDocumentVal1.setAttributes(_returnDocumentsDocumentVal1Attributes);
            javax.xml.bind.JAXBElement<es.indra.portafirmasws.cws.ArchiveOptions> _returnDocumentsDocumentVal1ArchiveOptions = null;
            _returnDocumentsDocumentVal1.setArchiveOptions(_returnDocumentsDocumentVal1ArchiveOptions);
            _returnDocumentsDocument.add(_returnDocumentsDocumentVal1);
            _returnDocuments.getDocument().addAll(_returnDocumentsDocument);
            _return.setDocuments(_returnDocuments);
            _return.setVersion("Version-132266821");
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see es.indra.portafirmasws.cws.Cws#downloadFile(es.indra.portafirmasws.cws.DownloadFileRequest  downloadFileRequest )*
     */
    public es.indra.portafirmasws.cws.DownloadFileResponse downloadFile(DownloadFileRequest downloadFileRequest) { 
        LOG.info("Executing operation downloadFile");
        System.out.println(downloadFileRequest);
        try {
            es.indra.portafirmasws.cws.DownloadFileResponse _return = new es.indra.portafirmasws.cws.DownloadFileResponse();
            es.indra.portafirmasws.cws.Result _returnResult = new es.indra.portafirmasws.cws.Result();
            _returnResult.setCode(0);
            _returnResult.setMessage("Message1488299047");
            _return.setResult(_returnResult);
            es.indra.portafirmasws.cws.DownloadFileResponseDocument _returnDocument = new es.indra.portafirmasws.cws.DownloadFileResponseDocument();
            _returnDocument.setId(1152950982);
            es.indra.portafirmasws.cws.Files _returnDocumentFiles = new es.indra.portafirmasws.cws.Files();
            java.util.List<es.indra.portafirmasws.cws.File> _returnDocumentFilesFile = new java.util.ArrayList<es.indra.portafirmasws.cws.File>();
            _returnDocumentFiles.getFile().addAll(_returnDocumentFilesFile);
            _returnDocument.setFiles(_returnDocumentFiles);
            _return.setDocument(_returnDocument);
            _return.setVersion("Version-1720767591");
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see es.indra.portafirmasws.cws.Cws#listServerSigners(es.indra.portafirmasws.cws.ListServerSignersRequest  listServerSignersRequest )*
     */
    public es.indra.portafirmasws.cws.ListServerSignersResponse listServerSigners(ListServerSignersRequest listServerSignersRequest) { 
        LOG.info("Executing operation listServerSigners");
        System.out.println(listServerSignersRequest);
        try {
            es.indra.portafirmasws.cws.ListServerSignersResponse _return = new es.indra.portafirmasws.cws.ListServerSignersResponse();
            es.indra.portafirmasws.cws.Result _returnResult = new es.indra.portafirmasws.cws.Result();
            _returnResult.setCode(0);
            _returnResult.setMessage("Message-1329504480");
            _return.setResult(_returnResult);
            javax.xml.bind.JAXBElement<es.indra.portafirmasws.cws.ServerSigners> _returnServerSigners = null;
            _return.setServerSigners(_returnServerSigners);
            _return.setVersion("Version427522547");
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see es.indra.portafirmasws.cws.Cws#updateDocument(es.indra.portafirmasws.cws.UpdateRequest  updateRequest )*
     */
    public es.indra.portafirmasws.cws.UpdateResponse updateDocument(UpdateRequest updateRequest) { 
        LOG.info("Executing operation updateDocument");
        System.out.println(updateRequest);
        try {
            es.indra.portafirmasws.cws.UpdateResponse _return = new es.indra.portafirmasws.cws.UpdateResponse();
            es.indra.portafirmasws.cws.Result _returnResult = new es.indra.portafirmasws.cws.Result();
            _returnResult.setCode(0);
            _returnResult.setMessage("Message924129046");
            _return.setResult(_returnResult);
            es.indra.portafirmasws.cws.UpdateResponseDocument _returnDocument = new es.indra.portafirmasws.cws.UpdateResponseDocument();
            _returnDocument.setId(-107330012);
            _return.setDocument(_returnDocument);
            _return.setVersion("Version1535611174");
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see es.indra.portafirmasws.cws.Cws#listTypeDocuments(es.indra.portafirmasws.cws.ListTypeRequest  listTypeRequest )*
     */
    public es.indra.portafirmasws.cws.ListTypeResponse listTypeDocuments(ListTypeRequest listTypeRequest) { 
        LOG.info("Executing operation listTypeDocuments");
        System.out.println(listTypeRequest);
        try {
            es.indra.portafirmasws.cws.ListTypeResponse _return = new es.indra.portafirmasws.cws.ListTypeResponse();
            es.indra.portafirmasws.cws.Result _returnResult = new es.indra.portafirmasws.cws.Result();
            _returnResult.setCode(0);
            _returnResult.setMessage("Message-1749261973");
            _return.setResult(_returnResult);
            es.indra.portafirmasws.cws.TypeDocuments _returnTypes = new es.indra.portafirmasws.cws.TypeDocuments();
            java.util.List<es.indra.portafirmasws.cws.TypeDocument> _returnTypesType = new java.util.ArrayList<es.indra.portafirmasws.cws.TypeDocument>();
            es.indra.portafirmasws.cws.TypeDocument _returnTypesTypeVal1 = new es.indra.portafirmasws.cws.TypeDocument();
            _returnTypesTypeVal1.setId(-645280432);
            _returnTypesTypeVal1.setName("Name-1649474996");
            _returnTypesTypeVal1.setDescription("Description1759128554");
            _returnTypesType.add(_returnTypesTypeVal1);
            _returnTypes.getType().addAll(_returnTypesType);
            _return.setTypes(_returnTypes);
            _return.setLanguage("Language629285343");
            _return.setVersion("Version-72972819");
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see es.indra.portafirmasws.cws.Cws#deleteDocuments(es.indra.portafirmasws.cws.DeleteRequest  deleteRequest )*
     */
    public es.indra.portafirmasws.cws.DeleteResponse deleteDocuments(DeleteRequest deleteRequest) { 
        LOG.info("Executing operation deleteDocuments");
        System.out.println(deleteRequest);
        try {
            es.indra.portafirmasws.cws.DeleteResponse _return = new es.indra.portafirmasws.cws.DeleteResponse();
            es.indra.portafirmasws.cws.Result _returnResult = new es.indra.portafirmasws.cws.Result();
            _returnResult.setCode(0);
            _returnResult.setMessage("Message1715042142");
            _return.setResult(_returnResult);
            es.indra.portafirmasws.cws.DeleteResponseDocuments _returnDocuments = new es.indra.portafirmasws.cws.DeleteResponseDocuments();
            java.util.List<es.indra.portafirmasws.cws.DeleteResponseDocument> _returnDocumentsDocument = new java.util.ArrayList<es.indra.portafirmasws.cws.DeleteResponseDocument>();
            es.indra.portafirmasws.cws.DeleteResponseDocument _returnDocumentsDocumentVal1 = new es.indra.portafirmasws.cws.DeleteResponseDocument();
            _returnDocumentsDocumentVal1.setId(-830964324);
            _returnDocumentsDocument.add(_returnDocumentsDocumentVal1);
            _returnDocuments.getDocument().addAll(_returnDocumentsDocument);
            _return.setDocuments(_returnDocuments);
            _return.setVersion("Version1191230470");
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
