package es.indra.portafirmasws.cws;

import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;

/**
 * This class was generated by Apache CXF 3.0.0-milestone2
 * 2014-04-30T11:26:03.938+02:00
 * Generated source version: 3.0.0-milestone2
 * 
 */
@WebServiceClient(name = "CwsService", 
                  wsdlLocation = "file:/C:/Users/javierg/workspace_helium_30/z/WebContent/WEB-INF/cws.wsdl",
                  targetNamespace = "http://www.indra.es/portafirmasws/cws") 
public class CwsService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://www.indra.es/portafirmasws/cws", "CwsService");
    public final static QName CWS = new QName("http://www.indra.es/portafirmasws/cws", "CWS");
    static {
        URL url = null;
        try {
            url = new URL("file:/C:/Users/javierg/workspace_helium_30/z/WebContent/WEB-INF/cws.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(CwsService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/C:/Users/javierg/workspace_helium_30/z/WebContent/WEB-INF/cws.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public CwsService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public CwsService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CwsService() {
        super(WSDL_LOCATION, SERVICE);
    }

    /**
     *
     * @return
     *     returns Cws
     */
    @WebEndpoint(name = "CWS")
    public Cws getCWS() {
        return super.getPort(CWS, Cws.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Cws
     */
    @WebEndpoint(name = "CWS")
    public Cws getCWS(WebServiceFeature... features) {
        return super.getPort(CWS, Cws.class, features);
    }

}
