-------------------------------------------------------------------
-- #1314 Afegir dades d'enviament als interessats per a les notificacions postals
-------------------------------------------------------------------

-- Oracle
-- El NIF pot ser null per administracions públiques
ALTER TABLE HELIUM.HEL_INTERESSAT MODIFY NIF VARCHAR2(9) NULL;


ALTER TABLE HEL_INTERESSAT ADD ENTREGAPOSTAL NUMBER(1,0) DEFAULT 0 NOT NULL;
ALTER TABLE HEL_INTERESSAT ADD ENTREGATIPUS NUMBER(10,0);
ALTER TABLE HEL_INTERESSAT ADD LINIA1 VARCHAR2(50 CHAR);
ALTER TABLE HEL_INTERESSAT ADD LINIA2 VARCHAR2(50 CHAR);
ALTER TABLE HEL_INTERESSAT ADD ENTREGADEH NUMBER(1,0) DEFAULT 0 NOT NULL;
ALTER TABLE HEL_INTERESSAT ADD ENTREGADEHOBLIGAT NUMBER(1,0) DEFAULT 0 NOT NULL;
ALTER TABLE HEL_INTERESSAT ADD CODIPOSTAL VARCHAR2(5 CHAR);
ALTER TABLE HEL_INTERESSAT ADD DIR3CODI VARCHAR2(9 CHAR);

-- Actualitza el codi Dir3 als interessats de tipus adminstració
UPDATE HEL_INTERESSAT i SET i.DIR3CODI = NIF, i.NIF = NULL WHERE i.DIR3CODI IS NULL AND i.TIPUS = 0;

-- Postgres
-- El NIF pot ser null per administracions públiques
ALTER TABLE HELIUM.HEL_INTERESSAT MODIFY NIF VARCHAR2(9) NULL;

ALTER TABLE HEL_INTERESSAT ADD ENTREGAPOSTAL BOOLEAN DEFAULT FALSE NOT NULL;
ALTER TABLE HEL_INTERESSAT ADD ENTREGATIPUS INTEGER;
ALTER TABLE HEL_INTERESSAT ADD LINIA1 VARCHAR(50);
ALTER TABLE HEL_INTERESSAT ADD LINIA2 VARCHAR(50);
ALTER TABLE HEL_INTERESSAT ADD ENTREGADEH BOOLEAN DEFAULT FALSE NOT NULL;
ALTER TABLE HEL_INTERESSAT ADD ENTREGADEHOBLIGAT BOOLEAN DEFAULT FALSE NOT NULL;
ALTER TABLE HEL_INTERESSAT ADD CODIPOSTAL VARCHAR(5);
ALTER TABLE HEL_INTERESSAT ADD DIR3CODI VARCHAR(9 CHAR);

-- Actualitza el codi Dir3 als interessats de tipus adminstració
UPDATE HEL_INTERESSAT i SET i.DIR3CODI = NIF, i.NIF = NULL WHERE i.DIR3CODI IS NULL AND i.TIPUS = 0;
