-- #1335 Helium com a backoffice de Distribucio

-- ORACLE

-- Noves columnes a la taula de tipus d'expedient
ALTER TABLE HEL_EXPEDIENT_TIPUS ADD DISTRIBUCIO_ACTIU NUMBER(1) DEFAULT 0;
ALTER TABLE HEL_EXPEDIENT_TIPUS ADD DISTRIBUCIO_CODI_PROCEDIMENT VARCHAR2(200);

-- Noves taules per les anotacions
CREATE TABLE HEL_ANOTACIO (
  ID 						NUMBER(19) 		NOT NULL,
  EXPEDIENT_TIPUS_ID		NUMBER(19) ,
  EXPEDIENT_ID				NUMBER(19) ,
  DITRIBUCIO_ID				VARCHAR2(200) NOT NULL,
  ESTAT						NUMBER(19)               NOT NULL,
  DATA_RECEPCIO				TIMESTAMP(6) NOT NULL, 
  DATA_PROCESSAMENT			TIMESTAMP(6), 
  REBUIG_MOTIU				VARCHAR2(500),
  APLICACIO_CODI 			VARCHAR2(20), 
  APLICACIO_VERSIO 			VARCHAR2(15), 
  ASSUMPTE_CODI_CODI 		VARCHAR2(16), 
  ASSUMPTE_CODI_DESC 		VARCHAR2(100), 
  ASSUMPTE_TIPUS_CODI		VARCHAR2(16), 
  ASSUMPTE_TIPUS_DESC 		VARCHAR2(100), 
  DATA 						TIMESTAMP(6) 	NOT NULL, 
  DOC_FISICA_CODI 			VARCHAR2(1), 
  DOC_FISICA_DESC 			VARCHAR2(100), 
  ENTITAT_CODI 				VARCHAR2(21) 	NOT NULL, 
  ENTITAT_DESC 				VARCHAR2(100), 
  EXPEDIENT_NUMERO 			VARCHAR2(80), 
  EXPOSA 					VARCHAR2(4000), 
  EXTRACTE					VARCHAR2(240),
  PROCEDIMENT_CODI			VARCHAR2(20),
  IDENTIFICADOR 			VARCHAR2(100) 	NOT NULL, 
  IDIOMA_CODI 				VARCHAR2(2) 	NOT NULL, 
  IDIOMA_DESC 				VARCHAR2(100), 
  LLIBRE_CODI 				VARCHAR2(4) 	NOT NULL, 
  LLIBRE_DESC 				VARCHAR2(100), 
  OBSERVACIONS 				VARCHAR2(50), 
  OFICINA_CODI 				VARCHAR2(21) 	NOT NULL, 
  OFICINA_DESC 				VARCHAR2(100), 
  ORIGEN_DATA 				TIMESTAMP(6), 
  ORIGEN_REGISTRE_NUM 		VARCHAR2(80), 
  REF_EXTERNA 				VARCHAR2(16), 
  SOLICITA 					VARCHAR2(4000), 
  TRANSPORT_NUM 			VARCHAR2(20), 
  TRANSPORT_TIPUS_CODI 		VARCHAR2(2), 
  TRANSPORT_TIPUS_DESC 		VARCHAR2(100), 
  USUARI_CODI 				VARCHAR2(20), 
  USUARI_NOM 				VARCHAR2(80), 
  DESTI_CODI 				VARCHAR2(21) 	NOT NULL, 
  DESTI_DESCRIPCIO 			VARCHAR2(100)
);


CREATE TABLE HEL_ANOTACIO_ANNEX (
	ID 						NUMBER(19) 		NOT NULL, 
	CONTINGUT BLOB,
	FIRMA_CONTINGUT BLOB,
	FIRMA_PERFIL VARCHAR2(4),
	FIRMA_TAMANY NUMBER(10),
	FIRMA_TIPUS VARCHAR2(4),
	NOM VARCHAR2(80) NOT NULL,
	FIRMA_NOM VARCHAR2(80),
	NTI_FECHA_CAPTURA TIMESTAMP(6) NOT NULL,
	NTI_ORIGEN VARCHAR2(20) NOT NULL,
	NTI_TIPO_DOC VARCHAR2(20) NOT NULL,
	OBSERVACIONS VARCHAR2(50),
	SICRES_TIPO_DOC VARCHAR2(20)  NOT NULL,
	SICRES_VALIDEZ_DOC VARCHAR2(30),
	TAMANY NUMBER(10) NOT NULL,
	TIPUS_MIME VARCHAR2(30),
	TITOL VARCHAR2(200) NOT NULL,
	UUID VARCHAR2(100),
	ANOTACIO_ID NUMBER(19) NOT NULL,
	ESTAT VARCHAR2(20),
	ERROR VARCHAR2(4000),
	NTI_ESTADO_ELABORACIO VARCHAR2(50) NOT NULL
);


CREATE TABLE HEL_ANOTACIO_INTERESSAT 
  ( 
     ID                  NUMBER(19) NOT NULL, 
     ADRESA              VARCHAR2(160), 
     CANAL               VARCHAR2(30), 
     CP                  VARCHAR2(5), 
     DOC_NUMERO          VARCHAR2(17), 
     DOC_TIPUS           VARCHAR2(15), 
     EMAIL               VARCHAR2(160), 
     LLINATGE1           VARCHAR2(30), 
     LLINATGE2           VARCHAR2(30), 
     MUNICIPI_CODI       VARCHAR2(100), 
     NOM                 VARCHAR2(30), 
     OBSERVACIONS        VARCHAR2(160), 
     PAIS_CODI           VARCHAR2(4), 
     PROVINCIA_CODI      VARCHAR2(100), 
     RAO_SOCIAL          VARCHAR2(80), 
     TELEFON             VARCHAR2(20), 
     TIPUS               VARCHAR2(40) NOT NULL, 
     REPRESENTANT_ID     NUMBER(19), 
     ANOTACIO_ID         NUMBER(19), 
     PAIS                VARCHAR2(200), 
     PROVINCIA           VARCHAR2(200), 
     MUNICIPI            VARCHAR2(200), 
     ORGAN_CODI          VARCHAR(9)
  ); 

ALTER TABLE HEL_ANOTACIO ADD (
  CONSTRAINT HEL_ANOTACIO_PK PRIMARY KEY (ID));
  
ALTER TABLE HEL_ANOTACIO_ANNEX ADD (
  CONSTRAINT HEL_ANOTACIO_ANNEX_PK PRIMARY KEY (ID));
  
ALTER TABLE HEL_ANOTACIO_INTERESSAT ADD (
  CONSTRAINT HEL_ANOTACIO_INTERESSAT_PK PRIMARY KEY (ID));  
  
  
ALTER TABLE HEL_ANOTACIO_INTERESSAT ADD (
  CONSTRAINT HEL_ANOTACIO_INTERESSAT_FK FOREIGN KEY (ANOTACIO_ID) 
    REFERENCES HEL_ANOTACIO (ID));
        
ALTER TABLE HEL_ANOTACIO_ANNEX ADD (
  CONSTRAINT HEL_ANOTACIO_ANNEX_FK FOREIGN KEY (ANOTACIO_ID) 
    REFERENCES HEL_ANOTACIO (ID));    
    
ALTER TABLE HEL_ANOTACIO ADD (
  CONSTRAINT HEL_ET_ANOTACIO_FK FOREIGN KEY (EXPEDIENT_TIPUS_ID) 
    REFERENCES HEL_EXPEDIENT_TIPUS (ID));    

ALTER TABLE HEL_ANOTACIO ADD (
  CONSTRAINT HEL_EXPEDIENT_ANOTACIO_FK FOREIGN KEY (EXPEDIENT_ID) 
    REFERENCES HEL_EXPEDIENT (ID));    


CREATE INDEX HEL_ANOTACIO_ANNEX_FK_I ON HEL_ANOTACIO_ANNEX(ANOTACIO_ID);
CREATE INDEX HEL_ANOTACIO_INTER_FK_I ON HEL_ANOTACIO_INTERESSAT(ANOTACIO_ID);
CREATE INDEX HEL_REPRESENTANT_ANOTACIO_FK_I ON HEL_ANOTACIO_INTERESSAT(REPRESENTANT_ID);
CREATE INDEX HEL_ANOTACIO_EXPEDIENT_FK_I ON HEL_ANOTACIO(EXPEDIENT_ID);
CREATE INDEX HEL_ANOTACIO_ET_FK_I ON HEL_ANOTACIO(EXPEDIENT_TIPUS_ID);

GRANT SELECT, UPDATE, INSERT, DELETE ON HEL_ANOTACIO TO WWW_HELIUM;
GRANT SELECT, UPDATE, INSERT, DELETE ON HEL_ANOTACIO_ANNEX TO WWW_HELIUM;
GRANT SELECT, UPDATE, INSERT, DELETE ON HEL_ANOTACIO_INTERESSAT TO WWW_HELIUM;


-- POSTGRES

-- Noves columnes a la taula de tipus d'expedient
ALTER TABLE HEL_EXPEDIENT_TIPUS ADD DISTRIBUCIO_ACTIU BOOLEAN DEFAULT FALSE;
ALTER TABLE HEL_EXPEDIENT_TIPUS ADD DISTRIBUCIO_CODI_PROCEDIMENT VARCHAR(200);

-- Noves taules per les anotacions
CREATE TABLE HEL_ANOTACIO (
  ID 						BIGINT 		NOT NULL, 
  EXPEDIENT_TIPUS_ID					BIGINT 		NOT NULL, 
  EXPEDIENT_ID				BIGINT, 
  DITRIBUCIO_ID				character varying (200) NOT NULL,
  ESTAT						BIGINT               NOT NULL,
  DATA_RECEPCIO				timestamp without time zone NOT NULL, 
  DATA_PROCESSAMENT			timestamp without time zone, 
  REBUIG_MOTIU				character varying (500),
  APLICACIO_CODI 			character varying (20), 
  APLICACIO_VERSIO 			character varying (15), 
  ASSUMPTE_CODI_CODI 		character varying (16), 
  ASSUMPTE_CODI_DESC 		character varying (100), 
  ASSUMPTE_TIPUS_CODI		character varying (16) 	NOT NULL, 
  ASSUMPTE_TIPUS_DESC 		character varying (100), 
  DATA 						timestamp without time zone 	NOT NULL, 
  DOC_FISICA_CODI 			character varying (1), 
  DOC_FISICA_DESC 			character varying (100), 
  ENTITAT_CODI 				character varying (21) 	NOT NULL, 
  ENTITAT_DESC 				character varying (100), 
  EXPEDIENT_NUMERO 			character varying (80), 
  EXPOSA 					character varying (4000), 
  EXTRACTE					character varying (240),
  PROCEDIMENT_CODI			character varying (20),
  IDENTIFICADOR 			character varying (100) 	NOT NULL, 
  IDIOMA_CODI 				character varying (2) 	NOT NULL, 
  IDIOMA_DESC 				character varying (100), 
  LLIBRE_CODI 				character varying (4) 	NOT NULL, 
  LLIBRE_DESC 				character varying (100), 
  OBSERVACIONS 				character varying (50), 
  OFICINA_CODI 				character varying (21) 	NOT NULL, 
  OFICINA_DESC 				character varying (100), 
  ORIGEN_DATA 				timestamp without time zone, 
  ORIGEN_REGISTRE_NUM 		character varying (80), 
  REF_EXTERNA 				character varying (16), 
  SOLICITA 					character varying (4000), 
  TRANSPORT_NUM 			character varying (20), 
  TRANSPORT_TIPUS_CODI 		character varying (2), 
  TRANSPORT_TIPUS_DESC 		character varying (100), 
  USUARI_CODI 				character varying (20), 
  USUARI_NOM 				character varying (80), 
  DESTI_CODI 				character varying (21) 	NOT NULL, 
  DESTI_DESCRIPCIO 			character varying (100)
);


CREATE TABLE HEL_ANOTACIO_ANNEX (
	ID 						BIGINT 		NOT NULL, 
	CONTINGUT BLOB,
	FIRMA_CONTINGUT BLOB,
	FIRMA_PERFIL character varying (4),
	FIRMA_TAMANY integer,
	FIRMA_TIPUS character varying (4),
	NOM character varying (80) NOT NULL,
	FIRMA_NOM character varying(80),
	NTI_FECHA_CAPTURA timestamp without time zone NOT NULL,
	NTI_ORIGEN character varying (20) NOT NULL,
	NTI_TIPO_DOC character varying (20) NOT NULL,
	OBSERVACIONS character varying (50),
	SICRES_TIPO_DOC character varying (20)  NOT NULL,
	SICRES_VALIDEZ_DOC character varying (30),
	TAMANY integer NOT NULL,
	TIPUS_MIME character varying (30),
	TITOL character varying (200) NOT NULL,
	UUID character varying (100),
	ANOTACIO_ID BIGINT NOT NULL,
	ESTAT character varying (20),
	ERROR character varying (4000),
	NTI_ESTADO_ELABORACIO character varying(50) NOT NULL
);


CREATE TABLE HEL_ANOTACIO_INTERESSAT (
	ID 						BIGINT 		NOT NULL, 
	ADRESA character varying (160),
	CANAL character varying (30),
	CP character varying (5),
	DOC_NUMERO character varying (17),
	DOC_TIPUS character varying (15),
	EMAIL character varying (160),
	LLINATGE1 character varying (30),
	LLINATGE2 character varying (30),
	MUNICIPI_CODI character varying (100),
	NOM character varying (30),
	OBSERVACIONS character varying (160),
	PAIS_CODI character varying (4),
	PROVINCIA_CODI character varying (100),
	RAO_SOCIAL character varying (80),
	TELEFON character varying (20),
	TIPUS character varying (40) NOT NULL,
	REPRESENTANT_ID BIGINT,
	ANOTACIO_ID BIGINT,
	PAIS character varying(200),
	PROVINCIA character varying(200),
	MUNICIPI character varying(200),	
	ORGAN_CODI CHARACTER VARYING(9)
);

ALTER TABLE ONLY HEL_ANOTACIO ADD CONSTRAINT HEL_ANOTACIO_PK PRIMARY KEY (ID);
ALTER TABLE ONLY HEL_ANOTACIO_ANNEX ADD CONSTRAINT HEL_ANOTACIO_ANNEX_PK PRIMARY KEY (ID);
ALTER TABLE ONLY HEL_ANOTACIO_INTERESSAT ADD  CONSTRAINT HEL_ANOTACIO_INTERESSAT_PK PRIMARY KEY (ID);  
  
ALTER TABLE HEL_ANOTACIO_INTERESSAT ADD CONSTRAINT HEL_ANOTACIO_INTERESSAT_FK FOREIGN KEY (ANOTACIO_ID) REFERENCES HEL_ANOTACIO (ID);
ALTER TABLE HEL_ANOTACIO_ANNEX ADD CONSTRAINT HEL_ANOTACIO_ANNEX_FK FOREIGN KEY (ANOTACIO_ID) REFERENCES HEL_ANOTACIO (ID);    
ALTER TABLE HEL_ANOTACIO ADD CONSTRAINT HEL_ET_ANOTACIO_FK FOREIGN KEY (EXPEDIENT_TIPUS_ID) REFERENCES HEL_EXPEDIENT_TIPUS (ID);
ALTER TABLE HEL_ANOTACIO ADD CONSTRAINT HEL_EXPEDIENT_ANOTACIO_FK FOREIGN KEY (EXPEDIENT_ID) REFERENCES HEL_EXPEDIENT (ID);

CREATE INDEX HEL_ANOTACIO_ANNEX_FK_I ON HEL_ANOTACIO_ANNEX(ANOTACIO_ID);
CREATE INDEX HEL_ANOTACIO_INTER_FK_I ON HEL_ANOTACIO_INTERESSAT(ANOTACIO_ID);
CREATE INDEX HEL_REPRESENTANT_ANOTACIO_FK_I ON HEL_ANOTACIO_INTERESSAT(REPRESENTANT_ID);
CREATE INDEX HEL_ANOTACIO_EXPEDIENT_FK_I ON HEL_ANOTACIO(EXPEDIENT_ID);
CREATE INDEX HEL_ANOTACIO_ET_FK_I ON HEL_ANOTACIO(EXPEDIENT_TIPUS_ID);