-- #1593 Assenyalar documents amb firma invàlida o estat esborrany provinents de Distribucio

ALTER TABLE HEL_ANOTACIO_ANNEX ADD DOCUMENT_VALID NUMBER(1);
ALTER TABLE HEL_ANOTACIO_ANNEX ADD DOCUMENT_ERROR VARCHAR2(1000);
ALTER TABLE HEL_ANOTACIO_ANNEX ADD ARXIU_ESTAT VARCHAR2(20);

ALTER TABLE HEL_DOCUMENT_STORE ADD DOCUMENT_VALID NUMBER(1);
ALTER TABLE HEL_DOCUMENT_STORE ADD DOCUMENT_ERROR VARCHAR2(1000);