--------------------------------------------------------
-- 1164 Integració amb NOTIB
--------------------------------------------------------

ALTER TABLE HEL_EXPEDIENT_TIPUS ADD NOTIB_ACTIU NUMBER(1);
UPDATE HEL_EXPEDIENT_TIPUS SET NOTIB_ACTIU = 0;
ALTER TABLE HEL_EXPEDIENT_TIPUS ADD NOTIB_SEU_UNITATADMIN VARCHAR2(100);
ALTER TABLE HEL_EXPEDIENT_TIPUS ADD NOTIB_SEU_OFICINA VARCHAR2(100);
ALTER TABLE HEL_EXPEDIENT_TIPUS ADD NOTIB_SEU_LLIBRE VARCHAR2(100);
ALTER TABLE HEL_EXPEDIENT_TIPUS ADD NOTIB_SEU_ORGAN VARCHAR2(100);
ALTER TABLE HEL_EXPEDIENT_TIPUS ADD NOTIB_SEU_IDIOMA VARCHAR2(10);
ALTER TABLE HEL_EXPEDIENT_TIPUS ADD NOTIB_AVISTITOL VARCHAR2(100);
ALTER TABLE HEL_EXPEDIENT_TIPUS ADD NOTIB_AVISTEXT VARCHAR2(1024);
ALTER TABLE HEL_EXPEDIENT_TIPUS ADD NOTIB_AVISTEXTSMS VARCHAR2(200);
ALTER TABLE HEL_EXPEDIENT_TIPUS ADD NOTIB_OFICITITOL VARCHAR2(256);
ALTER TABLE HEL_EXPEDIENT_TIPUS ADD NOTIB_OFICITEXT VARCHAR2(1024);

ALTER TABLE HEL_DOCUMENT ADD NOTIFICABLE NUMBER(1);
UPDATE HEL_DOCUMENT SET NOTIFICABLE = 0;