-------------------------------------------------------------------
-- #1098 Error esborrant versions de definicions de procés
-- Modifica les constraints de claus foràrines de jbpm per esborrar en cascada
-------------------------------------------------------------------

ALTER TABLE JBPM_SWIMLANE DROP CONSTRAINT FK_SWL_ASSDEL;

ALTER TABLE JBPM_SWIMLANE ADD
  CONSTRAINT FK_SWL_ASSDEL 
 FOREIGN KEY (ASSIGNMENTDELEGATION_) 
 REFERENCES JBPM_DELEGATION (ID_)
 ON DELETE CASCADE;

-------------------------------------------------------------------
-- Metadades Nti
-------------------------------------------------------------------
ALTER TABLE HEL_DOCUMENT ADD (NTI_TIPO_DOC VARCHAR2(32 CHAR));
ALTER TABLE HEL_DOCUMENT ADD (NTI_TIPO_FIRMA VARCHAR2(64 CHAR));
ALTER TABLE HEL_DOCUMENT ADD (NTI_VALOR_CSV VARCHAR2(128 CHAR));
ALTER TABLE HEL_DOCUMENT ADD (NTI_DEFINICION_GENERACION_CSV VARCHAR2(128 CHAR));

ALTER TABLE HEL_DOCUMENT_STORE ADD (NTI_VERSIO VARCHAR2(16 CHAR));
ALTER TABLE HEL_DOCUMENT_STORE ADD (NTI_IDENTIFICADOR VARCHAR2(107 CHAR));
ALTER TABLE HEL_DOCUMENT_STORE ADD (NTI_ORGANO VARCHAR2(64 CHAR));
ALTER TABLE HEL_DOCUMENT_STORE ADD (NTI_ORIGEN VARCHAR2(32 CHAR));
ALTER TABLE HEL_DOCUMENT_STORE ADD (NTI_ESTADO_ELAB VARCHAR2(32 CHAR));
ALTER TABLE HEL_DOCUMENT_STORE ADD (NTI_NOM_FORMAT VARCHAR2(16 CHAR));
ALTER TABLE HEL_DOCUMENT_STORE ADD (NTI_TIPO_DOC VARCHAR2(32 CHAR));
ALTER TABLE HEL_DOCUMENT_STORE ADD (NTI_TIPO_FIRMA VARCHAR2(64 CHAR));
ALTER TABLE HEL_DOCUMENT_STORE ADD (NTI_VALOR_CSV VARCHAR2(128 CHAR));
ALTER TABLE HEL_DOCUMENT_STORE ADD (NTI_DEFINICION_GENERACION_CSV VARCHAR2(128 CHAR));
ALTER TABLE HEL_DOCUMENT_STORE ADD (NTI_ID_DOC_ORIGEN VARCHAR2(107 CHAR));
ALTER TABLE HEL_DOCUMENT_STORE ADD (NTI_ACTIVO NUMBER(1) DEFAULT 0);


ALTER TABLE HEL_EXPEDIENT ADD (NTI_ACTIVO NUMBER(1) DEFAULT 0);
ALTER TABLE HEL_EXPEDIENT ADD (NTI_VERSIO VARCHAR2(16 CHAR));
ALTER TABLE HEL_EXPEDIENT ADD (NTI_ORGANO VARCHAR2(64 CHAR));
ALTER TABLE HEL_EXPEDIENT ADD (NTI_CLASIFICACION VARCHAR2(64 CHAR));
ALTER TABLE HEL_EXPEDIENT ADD (NTI_IDENTIFICADOR VARCHAR2(107 CHAR));
ALTER TABLE HEL_EXPEDIENT ADD (NTI_TIPO_FIRMA VARCHAR2(64 CHAR));
ALTER TABLE HEL_EXPEDIENT ADD (NTI_VALOR_CSV VARCHAR2(128 CHAR));
ALTER TABLE HEL_EXPEDIENT ADD (NTI_DEFINICION_GENERACION_CSV VARCHAR2(128 CHAR));

ALTER TABLE HEL_EXPEDIENT_TIPUS ADD (NTI_ORGANO VARCHAR2(64 CHAR));
ALTER TABLE HEL_EXPEDIENT_TIPUS ADD (NTI_CLASIFICACION VARCHAR2(64 CHAR));
ALTER TABLE HEL_EXPEDIENT_TIPUS ADD (NTI_TIPO_FIRMA VARCHAR2(64 CHAR));
ALTER TABLE HEL_EXPEDIENT_TIPUS ADD (NTI_VALOR_CSV VARCHAR2(128 CHAR));
ALTER TABLE HEL_EXPEDIENT_TIPUS ADD (NTI_DEFINICION_GENERACION_CSV VARCHAR2(128 CHAR));
ALTER TABLE HEL_EXPEDIENT_TIPUS ADD (NTI_ACTIVO NUMBER(1) DEFAULT 0);

