-- #1428 No funciona "reintentar processament" pels annexos de les anotacions de Distribucio 
-- Afegir HEL_ANOTACIO_ANNEX.DOCUMENT_STORE_ID per quan l'annex s'incorpora a l'expedient
-- Incrementa les columnes HEL_ANOTACIO_ANNEX FIRMA_TIPUS i FIRMA_PEFIL a VARCHAR2(30 CHAR)

ALTER TABLE HEL_ANOTACIO_ANNEX ADD DOCUMENT_STORE_ID NUMBER(19);

ALTER TABLE HEL_ANOTACIO_ANNEX MODIFY (FIRMA_TIPUS VARCHAR2(30 CHAR));
ALTER TABLE HEL_ANOTACIO_ANNEX MODIFY (FIRMA_PERFIL VARCHAR2(30 CHAR));