-- #1335 Helium com a backoffice de Distribucio

-- Noves columnes a la taula de tipus d'expedient
ALTER TABLE HEL_EXPEDIENT_TIPUS ADD DISTR_ACTIU NUMBER(1) DEFAULT 0;
ALTER TABLE HEL_EXPEDIENT_TIPUS ADD DISTR_CODI_PROCEDIMENT VARCHAR2(200);
ALTER TABLE HEL_EXPEDIENT_TIPUS ADD DISTR_CODI_ASSUMPTE VARCHAR2(20);

-- Noves taules per les anotacions
CREATE TABLE HEL_ANOTACIO (
  ID 						NUMBER(19) 		NOT NULL,
  EXPEDIENT_TIPUS_ID		NUMBER(19) ,
  EXPEDIENT_ID				NUMBER(19) ,
  DITRIBUCIO_ID				VARCHAR2(80) NOT NULL,
  DITRIBUCIO_CLAU_ACCES		VARCHAR2(200) NOT NULL,
  ESTAT						NUMBER(19)               NOT NULL,
  DATA_RECEPCIO				TIMESTAMP(6) NOT NULL, 
  DATA_PROCESSAMENT			TIMESTAMP(6), 
  REBUIG_MOTIU				VARCHAR2(500),
  APLICACIO_CODI 			VARCHAR2(20), 
  APLICACIO_VERSIO 			VARCHAR2(15), 
  ASSUMPTE_CODI_CODI 		VARCHAR2(16), 
  ASSUMPTE_CODI_DESC 		VARCHAR2(100), 
  ASSUMPTE_TIPUS_CODI		VARCHAR2(16), 
  ASSUMPTE_TIPUS_DESC 		VARCHAR2(100), 
  DATA 						TIMESTAMP(6) 	NOT NULL, 
  DOC_FISICA_CODI 			VARCHAR2(1), 
  DOC_FISICA_DESC 			VARCHAR2(100), 
  ENTITAT_CODI 				VARCHAR2(21) 	NOT NULL, 
  ENTITAT_DESC 				VARCHAR2(100), 
  EXPEDIENT_NUMERO 			VARCHAR2(80), 
  EXPOSA 					CLOB, 
  EXTRACTE					VARCHAR2(240),
  PROCEDIMENT_CODI			VARCHAR2(20),
  IDENTIFICADOR 			VARCHAR2(100) 	NOT NULL, 
  IDIOMA_CODI 				VARCHAR2(2) 	NOT NULL, 
  IDIOMA_DESC 				VARCHAR2(100), 
  LLIBRE_CODI 				VARCHAR2(4) 	NOT NULL, 
  LLIBRE_DESC 				VARCHAR2(100), 
  OBSERVACIONS 				VARCHAR2(50), 
  OFICINA_CODI 				VARCHAR2(21) 	NOT NULL, 
  OFICINA_DESC 				VARCHAR2(100), 
  ORIGEN_DATA 				TIMESTAMP(6), 
  ORIGEN_REGISTRE_NUM 		VARCHAR2(80), 
  REF_EXTERNA 				VARCHAR2(16), 
  SOLICITA 					CLOB, 
  TRANSPORT_NUM 			VARCHAR2(20), 
  TRANSPORT_TIPUS_CODI 		VARCHAR2(2), 
  TRANSPORT_TIPUS_DESC 		VARCHAR2(100), 
  USUARI_CODI 				VARCHAR2(20), 
  USUARI_NOM 				VARCHAR2(80), 
  DESTI_CODI 				VARCHAR2(21) 	NOT NULL, 
  DESTI_DESCRIPCIO 			VARCHAR2(100)
);


CREATE TABLE HEL_ANOTACIO_ANNEX (
	ID 						NUMBER(19) 		NOT NULL, 
	CONTINGUT BLOB,
	FIRMA_CONTINGUT BLOB,
	FIRMA_PERFIL VARCHAR2(4),
	FIRMA_TAMANY NUMBER(10),
	FIRMA_TIPUS VARCHAR2(4),
	NOM VARCHAR2(80) NOT NULL,
	FIRMA_NOM VARCHAR2(80),
	NTI_FECHA_CAPTURA TIMESTAMP(6) NOT NULL,
	NTI_ORIGEN VARCHAR2(20) NOT NULL,
	NTI_TIPO_DOC VARCHAR2(20) NOT NULL,
	OBSERVACIONS VARCHAR2(50),
	SICRES_TIPO_DOC VARCHAR2(20),
	SICRES_VALIDEZ_DOC VARCHAR2(30),
	TAMANY NUMBER(10) NOT NULL,
	TIPUS_MIME VARCHAR2(255),
	TITOL VARCHAR2(200) NOT NULL,
	UUID VARCHAR2(100),
	ANOTACIO_ID NUMBER(19) NOT NULL,
	ESTAT VARCHAR2(20),
	ERROR VARCHAR2(4000),
	NTI_ESTADO_ELABORACIO VARCHAR2(50) NOT NULL
);


CREATE TABLE HEL_ANOTACIO_INTERESSAT 
  ( 
     ID                  NUMBER(19) NOT NULL, 
     ADRESA              VARCHAR2(160), 
     CANAL               VARCHAR2(30), 
     CP                  VARCHAR2(5), 
     DOC_NUMERO          VARCHAR2(17), 
     DOC_TIPUS           VARCHAR2(15), 
     EMAIL               VARCHAR2(160), 
     LLINATGE1           VARCHAR2(30), 
     LLINATGE2           VARCHAR2(30), 
     MUNICIPI_CODI       VARCHAR2(100), 
     NOM                 VARCHAR2(30), 
     OBSERVACIONS        VARCHAR2(160), 
     PAIS_CODI           VARCHAR2(4), 
     PROVINCIA_CODI      VARCHAR2(100), 
     RAO_SOCIAL          VARCHAR2(80), 
     TELEFON             VARCHAR2(20), 
     TIPUS               VARCHAR2(40) NOT NULL, 
     REPRESENTANT_ID     NUMBER(19), 
     ANOTACIO_ID         NUMBER(19), 
     PAIS                VARCHAR2(200), 
     PROVINCIA           VARCHAR2(200), 
     MUNICIPI            VARCHAR2(200), 
     ORGAN_CODI          VARCHAR(9)
  ); 

ALTER TABLE HEL_ANOTACIO ADD (
  CONSTRAINT HEL_ANOTACIO_PK PRIMARY KEY (ID));
  
ALTER TABLE HEL_ANOTACIO_ANNEX ADD (
  CONSTRAINT HEL_ANOTACIO_ANNEX_PK PRIMARY KEY (ID));
  
ALTER TABLE HEL_ANOTACIO_INTERESSAT ADD (
  CONSTRAINT HEL_ANOTACIO_INTERESSAT_PK PRIMARY KEY (ID));  
  
  
ALTER TABLE HEL_ANOTACIO_INTERESSAT ADD (
  CONSTRAINT HEL_ANOTACIO_INTERESSAT_FK FOREIGN KEY (ANOTACIO_ID) 
    REFERENCES HEL_ANOTACIO (ID));
        
ALTER TABLE HEL_ANOTACIO_ANNEX ADD (
  CONSTRAINT HEL_ANOTACIO_ANNEX_FK FOREIGN KEY (ANOTACIO_ID) 
    REFERENCES HEL_ANOTACIO (ID));    
    
ALTER TABLE HEL_ANOTACIO ADD (
  CONSTRAINT HEL_ET_ANOTACIO_FK FOREIGN KEY (EXPEDIENT_TIPUS_ID) 
    REFERENCES HEL_EXPEDIENT_TIPUS (ID));    

ALTER TABLE HEL_ANOTACIO ADD (
  CONSTRAINT HEL_EXPEDIENT_ANOTACIO_FK FOREIGN KEY (EXPEDIENT_ID) 
    REFERENCES HEL_EXPEDIENT (ID));    


CREATE INDEX HEL_ANOTACIO_ANNEX_FK_I ON HEL_ANOTACIO_ANNEX(ANOTACIO_ID);
CREATE INDEX HEL_ANOTACIO_INTER_FK_I ON HEL_ANOTACIO_INTERESSAT(ANOTACIO_ID);
CREATE INDEX HEL_REPRESENTANT_ANOTACIO_FK_I ON HEL_ANOTACIO_INTERESSAT(REPRESENTANT_ID);
CREATE INDEX HEL_ANOTACIO_EXPEDIENT_FK_I ON HEL_ANOTACIO(EXPEDIENT_ID);
CREATE INDEX HEL_ANOTACIO_ET_FK_I ON HEL_ANOTACIO(EXPEDIENT_TIPUS_ID);

GRANT SELECT, UPDATE, INSERT, DELETE ON HEL_ANOTACIO TO WWW_HELIUM;
GRANT SELECT, UPDATE, INSERT, DELETE ON HEL_ANOTACIO_ANNEX TO WWW_HELIUM;
GRANT SELECT, UPDATE, INSERT, DELETE ON HEL_ANOTACIO_INTERESSAT TO WWW_HELIUM;

