CREATE TABLE HEL_INTERESSAT
(
	ID					NUMBER(19)               NOT NULL,
	CODI                VARCHAR2(64 CHAR)        NOT NULL,
	NIF					VARCHAR2(9 CHAR)		 NOT NULL,
	NOM					VARCHAR2(255 CHAR) 		 NOT NULL,
	LLINATGE1			VARCHAR2(255 CHAR),
	LLINATGE2			VARCHAR2(255 CHAR),
	TIPUS				NUMBER(10),
	EMAIL				VARCHAR2(255 CHAR),
	TELEFON				VARCHAR2(16 CHAR),
	EXPEDIENT_ID  		NUMBER(19)
);

 ALTER TABLE HEL_INTERESSAT ADD (
  CONSTRAINT HEL_EXPEDIENT_INTERESSAT_FK FOREIGN KEY (EXPEDIENT_ID) 
 REFERENCES HEL_EXPEDIENT (ID));
 
 
 