ALTER TABLE HEL_DOCUMENT ADD (NTI_SERIEDOCUMENTAL VARCHAR2(64 CHAR));
ALTER TABLE HEL_DOCUMENT_STORE ADD (NTI_SERIEDOCUMENTAL VARCHAR2(64 CHAR));
ALTER TABLE HEL_EXPEDIENT ADD (NTI_SERIEDOCUMENTAL VARCHAR2(64 CHAR));
ALTER TABLE HEL_EXPEDIENT_TIPUS ADD (NTI_SERIEDOCUMENTAL VARCHAR2(64 CHAR));