
--------------------------------------------------------
-- 1173 Integració amb l'arxiu digital de la CAIB
--------------------------------------------------------
ALTER TABLE HEL_EXPEDIENT_TIPUS DROP COLUMN NTI_ACTIVO;
ALTER TABLE HEL_EXPEDIENT_TIPUS DROP COLUMN NTI_TIPO_FIRMA;
ALTER TABLE HEL_EXPEDIENT_TIPUS DROP COLUMN NTI_VALOR_CSV;
ALTER TABLE HEL_EXPEDIENT_TIPUS DROP COLUMN NTI_DEFINICION_GENERACION_CSV;
ALTER TABLE HEL_EXPEDIENT_TIPUS ADD NTI_ACTIU NUMBER(1);
UPDATE HEL_EXPEDIENT_TIPUS SET NTI_ACTIU = 0;
ALTER TABLE HEL_EXPEDIENT_TIPUS MODIFY NTI_ORGANO VARCHAR2(256);
ALTER TABLE HEL_EXPEDIENT_TIPUS MODIFY NTI_CLASIFICACION VARCHAR2(44);
ALTER TABLE HEL_EXPEDIENT_TIPUS MODIFY NTI_SERIEDOCUMENTAL VARCHAR2(16);
ALTER TABLE HEL_EXPEDIENT_TIPUS ADD ARXIU_ACTIU NUMBER(1);
UPDATE HEL_EXPEDIENT_TIPUS SET ARXIU_ACTIU = 0;

ALTER TABLE HEL_DOCUMENT DROP COLUMN NTI_TIPO_DOC;
ALTER TABLE HEL_DOCUMENT DROP COLUMN NTI_TIPO_FIRMA;
ALTER TABLE HEL_DOCUMENT DROP COLUMN NTI_VALOR_CSV;
ALTER TABLE HEL_DOCUMENT DROP COLUMN NTI_DEFINICION_GENERACION_CSV;
ALTER TABLE HEL_DOCUMENT ADD NTI_ORIGEN NUMBER(10);
ALTER TABLE HEL_DOCUMENT ADD NTI_ESTADO_ELAB NUMBER(10);
ALTER TABLE HEL_DOCUMENT ADD NTI_TIPO_DOC NUMBER(10);

ALTER TABLE HEL_DOCUMENT_STORE DROP COLUMN NTI_ACTIVO;
ALTER TABLE HEL_DOCUMENT_STORE DROP COLUMN NTI_VERSIO;
ALTER TABLE HEL_DOCUMENT_STORE DROP COLUMN NTI_IDENTIFICADOR;
ALTER TABLE HEL_DOCUMENT_STORE DROP COLUMN NTI_ORGANO;
ALTER TABLE HEL_DOCUMENT_STORE DROP COLUMN NTI_ORIGEN;
ALTER TABLE HEL_DOCUMENT_STORE DROP COLUMN NTI_ESTADO_ELAB;
ALTER TABLE HEL_DOCUMENT_STORE DROP COLUMN NTI_NOM_FORMAT;
ALTER TABLE HEL_DOCUMENT_STORE DROP COLUMN NTI_TIPO_DOC;
ALTER TABLE HEL_DOCUMENT_STORE DROP COLUMN NTI_TIPO_FIRMA;
ALTER TABLE HEL_DOCUMENT_STORE DROP COLUMN NTI_VALOR_CSV;
ALTER TABLE HEL_DOCUMENT_STORE DROP COLUMN NTI_DEFINICION_GENERACION_CSV;
ALTER TABLE HEL_DOCUMENT_STORE DROP COLUMN NTI_ID_DOC_ORIGEN;
ALTER TABLE HEL_DOCUMENT_STORE ADD NTI_VERSION VARCHAR2(256);
ALTER TABLE HEL_DOCUMENT_STORE ADD NTI_IDENTIFICADOR VARCHAR2(52);
ALTER TABLE HEL_DOCUMENT_STORE ADD NTI_ORGANO VARCHAR2(256);
ALTER TABLE HEL_DOCUMENT_STORE ADD NTI_ORIGEN NUMBER(10);
ALTER TABLE HEL_DOCUMENT_STORE ADD NTI_ESTADO_ELAB NUMBER(10);
ALTER TABLE HEL_DOCUMENT_STORE ADD NTI_NOMBRE_FMT NUMBER(10);
ALTER TABLE HEL_DOCUMENT_STORE ADD NTI_TIPO_DOC NUMBER(10);
ALTER TABLE HEL_DOCUMENT_STORE ADD NTI_IDDOC_ORIG VARCHAR2(52);
ALTER TABLE HEL_DOCUMENT_STORE ADD NTI_TIPO_FIRMA NUMBER(10);
ALTER TABLE HEL_DOCUMENT_STORE ADD NTI_CSV VARCHAR2(256);
ALTER TABLE HEL_DOCUMENT_STORE ADD NTI_DEF_GEN_CSV VARCHAR2(256);
ALTER TABLE HEL_DOCUMENT_STORE ADD ARXIU_UUID VARCHAR2(36);

ALTER TABLE HEL_EXPEDIENT DROP COLUMN NTI_ACTIVO;
ALTER TABLE HEL_EXPEDIENT DROP COLUMN NTI_VERSIO;
ALTER TABLE HEL_EXPEDIENT DROP COLUMN NTI_ORGANO;
ALTER TABLE HEL_EXPEDIENT DROP COLUMN NTI_CLASIFICACION;
ALTER TABLE HEL_EXPEDIENT DROP COLUMN NTI_SERIEDOCUMENTAL;
ALTER TABLE HEL_EXPEDIENT DROP COLUMN NTI_IDENTIFICADOR;
ALTER TABLE HEL_EXPEDIENT DROP COLUMN NTI_TIPO_FIRMA;
ALTER TABLE HEL_EXPEDIENT DROP COLUMN NTI_VALOR_CSV;
ALTER TABLE HEL_EXPEDIENT DROP COLUMN NTI_DEFINICION_GENERACION_CSV;
ALTER TABLE HEL_EXPEDIENT ADD NTI_VERSION VARCHAR2(256);
ALTER TABLE HEL_EXPEDIENT ADD NTI_IDENTIFICADOR VARCHAR2(52);
ALTER TABLE HEL_EXPEDIENT ADD NTI_ORGANO VARCHAR2(256);
ALTER TABLE HEL_EXPEDIENT ADD NTI_SERIEDOCUMENTAL VARCHAR2(16);
ALTER TABLE HEL_EXPEDIENT ADD NTI_CLASIFICACION VARCHAR2(44);
ALTER TABLE HEL_EXPEDIENT ADD NTI_TIPO_FIRMA NUMBER(10);
ALTER TABLE HEL_EXPEDIENT ADD NTI_CSV VARCHAR2(256);
ALTER TABLE HEL_EXPEDIENT ADD NTI_DEF_GEN_CSV VARCHAR2(256);
ALTER TABLE HEL_EXPEDIENT ADD NTI_ACTIU NUMBER(1);
UPDATE HEL_EXPEDIENT SET NTI_ACTIU = 0;
ALTER TABLE HEL_EXPEDIENT ADD ARXIU_ACTIU NUMBER(1);
UPDATE HEL_EXPEDIENT SET ARXIU_ACTIU = 0;
ALTER TABLE HEL_EXPEDIENT ADD ARXIU_UUID VARCHAR2(36);
