-- ORACLE

--#1569 Quan es deshabilita la integració amb tràmits SISTRA es perd el codi del tràmit
ALTER TABLE HEL_EXPEDIENT_TIPUS ADD SISTRA_ACTIU NUMBER(1) DEFAULT 0;
UPDATE HEL_EXPEDIENT_TIPUS SET SISTRA_ACTIU = 1 WHERE SISTRA_CODTRA IS NOT NULL;

--#1577  Incorporar en el grup de handlers predefinits en la gestió d'expedients la integració amb PINBAL
--Corregir la tasca de pinbal i afegir la configuració de la integració
ALTER TABLE HEL_EXPEDIENT_TIPUS ADD PINBAL_ACTIU NUMBER(1) DEFAULT 0;
ALTER TABLE HEL_EXPEDIENT_TIPUS ADD PINBAL_NIF_CIF VARCHAR2(44 CHAR);

-- #1595 Tractar els avisos de noves anotacions de Distribucio en una cua 
-- Modificar camps de la taula d'anotacions per a que puguin estar buits quan arribi una anotació
ALTER TABLE HEL_ANOTACIO MODIFY IDIOMA_CODI NULL;
ALTER TABLE HEL_ANOTACIO MODIFY LLIBRE_CODI NULL;
ALTER TABLE HEL_ANOTACIO MODIFY OFICINA_CODI NULL;
ALTER TABLE HEL_ANOTACIO MODIFY DESTI_CODI NULL;
ALTER TABLE HEL_ANOTACIO MODIFY "DATA" NULL;
ALTER TABLE HEL_ANOTACIO MODIFY ENTITAT_CODI NULL;
ALTER TABLE HEL_ANOTACIO MODIFY IDENTIFICADOR NULL;

ALTER TABLE HEL_ANOTACIO ADD CONSULTA_INTENTS NUMBER(10) DEFAULT 0;
ALTER TABLE HEL_ANOTACIO ADD CONSULTA_ERROR VARCHAR2(1024 CHAR);
ALTER TABLE HEL_ANOTACIO ADD CONSULTA_DATA TIMESTAMP(6);
ALTER TABLE HEL_ANOTACIO ADD ERROR_PROCESSAMENT VARCHAR2(1024 CHAR);

