
-- Actualització a la nova versió --
INSERT INTO HEL_VERSIO (
    ID,
    CODI,
    ORDRE,
    DATA_CREACIO,
    PROCES_EXECUTAT,
    SCRIPT_EXECUTAT,
    DATA_EXECUCIO_SCRIPT)
SELECT
    NEXTVAL('HIBERNATE_SEQUENCE') ID,
    '3.2.0' CODI,
    310 ORDRE,
    current_date data_creacio,
    false PROCES_EXECUTAT,
    true SCRIPT_EXECUTAT,
    current_date DATA_EXECUCIO_SCRIPT
WHERE (SELECT COUNT(*) FROM HEL_VERSIO WHERE ORDRE = 310) = 0;

--------------------------------------------------------
-- 820 Simplificació de la configuració en les definicions de procés
--------------------------------------------------------

-- Crea les noves columnes
ALTER TABLE HEL_EXPEDIENT_TIPUS ADD AMB_INFO_PROPIA BOOLEAN DEFAULT false NOT NULL;
ALTER TABLE HEL_CAMP 		ADD EXPEDIENT_TIPUS_ID BIGINT;
ALTER TABLE HEL_CAMP		ADD DEFPROC_JBPMKEY  VARCHAR(255);
ALTER TABLE HEL_CAMP_AGRUP 	ADD EXPEDIENT_TIPUS_ID BIGINT;
ALTER TABLE HEL_DOCUMENT 	ADD EXPEDIENT_TIPUS_ID BIGINT;
ALTER TABLE HEL_TERMINI 	ADD EXPEDIENT_TIPUS_ID BIGINT;
ALTER TABLE HEL_ACCIO 		ADD EXPEDIENT_TIPUS_ID BIGINT;
ALTER TABLE HEL_ACCIO 		ADD DEFPROC_JBPMKEY  VARCHAR(255);

-- Modifica les columnes existents per a que puguin ser nules
ALTER TABLE HEL_CAMP ALTER COLUMN 	DEFINICIO_PROCES_ID DROP NOT NULL;
ALTER TABLE HEL_CAMP_AGRUP ALTER COLUMN	DEFINICIO_PROCES_ID DROP NOT NULL;
ALTER TABLE HEL_DOCUMENT ALTER COLUMN	DEFINICIO_PROCES_ID DROP NOT NULL;
ALTER TABLE HEL_TERMINI ALTER COLUMN	DEFINICIO_PROCES_ID DROP NOT NULL;
ALTER TABLE HEL_ACCIO ALTER COLUMN	DEFINICIO_PROCES_ID DROP NOT NULL;

-- Distribució de camps de formulari
ALTER TABLE HEL_CAMP_TASCA ADD AMPLE_COLS BIGINT DEFAULT 12;
ALTER TABLE HEL_CAMP_TASCA ADD BUIT_COLS BIGINT DEFAULT 0;
ALTER TABLE HEL_CONSULTA_CAMP ADD AMPLE_COLS BIGINT DEFAULT 12;
ALTER TABLE HEL_CONSULTA_CAMP ADD BUIT_COLS BIGINT DEFAULT 0;

-- AFEGIM LA COLUMNA ROLS_ PER A CONTROL DE PERMISOS EN TASQUES EN SEGON PLA
ALTER TABLE JBPM_TASKINSTANCE ADD ROLS_ VARCHAR(2000);

-- Crea els índexos per a les noves columnes
CREATE INDEX HEL_CAMP_EXPTIP_I 		ON HEL_CAMP 			(EXPEDIENT_TIPUS_ID);
CREATE INDEX HEL_CAMPAGRUP_EXPTIP_I ON HEL_CAMP_AGRUP 		(EXPEDIENT_TIPUS_ID);
CREATE INDEX HEL_DOCUMENT_EXPTIP_I 	ON HEL_DOCUMENT 		(EXPEDIENT_TIPUS_ID);
CREATE INDEX HEL_TERMINI_EXPTIP_I 	ON HEL_TERMINI 			(EXPEDIENT_TIPUS_ID);
CREATE INDEX HEL_ACCIO_EXPTIP_I 	ON HEL_ACCIO			(EXPEDIENT_TIPUS_ID);
CREATE INDEX IDX_TASKINST_SUSPOPEN 	ON JBPM_TASKINSTANCE	(ISSUSPENDED_, ISOPEN_);


-- Esborra les constraints actuals de les taules hel_camp i hel_camp_agrup sobre les columnes codi, definicio_proces_id

 CREATE OR REPLACE FUNCTION Borra_restr(p_tab TEXT) RETURNS void AS $$
 DECLARE
	taula TEXT := p_tab;
	const_nom TEXT;
 BEGIN
	FOR const_nom IN
		SELECT
		    tc.constraint_name
		FROM 
		    information_schema.table_constraints AS tc 
		    JOIN information_schema.key_column_usage AS kcu
		      ON tc.constraint_name = kcu.constraint_name
		    JOIN information_schema.constraint_column_usage AS ccu
		      ON ccu.constraint_name = tc.constraint_name
		WHERE 
			tc.table_name = taula
			AND ccu.column_name = 'definicio_proces_id'
			AND kcu.column_name = 'codi'
	LOOP
		EXECUTE format('ALTER TABLE %I DROP CONSTRAINT IF EXISTS %I', taula, const_nom.nom);
	END LOOP;
  END;
  $$ LANGUAGE plpgsql;

DO $$ BEGIN
 PERFORM Borra_restr('HEL_CAMP');
 PERFORM Borra_restr('HEL_CAMP_AGRUP');
 PERFORM Borra_restr('HEL_DOCUMENT');
 PERFORM Borra_restr('HEL_ACCIO');
 PERFORM Borra_restr('HEL_TERMINI');
END $$;

-- Afegeix les constraints úniques de 3 camps
ALTER TABLE HEL_CAMP 		ADD UNIQUE (CODI, DEFINICIO_PROCES_ID, EXPEDIENT_TIPUS_ID);
ALTER TABLE HEL_CAMP_AGRUP 	ADD UNIQUE (CODI, DEFINICIO_PROCES_ID, EXPEDIENT_TIPUS_ID);
ALTER TABLE HEL_DOCUMENT 	ADD UNIQUE (CODI, DEFINICIO_PROCES_ID, EXPEDIENT_TIPUS_ID);
ALTER TABLE HEL_TERMINI 	ADD UNIQUE (CODI, DEFINICIO_PROCES_ID, EXPEDIENT_TIPUS_ID);
ALTER TABLE HEL_ACCIO 		ADD UNIQUE (CODI, DEFINICIO_PROCES_ID, EXPEDIENT_TIPUS_ID);

ALTER TABLE HEL_CAMP 		ADD  CONSTRAINT HEL_EXPTIP_CAMP_FK 		FOREIGN KEY (EXPEDIENT_TIPUS_ID) REFERENCES HEL_EXPEDIENT_TIPUS (ID);
ALTER TABLE HEL_CAMP_AGRUP 	ADD  CONSTRAINT HEL_EXPTIP_CAMPAGRUP_FK 	FOREIGN KEY (EXPEDIENT_TIPUS_ID) REFERENCES HEL_EXPEDIENT_TIPUS (ID);
ALTER TABLE HEL_DOCUMENT 	ADD  CONSTRAINT HEL_EXPTIP_DOC_FK 		FOREIGN KEY (EXPEDIENT_TIPUS_ID) REFERENCES HEL_EXPEDIENT_TIPUS (ID);
ALTER TABLE HEL_TERMINI		ADD  CONSTRAINT HEL_EXPTIP_TERMINI_FK 		FOREIGN KEY (EXPEDIENT_TIPUS_ID) REFERENCES HEL_EXPEDIENT_TIPUS (ID);
ALTER TABLE HEL_ACCIO 		ADD  CONSTRAINT HEL_EXPTIP_ACCIO_FK 		FOREIGN KEY (EXPEDIENT_TIPUS_ID) REFERENCES HEL_EXPEDIENT_TIPUS (ID);

--------------------------------------------------------
-- 8889 Millores en el procés d'importació de tipus d'expedients
--------------------------------------------------------

-- Esborra la restricció de clau única [id entorn - codi] del comini i hi afegeix la clau [id entorn, id tipus expedient, codi]
 CREATE OR REPLACE FUNCTION Borra_unique(p_tab TEXT) RETURNS void AS $$
 DECLARE
	taula TEXT := p_tab;
	const_nom TEXT;
 BEGIN
	FOR const_nom IN
		SELECT
		    tc.constraint_name
		FROM 
		    information_schema.table_constraints AS tc 
		    JOIN information_schema.key_column_usage AS kcu
		      ON tc.constraint_name = kcu.constraint_name
		    JOIN information_schema.constraint_column_usage AS ccu
		      ON ccu.constraint_name = tc.constraint_name
		WHERE 
			tc.table_name = taula
			AND ccu.column_name = 'codi'
			AND kcu.column_name = 'entorn_id'
	LOOP
		EXECUTE format('ALTER TABLE %I DROP CONSTRAINT IF EXISTS %I', taula, const_nom.nom);
	END LOOP;
  END;
  $$ LANGUAGE plpgsql;

DO $$ BEGIN
 PERFORM Borra_unique('HEL_DOMINI');
 PERFORM Borra_unique('HEL_CONSULTA');
END $$;

-- Afegeix les constraints úniques de 3 camps
ALTER TABLE HEL_DOMINI 		ADD UNIQUE (CODI, ENTORN_ID, EXPEDIENT_TIPUS_ID);
ALTER TABLE HEL_CONSULTA	ADD UNIQUE (CODI, ENTORN_ID, EXPEDIENT_TIPUS_ID);


--------------------------------------------------------
-- Modifica els camps OID per Bytea
--------------------------------------------------------

-- Crea la funció que transformarà OID en BYTEA
CREATE OR REPLACE FUNCTION merge_oid(val oid) 
returns bytea as $$
declare merged bytea;
declare arr bytea;
 BEGIN  
   FOR arr IN SELECT data from pg_largeobject WHERE loid = val ORDER BY pageno LOOP
     IF merged IS NULL THEN
       merged := arr;
     ELSE
       merged := merged || arr;
     END IF;
   END LOOP;
  RETURN merged;

END;  
$$ LANGUAGE plpgsql;
-- Modifica les columnes canviant el tipus
ALTER TABLE HEL_DOCUMENT 
    ALTER COLUMN ARXIU_CONTINGUT TYPE BYTEA 
    USING merge_oid(ARXIU_CONTINGUT);

ALTER TABLE HEL_DOCUMENT_STORE 
    ALTER COLUMN ARXIU_CONTINGUT TYPE BYTEA 
    USING merge_oid(ARXIU_CONTINGUT);

ALTER TABLE HEL_CONSULTA 
    ALTER COLUMN INFORME_CONTINGUT TYPE BYTEA 
    USING merge_oid(INFORME_CONTINGUT);
-- Esborra la funció declarada
DROP FUNCTION merge_oid(val oid);

--------------------------------------------------------
-- 1173 Integració amb l'arxiu digital de la CAIB
--------------------------------------------------------
ALTER TABLE HEL_EXPEDIENT_TIPUS DROP COLUMN NTI_ACTIVO;
ALTER TABLE HEL_EXPEDIENT_TIPUS DROP COLUMN NTI_TIPO_FIRMA;
ALTER TABLE HEL_EXPEDIENT_TIPUS DROP COLUMN NTI_VALOR_CSV;
ALTER TABLE HEL_EXPEDIENT_TIPUS DROP COLUMN NTI_DEFINICION_GENERACION_CSV;
ALTER TABLE HEL_EXPEDIENT_TIPUS ADD NTI_ACTIU BOOLEAN;
UPDATE HEL_EXPEDIENT_TIPUS SET NTI_ACTIU = false;
ALTER TABLE HEL_EXPEDIENT_TIPUS ALTER COLUMN NTI_ORGANO TYPE VARCHAR(256);
ALTER TABLE HEL_EXPEDIENT_TIPUS ALTER COLUMN NTI_CLASIFICACION TYPE VARCHAR(44);
ALTER TABLE HEL_EXPEDIENT_TIPUS ALTER COLUMN NTI_SERIEDOCUMENTAL TYPE VARCHAR(16);
ALTER TABLE HEL_EXPEDIENT_TIPUS ADD ARXIU_ACTIU BOOLEAN;
UPDATE HEL_EXPEDIENT_TIPUS SET ARXIU_ACTIU = false;

ALTER TABLE HEL_DOCUMENT DROP COLUMN NTI_TIPO_DOC;
ALTER TABLE HEL_DOCUMENT DROP COLUMN NTI_TIPO_FIRMA;
ALTER TABLE HEL_DOCUMENT DROP COLUMN NTI_VALOR_CSV;
ALTER TABLE HEL_DOCUMENT DROP COLUMN NTI_DEFINICION_GENERACION_CSV;
ALTER TABLE HEL_DOCUMENT ADD NTI_ORIGEN BIGINT;
ALTER TABLE HEL_DOCUMENT ADD NTI_ESTADO_ELAB BIGINT;
ALTER TABLE HEL_DOCUMENT ADD NTI_TIPO_DOC BIGINT;

ALTER TABLE HEL_DOCUMENT_STORE DROP COLUMN NTI_ACTIVO;
ALTER TABLE HEL_DOCUMENT_STORE DROP COLUMN NTI_VERSIO;
ALTER TABLE HEL_DOCUMENT_STORE DROP COLUMN NTI_IDENTIFICADOR;
ALTER TABLE HEL_DOCUMENT_STORE DROP COLUMN NTI_ORGANO;
ALTER TABLE HEL_DOCUMENT_STORE DROP COLUMN NTI_ORIGEN;
ALTER TABLE HEL_DOCUMENT_STORE DROP COLUMN NTI_ESTADO_ELAB;
ALTER TABLE HEL_DOCUMENT_STORE DROP COLUMN NTI_NOM_FORMAT;
ALTER TABLE HEL_DOCUMENT_STORE DROP COLUMN NTI_TIPO_DOC;
ALTER TABLE HEL_DOCUMENT_STORE DROP COLUMN NTI_TIPO_FIRMA;
ALTER TABLE HEL_DOCUMENT_STORE DROP COLUMN NTI_VALOR_CSV;
ALTER TABLE HEL_DOCUMENT_STORE DROP COLUMN NTI_DEFINICION_GENERACION_CSV;
ALTER TABLE HEL_DOCUMENT_STORE DROP COLUMN NTI_ID_DOC_ORIGEN;
ALTER TABLE HEL_DOCUMENT_STORE ADD NTI_VERSION VARCHAR(256);
ALTER TABLE HEL_DOCUMENT_STORE ADD NTI_IDENTIFICADOR VARCHAR(52);
ALTER TABLE HEL_DOCUMENT_STORE ADD NTI_ORGANO VARCHAR(256);
ALTER TABLE HEL_DOCUMENT_STORE ADD NTI_ORIGEN BIGINT;
ALTER TABLE HEL_DOCUMENT_STORE ADD NTI_ESTADO_ELAB BIGINT;
ALTER TABLE HEL_DOCUMENT_STORE ADD NTI_NOMBRE_FMT BIGINT;
ALTER TABLE HEL_DOCUMENT_STORE ADD NTI_TIPO_DOC BIGINT;
ALTER TABLE HEL_DOCUMENT_STORE ADD NTI_IDDOC_ORIG VARCHAR(52);
ALTER TABLE HEL_DOCUMENT_STORE ADD NTI_TIPO_FIRMA BIGINT;
ALTER TABLE HEL_DOCUMENT_STORE ADD NTI_CSV VARCHAR(256);
ALTER TABLE HEL_DOCUMENT_STORE ADD NTI_DEF_GEN_CSV VARCHAR(256);
ALTER TABLE HEL_DOCUMENT_STORE ADD ARXIU_UUID VARCHAR(36);

ALTER TABLE HEL_EXPEDIENT DROP COLUMN NTI_ACTIVO;
ALTER TABLE HEL_EXPEDIENT DROP COLUMN NTI_VERSIO;
ALTER TABLE HEL_EXPEDIENT DROP COLUMN NTI_ORGANO;
ALTER TABLE HEL_EXPEDIENT DROP COLUMN NTI_CLASIFICACION;
ALTER TABLE HEL_EXPEDIENT DROP COLUMN NTI_SERIEDOCUMENTAL;
ALTER TABLE HEL_EXPEDIENT DROP COLUMN NTI_IDENTIFICADOR;
ALTER TABLE HEL_EXPEDIENT DROP COLUMN NTI_TIPO_FIRMA;
ALTER TABLE HEL_EXPEDIENT DROP COLUMN NTI_VALOR_CSV;
ALTER TABLE HEL_EXPEDIENT DROP COLUMN NTI_DEFINICION_GENERACION_CSV;
ALTER TABLE HEL_EXPEDIENT ADD NTI_VERSION VARCHAR(256);
ALTER TABLE HEL_EXPEDIENT ADD NTI_IDENTIFICADOR VARCHAR(52);
ALTER TABLE HEL_EXPEDIENT ADD NTI_ORGANO VARCHAR(256);
ALTER TABLE HEL_EXPEDIENT ADD NTI_SERIEDOCUMENTAL VARCHAR(16);
ALTER TABLE HEL_EXPEDIENT ADD NTI_CLASIFICACION VARCHAR(44);
ALTER TABLE HEL_EXPEDIENT ADD NTI_TIPO_FIRMA BIGINT;
ALTER TABLE HEL_EXPEDIENT ADD NTI_CSV VARCHAR(256);
ALTER TABLE HEL_EXPEDIENT ADD NTI_DEF_GEN_CSV VARCHAR(256);
ALTER TABLE HEL_EXPEDIENT ADD NTI_ACTIU BOOLEAN;
UPDATE HEL_EXPEDIENT SET NTI_ACTIU = false;
ALTER TABLE HEL_EXPEDIENT ADD ARXIU_ACTIU NUMERIC(1);
UPDATE HEL_EXPEDIENT SET ARXIU_ACTIU = false;
ALTER TABLE HEL_EXPEDIENT ADD ARXIU_UUID VARCHAR(36);

