-------------------------------------------------------------------
-- #1314 Afegir dades d'enviament als interessats per a les notificacions postals
-------------------------------------------------------------------
ALTER TABLE HEL_INTERESSAT ADD ENTREGAPOSTAL BOOLEAN DEFAULT FALSE NOT NULL;
ALTER TABLE HEL_INTERESSAT ADD ENTREGATIPUS INTEGER;
ALTER TABLE HEL_INTERESSAT ADD LINIA1 VARCHAR(50);
ALTER TABLE HEL_INTERESSAT ADD LINIA2 VARCHAR(50);
ALTER TABLE HEL_INTERESSAT ADD ENTREGADEH BOOLEAN DEFAULT FALSE NOT NULL;
ALTER TABLE HEL_INTERESSAT ADD ENTREGADEHOBLIGAT BOOLEAN DEFAULT FALSE NOT NULL;
ALTER TABLE HEL_INTERESSAT ADD CODIPOSTAL VARCHAR(5);