-- #1253 Notificar un document a través de la interfície de Helium
-- Nova taula per a la informació dels interessats

CREATE TABLE HEL_INTERESSAT
(
	ID					BIGINT               NOT NULL,
	CODI                VARCHAR(64)          NOT NULL,
	NIF					VARCHAR(9)		 	 NOT NULL,
	NOM					VARCHAR(255) 		 NOT NULL,
	LLINATGE1			VARCHAR(255),
	LLINATGE2			VARCHAR(255),
	TIPUS				BIGINT,
	EMAIL				VARCHAR(255),
	TELEFON				VARCHAR(16),
	EXPEDIENT_ID  		BIGINT
);

ALTER TABLE HEL_INTERESSAT ADD 
  CONSTRAINT HEL_EXPEDIENT_INTERESSAT_FK 
 FOREIGN KEY (EXPEDIENT_ID) 
 REFERENCES HEL_EXPEDIENT (ID);
 
ALTER TABLE HEL_INTERESSAT ADD CONSTRAINT HEL_INTERESSAT_PK PRIMARY KEY (ID);

CREATE INDEX HEL_INTERESSAT_EXPEDIENT_ID_I ON HEL_INTERESSAT 
(EXPEDIENT_ID);
