--------------------------------------------------------
-- 1240 Nova funcionalitat Repro per a una tasca concreta
--------------------------------------------------------

ALTER TABLE HEL_REPRO ADD TASCA_CODI VARCHAR(255);
 
CREATE INDEX HEL_REPRO_TASCA_CODI_I ON HEL_REPRO 
(TASCA_CODI);

ALTER TABLE HEL_TASCA ADD AMB_REPRO BOOLEAN DEFAULT FALSE;
UPDATE HEL_TASCA SET AMB_REPRO = FALSE;

--------------------------------------------------------
-- 1164 Integració amb NOTIB
--------------------------------------------------------

ALTER TABLE HEL_EXPEDIENT_TIPUS ADD NOTIB_ACTIU BOOLEAN DEFAULT FALSE;
UPDATE HEL_EXPEDIENT_TIPUS SET NOTIB_ACTIU = FALSE;
ALTER TABLE HEL_EXPEDIENT_TIPUS ADD NOTIB_SEU_UNITATADMIN VARCHAR(100);
ALTER TABLE HEL_EXPEDIENT_TIPUS ADD NOTIB_SEU_OFICINA VARCHAR(100);
ALTER TABLE HEL_EXPEDIENT_TIPUS ADD NOTIB_SEU_LLIBRE VARCHAR(100);
ALTER TABLE HEL_EXPEDIENT_TIPUS ADD NOTIB_SEU_ORGAN VARCHAR(100);
ALTER TABLE HEL_EXPEDIENT_TIPUS ADD NOTIB_SEU_IDIOMA VARCHAR(10);
ALTER TABLE HEL_EXPEDIENT_TIPUS ADD NOTIB_AVISTITOL VARCHAR(100);
ALTER TABLE HEL_EXPEDIENT_TIPUS ADD NOTIB_AVISTEXT VARCHAR(1024);
ALTER TABLE HEL_EXPEDIENT_TIPUS ADD NOTIB_AVISTEXTSMS VARCHAR(200);
ALTER TABLE HEL_EXPEDIENT_TIPUS ADD NOTIB_OFICITITOL VARCHAR(256);
ALTER TABLE HEL_EXPEDIENT_TIPUS ADD NOTIB_OFICITEXT VARCHAR(1024);

ALTER TABLE HEL_DOCUMENT ADD NOTIFICABLE BOOLEAN DEFAULT FALSE;
UPDATE HEL_DOCUMENT SET NOTIFICABLE = FALSE;

CREATE TABLE HEL_DOCUMENT_NOTIFICACIO (  
  ID                   	BIGINT				NOT NULL,
  USUARI_CODI			VARCHAR(255),
  EXPEDIENT_ID         	BIGINT				NOT NULL,
  DOCUMENT_STORE_ID    	BIGINT				NOT NULL,
  CERTIFICACIO_STORE_ID	BIGINT,
  EMISOR				VARCHAR(10),
  TIPUS                	VARCHAR(255),
  DATA_PROGRAMADA      	TIMESTAMP(6),
  RETARD				BIGINT,
  DATA_CADUCITAT      	TIMESTAMP(6),
  TIT_NOM           	VARCHAR(100),
  TIT_LLINATGE1        	VARCHAR(100),
  TIT_LLINATGE2        	VARCHAR(100),
  TIT_NIF        		VARCHAR(100),
  TIT_TELEFON        	VARCHAR(16),
  TIT_EMAIL         	VARCHAR(160),
  DEST_NOM           	VARCHAR(100),
  DEST_LLINATGE1       	VARCHAR(100),
  DEST_LLINATGE2       	VARCHAR(100),
  DEST_NIF        		VARCHAR(100),
  DEST_TELEFON        	VARCHAR(16),
  DEST_EMAIL         	VARCHAR(160),
  IDIOMA               	VARCHAR(32),
  AVIS_TITOL           	VARCHAR(256),
  AVIS_TEXT            	VARCHAR(1024),
  AVIS_TEXT_MOBIL      	VARCHAR(256),
  OFICI_TITOL          	VARCHAR(256),
  OFICI_TEXT           	VARCHAR(1024),
  ENV_ID           		VARCHAR(100),
  ENV_REF           	VARCHAR(100),
  ENV_DAT_ESTAT        	VARCHAR(20),
  ENV_DAT_DATA        	TIMESTAMP(6),
  ENV_DAT_ORIGEN       	VARCHAR(20),
  ENV_CERT_DATA        	TIMESTAMP(6),
  ENV_CERT_ORIGEN      	VARCHAR(20),
  ENV_CERT_ARXIUUID		VARCHAR(50),
  ESTAT                	VARCHAR(20)			NOT NULL,
  ENVIAT_DATA       	TIMESTAMP(6),
  PROCESSAT_DATA       	TIMESTAMP(6),
  CANCELAT_DATA       	TIMESTAMP(6),
  ERROR         		BOOLEAN,
  ERROR_DESCRIPCIO		VARCHAR(2048),
  INTENT_NUM			BIGINT,
  INTENT_DATA          	TIMESTAMP(6),
  INTENT_PROXIM_DATA	TIMESTAMP(6),
  ENVIAMENT_TIPUS		VARCHAR(255),
  CONCEPTE				VARCHAR(256)		NOT NULL,
  DESCRIPCIO			VARCHAR(256)
);

CREATE TABLE HEL_DOCUMENT_NOTIFICACIO_ANX (
  DOCUMENT_NOTIFICACIO_ID BIGINT	NOT NULL,
  DOCUMENT_STORE_ID BIGINT			NOT NULL
);

ALTER TABLE HEL_DOCUMENT_NOTIFICACIO ADD
	CONSTRAINT HEL_EXPEDIENT_DOCNOT_FK FOREIGN KEY (EXPEDIENT_ID)
	REFERENCES HEL_EXPEDIENT (ID);
 
ALTER TABLE HEL_DOCUMENT_NOTIFICACIO ADD PRIMARY KEY (ID);
ALTER TABLE HEL_DOCUMENT_NOTIFICACIO ADD
	CONSTRAINT HEL_DOCUMENT_DOCNOTIF_FK FOREIGN KEY (DOCUMENT_STORE_ID) 
 	REFERENCES HEL_DOCUMENT_STORE (ID);
 	
 ALTER TABLE HEL_DOCUMENT_NOTIFICACIO ADD
	CONSTRAINT HEL_CERTIFICACIO_NOTIF_FK FOREIGN KEY (CERTIFICACIO_STORE_ID) 
 	REFERENCES HEL_DOCUMENT_STORE (ID);
 	