
-------------------------------------------------------------------
-- #1098 Error esborrant versions de definicions de procés
-- Modifica les constraints de claus foràrines de jbpm per esborrar en cascada
-------------------------------------------------------------------

ALTER TABLE JBPM_SWIMLANE DROP CONSTRAINT FK_SWL_ASSDEL;

ALTER TABLE JBPM_SWIMLANE ADD
  CONSTRAINT FK_SWL_ASSDEL 
 FOREIGN KEY (ASSIGNMENTDELEGATION_) 
 REFERENCES JBPM_DELEGATION (ID_)
 ON DELETE CASCADE;
 
-------------------------------------------------------------------
-- Metadades Nti
-------------------------------------------------------------------
ALTER TABLE HEL_DOCUMENT ADD COLUMN NTI_TIPO_DOC VARCHAR(32);
ALTER TABLE HEL_DOCUMENT ADD COLUMN NTI_TIPO_FIRMA VARCHAR(64);
ALTER TABLE HEL_DOCUMENT ADD COLUMN NTI_VALOR_CSV VARCHAR(128);
ALTER TABLE HEL_DOCUMENT ADD COLUMN NTI_DEFINICION_GENERACION_CSV VARCHAR(128);

ALTER TABLE HEL_DOCUMENT_STORE ADD COLUMN NTI_VERSIO VARCHAR(16);
ALTER TABLE HEL_DOCUMENT_STORE ADD COLUMN NTI_IDENTIFICADOR VARCHAR(107);
ALTER TABLE HEL_DOCUMENT_STORE ADD COLUMN NTI_ORGANO VARCHAR(64);
ALTER TABLE HEL_DOCUMENT_STORE ADD COLUMN NTI_ORIGEN VARCHAR(32);
ALTER TABLE HEL_DOCUMENT_STORE ADD COLUMN NTI_ESTADO_ELAB VARCHAR(32);
ALTER TABLE HEL_DOCUMENT_STORE ADD COLUMN NTI_NOM_FORMAT VARCHAR(16);
ALTER TABLE HEL_DOCUMENT_STORE ADD COLUMN NTI_TIPO_DOC VARCHAR(32);
ALTER TABLE HEL_DOCUMENT_STORE ADD COLUMN NTI_TIPO_FIRMA VARCHAR(64);
ALTER TABLE HEL_DOCUMENT_STORE ADD COLUMN NTI_VALOR_CSV VARCHAR(128);
ALTER TABLE HEL_DOCUMENT_STORE ADD COLUMN NTI_DEFINICION_GENERACION_CSV VARCHAR(128);
ALTER TABLE HEL_DOCUMENT_STORE ADD COLUMN NTI_ID_DOC_ORIGEN VARCHAR(107);
ALTER TABLE HEL_DOCUMENT_STORE ADD COLUMN NTI_ACTIVO BOOLEAN DEFAULT false;


ALTER TABLE HEL_EXPEDIENT ADD COLUMN NTI_ACTIVO BOOLEAN DEFAULT false;
ALTER TABLE HEL_EXPEDIENT ADD COLUMN NTI_VERSIO VARCHAR(16);
ALTER TABLE HEL_EXPEDIENT ADD COLUMN NTI_ORGANO VARCHAR(64);
ALTER TABLE HEL_EXPEDIENT ADD COLUMN NTI_CLASIFICACION VARCHAR(64);
ALTER TABLE HEL_EXPEDIENT ADD COLUMN NTI_IDENTIFICADOR VARCHAR(107);
ALTER TABLE HEL_EXPEDIENT ADD COLUMN NTI_TIPO_FIRMA VARCHAR(64);
ALTER TABLE HEL_EXPEDIENT ADD COLUMN NTI_VALOR_CSV VARCHAR(128);
ALTER TABLE HEL_EXPEDIENT ADD COLUMN NTI_DEFINICION_GENERACION_CSV VARCHAR(128);

ALTER TABLE HEL_EXPEDIENT_TIPUS ADD COLUMN NTI_ORGANO VARCHAR(64);
ALTER TABLE HEL_EXPEDIENT_TIPUS ADD COLUMN NTI_CLASIFICACION VARCHAR(64);
ALTER TABLE HEL_EXPEDIENT_TIPUS ADD COLUMN NTI_TIPO_FIRMA VARCHAR(64);
ALTER TABLE HEL_EXPEDIENT_TIPUS ADD COLUMN NTI_VALOR_CSV VARCHAR(128);
ALTER TABLE HEL_EXPEDIENT_TIPUS ADD COLUMN NTI_DEFINICION_GENERACION_CSV VARCHAR(128);
ALTER TABLE HEL_EXPEDIENT_TIPUS ADD COLUMN NTI_ACTIVO BOOLEAN DEFAULT false;

