CREATE TABLE HEL_INTERESSAT
(
	ID					BIGINT               NOT NULL,
	CODI                VARCHAR(64)          NOT NULL,
	NIF					VARCHAR(9)		 	 NOT NULL,
	NOM					VARCHAR(255) 		 NOT NULL,
	LLINATGE1			VARCHAR(255),
	LLINATGE2			VARCHAR(255),
	TIPUS				BIGINT,
	EMAIL				VARCHAR(255),
	TELEFON				VARCHAR(16),
	EXPEDIENT_ID  		BIGINT
);

 ALTER TABLE HEL_INTERESSAT ADD 
  CONSTRAINT HEL_EXPEDIENT_INTERESSAT_FK 
 FOREIGN KEY (EXPEDIENT_ID) 
 REFERENCES HEL_EXPEDIENT (ID);