
ALTER TABLE HEL_DOCUMENT ADD COLUMN NTI_SERIEDOCUMENTAL VARCHAR(64);
ALTER TABLE HEL_DOCUMENT_STORE ADD COLUMN NTI_SERIEDOCUMENTAL VARCHAR(64);
ALTER TABLE HEL_EXPEDIENT ADD COLUMN NTI_SERIEDOCUMENTAL VARCHAR(64);
ALTER TABLE HEL_EXPEDIENT_TIPUS ADD COLUMN NTI_SERIEDOCUMENTAL VARCHAR(64);