--------------------------------------------------------
-- 1164 Integració amb NOTIB
--------------------------------------------------------

ALTER TABLE HEL_EXPEDIENT_TIPUS ADD NOTIB_ACTIU BOOLEAN;
UPDATE HEL_EXPEDIENT_TIPUS SET NOTIB_ACTIU = false;
ALTER TABLE HEL_EXPEDIENT_TIPUS ADD NOTIB_SEU_UNITATADMIN VARCHAR(100);
ALTER TABLE HEL_EXPEDIENT_TIPUS ADD NOTIB_SEU_OFICINA VARCHAR(100);
ALTER TABLE HEL_EXPEDIENT_TIPUS ADD NOTIB_SEU_LLIBRE VARCHAR(100);
ALTER TABLE HEL_EXPEDIENT_TIPUS ADD NOTIB_SEU_ORGAN VARCHAR(100);
ALTER TABLE HEL_EXPEDIENT_TIPUS ADD NOTIB_SEU_IDIOMA VARCHAR(10);
ALTER TABLE HEL_EXPEDIENT_TIPUS ADD NOTIB_AVISTITOL VARCHAR(100);
ALTER TABLE HEL_EXPEDIENT_TIPUS ADD NOTIB_AVISTEXT VARCHAR(1024);
ALTER TABLE HEL_EXPEDIENT_TIPUS ADD NOTIB_AVISTEXTSMS VARCHAR(200);
ALTER TABLE HEL_EXPEDIENT_TIPUS ADD NOTIB_OFICITITOL VARCHAR(256);
ALTER TABLE HEL_EXPEDIENT_TIPUS ADD NOTIB_OFICITEXT VARCHAR(1024);
