--drop schema if exists seycon CASCADE; -- Ull borrant esquemes
create schema seycon;
set search_path to seycon;

CREATE TABLE SC_WL_CERTIF(
	CER_CODUSU 	VARCHAR(30),
	CER_EMISOR 	VARCHAR(1024),
	CER_SERIAL 	VARCHAR(128)
);

CREATE TABLE SC_WL_LOGAUT(
	LOG_DAT 	DATE NOT NULL,
	LOG_TIPO 	CHAR(1) NOT NULL,
	LOG_LOGIN 	VARCHAR(15) NOT NULL,
	LOG_CODUSU 	VARCHAR(250),
	LOG_RESUL	CHAR(1) NOT NULL,
	LOG_CERTIF 	VARCHAR(4000),
	LOG_DATA 	DATE,
	LOG_IP 		VARCHAR(240)
);

CREATE TABLE SC_WL_USUARI(
	USU_CODI	VARCHAR(512) NOT NULL PRIMARY KEY,
	USU_PASS	VARCHAR(255),
	USU_DATCAD	DATE,
	USU_NOM		VARCHAR(200),
	USU_NIF		VARCHAR(15)
);

CREATE TABLE SC_WL_USUGRU(
	UGR_CODUSU	VARCHAR(512) NOT NULL,
	UGR_CODGRU	VARCHAR(50) NOT NULL,
	CONSTRAINT UGR_WL_PK PRIMARY KEY(UGR_CODUSU, UGR_CODGRU)
);

CREATE VIEW SC_WL_USUGRU_TOMCAT AS 
	SELECT usu_codi, ugr_codgru FROM sc_wl_usuari JOIN sc_wl_usugru ON usu_codi = ugr_codusu;
