
package net.conselldemallorca.helium.integracio.forms;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b14002
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "GuardarFormulariImplService", targetNamespace = "http://forms.integracio.helium.conselldemallorca.net/", wsdlLocation = "file:/home/likewise-open/LIMIT_CECOMASA/josepg/git/helium/doc/wsdl/GuardarFormulari.wsdl")
public class GuardarFormulariImplService
    extends Service
{

    private final static URL GUARDARFORMULARIIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException GUARDARFORMULARIIMPLSERVICE_EXCEPTION;
    private final static QName GUARDARFORMULARIIMPLSERVICE_QNAME = new QName("http://forms.integracio.helium.conselldemallorca.net/", "GuardarFormulariImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/home/likewise-open/LIMIT_CECOMASA/josepg/git/helium/doc/wsdl/GuardarFormulari.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        GUARDARFORMULARIIMPLSERVICE_WSDL_LOCATION = url;
        GUARDARFORMULARIIMPLSERVICE_EXCEPTION = e;
    }

    public GuardarFormulariImplService() {
        super(__getWsdlLocation(), GUARDARFORMULARIIMPLSERVICE_QNAME);
    }

    public GuardarFormulariImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), GUARDARFORMULARIIMPLSERVICE_QNAME, features);
    }

    public GuardarFormulariImplService(URL wsdlLocation) {
        super(wsdlLocation, GUARDARFORMULARIIMPLSERVICE_QNAME);
    }

    public GuardarFormulariImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, GUARDARFORMULARIIMPLSERVICE_QNAME, features);
    }

    public GuardarFormulariImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public GuardarFormulariImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns GuardarFormulari
     */
    @WebEndpoint(name = "GuardarFormulariImplPort")
    public GuardarFormulari getGuardarFormulariImplPort() {
        return super.getPort(new QName("http://forms.integracio.helium.conselldemallorca.net/", "GuardarFormulariImplPort"), GuardarFormulari.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns GuardarFormulari
     */
    @WebEndpoint(name = "GuardarFormulariImplPort")
    public GuardarFormulari getGuardarFormulariImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://forms.integracio.helium.conselldemallorca.net/", "GuardarFormulariImplPort"), GuardarFormulari.class, features);
    }

    private static URL __getWsdlLocation() {
        if (GUARDARFORMULARIIMPLSERVICE_EXCEPTION!= null) {
            throw GUARDARFORMULARIIMPLSERVICE_EXCEPTION;
        }
        return GUARDARFORMULARIIMPLSERVICE_WSDL_LOCATION;
    }

}
