
package net.conselldemallorca.helium.integracio.forms;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b14002
 * Generated source version: 2.2
 * 
 */
@WebService(name = "GuardarFormulari", targetNamespace = "http://forms.integracio.helium.conselldemallorca.net/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface GuardarFormulari {


    /**
     * 
     * @param arg1
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "guardar", targetNamespace = "http://forms.integracio.helium.conselldemallorca.net/", className = "net.conselldemallorca.helium.integracio.forms.Guardar")
    @ResponseWrapper(localName = "guardarResponse", targetNamespace = "http://forms.integracio.helium.conselldemallorca.net/", className = "net.conselldemallorca.helium.integracio.forms.GuardarResponse")
    public void guardar(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        List<ParellaCodiValor> arg1);

}
