
package es.caib.zonaper.ws.v2.services;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.0
 * 
 */
@WebServiceClient(name = "BackofficeFacadeService", targetNamespace = "urn:es:caib:zonaper:ws:v2:services", wsdlLocation = "file:/C:/Users/PereP/git/sistra/moduls/modul-zonaper/moduls/webservices/wsdl/zonaper/v2/BackofficeFacade.wsdl")
public class BackofficeFacadeService
    extends Service
{

    private final static URL BACKOFFICEFACADESERVICE_WSDL_LOCATION;
    private final static WebServiceException BACKOFFICEFACADESERVICE_EXCEPTION;
    private final static QName BACKOFFICEFACADESERVICE_QNAME = new QName("urn:es:caib:zonaper:ws:v2:services", "BackofficeFacadeService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/C:/Users/PereP/git/sistra/moduls/modul-zonaper/moduls/webservices/wsdl/zonaper/v2/BackofficeFacade.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        BACKOFFICEFACADESERVICE_WSDL_LOCATION = url;
        BACKOFFICEFACADESERVICE_EXCEPTION = e;
    }

    public BackofficeFacadeService() {
        super(__getWsdlLocation(), BACKOFFICEFACADESERVICE_QNAME);
    }

    public BackofficeFacadeService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    /**
     * 
     * @return
     *     returns BackofficeFacade
     */
    @WebEndpoint(name = "BackofficeFacade")
    public BackofficeFacade getBackofficeFacade() {
        return super.getPort(new QName("urn:es:caib:zonaper:ws:v2:services", "BackofficeFacade"), BackofficeFacade.class);
    }

    private static URL __getWsdlLocation() {
        if (BACKOFFICEFACADESERVICE_EXCEPTION!= null) {
            throw BACKOFFICEFACADESERVICE_EXCEPTION;
        }
        return BACKOFFICEFACADESERVICE_WSDL_LOCATION;
    }

}
