<project xmlns="http://maven.apache.org/POM/4.0.0"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<parent>
		<groupId>es.caib.helium</groupId>
		<artifactId>helium</artifactId>
		<version>4.0</version>
	</parent>
	<artifactId>helium-back</artifactId>
	<packaging>war</packaging>
	<dependencies>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-devtools</artifactId>
			<optional>true</optional>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-web</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-security</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-actuator</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-aop</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-oauth2-client</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.security</groupId>
			<artifactId>spring-security-acl</artifactId>
			<version>${spring-security.version}</version>
		</dependency>
		<dependency>
			<groupId>org.springframework.security</groupId>
			<artifactId>spring-security-taglibs</artifactId>
			<version>${spring-security.version}</version>
			<exclusions>
				<exclusion>
					<artifactId>spring-aop</artifactId>
					<groupId>org.springframework</groupId>
				</exclusion>
				<exclusion>
					<artifactId>spring-jdbc</artifactId>
					<groupId>org.springframework</groupId>
				</exclusion>
				<exclusion>
					<artifactId>spring-tx</artifactId>
					<groupId>org.springframework</groupId>
				</exclusion>
				<exclusion>
					<artifactId>spring-core</artifactId>
					<groupId>org.springframework</groupId>
				</exclusion>
				<exclusion>
					<artifactId>spring-web</artifactId>
					<groupId>org.springframework</groupId>
				</exclusion>
				<exclusion>
					<artifactId>spring-expression</artifactId>
					<groupId>org.springframework</groupId>
				</exclusion>
			</exclusions>
		</dependency>
		<dependency>
			<groupId>dev.akkinoc.spring.boot</groupId>
			<artifactId>orika-spring-boot-starter</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springmodules</groupId>
			<artifactId>springmodules-validation</artifactId>
			<version>0.9</version>
			<scope>system</scope>
			<systemPath>${basedir}/src/main/webapp/WEB-INF/lib/spring-modules-validation.jar</systemPath>
		</dependency>
		<dependency>
			<groupId>net.sf.jasperreports</groupId>
			<artifactId>jasperreports</artifactId>
			<version>4.0.1</version>
			<exclusions>
				<exclusion>
					<artifactId>bcprov-jdk14</artifactId>
					<groupId>bouncycastle</groupId>
				</exclusion>
				<exclusion>
					<artifactId>bcprov-jdk14</artifactId>
					<groupId>org.bouncycastle</groupId>
				</exclusion>
				<exclusion>
					<artifactId>bcmail-jdk14</artifactId>
					<groupId>bouncycastle</groupId>
				</exclusion>
				<exclusion>
					<artifactId>bcmail-jdk14</artifactId>
					<groupId>org.bouncycastle</groupId>
				</exclusion>
				<exclusion>
					<artifactId>bctsp-jdk14</artifactId>
					<groupId>org.bouncycastle</groupId>
				</exclusion>
				<exclusion>
					<groupId>xml-apis</groupId>
					<artifactId>xml-apis</artifactId>
				</exclusion>
				<exclusion>
					<groupId>eclipse</groupId>
					<artifactId>jdtcore</artifactId>
				</exclusion>
			</exclusions>
		</dependency>
		<dependency>
			<groupId>org.apache.poi</groupId>
			<artifactId>poi-ooxml</artifactId>
			<version>3.7</version>
			<exclusions>
				<exclusion>
					<groupId>stax</groupId>
					<artifactId>stax-api</artifactId>
				</exclusion>
				<exclusion>
					<groupId>xml-apis</groupId>
					<artifactId>xml-apis</artifactId>
				</exclusion>
			</exclusions>
		</dependency>
		<dependency>
			<groupId>opensymphony</groupId>
			<artifactId>sitemesh</artifactId>
		</dependency>
		<dependency>
			<groupId>displaytag</groupId>
			<artifactId>displaytag</artifactId>
			<version>1.2</version>
			<type>jar</type>
			<scope>compile</scope>
			<exclusions>
				<exclusion>
					<artifactId>itext</artifactId>
					<groupId>com.lowagie</groupId>
				</exclusion>
				<exclusion>
					<artifactId>slf4j-log4j12</artifactId>
					<groupId>org.slf4j</groupId>
				</exclusion>
				<exclusion>
					<artifactId>jcl104-over-slf4j</artifactId>
					<groupId>org.slf4j</groupId>
				</exclusion>
				<exclusion>
					<groupId>commons-lang</groupId>
					<artifactId>commons-lang</artifactId>
				</exclusion>
			</exclusions>
		</dependency>
		<dependency>
			<groupId>displaytag</groupId>
			<artifactId>displaytag-export-poi</artifactId>
			<version>1.2</version>
			<exclusions>
				<exclusion>
					<artifactId>poi</artifactId>
					<groupId>org.apache.poi</groupId>
				</exclusion>
				<exclusion>
					<groupId>commons-lang</groupId>
					<artifactId>commons-lang</artifactId>
				</exclusion>
			</exclusions>
		</dependency>
		<dependency>
			<groupId>org.projectlombok</groupId>
			<artifactId>lombok</artifactId>
			<scope>provided</scope>
		</dependency>
		<dependency>
			<groupId>javax.servlet</groupId>
			<artifactId>javax.servlet-api</artifactId>
			<scope>provided</scope>
		</dependency>
		<dependency>
			<groupId>javax.servlet</groupId>
			<artifactId>jstl</artifactId>
		</dependency>
		<dependency>
			<groupId>${project.groupId}</groupId>
			<artifactId>helium-service-intf</artifactId>
			<version>${project.version}</version>
		</dependency>
		<!-- WEBJARS -->
		<dependency>
			<groupId>org.webjars.bower</groupId>
			<artifactId>jquery</artifactId>
			<version>2.0.0</version>
		</dependency>
		<dependency>
			<groupId>org.webjars</groupId>
			<artifactId>jquery-ui</artifactId>
			<version>1.12.0</version>
			<exclusions>
				<exclusion>
					<artifactId>jquery</artifactId>
					<groupId>org.webjars</groupId>
				</exclusion>
			</exclusions>
		</dependency>
		<dependency>
			<groupId>org.webjars.bower</groupId>
			<artifactId>bootstrap</artifactId>
			<version>3.3.6</version>
			<exclusions>
				<exclusion>
					<artifactId>jquery</artifactId>
					<groupId>org.webjars</groupId>
				</exclusion>
			</exclusions>
		</dependency>
		<dependency>
			<groupId>org.webjars.bower</groupId>
			<artifactId>font-awesome</artifactId>
			<version>4.5.0</version>
		</dependency>
		<dependency>
			<groupId>org.webjars.bower</groupId>
			<artifactId>datatables.net</artifactId>
			<version>1.10.25</version>
			<exclusions>
				<exclusion>
					<artifactId>jquery</artifactId>
					<groupId>org.webjars</groupId>
				</exclusion>
			</exclusions>
		</dependency>
		<dependency>
			<groupId>org.webjars.bower</groupId>
			<artifactId>datatables.net-bs</artifactId>
			<version>1.10.19</version>
			<exclusions>
				<exclusion>
					<artifactId>jquery</artifactId>
					<groupId>org.webjars</groupId>
				</exclusion>
			</exclusions>
		</dependency>
		<dependency>
			<groupId>org.webjars.bower</groupId>
			<artifactId>datatables.net-scroller</artifactId>
			<version>1.4.3</version>
			<exclusions>
				<exclusion>
					<artifactId>jquery</artifactId>
					<groupId>org.webjars</groupId>
				</exclusion>
			</exclusions>
		</dependency>
		<dependency>
			<groupId>org.webjars.bower</groupId>
			<artifactId>datatables.net-select</artifactId>
			<version>1.1.2</version>
			<exclusions>
				<exclusion>
					<artifactId>jquery</artifactId>
					<groupId>org.webjars</groupId>
				</exclusion>
			</exclusions>
		</dependency>
		<dependency>
			<groupId>org.webjars.bower</groupId>
			<artifactId>datatables.net-select-bs</artifactId>
			<version>1.1.2</version>
			<exclusions>
				<exclusion>
					<artifactId>jquery</artifactId>
					<groupId>org.webjars</groupId>
				</exclusion>
			</exclusions>
		</dependency>
		<dependency>
			<groupId>org.webjars.bower</groupId>
			<artifactId>datatables.net-rowgroup</artifactId>
			<version>1.0.3</version>
			<exclusions>
				<exclusion>
					<artifactId>jquery</artifactId>
					<groupId>org.webjars</groupId>
				</exclusion>
			</exclusions>
		</dependency>
		<dependency>
			<groupId>org.webjars.bower</groupId>
			<artifactId>select2</artifactId>
			<version>3.4.8</version>
		</dependency>
		<dependency>
			<groupId>org.webjars.bower</groupId>
			<artifactId>jsrender</artifactId>
			<version>1.0.0-rc.70</version>
		</dependency>
		<dependency>
			<groupId>org.webjars.bower</groupId>
			<artifactId>jstree</artifactId>
			<version>3.2.1</version>
			<exclusions>
				<exclusion>
					<artifactId>jquery</artifactId>
					<groupId>org.webjars</groupId>
				</exclusion>
			</exclusions>
		</dependency>
	</dependencies>
	<profiles>
		<profile>
			<id>ide</id>
			<activation>
				<activeByDefault>false</activeByDefault>
			</activation>
			<dependencies>
				<dependency>
					<groupId>org.keycloak</groupId>
					<artifactId>keycloak-core</artifactId>
				</dependency>
				<dependency>
					<groupId>javax.ejb</groupId>
					<artifactId>javax.ejb-api</artifactId>
				</dependency>
				<dependency>
					<groupId>org.apache.tomcat.embed</groupId>
					<artifactId>tomcat-embed-jasper</artifactId>
				</dependency>
				<dependency>
					<groupId>${project.groupId}</groupId>
					<artifactId>helium-service</artifactId>
					<version>${project.version}</version>
				</dependency>
			</dependencies>
			<build>
				<resources>
					<resource>
						<directory>src/main/webapp</directory>
						<targetPath>META-INF/resources</targetPath>
						<includes>
							<include>**/*.*</include>
						</includes>
					</resource>
				</resources>
				<plugins>
					<plugin>
						<groupId>org.springframework.boot</groupId>
						<artifactId>spring-boot-maven-plugin</artifactId>
						<configuration>
							<mainClass>es.caib.helium.HeliumBackBootApp</mainClass>
						</configuration>
					</plugin>
					<plugin>
						<groupId>org.apache.maven.plugins</groupId>
						<artifactId>maven-war-plugin</artifactId>
						<version>3.3.2</version>
						<configuration>
							<archive>
								<manifestEntries>
									<Build-Timestamp>${maven.build.timestamp}</Build-Timestamp>
									<Implementation-Vendor>${implementation.vendor}</Implementation-Vendor>
									<Implementation-Version>${project.version}</Implementation-Version>
									<Implementation-SCM-Branch>${scmBranch}</Implementation-SCM-Branch>
									<Implementation-SCM-Revision>${buildNumber}</Implementation-SCM-Revision>
								</manifestEntries>
							</archive>
						</configuration>
					</plugin>
				</plugins>
			</build>
		</profile>
		<profile>
			<id>jboss</id>
			<activation>
				<activeByDefault>true</activeByDefault>
			</activation>
			<dependencies>
				<dependency>
					<groupId>org.keycloak</groupId>
					<artifactId>keycloak-core</artifactId>
					<scope>provided</scope>
				</dependency>
				<dependency>
					<groupId>javax.ejb</groupId>
					<artifactId>javax.ejb-api</artifactId>
					<scope>provided</scope>
				</dependency>
				<dependency>
					<groupId>org.apache.tomcat.embed</groupId>
					<artifactId>tomcat-embed-jasper</artifactId>
					<scope>provided</scope>
				</dependency>
			</dependencies>
			<build>
				<plugins>
					<plugin>
						<groupId>org.apache.maven.plugins</groupId>
						<artifactId>maven-war-plugin</artifactId>
						<version>3.3.2</version>
						<configuration>
							<packagingExcludes>**/HeliumBackBootApp.class</packagingExcludes>
							<attachClasses>true</attachClasses>
							<archive>
								<manifestEntries>
									<Build-Timestamp>${maven.build.timestamp}</Build-Timestamp>
									<Implementation-Vendor>${implementation.vendor}</Implementation-Vendor>
									<Implementation-Version>${project.version}</Implementation-Version>
									<Implementation-SCM-Branch>${scmBranch}</Implementation-SCM-Branch>
									<Implementation-SCM-Revision>${buildNumber}</Implementation-SCM-Revision>
								</manifestEntries>
							</archive>
						</configuration>
					</plugin>
				</plugins>
			</build>
		</profile>
	</profiles>
	<build>
		<resources>
			<resource>
				<directory>src/main/resources</directory>
				<filtering>false</filtering>
			</resource>
			<resource>
				<directory>src/main/resources</directory>
				<includes>
					<include>banner.txt</include>
				</includes>
				<filtering>true</filtering>
			</resource>
		</resources>
	</build>
</project>
