-- #1661 Accés a expedients per permisos sobre unitats organitzatives

-- Oracle

-- -- Nova taula per les unitats organitzatives
CREATE TABLE HEL_UNITAT_ORGANITZATIVA (
  ID           				NUMBER(19)          NOT NULL,
  CODI 						VARCHAR2(9 CHAR) 		NOT NULL,
  DENOMINACIO 				VARCHAR2(300 CHAR) 		NOT NULL,
  NIF_CIF 					VARCHAR2(9 CHAR),
  CODI_UNITAT_SUPERIOR 		VARCHAR2(9 CHAR),
  CODI_UNITAT_ARREL 		VARCHAR2(9 CHAR),
  DATA_CREACIO_OFICIAL 		TIMESTAMP(6),
  DATA_SUPRESSIO_OFICIAL 	TIMESTAMP(6),
  DATA_EXTINCIO_FUNCIONAL 	TIMESTAMP(6),
  DATA_ANULACIO 	 		TIMESTAMP(6),
  DATA_SINCRONITZACIO 		TIMESTAMP(6),
  DATA_ACTUALITZACIO 		TIMESTAMP(6),
  ESTAT 					VARCHAR2(1 CHAR),
  CODI_PAIS 				VARCHAR2(3 CHAR),
  CODI_COMUNITAT 			VARCHAR2(2 CHAR),
  CODI_PROVINCIA 			VARCHAR2(2 CHAR),
  CODI_POSTAL 				VARCHAR2(5 CHAR),
  NOM_LOCALITAT 			VARCHAR2(50 CHAR),
  LOCALITAT 				VARCHAR2(40 CHAR),
  ADRESSA 					VARCHAR2(70 CHAR),
  TIPUS_VIA 	 			NUMBER(19),
  NOM_VIA 					VARCHAR2(200 CHAR),
  NUM_VIA 					VARCHAR2(100 CHAR),
  TIPUS_TRANSICIO 		    VARCHAR2(12 CHAR),

  CREATEDDATE          		TIMESTAMP(6),
  CREATEDBY_CODI       		VARCHAR2(256 CHAR),
  LASTMODIFIEDDATE     		TIMESTAMP(6),
  LASTMODIFIEDBY_CODI  		VARCHAR2(256 CHAR),
  CODI_DIR3_ENTITAT		 	VARCHAR2(9 CHAR)
);

CREATE TABLE HEL_UO_SINC_REL (
  ANTIGA_UO         			NUMBER(19)          NOT NULL,
  NOVA_UO           			NUMBER(19)          NOT NULL
);

ALTER TABLE HEL_UNITAT_ORGANITZATIVA ADD (
  CONSTRAINT HEL_UNITAT_ORGANITZATIVA_PK PRIMARY KEY (ID));
  
ALTER TABLE HEL_UO_SINC_REL ADD (
  CONSTRAINT HEL_UNITAT_ANTIGA_FK FOREIGN KEY (ANTIGA_UO) 
    REFERENCES HEL_UNITAT_ORGANITZATIVA (ID));
ALTER TABLE HEL_UO_SINC_REL ADD (
  CONSTRAINT HEL_UNITAT_NOVA_FK FOREIGN KEY (NOVA_UO) 
    REFERENCES HEL_UNITAT_ORGANITZATIVA (ID));
ALTER TABLE HEL_UO_SINC_REL ADD CONSTRAINT HEL_UO_SINC_REL_MULT_UK UNIQUE (ANTIGA_UO, NOVA_UO);

ALTER TABLE HEL_EXPEDIENT_TIPUS ADD PROCEDIMENT_COMU NUMBER(1);
UPDATE HEL_EXPEDIENT_TIPUS SET PROCEDIMENT_COMU = 0;

-- Nova taula pels procediments
CREATE TABLE HEL_PROCEDIMENT 
(
  ID						NUMBER(19)	    	NOT NULL,
  CODI          			VARCHAR2(64 CHAR)		NOT NULL,
  NOM						VARCHAR2(256 CHAR),
  CODISIA					VARCHAR2(64 CHAR),
  UNITAT_ORGANITZATIVA_ID   NUMBER(19),
  ESTAT                     VARCHAR2(20 CHAR) DEFAULT 'VIGENT' NOT NULL
);
ALTER TABLE HEL_PROCEDIMENT ADD (
  CONSTRAINT HEL_PROCEDIMENT_PK PRIMARY KEY (ID));

ALTER TABLE HEL_PROCEDIMENT ADD CONSTRAINT HEL_PROCEDIMENT_UNITAT_FK 
	FOREIGN KEY (UNITAT_ORGANITZATIVA_ID) REFERENCES HEL_UNITAT_ORGANITZATIVA(ID);

GRANT SELECT, UPDATE, INSERT, DELETE ON HEL_PROCEDIMENT TO WWW_HELIUM;
	
	

-- Postgesql
	
-- Nova taula pels procediments
CREATE TABLE HEL_PROCEDIMENT 
(
  ID						BIGSERIAL	    	NOT NULL,
  CODI          			character varying(64),		NOT NULL,
  NOM						character varying(256),
  CODISIA					character varying(64),
  ID_UNITAT_ORGANITZATIVA	BIGSERIAL,
  ESTAT                     character varying(20) default 'VIGENT' NOT NULL
);
ALTER TABLE HEL_PROCEDIMENT ADD (
  CONSTRAINT HEL_PROCEDIMENT_PK PRIMARY KEY (ID));

ALTER TABLE HEL_PROCEDIMENT ADD CONSTRAINT HEL_PROCEDIMENT_UNITAT_FK 
	FOREIGN KEY (ID_UNITAT_ORGANITZATIVA) REFERENCES HEL_UNITAT_ORGANITZATIVA(ID);
	
ALTER TABLE HEL_EXPEDIENT_TIPUS ADD PROCEDIMENT_COMU BOOLEAN;
UPDATE HEL_EXPEDIENT_TIPUS SET PROCEDIMENT_COMU = false;	
