# Url base
app.base.url=http://localhost:8080/helium

# Opcions de visualització de la capçalera
# Color de fons de la capçalera. Per defecte app.capsalera.color.fons=#ff9523 
app.capsalera.color.fons=

# Color de la lletra de la capçalera. Per defecte app.capsalera.color.lletra=white 
app.capsalera.color.lletra=

# Tamany màxim permès pels arxius pujats mitjançant HTTP (en bytes)
spring.http.multipart.max-file-size=50Mb

# Per a habilitar/deshabilitar l'accés a la gestió de persones (true,false)
app.persones.actiu=true

# Per a habilitar/deshabilitar l'accés a la gestió de l'organigrama (true,false)
app.organigrama.actiu=true

# Generador del número d'expedient per defecte (alerta amb els caràcters no permesos per Alfresco)
app.numexp.expression=${seq}/${any}

# ###
# Configuració del mòdul d'identitat
# ###
# Per a fer que el mòdul identity del jBPM agafi les dades de Helium o de les taules del jBPM (helium,jbpm)
app.jbpm.identity.source=helium
# Per a fer les assignacions de les persones d'una àrea recursives
app.jbpm.identity.recursiu=true

# ###
# Paràmetres per a la conversió de documents amb OpenOffice
# ###
app.conversio.actiu=true
app.conversio.openoffice.host=localhost
app.conversio.openoffice.port=8100
# Conversió de documents generant plantilles a les tasques
app.conversio.gentasca.actiu=true
app.conversio.gentasca.extension=doc
# Conversió de documents per la signatura
app.conversio.signatura.actiu=true
app.conversio.signatura.extension=pdf
app.conversio.signatura.estampa.actiu=true
app.conversio.signatura.estampa.posx=10
app.conversio.signatura.estampa.posy=400
app.conversio.signatura.estampa.rotation=90

# ###
# Dades del calendari laborable
# ###
# Dies no laborables de la setmana (1:dilluns, ..., 7:diumenge)
app.calendari.nolabs=6,7
# Horari laboral
app.calendari.horari=8:00-14:00 & 15:00-17:00
app.calendari.horeslab.dia=8
app.calendari.horeslab.setmana=40
app.calendari.dieslab.mes=21
app.calendari.dieslab.any=220

# ###
# Enviaments de correu
# ###
app.correu.remitent=helium@helium.org
app.correu.reintents=5

# ###
# URL base per a la verificació de firmes a Custòdia Antiga
# ###
app.arxiu.verificacio.baseurl=https://dev.caib.es/concsv/view.xhtml?hash=

# ###
# Hora en què s'enviaràn els emails agrupats d'anotacions a l'usuari
# ###
app.anotacions.emails.agrupats.cron=0 0 20 * * *

# Per indicar quin és l'entonr per diferenciar-lo en l'enviament de correus, només pels entorns previs DEV, PRE i SE
app.entorn.helium=DES

# Període en mil·lisegons per a comprovar si hi ha execucions massives pendents
es.caib.helium.massiu.periode.noves=10000


# ########
# Plugins
# ########


######################
# Plugin de Persones #
######################
#app.persones.plugin.class=es.caib.helium.integracio.plugins.persones.PersonesPluginJdbc
#app.persones.plugin.jdbc.driver=jdbc:oracle:thin:@10.35.3.242:1521:orcl
#app.persones.plugin.jdbc.jndi.parameter=java:comp/env/jdbc/SeyconDS
#app.persones.plugin.jdbc.url=jdbc:mysql://localhost:3306/db1?serverTimezone=UTC
#app.persones.plugin.jdbc.username=seycon
#app.persones.plugin.jdbc.password=seycon
#app.persones.plugin.jdbc.filter.grup=select usu_codi, usu_nom, usu_nif, usu_codi ||'@limit.es' from sc_wl_usuari u, sc_wl_usugru g where g.ugr_codgru=:grup and g.ugr_codusu=u.usu_codi
#app.persones.plugin.jdbc.filter.code=select usu_codi, usu_nom, usu_nif, usu_codi || '@limit.es' from sc_wl_usuari where usu_codi = :codi
#app.persones.plugin.jdbc.filter.name=select usu_codi, usu_nom, usu_nif, usu_codi || '@limit.es' from sc_wl_usuari where upper(usu_nom) like upper('%'||:nom||'%')
#app.persones.plugin.jdbc.nom.llimatges.junt=true


app.persones.plugin.class=es.caib.helium.integracio.plugins.persones.PersonesPluginKeycloak
app.plugin.persones.pluginsib.userinformation.keycloak.serverurl=https://authdev.limit.es
app.plugin.persones.pluginsib.userinformation.keycloak.realm=GOIB
app.plugin.persones.pluginsib.userinformation.keycloak.client_id=goib-ws
app.plugin.persones.pluginsib.userinformation.keycloak.client_id_for_user_autentication=goib-ws
app.plugin.persones.pluginsib.userinformation.keycloak.password_secret=KXbtEBU3kMpiekjvktZSmnpk5cGsnJNY
app.plugin.persones.pluginsib.userinformation.keycloak.mapping.administrationID=nif
app.plugin.persones.pluginsib.userinformation.keycloak.debug=true


##################################
# Integració amb l'arxiu digital #
##################################
app.arxiu.plugin.class=es.caib.plugins.arxiu.caib.ArxiuPluginCaib
app.plugin.arxiu.caib.base.url=https://esbse.caib.es:4430/esb
app.plugin.arxiu.caib.aplicacio.codi=HELIUM
app.plugin.arxiu.caib.usuari=helium
app.plugin.arxiu.caib.contrasenya=hvoxENDXAS0Z
app.plugin.arxiu.caib.csv.definicio=CSV_DEF
app.plugin.arxiu.caib.conversio.imprimible.url=https://se.caib.es/concsvapi/interna/printable/uuid
app.plugin.arxiu.caib.conversio.imprimible.usuari=$helium_concsv_se
app.plugin.arxiu.caib.conversio.imprimible.contrasenya=helium_concsv_se

########################################################################################## #
## Intregració amb el plugin de procediments per sincronitzar els procediments amb Rolsac  #
########################################################################################## #

# Rolsac 1
#app.procediments.plugin.class=es.caib.helium.integracio.plugins.procediment.ProcedimentPluginRolsac
#app.plugins.procediments.rolsac.service.url=https://dev.caib.es/rolsac/api/rest/v1
#app.plugins.procediments.rolsac.service.username=$distribucio_rolsac
#app.plugins.procediments.rolsac.service.password=distribucio_rolsac
# Rolsac 2
app.procediments.plugin.class=es.caib.helium.integracio.plugins.procediment.Rolsac2ProcedimentPlugin
app.plugins.procediments.rolsac.service.url=https://dev.caib.es/rolsac2api/interna/services/v1
app.plugins.procediments.rolsac.service.username=$helium_rolsac2
app.plugins.procediments.rolsac.service.password=helium_rolsac2


########################################################################################## #
## Plugin per consultar el Dir3                                                            #
########################################################################################## #

app.unitats.organiques.dir3.plugin.service.class=es.caib.helium.integracio.plugins.unitat.UnitatsOrganiquesPluginDir3
app.unitats.organiques.dir3.plugin.service.url=https://dev.caib.es/dir3caib/rest/unidades/
app.unitats.organiques.dir3.plugin.service.username=$helium_dir3caib
app.unitats.organiques.dir3.plugin.service.password=helium_dir3caib
app.unitats.organiques.dir3.plugin.service.connect.timeout=300000
app.unitats.organiques.dir3.plugin.service.request.timeout=300000
app.unitats.organiques.dir3.plugin.service.log.actiu=false
app.unitats.organiques.dir3.plugin.service.cerca.url=https://dev.caib.es/dir3caib/rest/busqueda/organismos

##############################
# Integració amb DISTRIBUCIO #
##############################
app.helium.distribucio.regles.api.rest.url=http://10.35.3.232:8080/distribucioapi/interna
app.helium.distribucio.regles.api.rest.usuari=dis_reglaws
app.helium.distribucio.regles.api.rest.password=dis_reglaws
app.helium.distribucio.regles.api.rest.codi.backoffice=HELIUM

##############################
# Plugin de dades externes
##############################
app.dadesext.dir3.plugin.service.class=es.caib.helium.integracio.plugins.dadesext.DadesExternesPluginDir3
app.dadesext.dir3.plugin.service.url=https://dev.caib.es/dir3caib/ws/Dir3CaibObtenerCatalogos

##############################
# Integració amb el servei de portasignatures
##############################
app.portasignatures.plugin.class=es.caib.helium.integracio.plugins.portasignatures.PortasignaturesPluginPortafibSimple

#app.portasignatures.plugin.portafib.base.url=https://dev.caib.es/portafib
app.portasignatures.plugin.portafib.base.url=https://proves.caib.es/portafib
#app.portasignatures.plugin.portafib.base.url=https://se.caib.es/portafib
app.portasignatures.plugin.portafib.firmasimpleasync.url=https://proves.caib.es/portafib/common/rest/apifirmaasyncsimple/v2
#app.portasignatures.plugin.portafib.firmasimpleasync.url=https://se.caib.es/portafib/common/rest/apifirmaasyncsimple/v2
app.portasignatures.plugin.portafib.username=$helium_portafib_pre
app.portasignatures.plugin.portafib.password=helium_portafib_pre
#app.portasignatures.plugin.portafib.perfil=
# S'ha d'afegir el perfil també per enviar a firmar
app.portasignatures.plugin.portafib.perfil=FIRMAAPISIMPLE
app.portasignatures.plugin.usuari.id=codi


##############################
# Plugin de validacio de firmes
##############################
app.validatesignature.plugin.class=org.fundaciobit.plugins.validatesignature.afirmacxf.AfirmaCxfValidateSignaturePlugin

# AfirmaCxfValidateSignaturePlugin
app.plugins.validatesignature.afirmacxf.applicationID=CAIBDEV2.HELIUM
# esborrar amb el nou plugin de validació
app.plugins.validatesignature.afirmacxf.ignoreservercertificates=true
app.plugins.validatesignature.afirmacxf.TransformersTemplatesPath=c:/helium/afirma/transformers
app.plugins.validatesignature.afirmacxf.endpoint=https://afirmades2.caib.es/afirmaws/services/DSSAfirmaVerify

# CERTIFICATE Token
#app.plugins.validatesignature.afirmacxf.authorization.ks.path=/opt/helium/afirma/dgdt_proves.jks
#app.plugins.validatesignature.afirmacxf.authorization.ks.type=JKS
#app.plugins.validatesignature.afirmacxf.authorization.ks.password=12341234
#app.plugins.validatesignature.afirmacxf.authorization.ks.cert.alias=preprod-dgdt
#app.plugins.validatesignature.afirmacxf.authorization.ks.cert.password=12341234

# USERNAME-PASSWORD Token
app.plugins.validatesignature.afirmacxf.authorization.username=HELIUM
app.plugins.validatesignature.afirmacxf.authorization.password=HELIUM
app.plugins.validatesignature.afirmacxf.authorization.method=UsernameToken

##############################
# Integració amb Comanda
##############################
# Configuració per comunicar tasques.
app.comanda.api.url=https://dev.caib.es/comandaapi/interna
app.comanda.api.user=helium
app.comanda.api.password=******
# Path als logs de Helium
app.comanda.logs.location=/app/jboss-eap-7.2/standalone/logs/
