# Url base
app.base.url=http://localhost:8080/helium2back

# Opcions de visualització de la capçalera
# Color de fons de la capçalera. Per defecte app.capsalera.color.fons=#ff9523
app.capsalera.color.fons=

# Color de la lletra de la capçalera. Per defecte app.capsalera.color.lletra=white
app.capsalera.color.lletra=

# Tamany màxim permès pels arxius pujats mitjançant HTTP (en bytes)
spring.http.multipart.max-file-size=50Mb

# Per a habilitar/deshabilitar l'accés a la gestió de persones (true,false)
app.persones.actiu=true

# Per a habilitar/deshabilitar l'accés a la gestió de l'organigrama (true,false)
app.organigrama.actiu=true

# Generador del número d'expedient per defecte (alerta amb els caràcters no permesos per Alfresco)
app.numexp.expression=${seq}/${any}

# ###
# Configuració del mòdul d'identitat
# ###
# Per a fer que el mòdul identity del jBPM agafi les dades de Helium o de les taules del jBPM (helium,jbpm)
app.jbpm.identity.source=helium
# Per a fer les assignacions de les persones d'una àrea recursives
app.jbpm.identity.recursiu=true

# ###
# Paràmetres per a la conversió de documents amb OpenOffice
# ###
app.conversio.actiu=true
app.conversio.openoffice.host=localhost
app.conversio.openoffice.port=8100
# Conversió de documents generant plantilles a les tasques
app.conversio.gentasca.actiu=true
app.conversio.gentasca.extension=doc
# Conversió de documents per la signatura
app.conversio.signatura.actiu=true
app.conversio.signatura.extension=pdf
app.conversio.signatura.estampa.actiu=true
app.conversio.signatura.estampa.posx=10
app.conversio.signatura.estampa.posy=400
app.conversio.signatura.estampa.rotation=90

# ###
# Dades del calendari laborable
# ###
# Dies no laborables de la setmana (1:dilluns, ..., 7:diumenge)
app.calendari.nolabs=6,7
# Horari laboral
app.calendari.horari=8:00-14:00 & 15:00-17:00
app.calendari.horeslab.dia=8
app.calendari.horeslab.setmana=40
app.calendari.dieslab.mes=21
app.calendari.dieslab.any=220

# ###
# Enviaments de correu
# ###
app.correu.remitent=helium@helium.org
app.correu.reintents=5

# ###
# URL base per a la verificació de firmes a Custòdia Antiga
# ###
app.arxiu.verificacio.baseurl=https://dev.caib.es/concsv/view.xhtml?hash=

# ###
# Hora en què s'enviaràn els emails agrupats d'anotacions a l'usuari
# ###
app.anotacions.emails.agrupats.cron=0 0 20 * * *

# Número de threads en paral·lel per consultar anotacions
es.caib.helium.anotacions.consulta.num.threads=5

# Número de reintents per provar la consulta d'una anotació pendent
es.caib.helium.anotacions.consulta.num.intents=5

# Per indicar quin és l'entonr per diferenciar-lo en l'enviament de correus, només pels entorns previs DEV, PRE i SE
app.entorn.helium=DEV

# Període en mil·lisegons per a comprovar si hi ha execucions massives pendents
es.caib.helium.massiu.periode.noves=10000

# Timeout opcional per establir un temps màxim en segons per a la creació d'un expedient.
es.caib.helium.expedient.creacio.timout=60000


# ########
# Plugins
# ########


######################
# Plugin de Persones #
######################
#es.caib.helium.plugin.persones.class=es.caib.helium.integracio.plugins.persones.PersonesPluginJdbc
#es.caib.helium.plugin.persones.jdbc.driver=jdbc:oracle:thin:@172.0.0.1:1521:orcl
#es.caib.helium.plugin.persones.jdbc.jndi.parameter=java:comp/env/jdbc/SeyconDS
#es.caib.helium.plugin.persones.jdbc.url=jdbc:mysql://localhost:3306/db1?serverTimezone=UTC
#es.caib.helium.plugin.persones.jdbc.username=seycon
#es.caib.helium.plugin.persones.jdbc.password=****
#es.caib.helium.plugin.persones.jdbc.filter.grup=select usu_codi, usu_nom, usu_nif, usu_codi ||'@limit.es' from sc_wl_usuari u, sc_wl_usugru g where g.ugr_codgru=:grup and g.ugr_codusu=u.usu_codi
#es.caib.helium.plugin.persones.jdbc.filter.code=select usu_codi, usu_nom, usu_nif, usu_codi || '@limit.es' from sc_wl_usuari where usu_codi = :codi
#es.caib.helium.plugin.persones.jdbc.filter.name=select usu_codi, usu_nom, usu_nif, usu_codi || '@limit.es' from sc_wl_usuari where upper(usu_nom) like upper('%'||:nom||'%')
#es.caib.helium.plugin.persones.jdbc.nom.llimatges.junt=true


es.caib.helium.plugin.persones.class=es.caib.helium.integracio.plugins.persones.PersonesPluginKeycloak
es.caib.helium.plugin.persones.pluginsib.userinformation.keycloak.serverurl=https://authdev.limit.es
es.caib.helium.plugin.persones.pluginsib.userinformation.keycloak.realm=GOIB
es.caib.helium.plugin.persones.pluginsib.userinformation.keycloak.client_id=goib-ws
es.caib.helium.plugin.persones.pluginsib.userinformation.keycloak.client_id_for_user_autentication=goib-ws
es.caib.helium.plugin.persones.pluginsib.userinformation.keycloak.password_secret=****
es.caib.helium.plugin.persones.pluginsib.userinformation.keycloak.mapping.administrationID=nif
es.caib.helium.plugin.persones.pluginsib.userinformation.keycloak.debug=true


##################################
# Integració amb l'arxiu digital #
##################################
es.caib.helium.plugin.arxiu.class=es.caib.pluginsib.arxiu.caib.ArxiuPluginCaib
es.caib.helium.plugin.arxiu.pluginsib.arxiu.caib.base.url=https://esbse.caib.es:4430/esb
es.caib.helium.plugin.arxiu.pluginsib.arxiu.caib.aplicacio.codi=HELIUM
es.caib.helium.plugin.arxiu.pluginsib.arxiu.caib.usuari=helium
es.caib.helium.plugin.arxiu.pluginsib.arxiu.caib.contrasenya=****
es.caib.helium.plugin.arxiu.pluginsib.arxiu.caib.csv.definicio=CSV_DEF
es.caib.helium.plugin.arxiu.pluginsib.arxiu.caib.conversio.imprimible.url=https://se.caib.es/concsvapi/interna/printable/uuid
es.caib.helium.plugin.arxiu.pluginsib.arxiu.caib.conversio.imprimible.usuari=$helium_concsv_se
es.caib.helium.plugin.arxiu.pluginsib.arxiu.caib.conversio.imprimible.contrasenya=****

########################################################################################## #
## Intregració amb el plugin de procediments per sincronitzar els procediments amb Rolsac  #
########################################################################################## #

# Rolsac 1
#es.caib.helium.plugin.procediments.class=es.caib.helium.integracio.plugins.procediment.ProcedimentPluginRolsac
#es.caib.helium.plugin.procediments.rolsac.service.url=https://dev.caib.es/rolsac/api/rest/v1
#es.caib.helium.plugin.procediments.rolsac.service.username=$distribucio_rolsac
#es.caib.helium.plugin.procediments.rolsac.service.password=****
# Rolsac 2
es.caib.helium.plugin.procediments.class=es.caib.helium.integracio.plugins.procediment.Rolsac2ProcedimentPlugin
es.caib.helium.plugin.procediments.rolsac.service.url=https://dev.caib.es/rolsac2api/interna/services/v1
es.caib.helium.plugin.procediments.rolsac.service.username=$helium_rolsac2
es.caib.helium.plugin.procediments.rolsac.service.password=****


########################################################################################## #
## Plugin per consultar el Dir3                                                            #
########################################################################################## #

es.caib.helium.plugin.unitats.organiques.dir3.service.class=es.caib.helium.integracio.plugins.unitat.UnitatsOrganiquesPluginDir3
es.caib.helium.plugin.unitats.organiques.dir3.service.url=https://dev.caib.es/dir3caib/rest/unidades/
es.caib.helium.plugin.unitats.organiques.dir3.service.username=$helium_dir3caib
es.caib.helium.plugin.unitats.organiques.dir3.service.password=****
es.caib.helium.plugin.unitats.organiques.dir3.service.connect.timeout=300000
es.caib.helium.plugin.unitats.organiques.dir3.service.request.timeout=300000
es.caib.helium.plugin.unitats.organiques.dir3.service.log.actiu=false
es.caib.helium.plugin.unitats.organiques.dir3.service.cerca.url=https://dev.caib.es/dir3caib/rest/busqueda/organismos

##############################
# Integració amb DISTRIBUCIO #
##############################
es.caib.helium.helium.distribucio.regles.api.rest.url=http://10.35.3.232:8080/distribucioapi/interna
es.caib.helium.helium.distribucio.regles.api.rest.usuari=dis_reglaws
es.caib.helium.helium.distribucio.regles.api.rest.password=****
es.caib.helium.helium.distribucio.regles.api.rest.codi.backoffice=HELIUM

##############################
# Plugin de dades externes
##############################
es.caib.helium.plugin.dadesext.dir3.service.class=es.caib.helium.integracio.plugins.dadesext.DadesExternesPluginDir3
es.caib.helium.plugin.dadesext.dir3.service.url=https://dev.caib.es/dir3caib/ws/Dir3CaibObtenerCatalogos
es.caib.helium.plugin.dadesext.dir3.service.username=$helium_dir3caib
es.caib.helium.plugin.dadesext.dir3.service.password=****

##############################
# Integració amb el servei de portasignatures
##############################
es.caib.helium.plugin.portasignatures.class=es.caib.helium.integracio.plugins.portasignatures.PortasignaturesPluginPortafibSimple

#es.caib.helium.plugin.portasignatures.portafib.base.url=https://dev.caib.es/portafib
es.caib.helium.plugin.portasignatures.portafib.base.url=https://proves.caib.es/portafib
#es.caib.helium.plugin.portasignatures.portafib.base.url=https://se.caib.es/portafib
es.caib.helium.plugin.portasignatures.portafib.firmasimpleasync.url=https://proves.caib.es/portafib/common/rest/apifirmaasyncsimple/v2
#es.caib.helium.plugin.portasignatures.portafib.firmasimpleasync.url=https://se.caib.es/portafib/common/rest/apifirmaasyncsimple/v2
es.caib.helium.plugin.portasignatures.portafib.username=$helium_portafib_pre
es.caib.helium.plugin.portasignatures.portafib.password=****
#es.caib.helium.portasignatures.portafib.perfil=
# S'ha d'afegir el perfil també per enviar a firmar
es.caib.helium.plugin.portasignatures.portafib.perfil=FIRMAAPISIMPLE
es.caib.helium.plugin.portasignatures.usuari.id=codi


##############################
# Plugin de validacio de firmes
##############################
es.caib.helium.plugin.validatesignature.class=org.fundaciobit.plugins.validatesignature.afirmacxf.AfirmaCxfValidateSignaturePlugin

# AfirmaCxfValidateSignaturePlugin
es.caib.helium.plugin.validatesignature.afirmacxf.applicationID=CAIBDEV2.HELIUM
# esborrar amb el nou plugin de validació
es.caib.helium.plugin.validatesignature.afirmacxf.ignoreservercertificates=true
es.caib.helium.plugin.validatesignature.afirmacxf.TransformersTemplatesPath=c:/helium/afirma/transformers
es.caib.helium.plugin.validatesignature.afirmacxf.endpoint=https://afirmades2.caib.es/afirmaws/services/DSSAfirmaVerify

# CERTIFICATE Token
#es.caib.helium.plugin.validatesignature.afirmacxf.authorization.ks.path=/opt/helium/afirma/dgdt_proves.jks
#es.caib.helium.plugin.validatesignature.afirmacxf.authorization.ks.type=JKS
#es.caib.helium.plugin.validatesignature.afirmacxf.authorization.ks.password=****
#es.caib.helium.plugin.validatesignature.afirmacxf.authorization.ks.cert.alias=preprod-dgdt
#es.caib.helium.plugin.validatesignature.afirmacxf.authorization.ks.cert.password=****

# USERNAME-PASSWORD Token
es.caib.helium.plugin.validatesignature.afirmacxf.authorization.username=HELIUM
es.caib.helium.plugin.validatesignature.afirmacxf.authorization.password=****
es.caib.helium.plugin.validatesignature.afirmacxf.authorization.method=UsernameToken

##############################
# Integració amb PINBAL      #
##############################
es.caib.helium.plugin.pinbal.class=es.caib.helium.integracio.plugins.pinbal.PinbalPlugin
es.caib.helium.plugin.pinbal.plugin.url=https://proves.caib.es/pinbalapi
es.caib.helium.plugin.pinbal.username=$helium_pinbal
es.caib.helium.plugin.pinbal.password=****
es.caib.helium.plugin.pinbal.perfil=
es.caib.helium.plugin.pinbal.isJBoss=true

##############################
# Integració amb Comanda
##############################
# Configuració per comunicar tasques.
es.caib.helium.comanda.api.url=http://10.35.3.9:18180/comandaapi/interna
es.caib.helium.comanda.api.user=com_ws
es.caib.helium.comanda.api.password=****
# Path als logs de Helium
es.caib.helium.comanda.logs.location=/app/jboss-eap-7.2/standalone/logs/

