ALTER TABLE HEL_EXPEDIENT_TIPUS ADD MOTOR_TIPUS VARCHAR2(16 CHAR);
ALTER TABLE HEL_DEFINICIO_PROCES ADD MOTOR_TIPUS VARCHAR2(16 CHAR);

UPDATE HEL_EXPEDIENT_TIPUS SET MOTOR_TIPUS = 'JBPM';
UPDATE HEL_DEFINICIO_PROCES SET MOTOR_TIPUS = 'JBPM';