CREATE TABLE HEL_DOCUMENT_NOTIF_DOC (
  DOCUMENT_NOTIF_ID NUMBER(19)              NOT NULL,
  DOCUMENT_STORE_ID NUMBER(19)              NOT NULL
);

ALTER TABLE HEL_DOCUMENT_NOTIF_DOC ADD (
  CONSTRAINT HEL_DOCUMENT_NOTIFDOC_PK PRIMARY KEY (DOCUMENT_NOTIF_ID, DOCUMENT_STORE_ID));

CREATE TABLE HEL_EXPEDIENT_NOTIFICACIO (  
  ID                   NUMBER(19)               NOT NULL,
  ASSUMPTE             VARCHAR2(256)            NOT NULL,
  ESTAT                VARCHAR2(255)            NOT NULL,
  DATA_ENVIAMENT       TIMESTAMP(6)             NOT NULL,
  OBSERVACIONS         VARCHAR2(256),
  DATA_PUBLICACIO      TIMESTAMP(6),
  TIPUS                VARCHAR2(255),
  DATA_RECEPCIO        TIMESTAMP(6),
  REGISTRE_NUM         VARCHAR2(100),
  INTER_DOCNUM        VARCHAR2(100),
  INTER_DOCTIP        NUMBER(10),
  INTER_EMAIL         VARCHAR2(160),
  INTER_LLING1        VARCHAR2(100),
  INTER_LLING2        VARCHAR2(100),
  INTER_NOM           VARCHAR2(100),
  INTER_PAICOD        VARCHAR2(100),
  INTER_PRVCOD        VARCHAR2(100),
  INTER_MUNCOD        VARCHAR2(100),
  INTER_REPRES        NUMBER(1),
  UNITAT_ADM           VARCHAR2(100),
  ORGAN_CODI           VARCHAR2(100),
  OFICINA_CODI          VARCHAR2(100),
  AVIS_TITOL           VARCHAR2(256),
  AVIS_TEXT            VARCHAR2(1024),
  AVIS_TEXTSMS         VARCHAR2(200),
  OFICI_TITOL          VARCHAR2(256),
  OFICI_TEXT           VARCHAR2(1024),
  IDIOMA               VARCHAR2(32),
  ENVIAM_DATA          TIMESTAMP(6),
  ENVIAM_COUNT         NUMBER(10),
  ENVIAM_ERROR         NUMBER(1),
  ENVIAM_ERROR_DESC    VARCHAR2(2048),
  PROCES_DATA          TIMESTAMP(6),
  PROCES_COUNT         NUMBER(10),
  PROCES_ERROR         NUMBER(1),
  PROCES_ERROR_DESC    VARCHAR2(2048),
  DOCUMENT_STORE_ID    NUMBER(19)               NOT NULL,
  EXPEDIENT_ID         NUMBER(19)               NOT NULL,
  RDS_CODI			   NUMBER(19),
  RDS_CLAU			   VARCHAR2(255),
  ERROR_NOTIFICACIO	   VARCHAR2(1024)
);

CREATE INDEX HEL_NOTIFICACIO_EXPEDIENT_ID_I ON HEL_EXPEDIENT_NOTIFICACIO (EXPEDIENT_ID);

ALTER TABLE HEL_EXPEDIENT_NOTIFICACIO ADD (
  CONSTRAINT HEL_NOTIF_PK PRIMARY KEY (ID),
  CONSTRAINT HEL_NOTIF_MULT_UK UNIQUE (EXPEDIENT_ID, DOCUMENT_STORE_ID, ASSUMPTE, DATA_ENVIAMENT, TIPUS, INTER_DOCTIP, INTER_DOCNUM));
  
ALTER TABLE HEL_EXPEDIENT_NOTIFICACIO ADD (
  CONSTRAINT HEL_EXPEDIENT_NOTIF_FK FOREIGN KEY (EXPEDIENT_ID) 
 REFERENCES HEL_EXPEDIENT (ID),
  CONSTRAINT HEL_DOCUMENT_NOTIF_FK FOREIGN KEY (DOCUMENT_STORE_ID) 
 REFERENCES HEL_DOCUMENT_STORE (ID));

ALTER TABLE HEL_DOCUMENT_NOTIF_DOC ADD (
  CONSTRAINT HEL_DOCUMENT_NOTIFDOC_NOTIF_FK FOREIGN KEY (DOCUMENT_NOTIF_ID) 
    REFERENCES HEL_EXPEDIENT_NOTIFICACIO (ID),
  CONSTRAINT HEL_DOCUMENT_NOTIFDOC_DOC_FK FOREIGN KEY (DOCUMENT_STORE_ID) 
    REFERENCES HEL_DOCUMENT_STORE (ID));
    







