/**
 * 
 */
package net.conselldemallorca.helium.v3.core.repository;

import java.util.Date;
import java.util.List;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.Query;
import org.springframework.data.repository.query.Param;

import net.conselldemallorca.helium.core.model.hibernate.ExplotacioFets;

/**
 * @author Limit Tecnologies <limit@limit.es>
 */
public interface ExplotacioFetsRepository extends JpaRepository<ExplotacioFets, Long> {
	
	@Query(value =    "	SELECT "
					+ "		ENTORN_ID AS entornId,"
					+ "		TIPUS_ID AS tipusExpedientId,"
					+ "		UNITAT_ORGANITZATIVA_ID AS unitatOrganitzativaId,"
					+ "		SUM(expedientsOberts) AS expedientsOberts,"
					+ "		SUM(expedientsTancats) AS expedientsTancats,"
					+ "		SUM(expedientsAnulats) AS expedientsAnulats,"
					+ "		SUM(expedientsArxiu) AS expedientsArxiu,"
					+ "		SUM(expedientsNoAnulats) AS expedientsNoAnulats,"
					+ "		SUM(expedientsTotals) AS expedientsTotals,"
					+ "		SUM(tasquesPendents) AS tasquesPendents,"
					+ "		SUM(tasquesFinalitzades) AS tasquesFinalitzades,"
					+ "		SUM(anotacionPendents) AS anotacionPendents,"
					+ "		SUM(anotacionProcessades) AS anotacionProcessades,"
					+ "		SUM(peticionsPinbal) AS peticionsPinbal,"
					+ "		SUM(peticionsPortafib) AS peticionsPortafib,"
					+ "		SUM(peticionsNotib) AS peticionsNotib"
					+ "	FROM (SELECT * "
					+ "	FROM "
					+ "	( "
					+ "	SELECT "
					+ "		ep.ENTORN_ID, "
					+ "		ep.TIPUS_ID, "
					+ "		ep.UNITAT_ORGANITZATIVA_ID, "
					+ "		SUM(ep.expedientsOberts) AS expedientsOberts, "
					+ "		SUM(ep.expedientsTancats) AS expedientsTancats , "
					+ "		SUM(CASE WHEN ep.anulat = 1 AND trunc(ep.DATA_ANULAT) = trunc(:data) THEN 1 ELSE 0 END) AS expedientsAnulats, "
					+ "		SUM(ep.expedientsArxiu) AS expedientsArxiu, "
					+ "		SUM(ep.expedientsNoAnulats) AS expedientsNoAnulats, "
					+ "		SUM(ep.expedientsTotals) AS expedientsTotals, "
					+ "		0 AS tasquesPendents, "
					+ "		0 AS tasquesFinalitzades, "
					+ "		0 AS anotacionPendents, "
					+ "		0 AS anotacionProcessades, "
					+ "		0 AS peticionsPinbal, "
					+ "		0 AS peticionsPortafib, "
					+ "		0 AS peticionsNotib "
					+ "	FROM ( "
					+ "		SELECT "
					+ "			e.ENTORN_ID, "
					+ "			e.TIPUS_ID, "
					+ "			e.UNITAT_ORGANITZATIVA_ID, "
					+ "			SUM(CASE WHEN trunc(e.data_Inici) = trunc(:data) THEN 1 ELSE 0 END) AS expedientsOberts, "
					+ "			SUM(CASE WHEN e.data_Fi IS NOT NULL AND trunc(e.data_Fi) = trunc(:data) THEN 1 ELSE 0 END) AS expedientsTancats, "
					+ "			SUM(CASE WHEN e.arxiu_Actiu = 1 AND e.arxiu_Uuid IS NOT NULL AND trunc(e.data_Inici) = trunc(:data) THEN 1 ELSE 0 END) AS expedientsArxiu, "
					+ "			SUM(CASE WHEN (trunc(e.data_Inici) = trunc(:data) AND (e.anulat is null OR e.anulat = 0)) THEN 1 ELSE 0 END) AS expedientsNoAnulats, "
					+ "			SUM(CASE WHEN trunc(e.data_Inici) = trunc(:data) THEN 1 ELSE 0 END) AS expedientsTotals, "
					+ "			e.anulat, "
					+ "			MAX(rr.DATA) AS DATA_ANULAT "
					+ "		FROM "
					+ "			HEL_EXPEDIENT e LEFT JOIN HEL_REGISTRE rr ON rr.EXPEDIENT_ID = e.ID AND rr.ACCIO = 9 "
					+ "		WHERE  "
					+ "			trunc(e.data_Inici) <= trunc(:data) OR "
					+ "			trunc(e.data_Fi) <= trunc(:data) "
					+ "		GROUP BY  "
					+ "			e.ENTORN_ID, "
					+ "			e.TIPUS_ID, "
					+ "			e.UNITAT_ORGANITZATIVA_ID, "
					+ "			e.anulat "
					+ "	) ep "
					+ "	GROUP BY  "
					+ "		ep.ENTORN_ID, "
					+ "		ep.TIPUS_ID, "
					+ "		ep.UNITAT_ORGANITZATIVA_ID "
					+ "	) UNION"
					+ "	("
					+ "		SELECT  e.ENTORN_ID,"
					+ "				e.TIPUS_ID,"
					+ "				e.UNITAT_ORGANITZATIVA_ID,"
					+ "				0 AS expedientsOberts,"
					+ "				0 AS expedientsTancats,"
					+ "				0 AS expedientsAnulats,"
					+ "				0 AS expedientsArxiu,"
					+ "				0 AS expedientsNoAnulats,"
					+ "				0 AS expedientsTotals,"
					+ "				SUM(CASE WHEN jt.CREATE_ IS NOT NULL AND jt.END_ IS NULL THEN 1 ELSE 0 END) AS tasquesPendents,"
					+ "				SUM(CASE WHEN jt.END_ IS NOT NULL THEN 1 ELSE 0 END) AS tasquesFinalitzades,"
					+ "				0 AS anotacionPendents,"
					+ "				0 AS anotacionProcessades,"
					+ "				0 AS peticionsPinbal,"
					+ "				0 AS peticionsPortafib,"
					+ "				0 AS peticionsNotib"
					+ "		FROM "
					+ "			JBPM_TASKINSTANCE jt, "
					+ "			JBPM_PROCESSINSTANCE jp,"
					+ "			HEL_EXPEDIENT e"
					+ "		WHERE"
					+ "		jt.PROCINST_ = jp.ID_ AND"
					+ "		jp.EXPEDIENT_ID_ = e.ID AND"
					+ "		((trunc(jt.CREATE_) = trunc(:data) OR trunc(jt.END_) = trunc(:data)))"
					+ "		GROUP BY e.ENTORN_ID, e.TIPUS_ID, e.UNITAT_ORGANITZATIVA_ID"
					+ "	) UNION "
					+ "	("
					+ "		SELECT"
					+ "			et.ENTORN_ID,"
					+ "			et.ID AS TIPUS_ID,"
					+ "			(CASE WHEN a.EXPEDIENT_ID IS NOT NULL THEN e.UNITAT_ORGANITZATIVA_ID ELSE NULL END) AS UNITAT_ORGANITZATIVA_ID,"
					+ "			0 AS expedientsOberts,"
					+ "			0 AS expedientsTancats,"
					+ "			0 AS expedientsAnulats,"
					+ "			0 AS expedientsArxiu,"
					+ "			0 AS expedientsNoAnulats,"
					+ "			0 AS expedientsTotals,"
					+ "			0 AS tasquesPendents,"
					+ "			0 AS tasquesFinalitzades,"
					+ "			SUM(CASE WHEN a.estat = 0 OR a.estat = 5 THEN 1 ELSE 0 END) AS anotacionPendents,"
					+ "			SUM(CASE WHEN a.estat = 1 AND (trunc(a.data_Processament) = trunc(:data)) THEN 1 ELSE 0 END) AS anotacionProcessades,"
					+ "			0 AS peticionsPinbal,"
					+ "			0 AS peticionsPortafib,"
					+ "			0 AS peticionsNotib"
					+ "		FROM"
					+ "			HEL_ANOTACIO a LEFT JOIN HEL_EXPEDIENT e ON e.ID = a.EXPEDIENT_ID LEFT JOIN HEL_EXPEDIENT_TIPUS et ON a.EXPEDIENT_TIPUS_ID = et.ID"
					+ "		GROUP BY "
					+ "			et.ENTORN_ID,"
					+ "			et.ID,"
					+ "			a.EXPEDIENT_ID,"
					+ "			e.UNITAT_ORGANITZATIVA_ID"
					+ "	) union"
					+ "	("
					+ "		SELECT"
					+ "			pp.ENTORN_ID,"
					+ "			pp.TIPUS_ID,"
					+ "			e.UNITAT_ORGANITZATIVA_ID AS UNITAT_ORGANITZATIVA_ID,"
					+ "			0 AS expedientsOberts,"
					+ "			0 AS expedientsTancats,"
					+ "			0 AS expedientsAnulats,"
					+ "			0 AS expedientsArxiu,"
					+ "			0 AS expedientsNoAnulats,"
					+ "			0 AS expedientsTotals,"
					+ "			0 AS tasquesPendents,"
					+ "			0 AS tasquesFinalitzades,"
					+ "			0 AS anotacionPendents,"
					+ "			0 AS anotacionProcessades,"
					+ "			COUNT(pp.id) AS peticionsPinbal,"
					+ "			0 AS peticionsPortafib,"
					+ "			0 AS peticionsNotib"
					+ "		FROM"
					+ "			HEL_PETICIO_PINBAL pp LEFT JOIN HEL_EXPEDIENT e ON e.ID = pp.EXPEDIENT_ID"
					+ "		WHERE"
					+ "			(trunc(pp.DATA_Peticio) = trunc(:data))"
					+ "		GROUP BY "
					+ "			pp.ENTORN_ID,"
					+ "			pp.TIPUS_ID,"
					+ "			e.UNITAT_ORGANITZATIVA_ID"
					+ "	) union"
					+ "	("
					+ "		SELECT"
					+ "			e.ENTORN_ID,"
					+ "			e.TIPUS_ID,"
					+ "			e.UNITAT_ORGANITZATIVA_ID,"
					+ "			0 AS expedientsOberts,"
					+ "			0 AS expedientsTancats,"
					+ "			0 AS expedientsAnulats,"
					+ "			0 AS expedientsArxiu,"
					+ "			0 AS expedientsNoAnulats,"
					+ "			0 AS expedientsTotals,"
					+ "			0 AS tasquesPendents,"
					+ "			0 AS tasquesFinalitzades,"
					+ "			0 AS anotacionPendents,"
					+ "			0 AS anotacionProcessades,"
					+ "			0 AS peticionsPinbal,"
					+ "			COUNT(ps.id) AS peticionsPortafib,"
					+ "			0 AS peticionsNotib"
					+ "		FROM"
					+ "			HEL_PORTASIGNATURES ps LEFT JOIN HEL_EXPEDIENT e ON e.ID = ps.EXPEDIENT_ID"
					+ "		WHERE"
					+ "			(trunc(ps.data_Enviat) = trunc(:data))"
					+ "		GROUP BY "
					+ "			e.ENTORN_ID,"
					+ "			e.TIPUS_ID,"
					+ "			e.UNITAT_ORGANITZATIVA_ID"
					+ "	) union"
					+ "	("
					+ "		SELECT"
					+ "			e.ENTORN_ID,"
					+ "			e.TIPUS_ID,"
					+ "			e.UNITAT_ORGANITZATIVA_ID,"
					+ "			0 AS expedientsOberts,"
					+ "			0 AS expedientsTancats,"
					+ "			0 AS expedientsAnulats,"
					+ "			0 AS expedientsArxiu,"
					+ "			0 AS expedientsNoAnulats,"
					+ "			0 AS expedientsTotals,"
					+ "			0 AS tasquesPendents,"
					+ "			0 AS tasquesFinalitzades,"
					+ "			0 AS anotacionPendents,"
					+ "			0 AS anotacionProcessades,"
					+ "			0 AS peticionsPinbal,"
					+ "			0 AS peticionsPortafib,"
					+ "			COUNT(dn.id) AS peticionsNotib"
					+ "		FROM"
					+ "			HEL_DOCUMENT_NOTIFICACIO dn LEFT JOIN HEL_EXPEDIENT e ON e.ID = dn.EXPEDIENT_ID"
					+ "		WHERE"
					+ "			(trunc(dn.ENVIAT_DATA) = trunc(:data))"
					+ "		GROUP BY "
					+ "			e.ENTORN_ID,"
					+ "			e.TIPUS_ID,"
					+ "			e.UNITAT_ORGANITZATIVA_ID) "
					+ "	) "
					+ "	GROUP BY "
					+ "		ENTORN_ID, "
					+ "		TIPUS_ID, "
					+ "		UNITAT_ORGANITZATIVA_ID"
					+ "	ORDER BY "
					+ "		UNITAT_ORGANITZATIVA_ID, "
					+ "		ENTORN_ID, "
					+ "		TIPUS_ID "
					, nativeQuery = true)
	public List<Object[]> getFetsPerEstadistiques(
			@Param("data") Date data);

	@Query("from ExplotacioFets ef where ef.temps.id = :tempsId order by ef.dimensio.unitatOrganitzativaId, ef.dimensio.unitatOrganitzativaCodi, ef.dimensio.entornId, ef.dimensio.entornCodi, ef.dimensio.tipusId, ef.dimensio.tipusCodi")
	public List<ExplotacioFets> findByTempsId(@Param("tempsId") Long tempsId);
}
