
-- Actualització a la nova versió --
INSERT INTO HEL_VERSIO (
    ID,
    CODI,
    ORDRE,
    DATA_CREACIO,
    PROCES_EXECUTAT,
    SCRIPT_EXECUTAT,
    DATA_EXECUCIO_SCRIPT)
SELECT
    HIBERNATE_SEQUENCE.NEXTVAL ID,
    '3.1.0' CODI,
    310 ORDRE,
    SYSDATE DATA_CREACIO,
    0 PROCES_EXECUTAT,
    1 SCRIPT_EXECUTAT,
    SYSDATE DATA_EXECUCIO_SCRIPT
FROM DUAL
WHERE (SELECT COUNT(*) FROM HEL_VERSIO WHERE ORDRE = 310) = 0;

-- Per a permetre desar informació per a poder realitzar la retroacció de l'expedient
ALTER TABLE HEL_EXPEDIENT_TIPUS ADD AMB_RETROACCIO NUMBER(1) DEFAULT 0 NOT NULL;
ALTER TABLE HEL_EXPEDIENT_TIPUS ADD REINDEXACIO_ASINCRONA NUMBER(1) DEFAULT 0 NOT NULL;
ALTER TABLE HEL_EXPEDIENT ADD AMB_RETROACCIO NUMBER(1) DEFAULT 1 NOT NULL;
ALTER TABLE HEL_EXPEDIENT ADD REINDEXAR_DATA TIMESTAMP(6);
ALTER TABLE HEL_EXPEDIENT ADD REINDEXAR_ERROR NUMBER(1) DEFAULT 0 NOT NULL;

-- Nova columna per a incloure l'eliminació de definicions de procés com a execucions massives
ALTER TABLE HEL_EXEC_MASEXP ADD DEFPROC_ID NUMBER(19);
ALTER TABLE HEL_EXEC_MASEXP ADD AUX_TEXT VARCHAR2(255 CHAR);

--------------------------------------------------------
-- TASQUES EN SEGÓN PLA
--------------------------------------------------------
ALTER TABLE
	JBPM_TASKINSTANCE 
ADD (
	MARCADAFINALITZAR_ TIMESTAMP(6),
	INICIFINALITZACIO_ TIMESTAMP(6),
	ERRORFINALITZACIO_ VARCHAR2(1000 CHAR),
	TITOLACTUALITZAT_ NUMBER(1),
	SELECTEDOUTCOME_ VARCHAR2(255 CHAR)
);

UPDATE JBPM_TASKINSTANCE
SET 
	TITOLACTUALITZAT_ = 0
;

ALTER TABLE
	JBPM_TASKINSTANCE
MODIFY (
	TITOLACTUALITZAT_ NUMBER(1) DEFAULT 0 NOT NULL
);


ALTER TABLE
	HEL_TASCA
ADD (
	FIN_SEGON_PLA NUMBER(1)
);

UPDATE HEL_TASCA
SET FIN_SEGON_PLA = 1;

ALTER TABLE
	HEL_TASCA
MODIFY (
	FIN_SEGON_PLA NUMBER(1) DEFAULT 1 NOT NULL
);

--Afegim la columan TIMEOUT per a la taula de dominis
ALTER TABLE HEL_DOMINI ADD TIMEOUT NUMBER(10);

--------------------------------------------------------
-- EXECUCIONS MASSIVES
--------------------------------------------------------
ALTER TABLE HEL_EXEC_MASSIVA 
ADD (
	ROLS VARCHAR2(2000 CHAR) NULL,
	CREDENCIALS RAW(2000) NULL
);

-- Index per a consulta d'operaicons massives pendents --
CREATE INDEX HEL_EXMASEXP_EXEMAS_I ON HEL_EXEC_MASEXP (EXECMAS_ID);

-- Index per a swimlaneinstance de jbpm --
CREATE INDEX JBPM_SWIMLANEINSTANCE_I ON JBPM_SWIMLANEINSTANCE (TASKMGMTINSTANCE_);

-- Actualització a la nova versió --
INSERT INTO HEL_VERSIO (
    ID,
    CODI,
    ORDRE,
    DATA_CREACIO,
    PROCES_EXECUTAT,
    SCRIPT_EXECUTAT,
    DATA_EXECUCIO_SCRIPT)
SELECT
    HIBERNATE_SEQUENCE.NEXTVAL ID,
    '3.1.0' CODI,
    310 ORDRE,
    SYSDATE DATA_CREACIO,
    0 PROCES_EXECUTAT,
    1 SCRIPT_EXECUTAT,
    SYSDATE DATA_EXECUCIO_SCRIPT
FROM DUAL
WHERE (SELECT COUNT(*) FROM HEL_VERSIO WHERE ORDRE = 310) = 0;