
-- Actualització a la nova versió --
INSERT INTO HEL_VERSIO (
    ID,
    CODI,
    ORDRE,
    DATA_CREACIO,
    PROCES_EXECUTAT,
    SCRIPT_EXECUTAT,
    DATA_EXECUCIO_SCRIPT)
SELECT
    HIBERNATE_SEQUENCE.NEXTVAL ID,
    '3.1.0' CODI,
    310 ORDRE,
    SYSDATE DATA_CREACIO,
    0 PROCES_EXECUTAT,
    1 SCRIPT_EXECUTAT,
    SYSDATE DATA_EXECUCIO_SCRIPT
FROM DUAL
WHERE (SELECT COUNT(*) FROM HEL_VERSIO WHERE ORDRE = 310) = 0;

-- Per a permetre desar informació per a poder realitzar la retroacció de l'expedient
ALTER TABLE HEL_EXPEDIENT_TIPUS ADD AMB_RETROACCIO NUMBER(1) DEFAULT 0 NOT NULL;
ALTER TABLE HEL_EXPEDIENT_TIPUS ADD REINDEXACIO_ASINCRONA NUMBER(1) DEFAULT 0 NOT NULL;
ALTER TABLE HEL_EXPEDIENT_TIPUS ADD NOTIFICACIONS_ACTIVADES NUMBER(1) DEFAULT 0 NOT NULL;
ALTER TABLE HEL_EXPEDIENT_TIPUS ADD NOTIFICACIO_ORGANCODI VARCHAR2(9 );
ALTER TABLE HEL_EXPEDIENT_TIPUS ADD NOTIFICACIO_OFICINACODI VARCHAR2(4);
ALTER TABLE HEL_EXPEDIENT_TIPUS ADD NOTIFICACIO_UNITATADMIN VARCHAR2(9);
ALTER TABLE HEL_EXPEDIENT_TIPUS ADD NOTIFICACIO_CODPROC VARCHAR2(30);
ALTER TABLE HEL_EXPEDIENT_TIPUS ADD NOTIFICACIO_AVISTITOL VARCHAR2(256);
ALTER TABLE HEL_EXPEDIENT_TIPUS ADD NOTIFICACIO_AVISTEXT VARCHAR2(1024);
ALTER TABLE HEL_EXPEDIENT_TIPUS ADD NOTIFICACIO_AVISTEXTSMS VARCHAR2(200);
ALTER TABLE HEL_EXPEDIENT_TIPUS ADD NOTIFICACIO_OFICITITOL VARCHAR2(256);
ALTER TABLE HEL_EXPEDIENT_TIPUS ADD NOTIFICACIO_OFICITEXT VARCHAR2(1024);
ALTER TABLE HEL_EXPEDIENT ADD AMB_RETROACCIO NUMBER(1) DEFAULT 1 NOT NULL;
ALTER TABLE HEL_EXPEDIENT ADD REINDEXAR_DATA TIMESTAMP(6);
ALTER TABLE HEL_EXPEDIENT ADD REINDEXAR_ERROR NUMBER(1) DEFAULT 0 NOT NULL;

-- Nova columna per a incloure l'eliminació de definicions de procés com a execucions massives
ALTER TABLE HEL_EXEC_MASEXP ADD DEFPROC_ID NUMBER(19);
ALTER TABLE HEL_EXEC_MASEXP ADD AUX_TEXT VARCHAR2(255 CHAR);

--------------------------------------------------------
-- TASQUES EN SEGÓN PLA
--------------------------------------------------------
ALTER TABLE
	JBPM_TASKINSTANCE 
ADD (
	MARCADAFINALITZAR_ TIMESTAMP(6),
	INICIFINALITZACIO_ TIMESTAMP(6),
	ERRORFINALITZACIO_ VARCHAR2(1000 CHAR),
	TITOLACTUALITZAT_ NUMBER(1),
	SELECTEDOUTCOME_ VARCHAR2(255 CHAR)
);

UPDATE JBPM_TASKINSTANCE
SET 
	TITOLACTUALITZAT_ = 0
;

ALTER TABLE
	JBPM_TASKINSTANCE
MODIFY (
	TITOLACTUALITZAT_ NUMBER(1) DEFAULT 0 NOT NULL
);


ALTER TABLE
	HEL_TASCA
ADD (
	FIN_SEGON_PLA NUMBER(1)
);

UPDATE HEL_TASCA
SET FIN_SEGON_PLA = 1;

ALTER TABLE
	HEL_TASCA
MODIFY (
	FIN_SEGON_PLA NUMBER(1) DEFAULT 1 NOT NULL
);

--Afegim la columan TIMEOUT per a la taula de dominis
ALTER TABLE HEL_DOMINI ADD TIMEOUT NUMBER(10);

--------------------------------------------------------
-- EXECUCIONS MASSIVES
--------------------------------------------------------
ALTER TABLE HEL_EXEC_MASSIVA 
ADD (
	ROLS VARCHAR2(2000 CHAR) NULL,
	CREDENCIALS RAW(2000) NULL
);

-- Index per a consulta d'operaicons massives pendents --
CREATE INDEX HEL_EXMASEXP_EXEMAS_I ON HEL_EXEC_MASEXP (EXECMAS_ID);

-- Index per a swimlaneinstance de jbpm --
CREATE INDEX JBPM_SWIMLANEINSTANCE_I ON JBPM_SWIMLANEINSTANCE (TASKMGMTINSTANCE_);

-- Actualització a la nova versió --
INSERT INTO HEL_VERSIO (
    ID,
    CODI,
    ORDRE,
    DATA_CREACIO,
    PROCES_EXECUTAT,
    SCRIPT_EXECUTAT,
    DATA_EXECUCIO_SCRIPT)
SELECT
    HIBERNATE_SEQUENCE.NEXTVAL ID,
    '3.1.0' CODI,
    310 ORDRE,
    SYSDATE DATA_CREACIO,
    0 PROCES_EXECUTAT,
    1 SCRIPT_EXECUTAT,
    SYSDATE DATA_EXECUCIO_SCRIPT
FROM DUAL
WHERE (SELECT COUNT(*) FROM HEL_VERSIO WHERE ORDRE = 310) = 0;


--Notificacions
CREATE TABLE HEL_EXPEDIENT_NOTIFICACIO (  
  ID                   NUMBER(19)               NOT NULL,
  ASSUMPTE             VARCHAR2(256)            NOT NULL,
  ESTAT                VARCHAR2(255)            NOT NULL,
  DATA_ENVIAMENT       TIMESTAMP(6)             NOT NULL,
  OBSERVACIONS         VARCHAR2(256),
  DATA_PUBLICACIO      TIMESTAMP(6),
  TIPUS                VARCHAR2(255),
  DATA_RECEPCIO        TIMESTAMP(6),
  REGISTRE_NUM         VARCHAR2(100),
  INTER_DOCNUM        VARCHAR2(17),
  INTER_DOCTIP        NUMBER(10),
  INTER_EMAIL         VARCHAR2(160),
  INTER_LLING1        VARCHAR2(30),
  INTER_LLING2        VARCHAR2(30),
  INTER_NOM           VARCHAR2(30),
  INTER_PAICOD        VARCHAR2(4),
  INTER_PRVCOD        VARCHAR2(2),
  INTER_MUNCOD        VARCHAR2(5),
  INTER_REPRES        NUMBER(1),
  UNITAT_ADM           VARCHAR2(9),
  ORGAN_CODI           VARCHAR2(9),
  OFICINA_CODI          VARCHAR2(4),
  AVIS_TITOL           VARCHAR2(256),
  AVIS_TEXT            VARCHAR2(1024),
  AVIS_TEXTSMS         VARCHAR2(200),
  OFICI_TITOL          VARCHAR2(256),
  OFICI_TEXT           VARCHAR2(1024),
  IDIOMA               VARCHAR2(2),
  ENVIAM_DATA          TIMESTAMP(6),
  ENVIAM_COUNT         NUMBER(10),
  ENVIAM_ERROR         NUMBER(1),
  ENVIAM_ERROR_DESC    VARCHAR2(2048),
  PROCES_DATA          TIMESTAMP(6),
  PROCES_COUNT         NUMBER(10),
  PROCES_ERROR         NUMBER(1),
  PROCES_ERROR_DESC    VARCHAR2(2048),
  DOCUMENT_STORE_ID    NUMBER(19)               NOT NULL,
  EXPEDIENT_ID         NUMBER(19)               NOT NULL,
  RDS_CODI			   NUMBER(19),
  RDS_CLAU			   VARCHAR2(255),
  ERROR_NOTIFICACIO	   VARCHAR2(1024)
);

CREATE TABLE HEL_DOCUMENT_NOTIF_DOC (
  DOCUMENT_NOTIF_ID NUMBER(19)              NOT NULL,
  DOCUMENT_STORE_ID NUMBER(19)              NOT NULL
);

CREATE INDEX HEL_NOTIFICACIO_EXPEDIENT_ID_I ON 
HEL_EXPEDIENT_NOTIFICACIO 
(EXPEDIENT_ID);

 
 ALTER TABLE HEL_EXPEDIENT_NOTIFICACIO ADD (
  CONSTRAINT HEL_NOTIF_PK PRIMARY KEY (ID),
  CONSTRAINT HEL_NOTIF_MULT_UK UNIQUE (EXPEDIENT_ID, DOCUMENT_STORE_ID, ASSUMPTE, DATA_ENVIAMENT, TIPUS, INTER_DOCTIP, INTER_DOCNUM));

 
 ALTER TABLE HEL_EXPEDIENT_NOTIFICACIO ADD (
  CONSTRAINT HEL_EXPEDIENT_NOTIF_FK FOREIGN KEY (EXPEDIENT_ID) 
 REFERENCES HEL_EXPEDIENT (ID),
  CONSTRAINT HEL_DOCUMENT_NOTIF_FK FOREIGN KEY (DOCUMENT_STORE_ID) 
 REFERENCES HEL_DOCUMENT_STORE (ID));
	
	
ALTER TABLE HEL_DOCUMENT_NOTIF_DOC ADD (
  CONSTRAINT HEL_DOCUMENT_NOTIFDOC_PK PRIMARY KEY (DOCUMENT_NOTIF_ID, DOCUMENT_STORE_ID));
  
ALTER TABLE HEL_DOCUMENT_NOTIF_DOC ADD (
  CONSTRAINT HEL_DOCUMENT_NOTIFDOC_NOTIF_FK FOREIGN KEY (DOCUMENT_NOTIF_ID) 
    REFERENCES HEL_EXPEDIENT_NOTIFICACIO (ID),
  CONSTRAINT HEL_DOCUMENT_NOTIFDOC_DOC_FK FOREIGN KEY (DOCUMENT_STORE_ID) 
    REFERENCES HEL_DOCUMENT_STORE (ID));