/*
 * HeliumMS Dominis API
 * Microservei de Dominis de HeliumMS
 *
 * OpenAPI spec version: 1.0.0
 * Contact: limit@limit.es
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package net.conselldemallorca.helium.ms.domini.client.model;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * FilaResultat
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2021-04-15T16:51:41.639+02:00[Europe/Paris]")
public class FilaResultat {
	@JsonProperty("columnes")
	private List<ParellaCodiValor> columnes = null;

	public FilaResultat columnes(List<ParellaCodiValor> columnes) {
		this.columnes = columnes;
		return this;
	}

	public FilaResultat addColumnesItem(ParellaCodiValor columnesItem) {
		if (this.columnes == null) {
			this.columnes = new ArrayList<ParellaCodiValor>();
		}
		this.columnes.add(columnesItem);
		return this;
	}

	/**
	 * Get columnes
	 * 
	 * @return columnes
	 **/
	public List<ParellaCodiValor> getColumnes() {
		return columnes;
	}

	public void setColumnes(List<ParellaCodiValor> columnes) {
		this.columnes = columnes;
	}

	@Override
	public boolean equals(java.lang.Object o) {
		if (this == o) {
			return true;
		}
		if (o == null || getClass() != o.getClass()) {
			return false;
		}
		FilaResultat filaResultat = (FilaResultat) o;
		return Objects.equals(this.columnes, filaResultat.columnes);
	}

	@Override
	public int hashCode() {
		return Objects.hash(columnes);
	}

	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append("class FilaResultat {\n");

		sb.append("    columnes: ").append(toIndentedString(columnes)).append("\n");
		sb.append("}");
		return sb.toString();
	}

	/**
	 * Convert the given object to string with each line indented by 4 spaces
	 * (except the first line).
	 */
	private String toIndentedString(java.lang.Object o) {
		if (o == null) {
			return "null";
		}
		return o.toString().replace("\n", "\n    ");
	}

}
