/*
 * HeliumMS Dominis API
 * Microservei de Dominis de HeliumMS
 *
 * OpenAPI spec version: 1.0.0
 * Contact: limit@limit.es
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package net.conselldemallorca.helium.ms.domini.client.model;

import java.util.Objects;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * ParellaCodiValor
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2021-04-15T16:51:41.639+02:00[Europe/Paris]")
public class ParellaCodiValor {
	@JsonProperty("codi")
	private String codi = null;

	@JsonProperty("valor")
	private Object valor = null;

	public ParellaCodiValor codi(String codi) {
		this.codi = codi;
		return this;
	}

	/**
	 * Get codi
	 * 
	 * @return codi
	 **/
	public String getCodi() {
		return codi;
	}

	public void setCodi(String codi) {
		this.codi = codi;
	}

	public ParellaCodiValor valor(Object valor) {
		this.valor = valor;
		return this;
	}

	/**
	 * Get valor
	 * 
	 * @return valor
	 **/
	public Object getValor() {
		return valor;
	}

	public void setValor(Object valor) {
		this.valor = valor;
	}

	@Override
	public boolean equals(java.lang.Object o) {
		if (this == o) {
			return true;
		}
		if (o == null || getClass() != o.getClass()) {
			return false;
		}
		ParellaCodiValor parellaCodiValor = (ParellaCodiValor) o;
		return Objects.equals(this.codi, parellaCodiValor.codi) && Objects.equals(this.valor, parellaCodiValor.valor);
	}

	@Override
	public int hashCode() {
		return Objects.hash(codi, valor);
	}

	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append("class ParellaCodiValor {\n");

		sb.append("    codi: ").append(toIndentedString(codi)).append("\n");
		sb.append("    valor: ").append(toIndentedString(valor)).append("\n");
		sb.append("}");
		return sb.toString();
	}

	/**
	 * Convert the given object to string with each line indented by 4 spaces
	 * (except the first line).
	 */
	private String toIndentedString(java.lang.Object o) {
		if (o == null) {
			return "null";
		}
		return o.toString().replace("\n", "\n    ");
	}

}
