ALTER TABLE HEL_USUARI_PREFS
ADD ( CABECERA_REDUCIDA NUMBER(1) NULL  ) 
ADD ( LISTADO NUMBER(1) NULL  ) 
ADD ( CONSULTA_ID NUMBER(19) NULL  ) 
ADD ( FILTRO_TAREAS_ACTIVAS NUMBER(1) NULL  ) 
ADD ( NUM_ELEMENTOS_PAGINA NUMBER(3) NULL  ) ;

ALTER TABLE HEL_USUARI_PREFS ADD ( DEFAULT_TIPUS_EXPEDIENT NUMBER(19) NULL  ) ;

-- Actualització a la nova versió --
INSERT INTO HEL_VERSIO (
    ID,
    CODI,
    ORDRE,
    DATA_CREACIO,
    PROCES_EXECUTAT,
    SCRIPT_EXECUTAT,
    DATA_EXECUCIO_SCRIPT)
SELECT
    HIBERNATE_SEQUENCE.NEXTVAL ID,
    '3.0.0' CODI,
    300 ORDRE,
    SYSDATE DATA_CREACIO,
    0 PROCES_EXECUTAT,
    1 SCRIPT_EXECUTAT,
    SYSDATE DATA_EXECUCIO_SCRIPT
FROM DUAL
WHERE (SELECT COUNT(*) FROM HEL_VERSIO WHERE ORDRE = 300) = 0;
