
package net.conselldemallorca.helium.integracio.domini.service.wsdl;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.2.2
 * Thu Jan 14 16:20:28 CET 2010
 * Generated source version: 2.2.2
 * 
 */

@WebFault(name = "fault", targetNamespace = "urn:es:caib:sistra:ws:v1:model:SistraFacade")
public class SistraFacadeException_Exception extends Exception {
    public static final long serialVersionUID = 20100114162028L;
    
    private net.conselldemallorca.helium.integracio.domini.service.wsdl.SistraFacadeException fault;

    public SistraFacadeException_Exception() {
        super();
    }
    
    public SistraFacadeException_Exception(String message) {
        super(message);
    }
    
    public SistraFacadeException_Exception(String message, Throwable cause) {
        super(message, cause);
    }

    public SistraFacadeException_Exception(String message, net.conselldemallorca.helium.integracio.domini.service.wsdl.SistraFacadeException fault) {
        super(message);
        this.fault = fault;
    }

    public SistraFacadeException_Exception(String message, net.conselldemallorca.helium.integracio.domini.service.wsdl.SistraFacadeException fault, Throwable cause) {
        super(message, cause);
        this.fault = fault;
    }

    public net.conselldemallorca.helium.integracio.domini.service.wsdl.SistraFacadeException getFaultInfo() {
        return this.fault;
    }
}
